### ISSUE TITLE
请支持getContent的自由设置，因为swoole的rawContent 无法用 php://input获取

### ISSUE THREAD

**Issue by hanwenbo** [yansongda/pay#100]
## 包版本号
2.0

## 问题描述
请支持getContent的自由设置，因为swoole的rawContent 无法用 php://input获取
感谢yansongda，我很喜欢用你这个依赖，望支持该功能

**Comment by hanwenbo** [comment]
某微信的依赖类 实现了设置request或者说是替换request的某个方法，不过经过多个swoole 项目的开发，目前需要解决的就是getContent的设置，其他的全局变量swoole是可以定义的。所以我觉得不需要那么复杂，在您的类里  来个设置content接口即可，request里的其他方法 swoole 用不到

**Comment by yansongda** [comment]
请升级至最新版本。

感谢支持

**Comment by hanwenbo** [comment]
卧槽 这么效率  好的 挣钱了 我给你捐一笔

**Comment by hanwenbo** [comment]
请问您有qq群么

**Comment by yansongda** [comment]
QQ 群请见 README

感谢支持
