### ISSUE TITLE
微信支付回调报错

### ISSUE THREAD

**Issue by pasawu** [yansongda/pay#1004]
## 包版本号
thinkphp8

"yansongda/pay": "~3.2.0",

## 问题描述

微信支付回调报错，但没有具体的报错信息，微信支付回调会回调多次，前面的回调正常，没有报错，大概过了8小时微信又重复回调就报错了(已经返回微信回调成功)

## 你的代码

    /**
     * 微信支付回调
     * @throws ErrorException
     */
    public function notify()
    {
        try {
            Pay::config(Config::get('payment'));
            $result = Pay::wechat()->callback();
            $res    = $this->service->wechatNotify($result);

        } catch (\Exception $e) {
            xdebug($this->request->param(), 'wechatNotify-param', 'error');
            xdebug([$e->getLine(), $e->getMessage(), $e->getFile()], 'wechatNotify-Exception', 'error');
            throw new ErrorException($e->getMessage());
        }

        if (isset($res) && $res) {
            return Pay::wechat()->success();
        }
    }

## 报错详情

[186,"","\/opt\/data\/www\/web\/www.baidu.com\/vendor\/yansongda\/pay\/src\/Functions.php"]

![image](https://github.com/yansongda/pay/assets/40690686/d2351011-82ce-4131-b2ce-df24cc52ad2e)

vendor/yansongda/pay/src/Functions.php

## sdk 日志

无

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
https://github.com/yansongda/pay/issues/947

先参考这个排查下
