### ISSUE TITLE
签名异常: 验证微信签名失败

### ISSUE THREAD

**Issue by gavinliu6** [yansongda/pay#1007]
## 包版本号

`3.7.4`

## 问题描述

微信支付通知时，验证微信签名失败（**偶发**）。

## 报错详情

```json
"exception": "[object] (Yansongda\\Pay\\Exception\\InvalidSignException(code: 9500): 签名异常: 验证微信签名失败 at <应用目录>/vendor/yansongda/pay/src/Functions.php:252)
```

## nginx/apache 日志

> 101.226.103.15 - - [02/Jul/2024:20:01:04 +0800] ＂POST <回调路径> HTTP/1.1＂ 500 130 ＂-＂ ＂Mozilla/4.0＂

**Comment by yansongda** [comment]
https://github.com/yansongda/pay/issues/947

先参考这个排查下

**Comment by gavinliu6** [comment]
确认是微信官方流量探测引起的。
