### ISSUE TITLE
return Pay::wechat()->success();

### ISSUE THREAD

**Issue by ken678** [yansongda/pay#1012]
return Pay::wechat()->success();
有接收回调成功 没有回调失败嘛
return Pay::wechat()->error();
![image](https://github.com/user-attachments/assets/868fd9ee-3231-4dee-98f5-864d1a97e6da)
虽然可以这么用
return new Response(
            500,
            ['Content-Type' => 'application/json'],
            json_encode(['code' => 'FAIL', 'message' => '失败']),
        );

**Comment by yansongda** [comment]
不用。非成功状态，其他腾讯或支付宝 那边都会认为是失败
