### ISSUE TITLE
微信返回状态码异常，请检查参数是否错误

### ISSUE THREAD

**Issue by gyp719** [yansongda/pay#1015]
`
$config = config('pay');

    Pay::config($config);

    $order = [
        'out_trade_no' => time().'',
        'description' => 'subject-测试',
        'amount' => [
            'total' => 1,
        ],
    ];

    $result = Pay::wechat()->app($order);
    dd($result) ;
`

<img width="1120" alt="image" src="https://github.com/user-attachments/assets/2584148a-75f6-4013-b511-3a0e93d609d2">

**Comment by yansongda** [comment]
自己捕获异常，看详细信息，或者看日志里微信返回的原始消息。一般是参数不对，看微信的文档确认

**Comment by 490626721** [comment]
我也出现这个问题，用thinkphp8.0集成后没法使用日志；我看了报错代码
` protected function validateResponse(Rocket $rocket): void
    {
        $response = $rocket->getDestinationOrigin();

        if ($response instanceof ResponseInterface
            && ($response->getStatusCode() < 200 || $response->getStatusCode() >= 300)) {
            throw new InvalidResponseException(Exception::RESPONSE_CODE_WRONG, '微信返回状态码异常，请检查参数是否错误', $rocket->getDestination());
        }
    }`
为什么这个地方不直接输出错误的状态码方便排查呢？

**Comment by wind-xiaojiu** [comment]
是的 我也遇到同样问题
