### ISSUE TITLE
2.0版本出错误问题反馈

### ISSUE THREAD

**Issue by 51xvf** [yansongda/pay#102]
问题1
**经测试，在php7.0版本thinkphp5.1下，会报错，升级到php7.1后，问题解决:。**
问题2：
**微信h5支付报“商家参数格式有误”，但在v1版本下没有问题**

protected $wxh5_config= [
        'app_id' => 'aaaaa', // 公众号 APPID
        'mch_id' => 'bbbbbb',
        'key' => 'dddddd',
        'notify_url' => 'https://a.abc.com/index/index/notify',
        'cert_client' => '../config/cert/apiclient_cert.pem', // optional, 退款，红包等情况时需要用到
        'cert_key' => '../config/cert/apiclient_key.pem',// optional, 退款，红包等情况时需要用到
        'log' => [ // optional
            'file' => '../runtime/wechat/wechat.log',
            'level' => 'debug'
        ],
    ];

    public function wxh5pay()
    {
        $order = [
            'out_trade_no' => time(),
            'body' => 'subject-测试',
            'total_fee' => 1
        ];

        $wechat = Pay::wechat($this->wxh5_config);

        $tz = $wechat->wap($order)->send();

        echo $tz; //这里压根都输出不来地址

       // $this->assign('tz_url', $tz);

       // return $this->fetch();

    }

以上为v2版本下的配置！

麻烦看看我的配置有什么问题吗，不胜感激！！

**Comment by yansongda** [comment]
麻烦请开启 debug 模式后，看下日志输出情况。单凭您这些信息是没有任何价值的

谢谢

**Comment by 51xvf** [comment]
您好，我把输出的错误日志发给您看看，非常感谢！

关键点：https://api.mch.weixin.qq.com/pay/unifiedorder


2018-04-13 19:52:06 > DEBUG > Request To Wechat Api ["https://api.mch.weixin.qq.com/pay/unifiedorder",{"appid":"aaaaa","mch_id":"bbbb","nonce_str":"nbNZM9jOMlVSWT1N","notify_url":"https://xcx.abc.com/","sign":"6D89C60128B36F9F86F19FEBC8A4BFCD","trade_type":"MWEB","spbill_create_ip":"117.136.86.92","out_trade_no":1523620326,"body":"subject-测试--yjft","total_fee":10}] []

**Comment by hebiao6446** [comment]
APP 支付 ，  提示签名错误 ， 使用微信的签名工具 https://pay.weixin.qq.com/wiki/tools/signverify/  
和你的签名返回是一样的 ，但是  Get Wechat API Error:签名错误   还是 提示 这个错误 。。

**Comment by roomate** [comment]
他报错找不到key  我明明写了key的
![qq 20180612194637](https://user-images.githubusercontent.com/31603622/41288687-c1c8fed6-6e79-11e8-832b-5c649f9673cb.png)
![qq 20180612194735](https://user-images.githubusercontent.com/31603622/41288690-c6063f90-6e79-11e8-857f-0b9c944be2c6.png)

**Comment by flyRen** [comment]
支付宝 APP支付成功,   退款说签名验证失败, 确保配置参数正确的前提下.

**Comment by hebiao6446** [comment]
去掉外面的 wechat 包裹
