### ISSUE TITLE
config error code:3005 EVENT_CONFIG_ERROR

### ISSUE THREAD

**Issue by bruceJukui** [yansongda/pay#1023]
## 包版本号
3.3.1

## 问题描述
刚完成一个 laravel8 的，代码版本都一摸一样，结果thinkphp6   提示异常
thinkphp6

config error
code:3005

## 你的代码
 'wechat' => [
        'default' => [
            // 必填-商户号，服务商模式下为服务商商户号
            // 可在 https://pay.weixin.qq.com/ 账户中心->商户信息 查看
            'mch_id' => '******',
            // 选填-v2商户私钥
            'mch_secret_key_v2' => '',
            // 必填-v3 商户秘钥
            // 即 API v3 密钥(32字节，形如md5值)，可在 账户中心->API安全 中设置
            'mch_secret_key' => '******',
            // 必填-商户私钥 字符串或路径
            // 即 API证书 PRIVATE KEY，可在 账户中心->API安全->申请API证书 里获得
            // 文件名形如：apiclient_key.pem
            'mch_secret_cert' => '../cert/apiclient_key.pem',
            // 必填-商户公钥证书路径
            // 即 API证书 CERTIFICATE，可在 账户中心->API安全->申请API证书 里获得
            // 文件名形如：apiclient_cert.pem
            'mch_public_cert_path' => '../cert/apiclient_cert.pem',
            // 必填-微信回调url
            // 不能有参数，如?号，空格等，否则会无法正确回调
            'notify_url' => 'http://xmfyl.eenuo.cn/api/order/wechatPayCallback',
            // 选填-公众号 的 app_id
            // 可在 mp.weixin.qq.com 设置与开发->基本配置->开发者ID(AppID) 查看
            'mp_app_id' => '',
            // 选填-小程序 的 app_id
            'mini_app_id' => '******',
            // 选填-app 的 app_id
            'app_id' => '',
            // 选填-服务商模式下，子公众号 的 app_id
            'sub_mp_app_id' => '',
            // 选填-服务商模式下，子 app 的 app_id
            'sub_app_id' => '',
            // 选填-服务商模式下，子小程序 的 app_id
            'sub_mini_app_id' => '',
            // 选填-服务商模式下，子商户id
            'sub_mch_id' => '',
            // 选填-微信平台公钥证书路径, optional，强烈建议 php-fpm 模式下配置此参数
            'wechat_public_cert_path' => [
                '4EF5B25FF64F46BD1FFAD39C76FF2B5551EE9711' => __DIR__ . '/Cert/wechatPublicKey.crt',
            ],
            // 选填-默认为正常模式。可选为： MODE_NORMAL, MODE_SERVICE
            'mode' => Pay::MODE_NORMAL,
        ]
    ],

## 报错详情
		"message": "Config Error",
		"file": "D:\\RuanJian\\phpstudy_pro\\WWW\\datong_road_php\\vendor\\yansongda\\pay\\src\\Event.php",
		"code": 3005,
		"line": 36,

## sdk 日志
yansongda.pay.INFO > [AbstractProvider] 即将进行 pay 操作 [["Yansongda\\Pay\\Plugin\\Wechat\\PreparePlugin","Yansongda\\Pay\\Plugin\\Wechat\\Pay\\Mini\\PrepayPlugin","Yansongda\\Pay\\Plugin\\Wechat\\Pay\\Mini\\InvokePrepayPlugin","Yansongda\\Pay\\Plugin\\Wechat\\RadarSignPlugin","Yansongda\\Pay\\Plugin\\Wechat\\LaunchPlugin","Yansongda\\Pay\\Plugin\\ParserPlugin"],{"out_trade_no":"P202408301042371315","description":"箱好运P202408301042371315箱好运","amount":{"total":35500,"currency":"CNY"},"notify_url":"https://datongdao.wukong1756.com/api/order/wechatPayCallback","payer":{"openid":"o_VUY7ZKnPe3myEsgs8qxfvhR230"}}] 

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
尝试 `composer require symfony/event-dispatcher` 试试看

或者升级到最新版本看看
