### ISSUE TITLE
支付宝支付返回结果

### ISSUE THREAD

**Issue by 736048546** [yansongda/pay#1027]
![image](https://github.com/user-attachments/assets/57cfeb18-e7e1-471b-9ffb-46bdfdf5c3c8)
![image](https://github.com/user-attachments/assets/c58a926b-cd8e-4d0d-a994-625c4609c942)

 刷卡支付 支付调起失败的时候好像只会返回错误内容，不会返回状态码

**Comment by yansongda** [comment]
可尝试升级到最新 V3 版本

**Comment by 736048546** [comment]
好的好的
