### ISSUE TITLE
支付宝h5支付不能拿到跳转url吗？

### ISSUE THREAD

**Issue by Funny-dot** [yansongda/pay#1028]
## 包版本号

v2
## 问题描述
 public function buildOrderParams(): array
    {
        return [
            'out_trade_no' => $this->tradeNo,
            'subject' => $this->subject,
            'total_amount' => (string)$this->orderPrice,
            'time_expire' => $this->expire_time,
            'http_method' => 'GET',
        ];
    }

## 你的代码
                $pay = Pay::alipay($this->buildConfig())->wap($this->buildOrderParams());

## 报错详情
支付宝h5支付不能拿到跳转url吗？

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by Funny-dot** [comment]
$pay = Pay::alipay($this->buildConfig())->wap($this->buildOrderParams())->getContent(); 或者->send();都拿不到跳转url；
http_method也是设置的get

**Comment by yansongda** [comment]
得自己从 html 的代码里拿 url
