### ISSUE TITLE
微信支付回调报错

### ISSUE THREAD

**Issue by yljphp** [yansongda/pay#1029]
## 包版本号

yansongda/pay 3.0.27
php 7.3
laravel 5.8

## 问题描述

Class 'Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory' not found

## 你的代码

```php
Pay::config(config('pay'));

$pay = Pay::wechat();

/**@var $pay Wechat* */


$data = $pay->callback(null, [
    '_config' => $config
]);
```

## 报错详情

Class 'Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory' not found

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
https://pay.yansongda.cn/docs/v3/quick-start/return-format.html#messageinterface


> laravel 框架中，自行安装 symfony/psr-http-message-bridge 即可支持返回相关响应数据
