### ISSUE TITLE
WeChat Pay - 签名错误

### ISSUE THREAD

**Issue by grantholle** [yansongda/pay#103]
## 包版本号
2.1

## 问题描述
I'm trying to do native pay and I keep getting 签名错误. I need help in English 😂

## 报错详情
I have a lumen app. This is my controller function:

```php
$config = [
    'appid' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'app_id' => 'wxxxxxxxxxxxxxxxxx',
    'mch_id' => '15xxxxxxxx',
    'key' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
];

$order = [
    'out_trade_no' => time(),
    'body' => 'Test 测试',
    'total_fee' => '1',
];

return Pay::wechat($config)->scan($order);
```

From the stack trace:
```
Support::requestApi('pay/unifiedorder', array('appid' => 'wxxxxxxxxxxxxxxxxx', 'mch_id' => '15xxxxxxxx', 'nonce_str' => 'w1vyILONDW9dSjsM', 'notify_url' => '', 'sign' => '4A776DE4FC92A890F506547885CEC771', 'trade_type' => 'NATIVE', 'spbill_create_ip' => null, 'out_trade_no' => 1523596778, 'body' => 'Test 测试', 'total_fee' => '1'), 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')
```

Is it the `sign` parameter?

**Comment by yansongda** [comment]
1. Make sure you use the right **KEY**(IT'S VERY IMPORTENT). You can login the tencent pay website to check.

2. I find your `spbill_create_ip` is null, and what environment do you use?

THX

**Comment by grantholle** [comment]
I'm local right now. I will check on the key

**Comment by grantholle** [comment]
That was it! It's working now. Great package, thank you
