### ISSUE TITLE
证书秘钥支持字符串的方式

### ISSUE THREAD

**Issue by anhao** [yansongda/pay#1036]
如 支付宝公钥证书、支付宝根证书  、微信商户公钥证书路径等，支持字符串传入，而不是只是文件路径

**Comment by yansongda** [comment]
支付宝公钥中包含多个证书，字符串不好处理，必须传入 path，其他的现在是支持字符串的，但是推荐都用文件路径，出错率少一些，所以命名上就都以 path 命名的

**Comment by suyar** [comment]
> 支付宝公钥中包含多个证书，字符串不好处理，必须传入 path，其他的现在是支持字符串的，但是推荐都用文件路径，出错率少一些，所以命名上就都以 path 命名的

@yansongda  我目前也遇到了这个问题，证书我们是通过配置中心下发的，所以用文件不一定那边方便；如果可以的话，我提交个PR支持字符串证书的处理可以不。

**Comment by yansongda** [comment]
欢迎 PR

**Comment by suyar** [comment]
是我眼瞎，已经支持了

**Comment by anhao** [comment]
好像不支持吧

> 是我眼瞎，已经支持了

**Comment by anhao** [comment]
> 是我眼瞎，已经支持了

好像还不支持吧

**Comment by suyar** [comment]
@anhao  支付宝是支持的，证书都是通过 `get_public_cert` 和 `get_private_cert` 函数获取，有判断是否文件：
https://github.com/yansongda/pay/blob/8f992f897603ca66f70253765a579c0df42d20ba/src/Functions.php#L40-L54

微信默认给了PEM证书，所以这边证书读取做了下优化，等合并后就支持了：https://github.com/yansongda/pay/pull/1081
