### ISSUE TITLE
支付发起提示 Get Wechat Public Cert Error 

### ISSUE THREAD

**Issue by Wbin123** [yansongda/pay#1038]
## 包版本号
3.2.12

## 问题描述
证书配置正常，发起支付提示上述错误

## 你的代码
![image](https://github.com/user-attachments/assets/d85d46aa-0b8e-434b-8752-8f70047de7f0)

## 报错详情
![image](https://github.com/user-attachments/assets/de1076f1-bcdf-499c-a567-59c6e8942a67)

## sdk 日志
{"radar":{"Yansongda\\Pay\\Request":{"url":"https://api.mch.weixin.qq.com/v3/certificates","method":"GET","headers":{"Host":["api.mch.weixin.qq.com"],"Accept":["application/json, text/plain, application/x-gzip"],"User-Agent":["yansongda/pay-v3"],"Content-Type":["application/json; charset=utf-8"],"Authorization":["WECHATPAY2-SHA256-RSA2048 mchid=\"1699569355\",nonce_str=\"8sZ5xiNcpbFf7UteggtK2YKnBSsDu4ZA\",timestamp=\"1732070295\",serial_no=\"4F74D5C7E226F72263FF26D7A40EA8E36F997BF7\",signature=\"hKrycnBKVDCbqGjhxizaPlOysnR9+3Aj3sJ47WaYWAHKctFhelX56LPg6if8NQGTu/2ANerAUBEvt2TNJV0MCuoEsz8ZCoJd1OahnTvZsM90nuNiZmAj8labyEP0vcYQrOP8hVm1D6TPJDjc3igfM8NO4pITmR91pNjdOc/BszzwhxEN2vDtKbGsObUNpfY20AkdBB3kWCrd32Rhx5MY/GCd+FdKvE6wWSMvQdEvCgCiNr7wWAfqxJCWpsJrACp3WM5NeIB25dJHx5kUNfU9/OcZPD4jT9U8SDrpIpchv5utnRAlYqlHEcRTKCziiL/SVK2PoQst+BaOfvx0W/TpjA==\""]},"body":""}},"params":{"out_trade_no":"202411201038054721219624","description":"订单支付-17320702856499821903","amount":{"total":31596},"notify_url":"/api/v1/wechat","payer":{"openid":"ojV9_69_tfsuR71_4_EtcvGvj8gE"}},"payload":null,"direction":null,"destination":null,"destination_origin":null} 

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
参考下：https://pay.yansongda.cn/docs/v3/others/faq.html
