### ISSUE TITLE
支付宝回调验签总是失败INVALID_SIGN: Alipay Sign Verify FAILED

### ISSUE THREAD

**Issue by Funny-dot** [yansongda/pay#1042]
## 包版本号
^2.10

## 问题描述
支付宝回调验签总是失败INVALID_SIGN: Alipay Sign Verify FAILED
支付宝公钥、商户私钥是没有错的。
## 你的代码
         Pay::alipay($this->buildConfig())->verify($data);

## 报错详情
INVALID_SIGN: Alipay Sign Verify FAILED

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
有条件的话，更新到 v3 版本吧
