### ISSUE TITLE
服务商模式，子商户配置了显示受理机构必须传入sub_mch_id

### ISSUE THREAD

**Issue by leon0606** [yansongda/pay#1049]
## 包版本号
3.7.1

## 问题描述
微信服务商配置了子商户，但是还显示受理机构必须传入sub_mch_id

## 你的代码
"wechat": {
    "default": {
      "mch_id": "...",
      "mch_secret_key_v2": "",
      "mch_secret_key": "...",
      "mch_secret_cert": "...",
      "mch_public_cert_path": "...",
      "notify_url": "...",
      "mp_app_id": "...",
      "mini_app_id": "...",
      "app_id": "...",
      "combine_app_id": "",
      "combine_mch_id": "",
      "sub_mp_app_id": "",
      "sub_app_id": "",
      "sub_mini_app_id": "...",
      "sub_mch_id": "...",
      "wechat_public_cert_path": {
        "...": "..."
      },
      "mode": "2"
    }
  }

## 报错详情
"Wechatpay-Signature-Type":["WECHATPAY2-SHA256-RSA2048"]},"body":"{\"code\":\"PARAM_ERROR\",\"message\":\"受理机构必须传入sub_mch_id\"}"}}}} 

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
哪个 api 出现这个提示的？

**Comment by leon0606** [comment]
&nbsp;[ParserPlugin] 插件装载完毕 {"rocket":{"Yansongda\\Artful\\Rocket":{"radar":{"url":"https://api.mch.weixin.qq.com/v3/pay/transactions/jsapi","method":"POST","headers":{"Host":["api.mch.weixin.qq.com"],"Accept":["application/json, text/plain, application/x-gzip"],"User-Agent":["yansongda/pay-v3"],"Content-Type":["application/json; charset=utf-8"],"Authorization":["WECHATPAY2-SHA256-RSA2048 mchid=\"1635149762\",nonce_str=\"GACxFVtIUNFywryCrpXEXuW8e3unbhgJ\",timestamp=\"1734935548\",serial_no=\"75D2A44E3673E4F40BAC6AAE10333CCF1EE88F9E\",signature=\"tONughDI63TgfVlKbPotydKuVE1TVVwGmfK/gaJedRIR7Ak+89GCu2WjdT2Vj9crbkmCqtnWvoOYXI7ar8m9mWrfWDJJo1o0VMS52TAS0Cp6sdmB17V+rxEsHpVWp0mV/B5+Y+HisrdiVljV+RDvBqzYyThbTQQSYbxCpely2hrMwcGmAGJjT/aFGboOtDrQYEzrXlzLhXqPlMCUxRR6tgaPJbgiol250Q+2mHNiDqVoVHOPnd4ZQT4Z5mNND4TdUdyj6/aHFpmx2bu2sqdzqsn28/tLWMcuANNG0M2U1vnwCmVlGXH7PRmPVcY3AQsE/R/b3BhWEWK/B0Gw3FNXYA==\""]},"body":"{\"out_trade_no\":\"2024122310201394957\",\"description\":\"订单支付\",\"attach\":\"project\",\"amount\":{\"total\":1},\"payer\":{\"openid\":\"o70PG5Pno_64way8BdF3Quazwcv0\"},\"notify_url\":\"https:\\/\\/sai-api.sebayun.com\\/api\\/minipay\\/notifySebaServer\",\"appid\":\"wx0fe9ac7e9f636d77\",\"mchid\":\"1635149762\"}"},"params":{"out_trade_no":"2024122310201394957","description":"订单支付","attach":"project","amount":{"total":1.0},"payer":{"openid":"o70PG5Pno_64way8BdF3Quazwcv0"}},"payload":{"out_trade_no":"2024122310201394957","description":"订单支付","attach":"project","amount":{"total":1.0},"payer":{"openid":"o70PG5Pno_64way8BdF3Quazwcv0"},"_method":"POST","_url":"v3/pay/transactions/jsapi","_service_url":"v3/pay/partner/transactions/jsapi","notify_url":"https://sai-api.sebayun.com/api/minipay/notifySebaServer","appid":"wx0fe9ac7e9f636d77","mchid":"1635149762","_body":"{\"out_trade_no\":\"2024122310201394957\",\"description\":\"订单支付\",\"attach\":\"project\",\"amount\":{\"total\":1},\"payer\":{\"openid\":\"o70PG5Pno_64way8BdF3Quazwcv0\"},\"notify_url\":\"https:\\/\\/sai-api.sebayun.com\\/api\\/minipay\\/notifySebaServer\",\"appid\":\"wx0fe9ac7e9f636d77\",\"mchid\":\"1635149762\"}","_authorization":"WECHATPAY2-SHA256-RSA2048 mchid=\"1635149762\",nonce_str=\"GACxFVtIUNFywryCrpXEXuW8e3unbhgJ\",timestamp=\"1734935548\",serial_no=\"75D2A44E3673E4F40BAC6AAE10333CCF1EE88F9E\",signature=\"tONughDI63TgfVlKbPotydKuVE1TVVwGmfK/gaJedRIR7Ak+89GCu2WjdT2Vj9crbkmCqtnWvoOYXI7ar8m9mWrfWDJJo1o0VMS52TAS0Cp6sdmB17V+rxEsHpVWp0mV/B5+Y+HisrdiVljV+RDvBqzYyThbTQQSYbxCpely2hrMwcGmAGJjT/aFGboOtDrQYEzrXlzLhXqPlMCUxRR6tgaPJbgiol250Q+2mHNiDqVoVHOPnd4ZQT4Z5mNND4TdUdyj6/aHFpmx2bu2sqdzqsn28/tLWMcuANNG0M2U1vnwCmVlGXH7PRmPVcY3AQsE/R/b3BhWEWK/B0Gw3FNXYA==\""},"packer":"Yansongda\\Artful\\Contract\\PackerInterface","direction":"Yansongda\\Artful\\Contract\\DirectionInterface","destination":{"code":"PARAM_ERROR","message":"受理机构必须传入sub_mch_id"},"destination_origin":{"status":400,"headers":{"Server":["nginx"],"Date":["Mon, 23 Dec 2024 06:32:28 GMT"],"Content-Type":["application/json; charset=utf-8"],"Content-Length":["69"],"Connection":["keep-alive"],"Keep-Alive":["timeout=8"],"Cache-Control":["no-cache, must-revalidate"],"X-Content-Type-Options":["nosniff"],"Request-ID":["08FC87A4BB0610D3011884C48C5820F7C61428E7DF02-268443704"],"Content-Language":["zh-CN"],"Wechatpay-Nonce":["dd35ce4fe05a1fdb71efcc19788a846c"],"Wechatpay-Signature":["rtwTGrTIN9Kp6d4Z4HC9jz54OoBG+RJu8OT7xlTa1iXwSLXUL8STZXRYkOG4jh3OJ0tIx8Yd38aPDlgfGmxkEqw4RtJx+HN1bouoEG7o0L3xCoD5a6oXs6uQPolqYJPrtvC9D0cChZrtHSY0klQq9QGIymcAFHg/ezBncR4zU7tje23Uw8W10/LgBLcEx+PNp5f0p4iPyswqJ+Gtkn1hnR+z5+uX4c5KrYf6nZ1LUr1nHr/7md3JMFKEzsW1QNACTkFWRWanEne48hx6/dEOBbxATmDy9ju0t0e4ss2f+7dUuysuO/WXtXvOkE+r0yG6NQ7z8JgLfIQT3vpHw6fCDQ=="],"Wechatpay-Timestamp":["1734935548"],"Wechatpay-Serial":["2801230985FA63B822B6279ACC087F726C0935C3"],"Wechatpay-Signature-Type":["WECHATPAY2-SHA256-RSA2048"]},"body":"{\"code\":\"PARAM_ERROR\",\"message\":\"受理机构必须传入sub_mch_id\"}"}}}}&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年12月23日(星期一) 下午2:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yansongda/pay] 服务商模式，子商户配置了显示受理机构必须传入sub_mch_id (Issue #1049)















哪个api出现这个提示的？

-
直接回复此邮件，在GitHub上查看它，或取消订阅.
***@***.*** &gt;

**Comment by yansongda** [comment]
`"mode": "2"` 改为 `Pay::MODE_SERVICE`
