### ISSUE TITLE
请问下微信H5支付同步回调 怎么取到数据 

### ISSUE THREAD

**Issue by xiaoxiaoxuan** [yansongda/pay#105]
## 代码
涉及到 异步通知、同步通知 的问题，请将 nginx/Apache 的相关日志贴出来

**Comment by dreammdh** [comment]
// TODO 小程序支付回调验签
$pay = Pay::wechat($this->config);
$data = $pay->verify();
Log::info('Applets notify', $data->all());
日志里看不到Applets notify日志数据
