### ISSUE TITLE
「新功能建议」大家还想要什么功能？

### ISSUE THREAD

**Issue by yansongda** [yansongda/pay#108]
对于这个包，大家还想要什么功能？

麻烦大家使劲说，多到一定程度看不下去了，就开干。

---

回复格式：「XX支付」+「XX功能」：XX描述

例如：「微信支付」+「企业转账到银行卡功能」：这个不用多描述了，你懂得。:)

---

**同时，本包只专注于支付，对于支付以外的功能暂不考虑。**

感谢大家支持！

**Comment by Tuniverse** [comment]
qqpay

**Comment by duchao1990** [comment]
退款查询,
服务商版的多商户,或许加上了但是文档
账单下载功能

**Comment by saonian** [comment]
能否加入银联支付

**Comment by leo108** [comment]
微信退款的 `notify_url` 参数不生效。 https://github.com/yansongda/pay/blob/master/src/Gateways/Wechat/Support.php#L110 在这一行被 unset 了。

**Comment by chinanathan** [comment]
退款查询,

**Comment by hanwenbo** [comment]
回复格式：「微信支付」+「退款查询」：客户需要的

**Comment by almas1992** [comment]
「微信支付」+「微信委托扣款」：微信委托扣款可应用于定期扣款或需事后扣款以提高效率的场景。例如但不限于：会员制缴费、水电煤缴费、黄钻绿钻增值服务、打车类软件、停车场或高速公路无人缴费、理财通基金定投、信用卡还款等通过用户授权给商户，进行委托扣款的场景。

开发文档链接： https://pay.weixin.qq.com/wiki/doc/api/pap.php?chapter=18_1&index=1

**Comment by zhangfud** [comment]
达哥，微信支付我用的是laravel5.6版本的，在支付成功回调的时候出现
Yansongda \ Pay \ Exceptions \ InvalidArgumentException (3)
Convert To Array Error! Invalid Xml! 这个问题，怎么解决或者是我哪里的配置错的呢！！

**Comment by liangshuocj** [comment]
需要一个芝麻信用认证查询接口功能。。

**Comment by xuhaoxian** [comment]
「微信支付」+「企业付款到银行卡」：可以提现到银行卡   使用场景：平台的商户要体现到银行卡

**Comment by yansongda** [comment]
「已实现」

- 微信退款异步通知
- 微信/支付宝退款查询

以上两个功能已经完成，请使用 v2.4.0-beta2。

欢迎大家体验！

**Comment by SingleSheep** [comment]
「QQ钱包」+「扫码支付和APP支付」：平台针对QQ用户提供QQ支付方式。:)

**Comment by yansongda** [comment]
@iiDestiny 新功能有同步更新文档的哦。微信退款验证与退款订单查询都有文档更新的。

感谢支持

**Comment by ybzy920** [comment]
「支付宝」+「查询转账订单」
「微信支付」+「查询企业付款」

**Comment by iiDestiny** [comment]
「支付宝」+ 「开放平台代理支付」
「微信」 + 「授权」

**Comment by liansong2011** [comment]
【支付宝】+【查询转账订单接口】

**Comment by Tinywan** [comment]
@yansongda 查询转账订单接口

**Comment by mayunfeng0614** [comment]
「微信支付」+「微信委托扣款」：
「支付宝支付」+「第三方应用授权，支付宝授权委托支付」

**Comment by swat199538** [comment]
能否提供一份方法不要返回 web和wap 支付 不要返回  html , 而是返回url链接

**Comment by rainsens** [comment]
微信转账到银行卡功能有了吗？

**Comment by essaying** [comment]
希望有个可扩展的方法来让我们自己手动添加自己的支付网关, 这样有什么需求自己就可以在上面扩展, 这个我看有挺多人提了 @yansongda

**Comment by almas1992** [comment]
> ![image](https://user-images.githubusercontent.com/17637481/42071595-aa676fbc-7b8e-11e8-92e0-d04fff34ed42.png)
> 
> 「支付宝支付」+「第三方应用授权，支付宝授权委托支付」：因为有很多 SaaS 服务公司需要让客户授权，然后代替客户操作一些支付功能，微信版本的 easyWeChat 已经实现，支付宝如果能记上这个功能那真的是太完美了。 @yansongda 另外希望楼主实现了新功能后更新下文档哟。哈哈

easyWechat 有实现【微信委托扣款】么？ @iiDestiny

**Comment by ruoxiao-zh** [comment]
「微信支付」+「企业付款到银行卡」：可以提现到银行卡使用场景：平台的商户要提现到银行卡

**Comment by flycj** [comment]
「paypal支付」+「paypal海外付款」：如果能支持海外付款功能，相信这个包会更加强大

**Comment by haiyangsjl** [comment]
「微信支付」+「公众号、小程序根据authCode获取openid」
「支付宝支付」+「公众号、小程序根据authCode获取userId」

**Comment by wersion** [comment]
「微信支付」+「企业转账到银行卡功能」+1

**Comment by lylovexm** [comment]
「微信支付」+「企业转账到银行卡功能」+1
「支付宝支付」+「企业转账到银行卡功能」+1

**Comment by aikunzhe** [comment]
「支付宝支付」+「收款到银行账户」：具体描述：https://b.alipay.com/signing/productDetailV2.htm?productId=I1011000001000001984

**Comment by yangweijie** [comment]
[支付宝支付]  + [pc站点扫码支付] 二维码的生成 ： https://docs.open.alipay.com/api_1/alipay.trade.page.pay qr_pay_mode 4

**Comment by iiDestiny** [comment]
「支付宝」 + 「统一转账功能」，需要转账到银行卡等

https://docs.open.alipay.com/api_28/alipay.fund.trans.uni.transfer/

**Comment by yansongda** [comment]
除了 QQ，银联 支付功能，该 issue 里绝大部分功能都已经实现

欢迎大家体验最新版 v3.0.0
