### ISSUE TITLE
Undefined index: sign

### ISSUE THREAD

**Issue by pandaria2012** [yansongda/pay#109]
## 包版本号
"yansongda/pay": "^2.1"

##### 支付宝当面付

vendor/yansongda/pay/src/Gateways/Alipay/Support.php
67行

```php
if (!self::verifySign($result[$method], $publicKey, true, $result['sign'])) {
            Log::warning('Alipay Sign Verify FAILED', $result);

            throw new InvalidSignException('Alipay Sign Verify FAILED', 3, $result);
    }
```

这里的 $result['sign'], 是不是要 isset($result['sign']) 下, 没有的话 直接 throw config error 之类的.
直接这样 容易数组越界

**Comment by yansongda** [comment]
请按照 issue 模板进行 issue，提供信息不足，无法判断。

这里的代码是和支付宝服务器通讯时的相关代码，和配置无关

**Comment by lawmillion** [comment]
这个问题我也遇到了，是通信之后，支付宝返回字段里没有sign引起的
`
/var/www/laravel/vendor/yansongda/pay/src/Gateways/Alipay/Support.php:66:
array (size=1)
  'alipay_fund_trans_toaccount_transfer_response' => 
    array (size=4)
      'code' => string '40002' (length=5)
      'msg' => string 'Invalid Arguments' (length=17)
      'sub_code' => string 'isv.invalid-app-id' (length=18)
      'sub_msg' => string '无效的AppID参数' (length=20)
`
比如报错了这种错误
我不能直观查到问题，只能通过内部打印才看到问题所在

**Comment by lawmillion** [comment]
@pandaria2012 
 是的，不过我更想知道这种错误怎么捕获

**Comment by lawmillion** [comment]
@yansongda 
 类似于我上边发的这种错误信息，我需要怎么捕获呢。
try catch出来的都是Undefined index: sign

**Comment by yansongda** [comment]
已修复，感谢大家的支持。

升级到最新版即可。

如果出现上面的情况，会抛出 `InvalidSignException` 错误。
