### ISSUE TITLE
为什么微信app支付网关要返回JsonResponse

### ISSUE THREAD

**Issue by GuihaiHU** [yansongda/pay#112]
## 包版本号
 "yansongda/laravel-pay": "^2.0"

## 问题描述
微信app支付网关使用一切正常。但是它跟其他网关返回的数据不一样，不是Collection而是Symfony\Component\HttpFoundation\JsonResponse。这样子造成接口返回不一致，自己要再定制一下response也多了一步。
请教一下，为什么要这么设计呢？

**Comment by yansongda** [comment]
仔细看文档。

谢谢
