### ISSUE TITLE
1.x请求异常

### ISSUE THREAD

**Issue by zlwleng** [yansongda/pay#113]
## 包版本号
1.x
## 问题描述
请求异常 post
## 代码
涉及到 异步通知、同步通知 的问题，请将 nginx/Apache 的相关日志贴出来
 ConnectException in CurlFactory.php line 185
## 报错详情
cURL error 28: Resolving timed out after 5519 milliseconds (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by yansongda** [comment]
请体验 v2.5.0-beta 版本，这个版本增加了对 guzzle 的配置支持，可单独设置 超时时间

感谢您的支持
