### ISSUE TITLE
可以加个对guzzlehttp的配置支持吗？

### ISSUE THREAD

**Issue by chenly** [yansongda/pay#117]
## 包版本号
2.2.3

## 问题描述
使用wechat pay没办法给guzzle client加载自定义证书

## 代码
https://github.com/yansongda/pay/blob/89eb0161925dd080069b51187448164b859c3e81/src/Gateways/Wechat/Support.php#L59
http://docs.guzzlephp.org/en/stable/request-options.html#cert
## 报错详情
无

**Comment by yansongda** [comment]
请问什么使用场景？

**Comment by chenly** [comment]
在同样使用overtrue和yansongda默认配置情况下，调用wechatpay的app的prepay_id， overtrue能成功挑起，yansongda提示curl超时， 我想是不是要改一点guzzle client 配置

**Comment by chenly** [comment]
对guzzlehttp的配置支持还是有一些场景的， 不过这个是我个人建议，而且开发优先级也不高

例如：如果运行在老的服务器上，开发人员可以自己使用最新的CA证书列表

[【重要】微信支付计划更换服务器证书，请开发人员验证以免影响交易](https://pay.weixin.qq.com/index.php/public/cms/content_detail?lang=zh&id=56602)
[微信支付HTTPS服务器证书验证指引
](https://pay.weixin.qq.com/wiki/doc/api/micropay.php?chapter=23_4)

**Comment by yansongda** [comment]
目前默认请求超时时间为 5 秒，即5秒内微信或支付宝服务器没有反应，则视为超时。

5秒这个数值理论上已经很大了，不建议再更改，您说的现象有可能因为网络原因造成请求失败。这个暂无解决办法。

至于服务器根证书的问题，guzzle/curl 默认会自动在操作系统中找到合适的CA包，保持操作系统到最新即可，所以一般无需特殊操作。

您说的手动配置根证书的问题，将在下一个版本中考虑！

感谢您的支持

**Comment by yansongda** [comment]
v2.5.0-beta 版本开始已经支持 guzzle 配置。

感谢支持
