### ISSUE TITLE
安装不上这个包。。。

### ISSUE THREAD

**Issue by iiDestiny** [yansongda/pay#120]
## 问题描述

![image](https://user-images.githubusercontent.com/17637481/40989287-ee76ea92-691f-11e8-8394-b7e6420cb7c8.png)

好像按照不上。 这是 laravel 5.1 的项目

## 代码
涉及到 异步通知、同步通知 的问题，请将 nginx/Apache 的相关日志贴出来

**Comment by iiDestiny** [comment]
楼主，你的 supports 要求 guzzle 6.3， 我项目用的 guzzle 6.2，而且项目 guzzle 不能升级，这肿么办。。。

**Comment by yansongda** [comment]
已增加 对 guzzle 6.2 的支持。

您直接重新安装即可

**Comment by iiDestiny** [comment]
@yansongda 十分感谢作者回复 👍 ，哎，老项目让人头大而且还没办法去升级。老项目用的好多组件都不维护了。依赖的一些包的版本也比较老。。。monolog 也只最高支持 1.9 http-foundation 也是稍微低一点版本。这两个条件在还是安装不上项目。。不过我已经把项目本地化了。把你的依赖约束移除了下。。。可能是我这个项目比较特殊点。测试了一下支付，暂时没什么问题。

大版本号不变 API 方法应该没什么问题吧？项目的 `monolog 1.19` `http-foundation 2.7.11` 不影响使用哈。。。

**Comment by yansongda** [comment]
是的，一般情况下大版本号不变的情况下问题不大。不过建议还是看看相关包的 release 说明确定下比较好。

**Comment by iiDestiny** [comment]
因为组件要去 http-foundation 3 我的是 http-foundation 2.7.11，去看了看  release 说明。没有文字描述的改变事项。
