### ISSUE TITLE
支付回调验证问题

### ISSUE THREAD

**Issue by alukaa** [yansongda/pay#123]
### 支付宝
[支付宝返回参数验签](https://docs.open.alipay.com/204/105301/)
![image](https://user-images.githubusercontent.com/8164389/41286068-cdb8231a-6e70-11e8-8625-62f9d9079724.png)
### 微信
[微信返回参数验证](https://pay.weixin.qq.com/wiki/doc/api/app/app.php?chapter=9_7)
![image](https://user-images.githubusercontent.com/8164389/41286180-1efd3986-6e71-11e8-854e-431071732150.png)

@yansongda 代码里面都只对sign进行了验证，对于其他回传参数的验证，有没有什么想法

**Comment by alukaa** [comment]
sign要验证的，没问题，但是在sign啊验证过后，对于微信和支付宝而言，还需要验证其他的回传参数，以支付宝为例:

### 在第四步签名验证通过后，必须严格按照如下的描述校验通知参数的合法性：
1、商户需要验证该通知数据中的out_trade_no是否为商户系统中创建的订单号；2、判断total_amount是否确实为该订单的实际金额（即商户订单创建时的金额）；3、校验通知中的seller_id（或者seller_email) 是否为out_trade_no这笔单据对应的操作方（有的时候，一个商户可能有多个seller_id/seller_email）；4、验证app_id是否为该商户本身。上述1、2、3、4有任何一个验证不通过，则表明同步校验结果是无效的，只有全部验证通过后，才可以认定买家付款成功。

这是支付宝文档的[原话](https://docs.open.alipay.com/204/105301/)

**Comment by yansongda** [comment]
您说的是业务逻辑了。SDK 无法做到对所有业务逻辑进行判断， README 中也有说明。

感谢您的支持！
