### ISSUE TITLE
阿里沙箱环境支付回调参数缺少 passback_params 

### ISSUE THREAD

**Issue by specialnote** [yansongda/pay#124]
## 包版本号
1.0

## 问题描述
在阿里沙箱环境使用 web | wap 支付，请求参数中带有 passback_params  参数，且参数进过了 urlencode，但是响应中无此参数

### 支付调用
 ```
$orderConfig = [
    'out_trade_no' => time(),
    'total_amount' => '0.01',
    'subject'      => '(7天无理由退款)python 机器学习【进阶篇】',
    'passback_params' => urlencode(http_build_query([
        'orderId' => 1,
        'type' => 'promo',
    ]))
];
$pay = new Pay(Yii::$app->params['aliPayAccount']);
$driver = $pay->driver('alipay');
if ($this->inMobile()) {
    if ($this->inWechat()) {
        return 'todo 使用微信支付';
    }
    $gateway = $driver->gateway('wap');
} else {
    $gateway = $driver->gateway('web');
}
return $gateway->pay($orderConfig);
```
### 回调参数
{"charset":"GBK","out_trade_no":"1529484863","method":"alipay.trade.page.pay.return","total_amount":"1.00","sign":"aHBG2DHPGuYAHFowcpXFgCEwUe39HVs+itHeXCbuvUwjDiux1vMZq25mF2\/xR3zN5\/zSeDoU47U4eeVWRTkhLX2WUssxH83x+BmTNdIdNnFXvMErfBzjxmdILIZGxrYny\/xfyYRK4r4RGiQxx+lu7uPwPGVKZztQUPbkCg+\/mmAY8D9s6I7e44fRV797MZ3U9bktG7dlWHa0AjpTWhYGrU3NDAhG+rlR5LzHGVE+T1SzN3KGla6B9Iuw6LqnKi2mlD1Zonq0Abi7SC\/k5raTpIN+8iy3i80hrFs7Is5WGkM2Zr9CjlTVaNpkfTr5nVmQPMJ8ioo3\/3MZxBFPWIc3CQ==","trade_no":"2018062021001004440200430551","auth_app_id":"2016091300502568","version":"1.0","app_id":"2016091300502568","sign_type":"RSA2","seller_id":"2088102175462013","timestamp":"2018-06-20 16:54:50"} 

### nginx 日志
 124.126.198.50 - - [20/Jun/2018:16:54:53 +0800] "GET /pmobile/ali/callback?charset=GBK&out_trade_no=1529484863&method=a    lipay.trade.page.pay.return&total_amount=1.00&sign=aHBG2DHPGuYAHFowcpXFgCEwUe39HVs%2BitHeXCbuvUwjDiux1vMZq25mF2%2FxR3zN    5%2FzSeDoU47U4eeVWRTkhLX2WUssxH83x%2BBmTNdIdNnFXvMErfBzjxmdILIZGxrYny%2FxfyYRK4r4RGiQxx%2Blu7uPwPGVKZztQUPbkCg%2B%2FmmA    Y8D9s6I7e44fRV797MZ3U9bktG7dlWHa0AjpTWhYGrU3NDAhG%2BrlR5LzHGVE%2BT1SzN3KGla6B9Iuw6LqnKi2mlD1Zonq0Abi7SC%2Fk5raTpIN%2B8i    y3i80hrFs7Is5WGkM2Zr9CjlTVaNpkfTr5nVmQPMJ8ioo3%2F3MZxBFPWIc3CQ%3D%3D&trade_no=2018062021001004440200430551&auth_app_id=    2016091300502568&version=1.0&app_id=2016091300502568&sign_type=RSA2&seller_id=2088102175462013&timestamp=2018-06-20+16%    3A54%3A50 HTTP/1.1" 200 914 "https://unitradeprod.alipaydev.com/acq/cashierReturn.htm?sign=K1iSL1gn5tqoqiMMQQv4xDB9gImZ    GFmFLUHmtw%252BOtSYx%252FN6jbTOLrXoPV8k%253D&outTradeNo=1529484863&pid=2088102175462013&type=1" "Mozilla/5.0 (Windows N    T 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36"   

## 报错详情
回调参数中没有 passback_params 数据

**Comment by specialnote** [comment]
buildPayHtml result

<form id='alipaysubmit' name='alipaysubmit' action='https://openapi.alipaydev.com/gateway.do' method='POST'><input type    ='hidden' name='app_id' value='2016091300502568'/><input type='hidden' name='method' value='alipay.trade.page.pay'/><in    put type='hidden' name='format' value='JSON'/><input type='hidden' name='charset' value='utf-8'/><input type='hidden' n    ame='sign_type' value='RSA2'/><input type='hidden' name='version' value='1.0'/><input type='hidden' name='return_url' v    alue='https://xcx.chinahadoop.cn/pmobile/ali/callback'/><input type='hidden' name='notify_url' value='https://xcx.china    hadoop.cn/pmobile/ali/pay-notify'/><input type='hidden' name='timestamp' value='2018-06-20 17:31:31'/><input type='hidd    en' name='sign' value='XNhg0ZjrNtofZZlRzIBdtpI+DploFVvdMC665ktys6LJ9B5hFWs8FvwslgE668cx7UWeo8SFOE2MdL8p0U5s5LXJ5SgcBebZ    uIKAuJNLTmdgeQpvCHJqzvuxW0NphSGnMorOPTjSxEHPDBSQw6RTQYjaceW3D3NjfeqKZiOMkKPvxczKgAldyUNdTYFy0iXjaeVrUecraIAnFEWQXKgSIr3    irVNLRxqLwBJHgxofsMyp8qVzGuGJ7FeqHbslZzwNX3gYTL+KHP9xKRnts/R4ghm+DLND883C6m+YDFb9oYL+3FT1rNu3pkxYpZp9ce+nb3I8rJ21Pjvyrm    OBvoBpJg=='/><input type='hidden' name='biz_content' value='{"out_trade_no":1529487091,"total_amount":"1","subject":"(7    \u5929\u65e0\u7406\u7531\u9000\u6b3e)python \u673a\u5668\u5b66\u4e60\u3010\u8fdb\u9636\u7bc7\u3011","passback_params":"    orderId%3D1%26type%3Dladder","product_code":"FAST_INSTANT_TRADE_PAY"}'/><input type='submit' value='ok' style='display:    none;''></form><script>document.forms['alipaysubmit'].submit();</script>

**Comment by specialnote** [comment]
## buildPayHtml result

```
<form id='alipaysubmit' name='alipaysubmit' action='https://openapi.alipaydev.com/gateway.do' method='POST'><input type='hidden' name='app_id' value='2016091300502568'/><input type='hidden' name='method' value='alipay.trade.page.pay'/><input type='hidden' name='format' value='JSON'/><input type='hidden' name='charset' value='utf-8'/><input type='hidden' name='sign_type' value='RSA2'/><input type='hidden' name='version' value='1.0'/><input type='hidden' name='return_url' value='https://xcx.chinahadoop.cn/pmobile/ali/callback'/><input type='hidden' name='notify_url' value='https://xcx.chinahadoop.cn/pmobile/ali/pay-notify'/><input type='hidden' name='timestamp' value='2018-06-20 17:31:31'/><input type='hidden' name='sign' value='XNhg0ZjrNtofZZlRzIBdtpI+DploFVvdMC665ktys6LJ9B5hFWs8FvwslgE668cx7UWeo8SFOE2MdL8p0U5s5LXJ5SgcBebZuIKAuJNLTmdgeQpvCHJqzvuxW0NphSGnMorOPTjSxEHPDBSQw6RTQYjaceW3D3NjfeqKZiOMkKPvxczKgAldyUNdTYFy0iXjaeVrUecraIAnFEWQXKgSIr3irVNLRxqLwBJHgxofsMyp8qVzGuGJ7FeqHbslZzwNX3gYTL+KHP9xKRnts/R4ghm+DLND883C6m+YDFb9oYL+3FT1rNu3pkxYpZp9ce+nb3I8rJ21PjvyrmOBvoBpJg=='/><input type='hidden' name='biz_content' value='{"out_trade_no":1529487091,"total_amount":"1","subject":"(7\u5929\u65e0\u7406\u7531\u9000\u6b3e)python \u673a\u5668\u5b66\u4e60\u3010\u8fdb\u9636\u7bc7\u3011","passback_params":"orderId%3D1%26type%3Dladder","product_code":"FAST_INSTANT_TRADE_PAY"}'/><input type='submit' value='ok' style='display:none;''></form><script>document.forms['alipaysubmit'].submit();</script>

```

**Comment by yansongda** [comment]
麻烦请直接贴出包产生的日志

**Comment by specialnote** [comment]
我使用的是 1.0 版本，项目没有引入日志系统

**Comment by yansongda** [comment]
buildPayHtml 的结果中有包含 `passback_params` 参数的，所以，支付方面是没问题的。

而回调验证中， SDK 是没有对返回的参数做任何更改调整的，从 nginx 看到，支付宝返回的直接数据中也没有看到 `passback_params` 所以，这个和 SDK 无关的哦！

综上，这个问题和 SDK 无关。暂时不能判断原因。

**Comment by specialnote** [comment]
我我的结论差不多，可能是沙箱环境换题，甚至是支付宝问题，等正式账号审核下来之后我再测试一下，实在不行就只有舍弃这个参数使用别的方案了。非常感谢!

**Comment by specialnote** [comment]
我我的结论差不多，可能是沙箱环境问题，甚至是支付宝问题，等正式账号审核下来之后我再测试一下，实在不行就只有舍弃这个参数使用别的方案了。非常感谢!

**Comment by yansongda** [comment]
是的，建议通过其他方案，最直接的是直接通过 订单号进行判断。

感谢您的支持
