### ISSUE TITLE
单笔转账到支付宝

### ISSUE THREAD

**Issue by liangshuocj** [yansongda/pay#126]
## 包版本号
yansongda/pay             v2.1.0

## 代码
涉及到 异步通知、同步通知 的问题，请将 nginx/Apache 的相关日志贴出来

## 报错详情

curl error 35:unknown ssl protocol error in connection to openapi.alipay.com:443(see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by yansongda** [comment]
并非 SDK 问题，请检查服务器相关配置。

请检查是否使用 windows 环境，是否使用了诸如 wamp 等集成环境。

感谢支持
