### ISSUE TITLE
1.x 支付宝签名错误

### ISSUE THREAD

**Issue by Andy-Yuen** [yansongda/pay#127]
支付宝签名错误，经过调试 ，提交表单参数中的 charset:utf-8  应该改成 charset:UTF-8 ，大小写敏感

**Comment by yansongda** [comment]
您好，支付宝官方文档请求参数中 charset 均为 utf-8，经测试，也一直是正常的，也未曾有其他人报告过这个问题，请问您用的具体是哪个版本？

**Comment by guihouchang** [comment]
我也存在这样的错误，不过在最新版已经修复了这个BUG了
