### ISSUE TITLE
WeChat H5 支付 微信客户端唤起浏览器重定向问题

### ISSUE THREAD

**Issue by yushengbuilder** [yansongda/pay#128]
## 包版本号
yansongda/laravel-pay": "^2.0

## 问题描述
问题1 ： https://pay.weixin.qq.com/wiki/doc/api/H5.php?chapter=15_4
这个微信文档中部说了可以在微信客户端跳回浏览器进行重定向。
在您的文档中没有找到这个参数。如果有麻烦指点一下，如果没有，建议加上这个参数。

问题2 ：https://pay.weixin.qq.com/wiki/doc/api/H5.php?chapter=9_20&index=1
文档中说是返回参数，但是我在laravel中执行 `return $this->pay->wap($order);`
只直接调起了微信客户端，请问有办法获取这鞋参数吗，然后手动调起微信客户端。

## 代码
涉及到 异步通知、同步通知 的问题，请将 nginx/Apache 的相关日志贴出来
没有代码
## 报错详情
没有报错

**Comment by yushengbuilder** [comment]
@yansongda

**Comment by yansongda** [comment]
SDK 支持所有官方功能。

在微信客户端，建议直接使用 公众号支付

**Comment by yushengbuilder** [comment]
@yansongda 主要是问题一。手机浏览器中使用微信支付。当微信端支付完成后，会回跳浏览器。这个并不是文档正文中的，而是微信文档常见问题里提到的。
但是我反复看了您的包，没有看到这个。
建议您看看我贴的第一个链接。

**Comment by yushengbuilder** [comment]
而且我提的这个issues只是h5支付，没涉及到微信公众号支付。

**Comment by yushengbuilder** [comment]
h5支付流程不应该是    浏览器调起微信客户端进行支付-》支付完成-》微信客户端调起浏览器并重新打开跳转之前的页面。
这里在微信中是可以修改最后这个跳转地址的，但是是写在常见问题中，并不是作为一个正式参数子啊文档中。因为问题都是在后半段，所以我就没写之前的流程。

**Comment by yushengbuilder** [comment]
h5支付流程不应该是 浏览器调起微信客户端进行支付-》支付完成-》微信客户端调起浏览器并重新打开跳转之前的页面。
这里在微信中是可以修改最后这个跳转地址的，但是是写在常见问题中，并不是作为一个正式参数写在文档中。   因为问题都是在后半段，所以标题就没写之前的流程。

**Comment by yushengbuilder** [comment]
![image](https://user-images.githubusercontent.com/26155226/42306442-93c1aa5c-8061-11e8-8339-afc96e2990ec.png)

**Comment by yansongda** [comment]
设置 `return_url` 即可

**Comment by yushengbuilder** [comment]
微信pay的h5支付中没有return_url这个参数啊大佬 @yansongda

**Comment by yansongda** [comment]
使用 H5 支付时，如果配置参数中有 return_url 参数，则 SDK 将自动将return_url 设置为 redirect_url。

**Comment by yushengbuilder** [comment]
感谢大佬，建议吧这个写在文档上。 @yansongda
