### ISSUE TITLE
微信退款回调优化

### ISSUE THREAD

**Issue by VWenX** [yansongda/pay#133]
## 包版本号
2.4.0

## 问题描述
刚改好想来说发现作者已经更新了，$data['req_info']建议unset掉，不然冗长的未解析字符串打到log里看起来很别扭。

**Comment by yansongda** [comment]
确实是，不过既然是 debug，就要信息尽量全一些，不是吗？

如果您觉得太长了，可以将日志级别调高些

感谢您的支持
