### ISSUE TITLE
Missing Wechat Config -- [key]

### ISSUE THREAD

**Issue by gyp719** [yansongda/pay#137]
## 问题描述
微信扫码支付， 配置项的 key 指的是什么，还有 timeStamp，nonceStr，product_id，sign这个个参数也是必填的啊

## 报错详情
![image](https://user-images.githubusercontent.com/30563368/43674006-0d88a5b6-97ff-11e8-94ca-73b2a8eb6e04.png)

![image](https://user-images.githubusercontent.com/30563368/43673985-ac427890-97fe-11e8-8c4e-82edea85d537.png)

**Comment by yansongda** [comment]
1，按 issue 模板提

2，请先仔细看文档

谢谢
