### ISSUE TITLE
可不可以支持HttpClient外部配置

### ISSUE THREAD

**Issue by limingxinleo** [yansongda/pay#139]
## 问题描述

fpm里直接调用http请求会产生一部分网络IO，所以我们想在协程框架中使用，那就需要重写Http客户端，但现在的扩展，似乎不支持外部配置HttpClient。

希望可以留一个入口，让用户自定义HttpClient

**Comment by yansongda** [comment]
现在 http client 不像 response 那样有统一标准。所以要想实现不同的 http 客户端，还需要从长计议，好好思考下怎么实现。

感谢支持

**Comment by woann** [comment]
@yansongda 狗幣

**Comment by leoleoasd** [comment]
https://wiki.swoole.com/wiki/page/965.html
guzzle配置 传入禁止curl即可协程

**Comment by guihouchang** [comment]
@limingxinleo 现在hyperf要用这个这个组件，怎么用呢？

**Comment by yansongda** [comment]
v3 版已经支持

后续将很快发布 v3 版本

感谢支持

**Comment by jonny77** [comment]
> v3 版已经支持
> 
> 后续将很快发布 v3 版本
> 
> 感谢支持

期待...
