### ISSUE TITLE
response 自定义

### ISSUE THREAD

**Issue by zsj1029** [yansongda/pay#141]
## 包版本号
2.0

## 问题描述
sdk很好用
但是response直接http 返回了
虽然通过getContent能拿到返回信息
但最终返回给客户端的还是HttpFoundation直接返回
我想自己处理返回信息，根据需组装json数据
不知设计上是不是支持

## 代码
涉及到 异步通知、同步通知 的问题，请将 nginx/Apache 的相关日志贴出来

**Comment by zsj1029** [comment]
这边用的不是laravel
调用方式
$alipay->send()->getContent();
虽然拿到了内容，但是依旧是sdk直接返回的http response 
在我组装json返回之前，就被sdk提前返回了

**Comment by yansongda** [comment]
如果要自己返回自定义内容，不用 send .

请仔细看看文档。同时理解返回的对象。要慢慢培养独立思考的能力

感谢支持
