### ISSUE TITLE
verify()验证失败

### ISSUE THREAD

**Issue by Jingfengshi** [yansongda/pay#142]
Array
(
    [gmt_create] => 2018-08-13 10:05:22
    [charset] => utf-8
    [gmt_payment] => 2018-08-13 10:05:29
    [notify_time] => 2018-08-14 05:59:30
    [subject] => test subject - 测试
    [sign] => i9ElrTl6ff5yTHvRLXrAf+yTBsr58BEyt03Kqcc52+Eu+OoxzwM94Tiv2/qG54go1jj65iOksEAGN3WB0pPTwK7FMaINUpn/EKAxuW78Ee4zTgmo7p6hDPKXnCjekP1x3UzefJmQ0U40E85Yoxleyza6Ni8W+eUxVFcUS9aMtIBpYmVrdyinufO+5TfWue6+m+0LJ+UXyIV7oxWj2elkuB886NRTZ5p/Gc6Zm11P1u3C0l58634nzbijgKCMXKzddhsGvxtifGkO6oZZu3vzeEIQHjQ0jHxlTmyJhdEwD2cLT0dpfQdgENCMVM6TjcUOgIiCUJLlDNY00JjhQDIKPw==
    [buyer_id] => 2088102176077953
    [invoice_amount] => 1.00
    [version] => 1.0
    [notify_id] => aa19a5f7ca65ee5647e0450bee7cba8nby
    [fund_bill_list] => [{"amount":"1.00","fundChannel":"ALIPAYACCOUNT"}]
    [notify_type] => trade_status_sync
    [out_trade_no] => 1534125897
    [total_amount] => 1.00
    [trade_status] => TRADE_SUCCESS
    [trade_no] => 2018081321001004950200554143
    [auth_app_id] => 2016091300504472
    [receipt_amount] => 1.00
    [point_amount] => 0.00
    [app_id] => 2016091300504472
    [buyer_pay_amount] => 1.00
    [sign_type] => RSA2
    [seller_id] => 2088102175498850
    [PHPSESSID] => 6ag7hmfjkqiepmvppluh2dabs1
)
我这样的数据，每次进行验证的时候，数据验证失败

**Comment by yansongda** [comment]
`[PHPSESSID] => 6ag7hmfjkqiepmvppluh2dabs1`  哪儿来的？这个应该不是支付宝官方的吧？

请仔细看文档，谢谢
