### ISSUE TITLE
subject中存在'&' 符App支付，支付宝返回“系统繁忙，稍后再试

### ISSUE THREAD

**Issue by algery** [yansongda/pay#150]
## 包版本号

v2.0

## 问题描述

`subject`中存在'&' 符App支付，支付宝返回`系统繁忙，稍后再试`

## 报错详情
`系统繁忙，稍后再试`

猜测：不是字符集编码的问题，应该是特殊字符的处理上吧

**Comment by yansongda** [comment]
支付宝官方文档有明确说明 避免使用 &，请参考支付宝官方文档。

这个问题也并非 SDK 所能解决的。

感谢您的支持
