### ISSUE TITLE
微信退款回调通知验证

### ISSUE THREAD

**Issue by zhangjiangyuan** [yansongda/pay#151]
## 包版本号
"yansongda/pay": "^2.4"

## 问题描述
微信退款回调通知：返回的XML中只有**req_info**进行了加密。如果调用**verify($content = null, $refund = false)**函数，第一个参数不传**req_info**，将会报错，希望能够在文档中说明，或解决

## 代码
涉及到 异步通知、同步通知 的问题，请将 nginx/Apache 的相关日志贴出来

## 报错详情
[2018-09-01 01:35:07] production.INFO: 收到微信退款回调
[2018-09-01 01:35:07] production.INFO: $request:POST /api/payment/wechat/refund_notify HTTP/1.1
Accept:         */*
Connection:     Keep-Alive
Content-Length: 1317
Content-Type:   text/xml
Host:           180831-gongxianghuiyi.cdfykj.net
Pragma:         no-cache
User-Agent:     Mozilla/4.0

<xml><return_code>SUCCESS</return_code><appid><![CDATA[wx2d78afd36632a341]]></appid><mch_id><![CDATA[1512913271]]></mch_id><nonce_str><![CDATA[c50f030632e42bde8194758ef8240029]]></nonce_str><req_info><![CDATA[5JvHbTSoaEVhZXCYc8M2zyHkhA4cOjtLC/tk559ylg6Fy+tNwE/F2IzbVfp4UUYv43eTP/OD8LyXvbUmz98YGsivwb6NSf6DztSUhg0YDzXITUU5zv8vqq9x9btaoANFOsx8UgWMU3DTL1MQz9+hVe6jHsIUrn6yRZtdmPGWXqqFC50bC2RqDwU0DzJXXhTyfHUaRxyG9E2ZjmsucRmCQMx4Kut4ZvFgfsJG/C1GrB7TYTHU6pTScBBAYT8zuHhIRgRXowvSCM+e73PoTLSK4B7H/MKHYljbAN4GNFX3eTTE8iRpP5H4iiQXh/6tGcAd5ure0uMna7CfHERBbRO4bQDG8ZnS9Ii2NeQel9Eqh/1NAwfpHvzxP8mImmJ14S6T5dOqEunLSEnuPkhjxfklYzkkXW4+1ji7nGMavDCyKMSE1xGQxoIk5SODFSdIbVU5C7TWh2ivJKSlVjFVAHic3Naq33QpgcyV694ikn3ADiL9gDbEKSJ9wh2EkTT2m7UoyKlfAqsmVgsDrRMGXGOaWlMv1H0g4JTeswhmWKslqan+vSgLENfvCfFtZfdSkjpXIOSltGQkAt/CAMFBroLSg5jnj6GL4jj5RlIq3zSdo/EId9IWqkZQW+rXp+5hfGIhoR7lGM7bfAaj4ECfedZ/fqfj5zukQCZpqZ+CQR/qWUYuQsFxxJZQE5VlY0asvLtQ+VoodGiEY1ZPGxtyAn02wAjqTLTNUUeO/uNVnsug1TCPUaF8NwX0BgvsJRRr+GUCbtPkXrZoFpA6XBXFauBNx9+9qilbHsvg3mDTT5wMEfESVu7TpdoUxe0zo448cIvbxqR4YmKF9lW1CLYpDrgHcrtD0ZIfZm+FWSqwL/+wPs3N8e4wQ8uGTbvCvOlXces6quZWVcq4t4KtyY7HTtcYdLHYHEp7xoZFiIUhXF8+jLcPZcrTlmU9W+nDEwWt7ZqtpazvmKCZ7GTB2u+YOfLcGfDlYt05hugkKBdU7GWVxgg/JvtuMMvk0vxI2LLwiLvdoX5Gf5]]></req_info></xml>
[2018-09-01 01:35:07] production.ERROR: Convert To Array Error! Invalid Xml! {"exception":"[object] (Yansongda\\Pay\\Exceptions\\InvalidArgumentException(code: 3): Convert To Array Error! Invalid Xml! at /data/wwwroot/180831-gongxianghuiyi.cdfykj.net/vendor/yansongda/pay/src/Gateways/Wechat/Support.php:223)

**Comment by yansongda** [comment]
请仔细查看文档。

感谢您的支持！
