### ISSUE TITLE
getsignkey  这个方法在哪

### ISSUE THREAD

**Issue by megumi-i** [yansongda/pay#153]
## 包版本号
2.4

## 问题描述
Get Wechat API Error:沙箱验证签名失败，请确认沙箱签名key是否正确（通过getsignkey调用生成）

## 代码
涉及到 异步通知、同步通知 的问题，请将 nginx/Apache 的相关日志贴出来

**Comment by woann** [comment]
別指望這個傻逼作者回答你的問題，他就是個狗。

**Comment by gd4Ark** [comment]
同问

**Comment by yansongda** [comment]
#62 

v2.7.0 及以上版本已经完全支持微信沙箱模式，欢迎体验

感谢大家支持
