### ISSUE TITLE
Get Wechat API Error:参数错误：spbill_create_ip字段必填,并且为合法的IP字符串.参数错误：spbill_create_ip字段必填,并且为合法的IP字符串.

### ISSUE THREAD

**Issue by megumi-i** [yansongda/pay#155]
## 包版本号
2.4
## 问题描述
企业转账出现
Get Wechat API Error:参数错误：spbill_create_ip字段必填,并且为合法的IP字符串.参数错误：spbill_create_ip字段必填,并且为合法的IP字符串.

在数组中加入spbill_create_ip 也同样报错
## 代码
Get Wechat API Error:参数错误：spbill_create_ip字段必填,并且为合法的IP字符串.参数错误：spbill_create_ip字段必填,并且为合法的IP字符串.

## 报错详情
Get Wechat API Error:参数错误：spbill_create_ip字段必填,并且为合法的IP字符串.参数错误：spbill_create_ip字段必填,并且为合法的IP字符串.

**Comment by yansongda** [comment]
请按 issue 模板提，并说明相关环境与复现方式。

感谢支持
