### ISSUE TITLE
微信支付提示支付回调链接存在XXE漏洞

### ISSUE THREAD

**Issue by FaithPatrick** [yansongda/pay#156]
## 包版本号
v1.x

## 问题描述
微信支付提示我系统的支付回调链接存在XXE漏洞，即XML外部实体注入漏洞，官方给出的PHP解决方案是
```
libxml_disable_entity_loader(true);
```
而我查看 pay 包的微信支付通知方法中，已经存在此配置语句，为何微信还会提示呢？我是否可以忽略？

**Comment by woann** [comment]
這項目就是垃圾，一堆bug，作者還愛裝逼。
