### ISSUE TITLE
支付宝scan网关支付的异步通知信息无法通过验证

### ISSUE THREAD

**Issue by zithan** [yansongda/pay#167]
## 问题描述
环境：沙箱
你好，支付宝如果网关是APP，那么支付回调是一个charset=utf-8，这时候验证签名通过，但是发现在网关scan的时候，支付宝异步回调信息是一个charset=GBK的，这时候验证无法通过。

但是如果修改包的沙箱地址，z这时候沙箱的scan网关的支付异步信息返回了charset=utf-8，就可以通过签名验证了。
![image](https://user-images.githubusercontent.com/1336063/46068985-07d98900-c1ad-11e8-8b27-3627e5b6316f.png)

## 代码
网关是scan的扫码支付回调
![image](https://user-images.githubusercontent.com/1336063/46068854-b4ffd180-c1ac-11e8-9815-2f3d58073803.png)

## 报错详情
网关为scan时，支付宝的异步信息，是gbk乱码格式，签名无法验证通过

**Comment by yansongda** [comment]
您好，麻烦您进入 ：http://test.yanda.net.cn/pay/ 此网站，将网址上的内容转换成二维码，然后使用沙箱测试账号：ghdhjw7124@sandbox.com   111111 进行支付。

您支付完成后，麻烦通知下我。我查看下日志！

感谢您的支持

**Comment by zithan** [comment]
您好，我已经按照沙箱支付了

**Comment by yansongda** [comment]
@zithan 无需自己填写 $_POST SDK 会自动处理。如果自行传入第一个参数，请自行处理编码问题。

请仔细看文档。

感谢支持

**Comment by zithan** [comment]
是的，如果是自己通过传入**回调信息**进行验证的，需要自行转码后再传入verify()进行验证，如下图：

![image](https://user-images.githubusercontent.com/1336063/46125822-6eb67b00-c25d-11e8-9f03-667cf19fae21.png)

@yansongda 感谢您的耐心解答和帮忙。
