### ISSUE TITLE
能不能留一个可扩展的方法？

### ISSUE THREAD

**Issue by aixiangfei** [yansongda/pay#169]
我知道你这个包是专注于支付，但是有的项目中偶尔需要用到一两个与支付相关的接口，再去重新找别的包比较麻烦，就想直接在你现有代码的基础上增加几行代码就可以完成的，比如说支付宝资金授权接口。
如果你预留出一个注册新方法的接口出来，我可以不用修改你现有代码，直接在我自己项目中增加少许代码就能轻松扩展更多的方法。
不知道我有没有说明白。。。

**Comment by yansongda** [comment]
了解您的意思了。您说的这个建议很好！考虑在下个版本中增加。

感谢您的支持！

**Comment by Arvin-Lee** [comment]
我是没整明白
