### ISSUE TITLE
和TP的配合

### ISSUE THREAD

**Issue by crstudio** [yansongda/pay#174]
## 包版本号
2.5.1

没有什么问题，就是想和大家分享一下
与TP5.1的配合
包里自带的`$wechat->success()->send()`，没法用，于是就用TP的`Response`的发送了，不过需要注意一点，如果开启调试模式，那么TP的输出始终带debug代码，就是一个JavaScript区块代码，直接return 是不行的，我是直接`exit($response)`的，并且直接用的TP的 `response\Xml` 的。但愿能帮助别人

**Comment by sorign** [comment]
楼主怎么处理的，能否贴下代码 好像遇到同样的问题了

**Comment by yangjingchuang** [comment]
大佬，微信支付对应多个商户号怎么进行配置的？？

**Comment by langjitianya123** [comment]
直接将Symfony\Component\HttpFoundation\Response换成use think\Response就好了

`<?php

namespace Yansongda\Pay\Gateways\Alipay;

use Symfony\Component\HttpFoundation\RedirectResponse;
// use Symfony\Component\HttpFoundation\Response;
use think\Response;
use Yansongda\Pay\Events;
use Yansongda\Pay\Exceptions\InvalidArgumentException;
use Yansongda\Pay\Exceptions\InvalidConfigException;
use Yansongda\Pay\Gateways\Alipay;

class WebGateway extends Gateway
{
    protected function buildPayHtml($endpoint, $payload, $method = 'POST'): Response
    {
        if ('GET' === strtoupper($method)) {
            return new RedirectResponse($endpoint.'&'.http_build_query($payload));
        }

        $sHtml = "<form id='alipay_submit' name='alipay_submit' action='".$endpoint."' method='".$method."'>";
        foreach ($payload as $key => $val) {
            $val = str_replace("'", '&apos;', $val);
            $sHtml .= "<input type='hidden' name='".$key."' value='".$val."'/>";
        }
        $sHtml .= "<input type='submit' value='ok' style='display:none;'></form>";
        $sHtml .= "<script>document.forms['alipay_submit'].submit();</script>";

        // return new Response($sHtml);
        return Response::create($sHtml);
    }

}`

**Comment by yansongda** [comment]
TP 不支持 PSR 的很多标准，所以难搞

大家需要自行解包处理，后续考虑出个 tp 的 bridge 吧
