### ISSUE TITLE
微信App支付，查询退款时报：Get Wechat API Error:不识别的参数spbill_create_ip

### ISSUE THREAD

**Issue by xiaozan** [yansongda/pay#181]
## 包版本号
2.5

## 问题描述
微信App支付，查询退款时报：Get Wechat API Error:不识别的参数spbill_create_ip

## 代码
查询退款接口，不需要spbill_create_ip参数

**Comment by yansongda** [comment]
已修复，感谢支持

**Comment by xiaozan** [comment]
测试了一下，现在报错：**Get Wechat API Error:签名错误**。
应该是在生成sign的时候，包含了spbill_create_ip，而后再移除spbill_create_ip，导致签名验证不通过。
可以把unset的代码移到Support::filterPayload()方法上面，试了一下，Ok的，麻烦帮忙看下。

**Comment by yansongda** [comment]
@xiaozan 麻烦了，感谢！
