### ISSUE TITLE
微信红包发送有一处判断问题

### ISSUE THREAD

**Issue by q2211404** [yansongda/pay#184]
## 包版本号
2.5.4

## 问题描述
微信红包发送有一处判断为服务商的问题, 导致非服务商发送红包提示 "授理模式/资金受理才需要填入msgappid"

## 代码
```
if ($this->mode !== Wechat::MODE_SERVICE) {
            $payload['msgappid'] = $payload['appid'];
        }
```
应该改成 等于吧
## 报错详情
Get Wechat API Error:参数错误:授理模式/资金受理才需要填入msgappid参数错误:授理模式/资金受理才需要填入msgappid

**Comment by q2211404** [comment]
文件 命名空间 Yansongda\Pay\Gateways\Wechat\RedpackGateway   line34-36

**Comment by yansongda** [comment]
请问您的 

mode 是否填写成了服务商模式？

**Comment by q2211404** [comment]
没有, 服务商模式没有设置 mode 为空 没设置

**Comment by yansongda** [comment]
已修复，感谢您的支持！

**Comment by q2211404** [comment]
good boy
