### ISSUE TITLE
应该在文档中说明一下这个情况吧？

### ISSUE THREAD

**Issue by lisqorz** [yansongda/pay#188]
https://github.com/yansongda/pay/blob/5816c97efa469974cd62c647212eda19ee88bfac/src/Gateways/Wechat/TransferGateway.php#L37-L39

这一行如果在cli下无法获取ip的话，是否应该在文档说说明、或者支持开发者自己传值？
当然我只是说针对cli下开发的用户

**Comment by yansongda** [comment]
文档中有，只是你不仔细看而已。

感谢支持
