### ISSUE TITLE
laravel5.7微信配置加载不到回调地址

### ISSUE THREAD

**Issue by lyxxg** [yansongda/pay#189]
## 包版本号
laravel5.7 + "yansongda/laravel-pay": "^2.0"

## 问题描述
一直Get Wechat API Error:invalid notify_url  爆这个错误
## 代码
[https://yansongda.gitbooks.io/pay/docs/wechat/pay.html#%E4%B8%80%E3%80%81%E5%85%AC%E4%BC%97%E5%8F%B7%E6%94%AF%E4%BB%98](https://yansongda.gitbooks.io/pay/docs/wechat/pay.html#%E4%B8%80%E3%80%81%E5%85%AC%E4%BC%97%E5%8F%B7%E6%94%AF%E4%BB%98)
## 报错详情
![image](https://user-images.githubusercontent.com/35553218/48458438-53013700-e801-11e8-8c06-a6bf34a0654c.png)

后面通过dd pay包源码的方式  发现notify_url一直为空的
于是改了源码   /vendor/yansongda/pay/src/Gateways/Wechat/Support.php
 public static function getInstance($config = null): self
{
$config['notify_url']=>'http://...';
}
终于成功了

**Comment by yansongda** [comment]
请提供代码
