### ISSUE TITLE
2.5.7 swoole 支付宝验证签名异常

### ISSUE THREAD

**Issue by cxlan** [yansongda/pay#190]
## 包版本号
2.5.7

## 问题描述
使用Laravel + swooletw/laravel-swoole  支付宝网页支付成功，验证签名异常，同样的支付宝配置不用swoole 可以正常支付验证签名。

## 报错详情
 Alipay Sign Verify FAILED {"exception":"[object] (Yansongda\\Pay\\Exceptions\\InvalidSignException(code: 5): Alipay Sign Verify FAILED at
Yansongda\\Pay\\Gateways\\Alipay->verify(Array)

**Comment by yansongda** [comment]
swoole 验签时，需要传第一个参数到 verify() 函数。

注意此参数为 数组格式，且需要注意编码情况。

感谢支持

**Comment by cxlan** [comment]
> swoole 验签时，需要传第一个参数到 verify() 函数。
> 
> 注意此参数为 数组格式，且需要注意编码情况。
> 
> 感谢支持

嗯， 问题已解决，参数有传递给verify()函数， 是路由定义了一个middleware  对请求参数进行了重新编码导致验证参数无效。
