### ISSUE TITLE
支付宝网页支付 buildPayHtml 问题

### ISSUE THREAD

**Issue by lifenglibao** [yansongda/pay#197]
## 包版本号
1.3

## 问题描述
支付宝网页支付 buildPayHtml 问题

## 代码

buildPayHtml  方法中 
$sHtml .= "<input type='submit' value='ok' style='display:none;''></form>";
display:none 后面多了一个单引号

## 报错详情

希望老版本可以根据 sign_type不同使用不同的open ssl 签名 和 验证 签名方式

**Comment by yansongda** [comment]
已修复，感谢您的支持

PS：老版本目前已进入维护期，只做 bug 修复，不做新功能开发。

如果有条件，还请尽快升级到 v2 版本
