### ISSUE TITLE
支付宝扫码支付不行 return false 

### ISSUE THREAD

**Issue by i838847058** [yansongda/pay#20]
## 问题描述
配置文件都正确，html输出形式没问题，二维码地址就不行。求赐教

## 代码
        $Pay = new Pay($config);
        return $Pay->driver('alipay')->gateway('scan')->pay($config_biz);

## 报错详情
cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by yansongda** [comment]
请参考 #16 。

感谢支持

**Comment by i838847058** [comment]
已解决，十分感谢！
