### ISSUE TITLE
支付宝支付接口异常

### ISSUE THREAD

**Issue by zithan** [yansongda/pay#200]
## 问题描述
更新composer后出现问题

## 你的代码
> 正常的支付接口调用

## 报错详情
类型错误: Argument 1 passed to Yansongda\Pay\Listeners\KernelLogSubscriber::writeApiRequestedLog() must be an instance of Yansongda\Pay\Events\ApiRequested, instance of Yansongda\Pay\Events\ApiRequesting given, called in /home/www/xjj/rpc/vendor/symfony/event-dispatcher/EventDispatcher.php on line 212

**Comment by yansongda** [comment]
已修复

感谢您体验测试版，此版本支持事件系统，欢迎体验。
