### ISSUE TITLE
微信扫码支付成功之后没回调

### ISSUE THREAD

**Issue by guodalin** [yansongda/pay#206]
## 包版本号
v2.x 

## 问题描述
微信支付成功之后，回调地址设置的是调用wxnotify方法，但wxnotify里面的日志没记录到，请问是什么问题

 $pay = Order::verify('wechat'); 和$pay = Pay::wechat($this->config);  是一个意思

## 你的代码
> 涉及到 异步通知、同步通知 的问题，请将 nginx/Apache 的相关日志贴出来
![image](https://user-images.githubusercontent.com/12906579/50268539-21196b00-0466-11e9-8c86-33ceca00268a.png)
![image](https://user-images.githubusercontent.com/12906579/50268830-3642c980-0467-11e9-813a-5f460ee7b4cd.png)

## 报错详情
没报错

**Comment by yansongda** [comment]
> 涉及到 异步通知、同步通知 的问题，请将 nginx/Apache 的相关日志贴出来

**Comment by xutl** [comment]
我觉得，你需要在支付管理后台，设置 扫码支付的回调地址。

**Comment by guodalin** [comment]
> > 涉及到 异步通知、同步通知 的问题，请将 nginx/Apache 的相关日志贴出来

之前nginx日志没开，现在开下来发现是419，大概知道什么原因了

**Comment by guodalin** [comment]
> 我觉得，你需要在支付管理后台，设置 扫码支付的回调地址。

微信后台也设置了回调地址，nginx日志反应是http状态码419

**Comment by hebo5485** [comment]
> > > 涉及到 异步通知、同步通知 的问题，请将 nginx/Apache 的相关日志贴出来
> 
> 之前nginx日志没开，现在开下来发现是419，大概知道什么原因了

csrfToken的相关设置没开
