### ISSUE TITLE
一个关于支付参数的问题

### ISSUE THREAD

**Issue by xutl** [yansongda/pay#209]
由于各个支付通道的返回的参数一般不同，或许可以考虑一下 虽然返回的内容不同，但是是否可考虑下把返回的类型固定一下。比如PC WAP，返回的直接是HTML。。。有时候并不想直接就去支付。而是先保存相关参数，在由客户端发起支付。

**Comment by yansongda** [comment]
请看文档，文档有返回类型及相关说明
