### ISSUE TITLE
下个版本有微信对账单功能吗？

### ISSUE THREAD

**Issue by zhangweixing21** [yansongda/pay#216]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yansongda** [comment]
会考虑支持的。

**欢迎 PR**

感谢支持

**Comment by kotlin360** [comment]
@yansongda 希望能够尽快增加微信对账单功能，谢谢，已经star

**Comment by yansongda** [comment]
最新版本已经支持，欢迎使用，如有问题欢迎及时提出

感谢支持。
