### ISSUE TITLE
可以随心所欲添加本项目中没有的支付网关？

### ISSUE THREAD

**Issue by imdgr** [yansongda/pay#218]
看了文档，也看了部分代码，根本不能增加新的支付网关啊

```php
protected function create($method): GatewayApplicationInterface
    {
        $gateway = __NAMESPACE__.'\\Gateways\\'.Str::studly($method);
        if (class_exists($gateway)) {
            return self::make($gateway);
        }
        throw new InvalidGatewayException("Gateway [{$method}] Not Exists");
    }
```

` $gateway = __NAMESPACE__.'\\Gateways\\'.Str::studly($method);`   
这要怎么增加，命名空间都写死了

**Comment by ranwu** [comment]
我也遇到这样的问题，比如调用支付宝的用户授权网关。我是直接拼装了请求数据，然后调用这个库的加签方法，然后用guzzle执行网络请求，基本上可以实现需求。一直有一个想法，就是能不能把加签和验签过程单独抽象成一个包，这样就可以使用其他的服务网关了。

**Comment by yansongda** [comment]
计划将增加自由扩展的 extend 方法，到时候会解决这个问题。

PS：README 中的【可以随心所欲添加本项目中没有的支付网关】 指的是：可以随意根据需求进行添加，然后 PR，和业务代码无关的哈
