### ISSUE TITLE
lumen框架向微信服务器确认收到异步通知

### ISSUE THREAD

**Issue by kotlin360** [yansongda/pay#219]
## 包版本号
lumen:5.7
yansongda/pay:2.6.1

## 问题描述
请问，如果使用的是lumen框架，支付成功后微信异步通知，向微信服务器确认收到异步通知，
是下面代码的哪一行？我使用的是lumen框架，经过我测试好像两个都可以，有啥区别？

## 你的代码
return $wechat->success()->send(); 
// 还是下面这一句
return $wechat->success();

## 报错详情
无错误，对lumen来说好像两种方式都可以，作者能讲解下区别在哪里吗？

## sdk 日志
日志中都会出现Wechat Success Method Has Called ["https://api.mch.weixin.qq.com/",[]] 

## nginx/apache 日志
无

**Comment by yansongda** [comment]
建议您看看 lumen 的相关源码就会明白的。

感谢支持
