### ISSUE TITLE
Missing Config -- [appid]

### ISSUE THREAD

**Issue by hjldev** [yansongda/pay#22]
## 问题描述 
按照文档上写的代码，直接请求提示 Missing Config -- [appid]
## 代码
public function wxPay(){
        $config = [
            'wechat' => [
                'app_id' => 'xxx',
                'mch_id' => 'xxx',
                'notify_url' => 'http://yansongda.cn/wechat_notify.php',
                'key' => 'xxx',
                'cert_client' => './apiclient_cert.pem',
                'cert_key' => './apiclient_key.pem',
            ],
        ];
        $config_biz = [
            'out_trade_no' => 'e2',
            'total_fee' => '1', // **单位：分**
            'body' => 'test body',
            'spbill_create_ip' => '8.8.8.8',
            'openid' => '123',
        ];

        $pay = new Pay($config);

        return $pay->driver('wechat')->gateway('app')->pay($config_biz);
    }

**Comment by yansongda** [comment]
app 支付的 appid 参数是不一样的，麻烦请仔细查看 readme 第 12 条。

感谢您的支持！
