### ISSUE TITLE
关于支付宝中 手机网站支付转Native支付 的问题

### ISSUE THREAD

**Issue by lmxdawn** [yansongda/pay#222]
手机网站支付转Native支付 时，如果用了 buildPayHtml 方式，则会跳转两次网页，这样的话虽然调起了支付，但是返回时会有一个支付宝的二级页面，我用了一种方式，pay() 方法里判断一下请求类型，如果是 GET 请求，则使用 GET 参数拼接成支付链接，如果不是 GET 请求，则使用 原来的方式，代码如下：

public function pay(array $config_biz = [])
    {
        parent::pay($config_biz);

        if (!empty($config_biz['httpMethod']) && $config_biz['httpMethod'] == 'GET'){

            //拼接GET请求串
            $requestUrl = $this->gateway."?".http_build_query($this->config);

            return $requestUrl;
        }

        return $this->buildPayHtml();
    }
就是想问问这边能不能考虑到这个因素改一下，不然每次我用的时候都要去改一下

**Comment by yansongda** [comment]
收到您的反馈，后续版本将考虑这个因素

感谢支持。

**Comment by yansongda** [comment]
v2.7.1 及以上版本已支持。

传 http_method 参数为 GET 即可

感谢您的支持

**Comment by lmxdawn** [comment]
好的，我去看了下，这样感觉也会有一个中间页面，我是觉得 如果是 http_method  参数为 GET 时，直接 重定向跳转到 支付宝的支付链接，如果还是使用 form 表单的话，这个表单是一个空白的中间页面，支付时会会出现一个空白页面，这样不友好，如果直接重定向到支付页面，则就不会存在这个 空白的表单页面

**Comment by yansongda** [comment]
UPDATED
