### ISSUE TITLE
lumen 微信支付Facade问题

### ISSUE THREAD

**Issue by zh761324952** [yansongda/pay#223]
支付订单时调用 
Pay::wechat()->find()
Pay::wechat()->miniapp()
第二次会提示没有回调地址参数错误 
原因：实例化一次 类中属性改变 没有重置类中属性

**Comment by zh761324952** [comment]
`
    Container::getInstance()->forgetInstance('pay.wechat');
`

**Comment by yansongda** [comment]
laravel / lumen 中，服务均使用的是单例模式。

感谢您的支持
