### ISSUE TITLE
支付宝查询订单的问题不成功

### ISSUE THREAD

**Issue by ugarden** [yansongda/pay#226]
## 包版本号
v2.0

## 问题描述
支付宝查询订单不成功

## 你的代码
Pay::alipay(config('pay.alipay'))->find($number);

## 报错详情
ErrorException: call_user_func() expects parameter 1 to be a valid callback, non-static method Yansongda\Pay\Gateways\Alipay\WapGateway::find() should not be called statically in D:\zhangwanglvyou\wamp64\www\zwo2o\vendor\yansongda\pay\src\Gateways\Alipay.php:204

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by jourdon** [comment]
刚刚测试也遇到这个问题

**Comment by yansongda** [comment]
请问  PHP 版本？

**Comment by jourdon** [comment]
php 7.2.16
laravel 5.8.7
yansongda/pay  ^2.7

**Comment by yansongda** [comment]
@jourdon 请问您也是 Windows 下出现此报错的吗？

**Comment by jourdon** [comment]
@yansongda 我是本地Homestead 环境测试出的问题

**Comment by ugarden** [comment]
@yansongda 我的是laravel5.4用的2.0版本请问是版本过高导致码

**Comment by yansongda** [comment]
应该是环境问题。我本机测试未出现相关问题。

不过已经升级为兼容方案。

composer update 即可

感谢支持

**Comment by ugarden** [comment]
好的，明天早上回公司试下
