### ISSUE TITLE
关于支付宝支付

### ISSUE THREAD

**Issue by GitHubSummerWind** [yansongda/pay#227]
## 包版本号

  "yansongda/laravel-pay": "^2.0",
## 问题描述
使用场景  支付宝支付时：第一次唤起支付宝app 进入支付 但未进行支付，之后再调用支付宝支付 报错ALIN42273 后台无报错信息  
若一直支付成功就可以一直使用
百度 

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by TheSaltwaterRoom** [comment]
包版本号
"yansongda/pay": "^2.7"
问题描述
使用场景 支付宝网页支付时：
![image](https://user-images.githubusercontent.com/20590174/55667788-96813e00-5893-11e9-96ca-2e97adb13ef9.png)
一直报这个错误
