### ISSUE TITLE
为什么支付成功回调一直显示这个

### ISSUE THREAD

**Issue by SuenLinCN** [yansongda/pay#228]
## 包版本号
"yansongda/pay": "^2.7"

## 问题描述
没有任何报错，不管怎么修改都会显示这个
![image](https://user-images.githubusercontent.com/18395492/55708449-89da2280-5a18-11e9-9789-028644d5fca6.png)

## 你的代码
![image](https://user-images.githubusercontent.com/18395492/55708591-dcb3da00-5a18-11e9-85bd-cfec6f7d8cb8.png)

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by jourdon** [comment]
![image](https://user-images.githubusercontent.com/24295670/55708814-73809680-5a19-11e9-9518-0d9575c5c801.png)

**Comment by sorign** [comment]
我这样直接打开回调地址，也会返回成功，这样是没有带任何请求参数进来的
![image](https://user-images.githubusercontent.com/18395492/55709042-fe619100-5a19-11e9-9988-74e69a318515.png)
![image](https://user-images.githubusercontent.com/18395492/55709044-002b5480-5a1a-11e9-9fc0-19c30efe7e3f.png)

**Comment by jourdon** [comment]
建议你先去看支付宝的接口文档，把付款流程搞清楚，
不然怎么改代码都没有。

**Comment by sorign** [comment]
流程是不是这样的
1.网站选择支付宝支付
![image](https://user-images.githubusercontent.com/18395492/55710238-c60f8200-5a1c-11e9-9471-5e6e4e62738a.png)
2.支付宝支付
![image](https://user-images.githubusercontent.com/18395492/55710291-e9d2c800-5a1c-11e9-9cb0-95f601bca242.png)
3.付款完成跳转回调
![image](https://user-images.githubusercontent.com/18395492/55710344-0e2ea480-5a1d-11e9-87a7-d79892f39494.png)
4.回调里面无论怎么改，都是上面的文字提示

**Comment by sorign** [comment]
issues #174 里面有讲到这个 我也是tp框架 不知道有没有影响

**Comment by ken678** [comment]
你不应该这样写吗$this->success("恭喜你！充值成功!");异步回调才需要return $pay->success()->send();
