### ISSUE TITLE
请问下微信扫码支付成功后 使用verify()获取微信服务器信息报错

### ISSUE THREAD

**Issue by zyzplzyz** [yansongda/pay#229]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/20371988/56414740-25438100-62be-11e9-8fa0-c2b2d506ecf9.png)
![image](https://user-images.githubusercontent.com/20371988/56414762-355b6080-62be-11e9-96ec-d5c450c57111.png)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/20371988/56414740-25438100-62be-11e9-8fa0-c2b2d506ecf9.png)

**Comment by yansongda** [comment]
请使用 bug 模版并按模版格式填写

感谢支持
