### ISSUE TITLE
微信APP支付签名问题

### ISSUE THREAD

**Issue by lifenglibao** [yansongda/pay#23]
## 问题描述
调用微信APP下单API后会获取到prepayid这个参数，我看了微信文档说这个参数要额外进行一次签名，看了下你的code好像没有对这个参数进行额外的签名。

**Comment by yansongda** [comment]
[调起支付接口](https://pay.weixin.qq.com/wiki/doc/api/app/app.php?chapter=9_12&index=2)

[APP端调起支付](https://pay.weixin.qq.com/wiki/doc/api/app/app.php?chapter=8_5)

**请先熟悉 微信/支付宝开发文档**

如有问题，麻烦请按照 issue 模板发起 issue

感谢您的支持！

**Comment by hebiao6446** [comment]
同样的问题，报签名错误。
