### ISSUE TITLE
v2.7.3不向下兼容问题

### ISSUE THREAD

**Issue by xiaozan** [yansongda/pay#232]
v2.7.3版本中，支付宝查询方法第二个参数，由原来(v2.7.2)的`$refund = false`调整为`$type = 'wap'`，代码位置：https://github.com/yansongda/pay/blob/v2.7.3/src/Gateways/Alipay.php#L189

作为一个bugfix版本，如果用户不慎升级，可能会导致已有项目不能运行(当调用代码第二个参数传`false`时)

**Comment by yansongda** [comment]
代码层面有做兼容，请仔细看代码

**Comment by xiaozan** [comment]
@yansongda 
按照v2.7.2版本的代码，调用代码：`find($order, false)`, 能正常运行;
当升级到v2.7.3版本后, `$type`参数被赋值为`false`, 导致`Str::studly($type)`返回空字符串, 继而导致下面的`GatewayException`

**Comment by yansongda** [comment]
知道您说的什么意思了，您显式的指定了第二个参数为 `false`

**Comment by yansongda** [comment]
已发新版

感谢支持

**Comment by xiaozan** [comment]
@yansongda 
还有一个小问题想抬杠一下，关于语义方面的(不影响程序运行)。

https://github.com/yansongda/pay/blob/master/src/Contracts/GatewayApplicationInterface.php#L32
这里的Contracts定义的find方法：`public function find($order, $refund);`，第二个参数是`$refund`，Alipay现在的处理方式与这里的语义不符。
考虑到Wechat的处理方式还和原来一样，后续是否有考虑把Wechat也修改掉
