### ISSUE TITLE
支付接口请求跨域

### ISSUE THREAD

**Issue by Demontf** [yansongda/pay#235]
## 包版本号
yansongda pay V2.x
php 7.2.0 
laravel 5.6
## 问题描述
一切都正常。
但是，项目采用前后端分离。laravel提供接口前端访问时出现跨域，其他所有接口都没有问题。项目做了中间件处理跨域问题。如果返回值不写return Pay::alipay($config)->web($aliPayOrder) 就不会报跨域。求各位帮忙给指点一二。谢谢

## 你的代码
![image](https://user-images.githubusercontent.com/6856378/56851036-0340a300-693d-11e9-9a0e-8ce01602a0bb.png)
## 报错详情
接口请求跨域

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
后续考虑增加 跨域支持

感谢支持

**Comment by Demontf** [comment]
已解决谢谢回复
