### ISSUE TITLE
微信H5支付提示：网络环境未能通过安全验证

### ISSUE THREAD

**Issue by facesun** [yansongda/pay#240]
## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来
按说明文档写的，微信的PC扫描模式没问题，H5模式支付的时候提示：网络环境未能通过安全验证，请稍后再试，根据网上（[ https://blog.csdn.net/sdutphp/article/details/80373714]( https://blog.csdn.net/sdutphp/article/details/80373714)） 说的修改
get_client_ip()函数依然没用。相关代码如下：
`public function wap()
    {
       $order = [
		'out_trade_no' => (string)time().(string)random_int(1000,9999),
		'body' => 'subject-测试',
		'total_fee' => '1',
		];
		//手机网站支付
		$result = Pay::wechat($this->config)->wap($order)->send();

		return $result;
 
    }

$pay = new WxPay();
$res = $pay->wap(); `

**Comment by zoulux** [comment]
我也遇到了

**Comment by zoulux** [comment]
哥们 我终于解决了 ，

` 'spbill_create_ip' => Request::createFromGlobals()->getClientIp(),`

微信支付H5校验了ip，但是 spbill_create_ip 有问题，如果网络访问中间有多个 proxy 的话，取的值就不对，建议作者可以支持手动传 spbill_create_ip  ，
@yansongda

**Comment by Aexus** [comment]
> 哥们 我终于解决了 ，
> 
> ` 'spbill_create_ip' => Request::createFromGlobals()->getClientIp(),`
> 
> 微信支付H5校验了ip，但是 spbill_create_ip 有问题，如果网络访问中间有多个 proxy 的话，取的值就不对，建议作者可以支持手动传 spbill_create_ip ，
> @yansongda

请问下,这个放在哪里?下单那里还是配置文件中?

**Comment by yansongda** [comment]
@zoulux 支持手动传值的。
