### ISSUE TITLE
支付宝扫码支付成功之后没有异步通知

### ISSUE THREAD

**Issue by ChinaBygones** [yansongda/pay#241]
## 包版本号
V2

## 问题描述

支付宝扫码成功之后没有异步通知
## 你的代码
public function actionIndex()
    {
        $order = [
            'out_trade_no' => time(),
            'total_amount' => '1',
            'subject' => 'test',
        ];
        $alipay = Pay::alipay($this->config)->scan($order);
        return $alipay->qr_code;
    }

    public function return()
    {
        $data = Pay::alipay($this->config)->verify(app()->request->post()); // 是的，验签就这么简单！
        var_dump($data);
        // 订单号：$data->out_trade_no
        // 支付宝交易号：$data->trade_no
        // 订单总金额：$data->total_amount
    }

    public function notify()
    {
        $alipay = Pay::alipay($this->config);
        return $alipay->success()->send();
    }

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by ChinaBygones** [comment]
解决了

**Comment by xixigou** [comment]
你好，请问这个问题你那里怎么解决的？

**Comment by forecho** [comment]
同问，如何解决的？

**Comment by freadman** [comment]
同问，怎么解决的，我也没有异步通知。
