### ISSUE TITLE
我现在有多个支付账户应该怎么配置？？？再重新添加配置项吗？？

### ISSUE THREAD

**Issue by yangjingchuang** [yansongda/pay#243]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yansongda** [comment]
是的，多配置即可实现

**Comment by yangjingchuang** [comment]
好的，谢谢大佬，目前使用的框架是tp5.1，感觉你写的很nice




------------------ 原始邮件 ------------------
发件人: "yansongda"<notifications@github.com>; 
发送时间: 2019年5月28日(星期二) 上午10:57
收件人: "yansongda/pay"<pay@noreply.github.com>; 
抄送: "杨敬闯17621213817"<2580839896@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [yansongda/pay] 我现在有多个支付账户应该怎么配置？？？再重新添加配置项吗？？ (#243)




是的，多配置即可实现
 
&mdash;

**Comment by yangjingchuang** [comment]
对了，目前还有一个问题，关于微信支付，就是我们的项目中小程序与app的支付所对应的商户号也就是mch_id是不一致的，但是现在只能把他们分开来，有什么好的办法吗？？




------------------ 原始邮件 ------------------
发件人: "yansongda"<notifications@github.com>;
发送时间: 2019年5月28日(星期二) 上午10:57
收件人: "yansongda/pay"<pay@noreply.github.com>;
抄送: "杨敬闯17621213817"<2580839896@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [yansongda/pay] 我现在有多个支付账户应该怎么配置？？？再重新添加配置项吗？？ (#243)




是的，多配置即可实现

**Comment by yangjingchuang** [comment]
对了，目前还有一个问题，关于微信支付，就是我们的项目中小程序与应用程序的支付所对应的商户号也就是mch_id是不一致的，但是现在只能把他们分开来，有什么好的办法吗??
