### ISSUE TITLE
如果有 golang 的就好了。。。

### ISSUE THREAD

**Issue by JeffreyBool** [yansongda/pay#244]
在使用 golang 做项目。发现没有好用的包。难受

**Comment by lePig** [comment]
歪个楼。 
冒昧请教下题主从PHP怎么过渡到Golang的。目前学习了golang的一些语法，包括变量、运算符、条件控制、数组、切片等。但是好像学习完这些以后不知道如何进阶了。
也感觉到php用惯了以后，在写go的语法有点不习惯。思维一时还没转过来

**Comment by huangxingx** [comment]
> 歪个楼。
> 冒昧请教下题主从PHP怎么过渡到Golang的。目前学习了golang的一些语法，包括变量、运算符、条件控制、数组、切片等。但是好像学习完这些以后不知道如何进阶了。
> 也感觉到php用惯了以后，在写go的语法有点不习惯。思维一时还没转过来

做点实战项目应该就能转换思维了，我也是个go 小白

**Comment by huangxingx** [comment]
> 在使用 golang 做项目。发现没有好用的包。难受

可以自己搞一个，参考 这个项目，搞一个goland的吧

**Comment by lePig** [comment]
@huangxingx 谢谢啦。 目前水平还搞不了支付，怕坑到了其他人，哈哈
