### ISSUE TITLE
是不是不支持两个商户号的情况？

### ISSUE THREAD

**Issue by huangxingx** [yansongda/pay#245]
看 class Support 中 private static $instance;  是私有静态变量， php 小白，大神指教。

**Comment by huangxingx** [comment]
两个商户号应该是支持的， 尴尬；
但是 baseUrl 是不是第一次实例化之后就不能修改 mode 了

**Comment by yangjingchuang** [comment]
> 两个商户号应该是支持的，尴尬; 
> 但是是baseUrl是不是第一次实例化之后就不能修改模式了

大佬，两个商户号的情况你是怎么解决的？？？急求

**Comment by huangxingx** [comment]
@yangjingchuang   把两个商户号 做成两个 $config

$pay1 = Pay::wechat($this->config1)->mp($order)
$pay2 = Pay::wechat($this->config2)->mp($order)
每次调用都把config 传入，应该就行了

**Comment by yangjingchuang** [comment]
不是这样的，我想的是：微信支付小程序和app对应的是不同的商户号，然后可以这样的配置
        'appid'       => 'wxc9f38bbb341b6739', // APP APPID
        'app_id'      => 'wxb3fxxxxxxxxxxx', // 公众号 APPID
        'miniapp_id'  => '', // 小程序 APPID
        'mch_id'      => '', //小程序或公众号商户号
        'mch_id_for_app'      => '',//app商户号
懂了吧

**Comment by huangxingx** [comment]
如果想在配置中像你那样配置的话, 那你可以加个适配, 如果是app支付的时候, 你把 mch_id 换成你业务配置中的 mch_id_for_app 然后传入 Pay::wechat 中.

**Comment by yangjingchuang** [comment]
你这种的还是和刚才的思路是一样的呢

**Comment by huangxingx** [comment]
底层是这样写的 如果不加适配的话,那就只有去改底层的方法,但是一般不推荐这样做

**Comment by yangjingchuang** [comment]
好滴吧

**Comment by huangxingx** [comment]
$config = [
    'app_id' => 'app_id1',
    'notify_url' => 'notify_url1',
    'return_url' => 'notify_url1',
];

$config2 = [
    'app_id' => 'app_id2',
    'notify_url' => 'notify_url2',
    'return_url' => 'return_url2',
];
$pay1 = Pay::wechat($config);
$pay2 = Pay::wechat($config2);

$pay1->mp([]);
$pay2->mp([]);

如果项目一开始就实例两个application的实例，前一个config 会被后一个覆盖， class Support 中 private static $instance; 是私有静态变量

**Comment by yansongda** [comment]
如果想在同一个 fpm 进程中使用多商户，可以先在第一个使用完后调用 support 类下的 clean 静态方法再进行其他商户的支付处理

**Comment by yhs603** [comment]
微信的多商户支付还是挺简单，支付宝的对应是咋弄的？

**Comment by yansongda** [comment]
v3 支持多租户，使用 v3 版本即可

**Comment by yhs603** [comment]
V3版本我看到了 我的意思是支付宝不能像微信一样直接在A商户建好APP后直接授权给B商户就可以完成多商户支付，具体的技术细则在支付宝官网文档没找着呢 @yansongda
