### ISSUE TITLE
支付宝，微信退款

### ISSUE THREAD

**Issue by chengjiezhou** [yansongda/pay#246]
## 问题描述
退款时，两个平台均报我app_id不正确的问题，可是，我的配置能够正常签名，并支付app完成付款

## 你的代码
       $pay_type = 'alipay';
$config = 'alipay' => [
        'app_id'        => ALIPAY_APP_ID,
        'notify_url'    => ALIPAY_NOTIFY_URL,
        'return_url'    => ALIPAY_RETURN_URL,
        'ali_public_key'=> ALIPAY_PUB_KEY,
        // 加密方式： **RSA2**
        'private_key'   => ALIPAY_PRI_KEY,

        'log' => [ // optional
            'file'      => ROOT_PATH.DS.'storage'.DS.'alilogs'.DS.'alipay.log',
            'level'     => 'info', // 建议生产环境等级调整为 info，开发环境为 debug
            'type'      => 'single', // optional, 可选 daily.
            'max_file'  => 30, // optional, 当 type 为 daily 时有效，默认 30 天
        ],
        'http' => [ // optional
            'timeout'   => 5.0,
            'connect_timeout' => 5.0,
            // 更多配置项请参考 [Guzzle](https://guzzle-cn.readthedocs.io/zh_CN/latest/request-options.html)
        ],
        'mode'          => 'dev', // optional,设置此参数，将进入沙箱模式
        'charset'       => 'utf-8'
    ];
        $factory = Pay::$pay_type($config);

        $order =[
                    'refund_amount' => $data['refund_amount']*0.01,
                    'trade_no'      => $data['consumer_trade_no'],
                    'refund_reason' => $data['extra'],
                    ];

        return $factory->refund($order);

## 报错详情
{
code: 4,
msg: "ERROR_GATEWAY: Get Alipay API Error:Invalid Arguments - isv.invalid-app-id",
data: ""
}

## sdk 日志

685 2019-05-31 00:31:50 > yansongda.pay.INFO > Alipay Refund Method Has Called ["https://openapi.alipaydev.com/gateway.do",{"app_id":"20190*****331316","method":"alipay.trade.refund","format":"JSON","charset":"ut    f-8","sign_type":"RSA2","version":"1.0","return_url":"https://zhouchengjie-notice-api.dev.muztg.com/alipay/notify","notify_url":"https://zhouchengjie-notice-api.dev.muztg.com/alipay/notify","timestamp":"2019-    05-31 00:31:50","sign":"","biz_content":"{\"refund_amount\":1,\"trade_no\":\"2019052722001462881039370459\",\"refund_reason\":\"\\u9000\\u6b3e\\u7684\\u8d76\\u7d27\"}","app_auth_token":null}]
686 
687 2019-05-31 00:31:50 > yansongda.pay.INFO > Alipay Refund Method Has Called ["https://openapi.alipaydev.com/gateway.do",{"app_id":"20190*****331316","method":"alipay.trade.refund","format":"JSON","charset":"ut    f-8","sign_type":"RSA2","version":"1.0","return_url":"https://zhouchengjie-notice-api.dev.muztg.com/alipay/notify","notify_url":"https://zhouchengjie-notice-api.dev.muztg.com/alipay/notify","timestamp":"2019-    05-31 00:31:50","sign":"","biz_content":"{\"refund_amount\":1,\"trade_no\":\"2019052722001462881039370459\",\"refund_reason\":\"\\u9000\\u6b3e\\u7684\\u8d76\\u7d27\"}","app_auth_token":null}]
688 
689 2019-05-31 00:31:50 > yansongda.pay.INFO > Alipay Refund Method Has Called ["https://openapi.alipaydev.com/gateway.do",{"app_id":"20190*****331316","method":"alipay.trade.refund","format":"JSON","charset":"ut    f-8","sign_type":"RSA2","version":"1.0","return_url":"https://zhouchengjie-notice-api.dev.muztg.com/alipay/notify","notify_url":"https://zhouchengjie-notice-api.dev.muztg.com/alipay/notify","timestamp":"2019-    05-31 00:31:50","sign":"","biz_content":"{\"refund_amount\":1,\"trade_no\":\"2019052722001462881039370459\",\"refund_reason\":\"\\u9000\\u6b3e\\u7684\\u8d76\\u7d27\"}","app_auth_token":null}]
690 
691 2019-05-31 00:31:51 > yansongda.pay.INFO > Alipay Refund Method Has Called ["https://openapi.alipaydev.com/gateway.do",{"app_id":"20190*****331316","method":"alipay.trade.refund","format":"JSON","charset":"ut    f-8","sign_type":"RSA2","version":"1.0","return_url":"https://zhouchengjie-notice-api.dev.muztg.com/alipay/notify","notify_url":"https://zhouchengjie-notice-api.dev.muztg.com/alipay/notify","timestamp":"2019-    05-31 00:31:51","sign":"","biz_content":"{\"refund_amount\":1,\"trade_no\":\"2019052722001462881039370459\",\"refund_reason\":\"\\u9000\\u6b3e\\u7684\\u8d76\\u7d27\"}","app_auth_token":null}]
692 
693 2019-05-31 00:31:51 > yansongda.pay.INFO > Alipay Refund Method Has Called ["https://openapi.alipaydev.com/gateway.do",{"app_id":"20190*****331316","method":"alipay.trade.refund","format":"JSON","charset":"ut    f-8","sign_type":"RSA2","version":"1.0","return_url":"https://zhouchengjie-notice-api.dev.muztg.com/alipay/notify","notify_url":"https://zhouchengjie-notice-api.dev.muztg.com/alipay/notify","timestamp":"2019-    05-31 00:31:51","sign":"","biz_content":"{\"refund_amount\":1,\"trade_no\":\"2019052722001462881039370459\",\"refund_reason\":\"\\u9000\\u6b3e\\u7684\\u8d76\\u7d27\"}","app_auth_token":null}]
694 
695 2019-05-31 09:55:17 > yansongda.pay.INFO > Alipay Refund Method Has Called ["https://openapi.alipaydev.com/gateway.do",{"app_id":"20190*****331316","method":"alipay.trade.refund","format":"JSON","charset":"ut    f-8","sign_type":"RSA2","version":"1.0","return_url":"https://zhouchengjie-notice-api.dev.muztg.com/alipay/notify","notify_url":"https://zhouchengjie-notice-api.dev.muztg.com/alipay/notify","timestamp":"2019-    05-31 09:55:17","sign":"","biz_content":"{\"refund_amount\":1,\"trade_no\":\"2019052722001462881039370459\",\"refund_reason\":\"\\u9000\\u6b3e\\u7684\\u8d76\\u7d27\"}","app_auth_token":null}]

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by Jason-cqtan** [comment]
'mode' => 'normal',
