### ISSUE TITLE
v2.7.6 沙箱通过 正式生产环境 验签出错,请确认charset参数放在了URL查询

### ISSUE THREAD

**Issue by yangguangwuwu** [yansongda/pay#247]
## 包版本号

v2.7.6
## 问题描述
沙箱通过
正式生产环境
验签出错,请确认charset参数放在了URL查询

**Comment by yangguangwuwu** [comment]
支付宝 wap支付

**Comment by yangguangwuwu** [comment]
解决方案
\vendor\yansongda\pay\src\Gateways\Alipay\Support.php  __construct方法
 61行改为   $this->baseUri = Alipay::URL[$config->get('mode', Alipay::MODE_NORMAL)].'?charset=utf-8';

**Comment by yangguangwuwu** [comment]
包版本号
v2.7.6

问题描述
沙箱通过
正式生产环境
验签出错,证书验证失败


换官方sdk通过

**Comment by yansongda** [comment]
请升级至 v2.8.2-beta.0 尝试解决

感谢支持

**Comment by yansongda** [comment]
fixed
