### ISSUE TITLE
laravel 中获取 不到 事件 

### ISSUE THREAD

**Issue by zoulux** [yansongda/pay#248]
## 包版本号
最新的 laravel-pay 2.0

## 问题描述

laravel 中获取 不到 事件 
## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yangguangwuwu** [comment]
新版事件系统是有报错的 你可以看你的 框架日志

**Comment by zoulux** [comment]
@yangguangwuwu 没有看到日志😅

**Comment by yansongda** [comment]
需要先初始化 支付类后，再添加 listener。

感谢支持

**Comment by zoulux** [comment]
看来源码终于明白了，因为在 laravel 中 pay 实例是延迟初始化的，感谢指点🤣🤣
