### ISSUE TITLE
关于验证微信通信标识的疑问

### ISSUE THREAD

**Issue by koulerz** [yansongda/pay#25]
微信支付结果通知 API 文档中说只有当 `return_code` (通信标识) 为 `SUCCESS` 时，返回信息中才有 `sign` 等字段，所以当 `return_code` (通信标识) 为 `FAIL` 时，下面这段代码会因为找不到 `$data['sign']` 报错吧？

```php
public function verify($data, $sign = null, $sync = false)
{
    $data = $this->fromXml($data);
    $sign = is_null($sign) ? $data['sign'] : $sign;
    return $this->getSign($data) === $sign ? $data : false;
}
```

[微信文档链接](https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=9_7)
[代码链接](https://github.com/yansongda/pay/blob/9596a9415dc2f0a0df97c3d09d9f37172fe7ef7a/src/Gateways/Wechat/Wechat.php#L143)

**Comment by yansongda** [comment]
敢问通讯表示为 false 的话，连腾讯的没管这种处理，这里需要管么？

PS：您的业务中有遇到这种情况？

**Comment by koulerz** [comment]
并没有遇到过这种情况，多谢回复。
