### ISSUE TITLE
支付宝支付成功后，回调时出现问题

### ISSUE THREAD

**Issue by sqw00453579** [yansongda/pay#250]
## 包版本号
yansongda/pay v2.7.6
thinkphp v5.1.37

## 问题描述
支付宝支付成功后，回调时出现问题。

## 你的代码
$alipay = alipayPay::alipay($config);
$data = $alipay->verify();
$this->merchant->updateOrder($data);
return $alipay->success()->send();

## 报错详情
[ error ] [16384]Calling the "Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()" method with the event name as first argument is deprecated since Symfony 4.3, pass it second and provide the event object first instead.

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
麻烦把详细的 日志发一下

感谢您的支持

**Comment by sqw00453579** [comment]
[ error ] [16384]Calling the "Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()" method with the event name as first argument is deprecated since Symfony 4.3, pass it second and provide the event object first instead.[/xxx/vendor/symfony/event-dispatcher/EventDispatcher.php:58]

symfony/event-dispatcher的CHANGELOG.md特别提到：
 * The signature of the `EventDispatcherInterface::dispatch()` method should be updated to `dispatch($event, string $eventName = null)`, not doing so is deprecated
 * deprecated the `Event` class, use `Symfony\Contracts\EventDispatcher\Event` instead

不懂是不是这个原因

**Comment by yansongda** [comment]
好的，验证后将修复

感谢支持

**Comment by yansongda** [comment]
您确认是 SDK 抛出的错误吗？刚刚验证了，SDK 是支持最新版本的。

麻烦发一下 SDK 自带的详细日志。

感谢
