### ISSUE TITLE
关于Yii  签名验证错误的解决办法

### ISSUE THREAD

**Issue by Thomastar** [yansongda/pay#256]
\vendor\yansongda\pay\src\Gateways\Alipay.php

加多一行
unset($data['r']);

`public function verify($data = null, $refund = false): Collection
    {
        if (is_null($data)) {
            $request = Request::createFromGlobals();

            $data = $request->request->count() > 0 ? $request->request->all() : $request->query->all();
            unset($data['r']);
            $data = Support::encoding($data, 'utf-8', $data['charset'] ?? 'gb2312');
        }

        if (isset($data['fund_bill_list'])) {
            $data['fund_bill_list'] = htmlspecialchars_decode($data['fund_bill_list']);
        }

        Events::dispatch(Events::REQUEST_RECEIVED, new Events\RequestReceived('Alipay', '', $data));

        if (Support::verifySign($data)) {
            return new Collection($data);
        }

        Events::dispatch(Events::SIGN_FAILED, new Events\SignFailed('Alipay', '', $data));

        throw new InvalidSignException('Alipay Sign Verify FAILED', $data);
    }`

![image](https://user-images.githubusercontent.com/17611854/60651919-c97aa400-9e79-11e9-8d79-0a85b6671555.png)

**Comment by yansongda** [comment]
框架或者 nginx 重写的时候加的，文档中有写

感谢支持
