### ISSUE TITLE
Undefined class constant 'SIGN_FAILED'

### ISSUE THREAD

**Issue by guoxiaod** [yansongda/pay#257]
## 包版本号
"yansongda/pay": "^2.7",

## 问题描述

PHP Fatal error:  Uncaught Error: Undefined class constant 'SIGN_FAILED' in vendor/yansongda/pay/src/Gateways/Alipay/Support.php:336

## 报错详情

PHP Fatal error:  Uncaught Error: Undefined class constant 'SIGN_FAILED' in vendor/yansongda/pay/src/Gateways/Alipay/Support.php:336

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

vendor/yansongda/pay/src/Gateways/Alipay/Support.php:336:        Events::dispatch(Events::SIGN_FAILED, new Events\SignFailed('Alipay', '', $result));

**Comment by yansongda** [comment]
composer update 即可

感谢支持
