### ISSUE TITLE
代金券的功能可以加上不

### ISSUE THREAD

**Issue by warshipJian** [yansongda/pay#258]
微信支付代金券业务是基于微信支付，为了协助商户方便地实现营销优惠措施。针对部分有开发能力的商户，微信支付提供通过API接口实现运营代金券的功能
https://pay.weixin.qq.com/wiki/doc/api/tools/sp_coupon.php?chapter=12_1

**Comment by yansongda** [comment]
后续功能考虑加上

感谢支持
