### ISSUE TITLE
异步回调问题

### ISSUE THREAD

**Issue by echoBallon** [yansongda/pay#26]
## 问题描述

支付宝异步认证的时候问题
## 代码
 

>    public function verify($data, $sign = null, $sync = false)
>     {
>         if (is_null($this->user_config->get('ali_public_key'))) {
>             throw new InvalidArgumentException('Missing Config -- [ali_public_key]');
>         }
> 
>         $sign = is_null($sign) ? $data['sign'] : $sign;
> 
>         $res = "-----BEGIN PUBLIC KEY-----\n".
>                 wordwrap($this->user_config->get('ali_public_key'), 64, "\n", true).
>                 "\n-----END PUBLIC KEY-----";
> 
>         $toVerify = $sync ? json_encode($data) : $this->getSignContent($data, true);
> 
>         return openssl_verify($toVerify, base64_decode($sign), $res, OPENSSL_ALGO_SHA256) === 1 ? $data : false;
>     }

## 报错详情

> 与配置项不一样

**Comment by yansongda** [comment]
请问怎样一个不一样 法？

**Comment by echoBallon** [comment]
支付宝回调的时候，是否配置项不一样，
![image](https://user-images.githubusercontent.com/24312654/33007579-5514974c-ce0a-11e7-915e-0e753e486c52.png)
![image](https://user-images.githubusercontent.com/24312654/33007590-62817c24-ce0a-11e7-9a2b-bafc9abfc438.png)

**Comment by echoBallon** [comment]
支付宝的支付宝公钥配置。
![image](https://user-images.githubusercontent.com/24312654/33007695-e1b49d64-ce0a-11e7-928e-5122ae074304.png)

![image](https://user-images.githubusercontent.com/24312654/33007703-ec657e4a-ce0a-11e7-95a9-2eddc51bf05b.png)

**Comment by echoBallon** [comment]
配置不同会导致,回调失败

**Comment by yansongda** [comment]
大哥，配置和代码不一样当然不可以的~

您的问题到底是什么呀

**Comment by echoBallon** [comment]
我的意思是laravel-pay 也就是你的sdk集成的pay.conf和你的支付宝集成的conf的配置文件的阿里公钥的key值是不一致的。

**Comment by yansongda** [comment]
您的第一张图的 `config.php` 文件不是 yansongda/pay 中的文件，也没有这个文件，麻烦您看清楚了。

谢谢
