### ISSUE TITLE
composer 安装之后，没有引入‘symfony\contracts’

### ISSUE THREAD

**Issue by penguinSeven** [yansongda/pay#262]
## 包版本号
2.7

## 问题描述

- 使用 composer 安装

```
composer require yansongda/pay -vvv
```

![微信图片_20190722173141](https://user-images.githubusercontent.com/12382455/61622338-2b734000-aca7-11e9-8efc-6d3c6781c2c4.png)

## 你的代码

- 测试demo 

```
public function actionIndex()
    {
        $order = [
            'out_trade_no' => time(),
            'total_amount' => '1',
            'subject' => 'test subject - 测试',
        ];

        $alipay = Pay::alipay($this->config)->web($order);


        return $alipay->send();// laravel 框架中请直接 `return $alipay`
    }
```

## 报错详情

![image](https://user-images.githubusercontent.com/12382455/61622305-1a2a3380-aca7-11e9-867a-8ad4653d40a9.png)

**Comment by penguinSeven** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/12382455/61622181-e0f1c380-aca6-11e9-853e-91302c58cd9e.png)

**Comment by penguinSeven** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/12382455/61622259-0383dc80-aca7-11e9-9d49-c2f6d8b3fcca.png)

**Comment by penguinSeven** [comment]
> ## 包版本号
> 2.7
> 
> ## 问题描述
> * 使用 composer 安装
> 
> ```
> composer require yansongda/pay -vvv
> ```
> 
> ![微信图片_20190722173141](https://user-images.githubusercontent.com/12382455/61622338-2b734000-aca7-11e9-8efc-6d3c6781c2c4.png)
> 
> ## 你的代码
> * 测试demo
> 
> ```
> public function actionIndex()
>     {
>         $order = [
>             'out_trade_no' => time(),
>             'total_amount' => '1',
>             'subject' => 'test subject - 测试',
>         ];
> 
>         $alipay = Pay::alipay($this->config)->web($order);
> 
> 
>         return $alipay->send();// laravel 框架中请直接 `return $alipay`
>     }
> ```
> 
> ## 报错详情
> ![image](https://user-images.githubusercontent.com/12382455/61622305-1a2a3380-aca7-11e9-867a-8ad4653d40a9.png)

**Comment by penguinSeven** [comment]
## 临时解决

```
composer update symfony/contracts -vvv
```

**Comment by penguinSeven** [comment]
## 新问题， “Illegal offset type”， 调用数组的时候，数组变量的键名使用了数组。

- 报错

![image](https://user-images.githubusercontent.com/12382455/61624266-dd603b80-acaa-11e9-82e6-08d7292ac7de.png)

-  打印
![image](https://user-images.githubusercontent.com/12382455/61624430-24e6c780-acab-11e9-890a-006f7dbbf25f.png)


- 输出

![image](https://user-images.githubusercontent.com/12382455/61624398-17314200-acab-11e9-8b02-47a6199fb103.png)

**Comment by Nxir** [comment]
@penguinSeven 你好  我遇到了同样的问题 请问是怎么解决的

**Comment by wersion** [comment]
是啊 解决掉么
