### ISSUE TITLE
私钥文件路径格式自动添加 file:// 

### ISSUE THREAD

**Issue by delpan7** [yansongda/pay#264]
vendor\yansongda\pay\src\Gateways\Alipay\Support.php
openssl_pkey_get_private 读取文件私钥时需要绝对路径且路径前要加上 file:// 才能读取成功
当支付宝配置公私钥为文件时希望程序上能加个自动判断是否绝对路径，和是否有file://，不然得调试半天

**Comment by yansongda** [comment]
后续考虑加上，感谢支持

**Comment by yansongda** [comment]
已更新

欢迎体验

**Comment by delpan7** [comment]
谢谢

**Comment by delpan7** [comment]
你好，private_key  是没问题了，但ali_public_key 没改

**Comment by yansongda** [comment]
升级到最新版即可

感谢支持
