### ISSUE TITLE
微信统一下单 单品优惠这个功能是没有吗？

### ISSUE THREAD

**Issue by mohuidong** [yansongda/pay#266]
https://pay.weixin.qq.com/wiki/doc/api/danpin.php?chapter=9_102&index=2
看微信的文档是加三个参数，但是加了之后好像没有什么效果，是没有这个功能吗？

**Comment by yansongda** [comment]
微信新增的功能，暂不支持，将在后续版本中接入。

欢迎 PR

感谢支持

**Comment by mohuidong** [comment]
那我想在本地扩展一下这个功能 改在哪呢

**Comment by mohuidong** [comment]
不用扩展 可用

**Comment by yansongda** [comment]
是的，刚仔细看了微信文档，现有 sdk 是可用的。

感谢支持
