### ISSUE TITLE
微信下载账单判断未判断异常

### ISSUE THREAD

**Issue by xiaozan** [yansongda/pay#267]
## 包版本号
latest

## 问题描述
微信下载账单未判断异常，比如微信返回的invalid bill_date(20001)错误

## 代码位置
Yansongda\Pay\Gateways\Wechat::download()

## 提议方案
~~使用Support::requestApi()方法替代Support::getInstance()->post()~~
检测返回结果是否为xml，如果是则解析后抛出Exception

**Comment by yansongda** [comment]
感谢支持，将在后续版本中优化
