### ISSUE TITLE
微信查询退款订单

### ISSUE THREAD

**Issue by ligenhui** [yansongda/pay#270]
## 包版本号
"yansongda/pay": "^2.7"

## 问题描述
微信查询退款订单报错

## 你的代码
$wechat->find(['out_trade_no' => xxx)], 'refund');

## 报错详情
Class Yansongda\Pay\Gateways\Wechat\RefundGateway contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Yansongda\Pay\Gateways\Wechat\Gateway::pay, Yansongda\Pay\Gateways\Wechat\Gateway::getTradeType)

**Comment by yansongda** [comment]
请 composer update 升级至最新版

感谢支持
