### ISSUE TITLE
Class 'Symfony\\Contracts\\EventDispatcher\\Event' not found

### ISSUE THREAD

**Issue by serrt** [yansongda/pay#271]
## 包版本号
"yansongda/laravel-pay": "2.0.2"

laravel: 5.7.*

## 问题描述
在调用支付宝支付的时候, 出现的错误

## 你的代码

```php
use Yansongda\LaravelPay\Facades\Pay;

$data = Pay::alipay()->scan([
    'out_trade_no' => $order->out_trade_no,
    'total_amount' => 1,
    'subject' => $body
]);
```

## 报错详情

```json
{
    "message": "Class 'Symfony\\Contracts\\EventDispatcher\\Event' not found",
    "exception": "Symfony\\Component\\Debug\\Exception\\FatalErrorException",
    "file": "***/vendor/yansongda/pay/src/Events/Event.php",
    "line": 7,
    "trace": []
}
```

**Comment by yansongda** [comment]
请使用 composer 安装

感谢支持

**Comment by serrt** [comment]
额，我是用 composer 装的。也不知道为什么会出现这个情况😂

**Comment by 1498610150** [comment]
你好 请问你解决了么?  我也提示了这种报错, 我是用composer安装的 还安装了两边 composer require yansonda/pay

**Comment by wersion** [comment]
我也是使用composer出现了同样的问题。。。

**Comment by wersion** [comment]
找了好久，分析composer.lock中关于symfony/contracts 的版本，发现因为当前的lock文件是好久以前更新过的了，所以当前symfony/contracts版本竟然是1.0.2的，而当前需要的是有Symfony\\Contracts\\EventDispatcher\\Event类的版本，是最新版本中加入了该类。所以，直接执行 composer update -vvv  更新到最新版本就好了

**Comment by gygygbm** [comment]
建议不要composer update -vvv，所有的包都更新，导致框架和部分包不兼容，升级这个包composer update symfony/event-dispatcher -vvv，问题解决
