### ISSUE TITLE
使用沙箱环境报错

### ISSUE THREAD

**Issue by MrYuLei** [yansongda/pay#273]
使用支付宝沙箱环境经常出现这个错误：
ERROR_GATEWAY: Get Alipay API Error:Service Currently Unavailable - aop.SYSTEM_ERROR

**Comment by kliyadongkingks** [comment]
这么久 过去了，什么原因找到了吗？

**Comment by coder-yau** [comment]
我也是沙箱环境。目前用作者的demo测试了PC端网页支付，能支付成功。但是异步和同步通知验证都是false
