### ISSUE TITLE
应用公钥证书模式需要如何配置？

### ISSUE THREAD

**Issue by wu-weichao** [yansongda/pay#274]
## 问题描述
应用公钥证书模式需要如何配置？
![image](https://user-images.githubusercontent.com/23071875/63695726-dac5a880-c84b-11e9-9f6d-eb78e31c9fc2.png)

**Comment by 1498610150** [comment]
PHP 暂不支持公钥证书模式

**Comment by 0377** [comment]
可以参考这篇文章，配置公钥证书
[https://sbing.vip/archives/2019-new-alipay-php-docking.html](https://sbing.vip/archives/2019-new-alipay-php-docking.html)

**Comment by 191834552** [comment]
我申请了，但是现在没有对应的composer包。难受

**Comment by liangshuocj** [comment]
> 我申请了，但是现在没有对应的composer包。难受

请问找到可以使用的包了吗？
