### ISSUE TITLE
请问下，pos 刷卡支付，支持国外的信用卡或者储蓄卡吗？

### ISSUE THREAD

**Issue by gyp719** [yansongda/pay#275]
pos 刷卡支付，支持国外的信用卡或者储蓄卡吗？
能否支付 PayPal？

**Comment by yansongda** [comment]
国外信用卡或储蓄卡 的支持情况请查看 支付宝/微信支付

PayPal 的支持或许后续版本会支持吧，但近段时间应该不会，不过欢迎 PR

感谢支持
