### ISSUE TITLE
实例化之后，运行途中修改config参数

### ISSUE THREAD

**Issue by dreamingOf** [yansongda/pay#277]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yansongda** [comment]
可以先调用 `Alipay/Support::clear()`、`Wechat/Support::clear()` 方法，然后再进行初始化调用

https://github.com/yansongda/pay/blob/master/src/Gateways/Alipay/Support.php#L106

感谢支持
