### ISSUE TITLE
建议增加退款相关文档

### ISSUE THREAD

**Issue by FaithPatrick** [yansongda/pay#28]
## 问题描述
目前文档中已说明所有网关均支持 refund 方法，支付宝退款 $config_biz 传入订单号即可，但微信支付退款传入的配置项并未说明，建议完善一下退款的文档哦，谢谢。

**Comment by FaithPatrick** [comment]
我试了下，微信支付退款需要传的最小配置参数：

参数 | 备注 
----|------
out_trade_no | 商户平台订单号
out_refund_no | 商户平台生成的退款单号  
total_fee |  订单金额
refund_fee | 退款金额

**Comment by FaithPatrick** [comment]
对了，我用的是 Laravel 包，基础的支付配置已经写在配置文件里了，上述给出的最小配置不包含基础配置。

**Comment by yansongda** [comment]
因为退款较简单，所以没写文档，不过，确实是需要完善了。

我找时间完善下，同时欢迎 PR

感谢您的支持

**Comment by yansongda** [comment]
是的，支付宝和微信对退款没有做异步通知

**Comment by jwwb681232** [comment]
谢谢

**Comment by yansongda** [comment]
2.x 已发布，所有文档已经完善。麻烦请升级到最新版本。

感谢您的支持！

**Comment by anyforever** [comment]
@jwwb681232 微信退款异步通知，需要在商户系统里设置 。支付宝的还没有看
 https://pay.weixin.qq.com/index.php/core/refundconfig
