### ISSUE TITLE
微信分账功能

### ISSUE THREAD

**Issue by pianqifei** [yansongda/pay#285]
希望可以尽快支持微信分账功能
![image](https://user-images.githubusercontent.com/26913071/66623212-3772fc00-ec1d-11e9-9bf3-f4192d683838.png)

**Comment by weir008** [comment]
同需要微信分账, 希望大佬抽空安排一下~

**Comment by heshiweij** [comment]
求分账功能

**Comment by calchen** [comment]
https://github.com/yansongda/pay/issues/345#issuecomment-618146606

“下个版本考虑使用”
