### ISSUE TITLE
微信退款 curl 58错误

### ISSUE THREAD

**Issue by kg-rose** [yansongda/pay#293]
## 包版本号
2.5

## 问题描述
微信退款的时候出了curl 58，在openssl版本过低时候会出现这个问题。

## 报错详情
could not load PEM client certificate, OpenSSL error error:140AB18E:SSL routines:SSL_CTX_use_certificate:ca md too weak, (no key found, wrong pass phrase, or wrong file format?)

**Comment by binxyz** [comment]
你这个应该是证书  没有配置正确，报错信息提示了
