### ISSUE TITLE
微信h5支付成功后，如何设置回调地址？

### ISSUE THREAD

**Issue by datangkang123** [yansongda/pay#298]
回调页面
正常流程用户支付完成后会返回至发起支付的页面，如需返回至指定页面，则可以在MWEB_URL后拼接上redirect_url参数，来指定回调页面。
这个怎么加？

**Comment by datangkang123** [comment]
已经找到了，原来和支付宝一样，感谢了。

**Comment by Captain1** [comment]
@datangkang123 回调里面报文为空，verify()会报xml解析错误，打印$request没有发现所需要的参数内容

**Comment by 724008158** [comment]
$mweb_url                    = $wechat->wap($config)->getTargetUrl();

**Comment by yansongda** [comment]
麻烦尝试使用最新 v3 版

感谢支持
