### ISSUE TITLE
可以考虑增加支付宝支付能力中其他接口

### ISSUE THREAD

**Issue by involvements** [yansongda/pay#3]
可以考虑增加支付宝支付能力中其他接口
如转账到支付宝帐户https://doc.open.alipay.com/docs/doc.htm?spm=a219a.7629140.0.0.YGnnYd&treeId=193&articleId=106236&docType=1

**Comment by yansongda** [comment]
有道理，应该会在后续版本中逐步增加。

同时，欢迎 Fork 并 PR！
