### ISSUE TITLE
支付宝wap支付在生成跳转 URL，不是生成提交的<form>表单

### ISSUE THREAD

**Issue by myttyy** [yansongda/pay#300]
遇到一个业务需求，最终需要返回
{
"url": "https://openapi.alipay.com/gateway.do?charset=utf-8?app_id=xxxxx"
}
这样的URL地址给客户端自己完成请求，而不是输出HTML到页面完成支付宝的跳转 
请问题下大佬们这个包有什么好的解决方案？

**Comment by yansongda** [comment]
http_method 参数，仔细看文档

**Comment by myttyy** [comment]
好的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "yansongda"<notifications@github.com&gt;; 
发送时间: 2019年11月1日(星期五) 下午3:50
收件人: "yansongda/pay"<pay@noreply.github.com&gt;; 
抄送: "10000"<1297942619@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [yansongda/pay] 支付宝wap支付在生成跳转 URL，不是生成提交的<form&gt;表单 (#300)




http_method 参数，仔细看文档
