### ISSUE TITLE
laravel-pay中调用alipay->success()后还会陆续接到支付宝的通知

### ISSUE THREAD

**Issue by wanghanwanghan** [yansongda/pay#301]
## 包版本号
最新版

## 问题描述
laravel-pay中调用alipay->success()后还会陆续接到支付宝的通知

## 你的代码
$alipay->success()

**Comment by martaintao** [comment]
同问

**Comment by krissss** [comment]
支付宝存在3个月后会发送回调，通知商户订单关闭（不可退款）

**Comment by Yuii-guoguo** [comment]
常用包也会收到多次回调
