### ISSUE TITLE
http://pay.yansongda.cn/ 打不开了

### ISSUE THREAD

**Issue by imzhi** [yansongda/pay#302]
## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by imzhi** [comment]
看不到事件详细文档

**Comment by yansongda** [comment]
已经恢复了-------- 原始邮件 --------发件人： imzhi <notifications@github.com>日期： 2019年11月18日周一 16:54收件人： yansongda/pay <pay@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [yansongda/pay] http://pay.yansongda.cn/ 打不开了 (#302)包版本号

问题描述

你的代码

报错详情

sdk 日志

nginx/apache 日志



涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by imzhi** [comment]
谢谢~

在 2019-11-19 08:48:43，"yansongda" <notifications@github.com> 写道：
已经恢复了-------- 原始邮件 --------发件人： imzhi <notifications@github.com>日期： 2019年11月18日周一 16:54收件人： yansongda/pay <pay@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主 题： [yansongda/pay] http://pay.yansongda.cn/ 打不开了 (#302)包版本号
问题描述
你的代码
报错详情
sdk 日志
nginx/apache 日志

涉及到 异步通知、同步通知 的问题，请贴出来
