### ISSUE TITLE
支付宝同步通知验签失败，$data数组多了['s'=>'api/pay/alipay-return']参数呢？

### ISSUE THREAD

**Issue by lisgroup** [yansongda/pay#303]
## 包版本号
 "yansongda/laravel-pay": "^2.1"

## 问题描述
正式环境支付宝同步通知验签失败，
Alipay.php 中的 verify() 方法，其中参数 $data 数组多了['s'=>'api/pay/alipay-return']参数呢？

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
请检查所使用框架是否路由自带参数

此参数和 sdk 无关

感谢支持
