### ISSUE TITLE
为啥能发起支付能付钱，申请退款也能到账就是查询支付状态 和 申请退款返回报INVALID_SIGN: Alipay Sign Verify FAILED

### ISSUE THREAD

**Issue by itwangshun** [yansongda/pay#314]
为啥能发起支付能付钱，申请退款也能到账就是查询支付状态 和 申请退款返回报INVALID_SIGN: Alipay Sign Verify FAILED

**Comment by itwangshun** [comment]
return_url等其他参数 也都要对 之前return_url写的m.alipay.com 就导致了这种奇怪的问题 很坑

**Comment by liron-li** [comment]
解决了吗？我也遇到了相同的问题
