### ISSUE TITLE
签名使用MD5，该如何配置？

### ISSUE THREAD

**Issue by Tamn9208** [yansongda/pay#32]
暂时只获取到md5的秘钥，该如何配置呢？

**Comment by yansongda** [comment]
您好，不推荐也不支持使用 MD5 秘钥。

您使用的应该是老版本的 API，建议升级至最新版本 API。

感谢您的支持。

**Comment by Tamn9208** [comment]
请问不支持沙箱测试吗？ @yansongda

**Comment by Tamn9208** [comment]
请问不支持沙箱测试吗？ @yansongda

**Comment by yansongda** [comment]
沙箱支持，只需自行修改相关 endpoint 即可
