### ISSUE TITLE
$alipay->transfer() 转账方法必须使用 API证书

### ISSUE THREAD

**Issue by zhouzishu** [yansongda/pay#325]
错误：
```php
Yansongda\Pay\Exceptions\GatewayException
ERROR_GATEWAY: Get Alipay API Error:Invalid Arguments - isv.missing-app-cert-sn
```

使用转账接口提示错误，支付宝最新接口要求 `支付宝开放的接口中，涉及资金支出的接口需要使用到API证书，包括转账、退款等接口` 。

**Comment by iiDestiny** [comment]
@zhouzishu 你用其他的包吗？

**Comment by gyp719** [comment]
> 错误：
> 
> ```
> Yansongda\Pay\Exceptions\GatewayException
> ERROR_GATEWAY: Get Alipay API Error:Invalid Arguments - isv.missing-app-cert-sn
> ```
> 
> 使用转账接口提示错误，支付宝最新接口要求 `支付宝开放的接口中，涉及资金支出的接口需要使用到API证书，包括转账、退款等接口` 。

我配置的也是证书模式，和你一样的报错，请问你解决了吗？

**Comment by iiDestiny** [comment]
@gyp719 我解决了，请问你 php 是什么版本。

**Comment by gyp719** [comment]
> @gyp719 我解决了，请问你 php 是什么版本。

PHP 7.2

**Comment by iiDestiny** [comment]
@gyp719 我提了一个 PR 可能作者还没有发布新版本，php7.2 之后有一个精度问题，你可以在服务器上面手动修改一下，之后作者可能会发布

https://github.com/yansongda/pay/pull/335  你可以按照我的 PR 修改

**Comment by iiDestiny** [comment]
我看 v2.9.3 版本发布了，你可以更新一下，如果你还是报错你得检查一下你证书了。

**Comment by gyp719** [comment]
> 看 v2.9.3 版本发布了，你可以更新一下，如果你还是报错你得检查一下你证书了。
已经更新了， Updating yansongda/pay (v2.9.0 => v2.9.3): Loading from cache

可以加微信 交流下吗？   gyp719

**Comment by gyp719** [comment]
> 我看 v2.9.3 版本发布了，你可以更新一下，如果你还是报错你得检查一下你证书了。

ERROR_GATEWAY: Get Alipay API Error:Business Failed - INVALID_PARAMETER

wab 端拉取支付 确实 OK

**Comment by crazyfd** [comment]
php 7.4
接口返回是成功，但是做校验出现异常

 openssl_verify(): supplied key param cannot be coerced into a public key
\vendor\yansongda\pay\src\Gateways\Alipay\Support.php:222

日志记录是成功得，
Result Of Alipay Api {"alipay_fund_trans_uni_transfer_response":{"code":"10000","msg":"Success","order_id":"20201130110070000006200014420221","out_biz_no":"5fc4cd40189c4","pay_fund_order_id":"20201130110070001506200018862671","status":"SUCCESS","trans_date":"2020-11-30 18:45:20"},"alipay_cert_sn":"b5463deac50
