### ISSUE TITLE
支付宝转账问题

### ISSUE THREAD

**Issue by gyp719** [yansongda/pay#327]
支付宝转账 到支付宝账户可以， 请问下支付 转账到银行卡吗？

**Comment by krissss** [comment]
暂时不支持，因为不支持公钥证书模式 #316

**Comment by krissss** [comment]
已经支持了。。。刚看到 #288

**Comment by gyp719** [comment]
> 已经支持了。。。刚看到[＃288](https://github.com/yansongda/pay/pull/288)

新版的 已经支付了

**Comment by iiDestiny** [comment]
@gyp719 亲，你这边可以转正成功么？
