### ISSUE TITLE
关于支付宝单笔转账的问题报错，ERROR_GATEWAY: Get Alipay API Error:Business Failed - INVALID_PARAMETER

### ISSUE THREAD

**Issue by guihouchang** [yansongda/pay#339]
## 包版本号
v2.9.3

## 问题描述
使用最新版本的转账接口会报
ERROR_GATEWAY: Get Alipay API Error:Business Failed - INVALID_PARAMETER这个错误
提示是参数不正确。

## 你的代码
        $order = [
            'out_biz_no' => time(),
            'trans_amount' => 23.00,
            'product_code' => 'TRANS_ACCOUNT_NO_PWD',
            'payee_info' => [
                'identity' => 'pewwne3062@sandbox.com',
                'identity_type' => 'ALIPAY_LOGON_ID',
                'name' => '沙箱环境',
            ]
        ];

$alipay = Pay::alipay($this->payConfig)->transfer($order);

## 报错详情
ERROR_GATEWAY: Get Alipay API Error:Business Failed - INVALID_PARAMETER
后经过经过进一步测试，将TransferGateway中的
$payload['method'] = 'alipay.fund.trans.uni.transfer';
改为
$payload['method'] = 'alipay.fund.trans.toaccount.transfer';
并修改请求的参数
$order = [
            'out_biz_no' => time(),
            'amount' => 23.00,
            'product_code' => 'TRANS_ACCOUNT_NO_PWD',
            'payee_type' => 'ALIPAY_LOGONID',
            'payee_account' => 'pewwne3062@sandbox.com',

        ];
能请求成功,希望能解决下
## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by guihouchang** [comment]
补充下， 把版本降低到v2.8.6使用旧接口，但是会提示签名失败
"40002" "Invalid Arguments" "isv.invalid-signature"

**Comment by gyp719** [comment]
> ## 包版本号
> v2.9.3
> 
> ## 问题描述
> 使用最新版本的转账接口会报
> ERROR_GATEWAY: Get Alipay API Error:Business Failed - INVALID_PARAMETER这个错误
> 提示是参数不正确。
> 
> ## 你的代码
> ```
>     $order = [
>         'out_biz_no' => time(),
>         'trans_amount' => 23.00,
>         'product_code' => 'TRANS_ACCOUNT_NO_PWD',
>         'payee_info' => [
>             'identity' => 'pewwne3062@sandbox.com',
>             'identity_type' => 'ALIPAY_LOGON_ID',
>             'name' => '沙箱环境',
>         ]
>     ];
> ```
> 
> $alipay = Pay::alipay($this->payConfig)->transfer($order);
> 
> ## 报错详情
> ERROR_GATEWAY: Get Alipay API Error:Business Failed - INVALID_PARAMETER
> 后经过经过进一步测试，将TransferGateway中的
> $payload['method'] = 'alipay.fund.trans.uni.transfer';
> 改为
> $payload['method'] = 'alipay.fund.trans.toaccount.transfer';
> 并修改请求的参数
> $order = [
> 'out_biz_no' => time(),
> 'amount' => 23.00,
> 'product_code' => 'TRANS_ACCOUNT_NO_PWD',
> 'payee_type' => 'ALIPAY_LOGONID',
> 'payee_account' => '[pewwne3062@sandbox.com](mailto:pewwne3062@sandbox.com)',
> 
> ```
>     ];
> ```
> 
> 能请求成功,希望能解决下
> 
> ## sdk 日志
> ## nginx/apache 日志
> > 涉及到 异步通知、同步通知 的问题，请贴出来

你的支付宝配置 是用的 RSA 密钥模式 还是 公钥证书 模式？

**Comment by guihouchang** [comment]
> > ## 包版本号
> > v2.9.3
> > ## 问题描述
> > 使用最新版本的转账接口会报
> > ERROR_GATEWAY: Get Alipay API Error:Business Failed - INVALID_PARAMETER这个错误
> > 提示是参数不正确。
> > ## 你的代码
> > ```
> >     $order = [
> >         'out_biz_no' => time(),
> >         'trans_amount' => 23.00,
> >         'product_code' => 'TRANS_ACCOUNT_NO_PWD',
> >         'payee_info' => [
> >             'identity' => 'pewwne3062@sandbox.com',
> >             'identity_type' => 'ALIPAY_LOGON_ID',
> >             'name' => '沙箱环境',
> >         ]
> >     ];
> > ```
> > 
> > 
> > $alipay = Pay::alipay($this->payConfig)->transfer($order);
> > ## 报错详情
> > ERROR_GATEWAY: Get Alipay API Error:Business Failed - INVALID_PARAMETER
> > 后经过经过进一步测试，将TransferGateway中的
> > $payload['method'] = 'alipay.fund.trans.uni.transfer';
> > 改为
> > $payload['method'] = 'alipay.fund.trans.toaccount.transfer';
> > 并修改请求的参数
> > $order = [
> > 'out_biz_no' => time(),
> > 'amount' => 23.00,
> > 'product_code' => 'TRANS_ACCOUNT_NO_PWD',
> > 'payee_type' => 'ALIPAY_LOGONID',
> > 'payee_account' => '[pewwne3062@sandbox.com](mailto:pewwne3062@sandbox.com)',
> > ```
> >     ];
> > ```
> > 
> > 
> > 能请求成功,希望能解决下
> > ## sdk 日志
> > ## nginx/apache 日志
> > > 涉及到 异步通知、同步通知 的问题，请贴出来
> 
> 你的支付宝配置 是用的 RSA 密钥模式 还是 公钥证书 模式？

证书模式

**Comment by gyp719** [comment]
v2.9.3  的 转账问题，可以实现吗

**Comment by guihouchang** [comment]
> v2.9.3 的 转账问题，可以实现吗

可以，你fork一个自己改下转账接口。

**Comment by gyp719** [comment]
> > v2.9.3 的 转账问题，可以实现吗
> 
> 可以，你fork一个自己改下转账接口。

如何修改，能否 给一个示例？是公钥证书模式

**Comment by gyp719** [comment]
> > v2.9.3 的 转账问题，可以实现吗
> 
> 可以，你fork一个自己改下转账接口。

https://github.com/yansongda/pay/issues/339#issuecomment-611362665

按照 你上面的修改确实是可以实现转账到支付宝，但是 无法转账到银行卡的

**Comment by guihouchang** [comment]
> > > v2.9.3 的 转账问题，可以实现吗
> > 
> > 
> > 可以，你fork一个自己改下转账接口。
> 
> [#339 (comment)](https://github.com/yansongda/pay/issues/339#issuecomment-611362665)
> 
> 按照 你上面的修改确实是可以实现转账到支付宝，但是 无法转账到银行卡的

银行卡的接口支付宝已经不再使用了

**Comment by whitegraduate** [comment]
> > v2.9.3 的 转账问题，可以实现吗
> 
> 可以，你fork一个自己改下转账接口。

请问对于单笔转账要求填入姓名的情况如何处理。（一个账户对于多个账号要求传入姓名参数）
文档中没有查询到相关参数配置，官网的参数也是无效的。

**Comment by vipszx** [comment]
试了下需要再添加biz_scene参数
```php
$order = [
            'out_biz_no' => time(),
            'trans_amount' => 1,
            'product_code' => 'TRANS_ACCOUNT_NO_PWD',
            'biz_scene' => 'DIRECT_TRANSFER', //**添加这个参数**
            'payee_info' => [
                'identity' => 'pewwne3062@sandbox.com',
                'identity_type' => 'ALIPAY_LOGON_ID',
                'name' => '沙箱环境',
            ],
        ];
```

**Comment by f1999** [comment]
除了改成之前的转账接口，还有什么办法么，现在用最新的还是会报这个错
