### ISSUE TITLE
Wechat App 支付，Error:appid参数长度有误

### ISSUE THREAD

**Issue by pengxul** [yansongda/pay#343]
"yansongda/pay": "^2.9"

微信APP调用统一下单接口， 返回
ERROR_GATEWAY: Get Wechat API Error:appid参数长度有误

$order = [
    'out_trade_no' => time(),
    'body' => 'subject-测试',
    'total_fee' => '1',
];

ERROR_GATEWAY: Get Wechat API Error:appid参数长度有误

yansongda.pay.DEBUG > Result Of Wechat Api {"return_code":"FAIL","return_msg":"签名错误"}

**Comment by pengxul** [comment]
我定位问题是vendor/yansongda/pay/src/Gateways/Wechat/AppGateway.php line 31，

**Comment by zengbiwen** [comment]
我也遇到这个问题，可以把配置里的app_id改成appid
