### ISSUE TITLE
支付宝app支付的方式返回的数据为空

### ISSUE THREAD

**Issue by fangming666** [yansongda/pay#344]
环境：
php >7
yansongda/pay 2.9.3

问题描述：我使用组件提供的->app方法将订单传递进去，但是返回的信息却是空的，appid和相关参数都已经配置齐全，而且也申请了app支付

相关代码：
`if ($trade_type == 'app') {
            $result = $pay->app($order);
            $out['info'] = json_decode($result->getContent());
            return ApiService::success($out);
        }`

实际调用
`code: 0
msg: "ok"
data: {info: null}
info: null
errors: null`

**Comment by yansongda** [comment]
如果还有问题麻烦尝试使用最新 v3 版

感谢支持

**Comment by yansongda** [comment]
如果还有问题麻烦尝试使用最新 v3 版

感谢支持
