### ISSUE TITLE
支付宝切换服务商出现错误，希望尽快修复

### ISSUE THREAD

**Issue by Rmiku** [yansongda/pay#347]
## 环境
yansongda/pay v2.9.3
php v7.3.6
laravel v6.18.7

## 问题描述

支付宝切换到服务商下报错

## 你的代码
```
$config = [
    ....
    'mode' => 'service',
    'pid'  => '...',
];

$order = [
            'out_trade_no'     =>'20200422113840286',
            'subject'          => '测试订单',
            'total_amount'     => 0.01,
            'terminal_id'      => request()->getClientIp(),
            'scene'            => 'bar_code',
            'auth_code'        => '...',
            'timeout_express'  => '1m',
];

$app = Pay::alipay($config);
$app->pos($order)->toArray();
```
## 报错详情
1.  `Undefined index: service` In Class  Yansongda\Pay\Gateways\Alipay\Support.php line: 61
2. Class Yansongda\Pay\Gateways\Alipay\PosGateway.php line:31 `(!empty(Support::getInstance()->pid)))` 此处值为false(config携带了pid的情况下) , 请求参数无法携带 pid，且在$biz_array没有 extend_params 属性的情况下，会报 `Undefined index: extend_params`

注：已看到有修复bug申请中有修复支付宝服务商的申请，希望尽快修复该问题，出个版本

**Comment by yansongda** [comment]
由于并没有验证支付宝服务商模式在 sdk 的可行性，所以才并未合并 #342  的

考虑晚些时候先出个 beta 版吧

感谢支持

**Comment by Rmiku** [comment]
感谢，希望早日看到新版本😃
