### ISSUE TITLE
支付宝统一收单接口(网站支付/app支付)不可以返回支付链接

### ISSUE THREAD

**Issue by LiuMicah** [yansongda/pay#348]
## 问题描述
支付宝统一收单接口(网站支付/app支付), 部分业务场景是返回一个支付链接, 而不是html文件, 有可以直接获取支付链接的形式么?建议可以做一些内置的参数, 可以选择获取不同形式的响应参数 

## 你的代码
 /**
     * Build Html response.
     *
     * @author yansongda <me@yansongda.cn>
     *
     * @param string $endpoint
     * @param array  $payload
     * @param string $method
     *
     * @return Response
     */
    protected function buildPayHtml($endpoint, $payload, $method = 'POST'): Response
    {
        if (strtoupper($method) === 'GET') {
            return RedirectResponse::create($endpoint.'?'.http_build_query($payload));
        }

        $sHtml = "<form id='alipay_submit' name='alipay_submit' action='".$endpoint."' method='".$method."'>";
        foreach ($payload as $key => $val) {
            $val = str_replace("'", '&apos;', $val);
            $sHtml .= "<input type='hidden' name='".$key."' value='".$val."'/>";
        }
        $sHtml .= "<input type='submit' value='ok' style='display:none;'></form>";
        $sHtml .= "<script>document.forms['alipay_submit'].submit();</script>";

        return Response::create($sHtml);
    }

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by Ynwasususama** [comment]
同问 如何知道链接 抖音小程序那边需要aplipay_url

**Comment by Ynwasususama** [comment]
@LiuMicah 好像把send去掉直接getContent()就能获取到里面的参数那些了

**Comment by luosmallluo** [comment]
看这里
https://pay.yanda.net.cn/docs/2.x/others/faq

**Comment by iLay1678** [comment]
订单参数添加 'http_method'  => 'GET' 然后$response->getTargetUrl() 可获取跳转链接
