### ISSUE TITLE
composer require yansongda/pay -vvv 

### ISSUE THREAD

**Issue by sunjdk** [yansongda/pay#349]
Dependency resolution completed in 0.067 seconds
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install yansongda/pay v2.9.3
    - Conclusion: don't install yansongda/pay v2.9.2
    - Conclusion: don't install yansongda/pay v2.9.1
    - Conclusion: remove symfony/http-foundation v3.4.40
    - Installation request for yansongda/pay ^2.9 -> satisfiable by yansongda/pay[v2.9.0, v2.9.1, v2.9.2, v2.9.3].
    - Conclusion: don't install symfony/http-foundation v3.4.40
    - yansongda/pay v2.9.0 requires symfony/http-foundation ^4.0 -> satisfiable by symfony/http-foundation[v4.0.0, v4.0.1, v4.0.10, v4.0.11, v4.0.12, v4.0.13, v4.0.14, v4.0.15, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.2, v4.1.3, v4.1.4, v
4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.0, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.1, v4.3.10, v4.3.11, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9, v4.4.0, v4.4.1, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6, v4.4.7, v
4.4.8].
    - Can only install one of: symfony/http-foundation[v4.0.0, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.0.1, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.0.10, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.0.11, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.0.12, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.0.13, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.0.14, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.0.15, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.0.2, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.0.3, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.0.4, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.0.5, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.0.6, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.0.7, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.0.8, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.0.9, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.1.0, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.1.1, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.1.10, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.1.11, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.1.12, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.1.2, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.1.3, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.1.4, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.1.5, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.1.6, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.1.7, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.1.8, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.1.9, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.2.0, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.2.1, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.2.10, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.2.11, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.2.12, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.2.2, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.2.3, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.2.4, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.2.5, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.2.6, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.2.7, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.2.8, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.2.9, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.3.0, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.3.1, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.3.10, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.3.11, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.3.2, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.3.3, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.3.4, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.3.5, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.3.6, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.3.7, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.3.8, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.3.9, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.4.0, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.4.1, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.4.2, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.4.3, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.4.4, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.4.5, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.4.6, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.4.7, v3.4.40].
    - Can only install one of: symfony/http-foundation[v4.4.8, v3.4.40].
    - Installation request for symfony/http-foundation (locked at v3.4.40) -> satisfiable by symfony/http-foundation[v3.4.40].

Installation failed, reverting ./composer.json to its original content.

**Comment by calchen** [comment]
请检查你的项目的 symfony/http-foundation 版本的要求，这种保存一般是你的项目的要求的 symfony/http-foundation 版本与本项目要求的有冲突导致的

**Comment by minbaby** [comment]
2.7.8 -> 2.8.0 是一个BC， 不太符合版本规范，所以会出现这个问题，symfony/http-foundation 从 ~3.3 升级到了 ^4.0， 要么用低版本，要么升级项目版本

**Comment by yansongda** [comment]
麻烦使用最新 v3 版

感谢支持
