### ISSUE TITLE
微信退款APP方式到支付退款报：appid长度错误

### ISSUE THREAD

**Issue by wangguotao1215** [yansongda/pay#355]
## 报错详情
跟踪下来后发现配置里面app到话获取不到appid。refund方法未加载到正确的appid 只能默认取app_id

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by wangguotao1215** [comment]
ERROR_GATEWAY: Get Wechat API Error:appid参数长度有误

**Comment by calchen** [comment]
具体配置文件可以打码发一下嘛

**Comment by wangguotao1215** [comment]
> 具体配置文件可以打码发一下嘛
![image](https://user-images.githubusercontent.com/3202297/82813758-45ce0980-9ec8-11ea-8dc8-c1d670bc6df7.png)
![image](https://user-images.githubusercontent.com/3202297/82813810-6ac27c80-9ec8-11ea-8bd3-2d1857185c16.png)

**Comment by wangguotao1215** [comment]
> 具体配置文件可以打码发一下嘛

图片能正常看到吗

**Comment by calchen** [comment]
> > 具体配置文件可以打码发一下嘛
> 
> 图片能正常看到吗

是 refund 接口报的错误嘛？

**Comment by wangguotao1215** [comment]
> > > 具体配置文件可以打码发一下嘛
> > 
> > 
> > 图片能正常看到吗
> 
> 是 refund 接口报的错误嘛？

对的

**Comment by calchen** [comment]
审计了相关代码，未能找到bug，加我 qq 674447097，我帮你瞅瞅，稍后反馈到本 issue

**Comment by wangguotao1215** [comment]
> 是 refund 接口报的错误嘛？

感觉老兄陪我一起排查了问题，最终问题排查得知
![image](https://user-images.githubusercontent.com/3202297/82818811-e37a0680-9ed1-11ea-8067-47ffa5726ace.png)
refund方法跟进去的这个方法需要传一个type参数
所以解决办法就是
![image](https://user-images.githubusercontent.com/3202297/82818866-f5f44000-9ed1-11ea-9bfd-3ee0c21e6695.png)
传个type，ran hou然后赋值appid即可

**Comment by calchen** [comment]
文档这里：https://pay.yanda.net.cn/docs/2.x/wechat/refund

![企业微信截图_20200526125741](https://user-images.githubusercontent.com/3085383/82861837-88d3bf80-9f50-11ea-819a-1ead0c8bca2e.png)

**Comment by calchen** [comment]
PS：我俩这头像也是很搞笑了
![企业微信截图_20200526125903](https://user-images.githubusercontent.com/3085383/82861899-b02a8c80-9f50-11ea-859e-27228795ec83.png)

**Comment by wangguotao1215** [comment]
> PS：我俩这头像也是很搞笑了
> ![企业微信截图_20200526125903](https://user-images.githubusercontent.com/3085383/82861899-b02a8c80-9f50-11ea-859e-27228795ec83.png)

哈哈哈情侣头像
