### ISSUE TITLE
支付宝转账接口已经更新

### ISSUE THREAD

**Issue by 956632862** [yansongda/pay#356]
支付宝已经更新了转账接口，旧版接口已经不再维护。
求更新啊

**Comment by calchen** [comment]
能这个具体说的是哪个接口呀？能发一下文档嘛

**Comment by 956632862** [comment]
> 能这个具体说的是哪个接口呀？能发一下文档嘛

https://opendocs.alipay.com/open/00ou7f

**Comment by yansongda** [comment]
此接口最新版已支持

感谢支持
