### ISSUE TITLE
使用app支付，前端反应，安卓可以正常，ios不正常

### ISSUE THREAD

**Issue by chenzhulin** [yansongda/pay#357]
## 包版本号
2.1

## 问题描述
客户反应，安卓跳转正常，ios跳转不正常

## 你的代码
$apppay = Pay::alipay($config)->app($aliPayOrder);
$sdk_str = $apppay->getContent();
return $sdk_str;

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
v3.0 版本已发布，欢迎体验
