### ISSUE TITLE
支付宝当面付，请求回来之后，没有对应的trade_no支付宝交易号

### ISSUE THREAD

**Issue by chenzhulin** [yansongda/pay#358]
## 包版本号
2.1
laravel 5.8
## 问题描述
支付宝扫码支付，当面付

## 你的代码
$scan = Pay::alipay($config)->scan($aliPayOrder);
这是返回的信息，
#items: array:4 [▼
    "code" => "10000"
    "msg" => "Success"
    "out_trade_no" => "467bab2b569d6f4ebe1b1e6b3b7183a5"
    "qr_code" => "https://qr.alipay.com/bax00084pigbdqfnu9wv80fd"
  ]

没有trade_no参数
## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by iLay1678** [comment]
[https://opendocs.alipay.com/apis/api_1/alipay.trade.precreate#%E5%93%8D%E5%BA%94%E5%8F%82%E6%95%B0](url) 支付宝官方都没有返回这个参数，这里当然也不会有
