### ISSUE TITLE
symfony报deprecated错误

### ISSUE THREAD

**Issue by he426100** [yansongda/pay#363]
## 包版本号
2.9.3

## 报错详情
Since symfony/http-foundation 5.1: The "Symfony\Component\HttpFoundation\Response::create()" method is deprecated, use "new Symfony\Component\HttpFoundation\Response()" instead

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by raorao05** [comment]
找到 verder/yangsongda/pay/src/Gateways/Wechat.php的 success方法

替换成
return new Response(
            Support::toXml(['return_code' => 'SUCCESS', 'return_msg' => 'OK']),
            200,
            ['Content-Type' => 'application/xml']
        );

另外。作者该更新版本了。不少地方报这个错，从5.1开始，Symfony\Component\HttpFoundation\Response::create()被抛弃了

**Comment by yansongda** [comment]
安排。。。
