### ISSUE TITLE
appid字段部分文件不对应

### ISSUE THREAD

**Issue by kvfun** [yansongda/pay#368]
## 包版本号
 "yansongda/pay": "^2.9"

## 问题描述
微信app支付查询字段不一致。

## 你的代码

`
      `$this->config = [

            'appid' => env('wechat.appid'), 

            'mch_id' => env('wechat.mch_id'),

            'key'    => env('wechat.app_key'),//'mF2suE9sU6Mk1Cxxxxxxxxxxx',

            'notify_url' => 'https://'.$_SERVER['SERVER_NAME'].'/api/v1/recharge/notify',

            'cert_client' => root_path().'cert/apiclient_cert.pem', // optional，退款等情况时用到

            'cert_key' => root_path().'cert/apiclient_key.pem',// optional，退款等情况时用到

            'http' => [ // optional

                'timeout' => 5.0,

                'connect_timeout' => 5.0,

                // 更多配置项请参考 [Guzzle](https://guzzle-cn.readthedocs.io/zh_CN/latest/request-options.html)

            ],

            'mode' => 'normal', // optional, dev/hk;当为 `hk` 时，为香港 gateway。

        ];`

`$pay = Pay::wechat($this->config)->app($order);`

`$quey = Pay::wechat($this->config)->find($orderNumber, 'app');`
## 报错详情
![image](https://user-images.githubusercontent.com/15116804/85943083-4a229200-b960-11ea-8dcb-33f702b90ecd.png)
![image](https://user-images.githubusercontent.com/15116804/85943123-7fc77b00-b960-11ea-8229-d4dada0ac123.png)

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
因为 app 中需要 app 的 id
