### ISSUE TITLE
Laravel框架微信小程序支付，API证书放哪？

### ISSUE THREAD

**Issue by DreamboyA** [yansongda/pay#37]
## 问题描述
微信小程序支付的API具体路径放在哪？

## 代码
<pre>
<code>
                'cert_client' => './apiclient_cert.pem',
                'cert_key' => './apiclient_key.pem',
</code>
</pre>

**Comment by yansongda** [comment]
您好，证书地址是您直接在 config 中设置的。

**Comment by DreamboyA** [comment]
是的，我的问题的代码就是config的代码，我是指这个路径，对应具体路径放哪？ 如代码配置的路径，具体文件需要放在哪？

**Comment by yansongda** [comment]
config 没有路径，直接在代码中写即可。请参考使用说明。

谢谢

**Comment by DreamboyA** [comment]
可能是我的描述有问题，我的意思是，微信支付假设我在代码里写的config为如下，那么我的apiclient_cert.pem、apiclient_key.pem两个文件应该放在哪？Laravel工程的根目录下？ 和我这个Controller同级的目录下？
<pre>
<code>
$config = [
    'wechat' => [
        'miniapp_id' => '',             // 小程序APPID
        'mch_id' => '',             // 微信商户号
        'notify_url' => '',
        'key' => '',                // 微信支付签名秘钥
        'cert_client' => './apiclient_cert.pem',        // 客户端证书路径，退款时需要用到
        'cert_key' => './apiclient_key.pem',            // 客户端秘钥路径，退款时需要用到
    ],
];
</code>
</pre>

**Comment by yansongda** [comment]
可随意设置绝对路径或相对路径。您自己决定即可。

**Comment by riseno** [comment]
@DreamboyA 

我是放在 `storage/certs` 裡。都隨你放

**Comment by DreamboyA** [comment]
./ 相对路径是代表项目根目录对吧？

**Comment by riseno** [comment]
你直接用 laravel 裡的 `storage_path()` 吧

e.g. 
```php
// 如果你是放在 `storage/certs` 的話
storage_path('certs/apiclient_cert.pem');
```
