### ISSUE TITLE
 The requested PHP extension ext-password * is missing from your system. Install or enable PHP's password extension

### ISSUE THREAD

**Issue by liuxu379** [yansongda/pay#370]
## 包版本号
2.x

## 问题描述
Composer安装时提示找不到ext-password扩展,无法找到此扩展安装途径.

## 报错详情
Something's changed, looking at all rules again (pass #2)
Dependency resolution completed in 0.190 seconds
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested PHP extension ext-password * is missing from your system. Install or enable PHP's password extension.

Installation failed, reverting ./composer.json to its original content.

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
ext-password 应该不是 sdk 要求的

请检查下自己的 composer 依赖

感谢支持
