### ISSUE TITLE
Yansongda\Pay\Exceptions\InvalidSignException INVALID_SIGN: Alipay Sign Verify FAILED

### ISSUE THREAD

**Issue by songlen** [yansongda/pay#376]
## 包版本号
2.9.3

## 问题描述
我先用的正式环境配置，一切都正常使用，后来由于测试过程不方便支付，改成了沙箱环境。确发现有的业务订单能正常支付并正常回调成功。有的业务订单异步回调延签通过，但是同步回调延签失败。还有的订单同步和异步回调延签都失败。我就很纳闷了。关于沙箱配置，在文档中也没找到说明，，我是把配置中的 mod 配置成了 dev ，并把沙箱配置信息替换了正式环境配置，但是有的延签失败

## 你的代码
```
public function notify()
{
        // 直接调用方法延签
        $alipay = Pay::alipay(config('pay.alipay'));
       /// 业务处理
}
```

## 报错详情
Yansongda\Pay\Exceptions\InvalidSignException
INVALID_SIGN: Alipay Sign Verify FAILED
vendor/yansongda/pay/src/Gateways/Alipay.php:193

## sdk 日志
yansongda.pay.WARNING > Alipay Sign Verify FAILED {"charset":"utf-8","out_trade_no":"P202007202888316866","method":"alipay.trade.page.pay.return","total_amount":"20.00","sign":"n1hHGuAVa6CU+EiRj2D+jhKxt0FOCZ0xCLWpuWd/Sd+97XaC5RxuNKl04e6OZ0rrJ3lq3sbS5zeKsy808qtSSjD7rv8Gf0I+vO36SkaWQ0/Lvj+8n2t5hD4ERl8eh/q0n085W4R/F6VSsK9BW9zbrq3Yt4kpwiia7qIl/LPAIdz1SujF9bKpNvSi/Zf6Iws5W3EKsFhM2EHyk7UaS2XkUFjROBmk8NqFcPcqwRuw0/8/ab/FKd717Af/6QidA4guEXSgnW87y0iVhgCCIeuOGAofi9OO1zP28iZHYb6ZbrG4IjWgSHPUlhGm/3j6mmJYg+zErzJzsCbNaaXWtP68DQ==","trade_no":"2020072022001454170502520609","auth_app_id":"2016073000120000","version":"1.0","app_id":"2016073000120000","sign_type":"RSA2","seller_id":"2088102169110000","timestamp":"2020-07-20 16:59:14"}
 看回调信息都正常

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by puzzle9** [comment]
https://github.com/yansongda/pay/issues/375#issuecomment-682509770

**Comment by 734380794** [comment]
Alipay Sign Verify FAILED 支付宝签名不通过，应该怎么处理

**Comment by yansongda** [comment]
麻烦尝试使用最新 v3 版

感谢支持

**Comment by yansongda** [comment]
麻烦尝试使用最新 v3 版

感谢支持

**Comment by longxianlin** [comment]
v3 版要PHP8
