### ISSUE TITLE
微信V3版本的api会考虑支持吗？

### ISSUE THREAD

**Issue by flyrory** [yansongda/pay#377]
v3相较于的之前微信支付API，主要区别是：

1. 遵循统一的Restful的设计风格
2. 使用JSON作为数据交互的格式，不再使用XML
3. 使用基于非对称密钥的SHA256-RSA的数字签名算法，不再使用MD5或HMAC-SHA256
4. 不再要求HTTPS客户端证书
5. 使用AES-256-GCM，对回调中的关键信息进行加密保护

**Comment by yansongda** [comment]
后续 V3 版本考虑支持
