### ISSUE TITLE
微信公众号支付提示缺少参数,这个缺少什么参数怎么看呢

### ISSUE THREAD

**Issue by chenjun-0127** [yansongda/pay#379]
## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
这个得对比官方文档根据 debug 日志查看处理了

**Comment by chenjun-0127** [comment]
微信支付的那个key是干嘛的

**Comment by chenjun-0127** [comment]
> 这个得对比官方文档根据debug日志查看处理了

现在报签名错误,,微信支付的那个key是干嘛的,不知道跟这个有没有关系
