### ISSUE TITLE
是不是需要安装证书啊

### ISSUE THREAD

**Issue by dltjiangfeipeng** [yansongda/pay#381]
## 问题描述
用的tp5

## 报错详情
cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

## sdk 日志

![cw8](https://user-images.githubusercontent.com/30610103/88655724-b9c3a280-d101-11ea-835b-1fbd99268c68.png)

## nginx日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
文档

感谢支持
