### ISSUE TITLE
微信H5网页支付，如何不返回一个重定向响应而是返回一个重定向链接？

### ISSUE THREAD

**Issue by xushenjie** [yansongda/pay#382]
前端请求接口发起支付，需要携带Authorization的token，等一些其他参数
前端请求之后微信H5 但是  `return $wechat->wap($order);` 这个是直接返回一个重定向响应，
`代码中用到的是下面`
```
 # * @method RedirectResponse wap(array $config) H5 支付

return $wechat->wap($order);
```
想要返回微信的支付链接，这种情况怎么解决呢?

**Comment by yansongda** [comment]
请仔细看文档

感谢支持
