### ISSUE TITLE
请加上退款查询接口

### ISSUE THREAD

**Issue by ghujki** [yansongda/pay#383]
**需求描述**
当极端情况发生时，例如向支付宝或者微信服务器发出了退款申请，但发出后网络断开，不知道最后退款是否成功了。此时需要加上退款查询接口来查询这笔退款是否成功。

**建议**
增加queryRefund方法来查询微信和支付宝退款情况.

**Comment by yansongda** [comment]
仔细看文档，有退款查询

感谢支持

**Comment by ghujki** [comment]
文档上面只有pay,refund,find,cancel,close,PAYMETHOD这几个方法吧

**Comment by involvements** [comment]
find就可以查询退款订单
