### ISSUE TITLE
微信支付异步回调，验签过不去

### ISSUE THREAD

**Issue by xcm55054** [yansongda/pay#384]
## 包版本号
v2.8版本
## 问题描述
微信小程序支付能成功，但是回调的时候，能够看到nginx的请求，但是在验签那里过去，在验签代码的上一行和下一行分别打了日志，发现，压根走不到下一行。

## 你的代码
   $config = config('pay.wx');
        $pay = Pay::wechat($config);
        Db::beginTransaction();
        try{
            Log::get('pay')->info("支付回调开始验签，验签时间为".Carbon::now());
            $data = $pay->verify(); // 是的，验签就这么简单！
            Log::get('pay')->info("支付回调开始，支付时间为".Carbon::now()."验签数据为".var_export($data->all()));
## 报错详情
不报错，没有任何返回

## sdk 日志

2020-08-17T11:33:29.054811+08:00 > yansongda.pay.INFO > Received Wechat Request [""] 

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来
101.226.103.15 - - [17/Aug/2020:12:10:27 +0800] "POST /api/pay/notify HTTP/1.1" 200 89 "-" "Mozilla/4.0"

**Comment by xcm55054** [comment]
有哪位大佬可以帮忙看看吗

**Comment by xcm55054** [comment]
找到问题了，我用的是hyperf，不支持$_POST这种全局变量。。。

**Comment by xcm55054** [comment]
找到问题了，我用的是hyperf，不支持$_POST这种全局变量。。。

**Comment by yansongda** [comment]
麻烦尝试使用最新 v3 版

感谢支持

**Comment by yansongda** [comment]
同时，现在有针对 hyperf 的包，欢迎使用
