### ISSUE TITLE
return $alipay->success()->send(); 会打印多个 success

### ISSUE THREAD

**Issue by twhmr** [yansongda/pay#386]
在 send() 方法内部，调用了 $this->sendContent(); 把content打印了出来
然后return 这个response对象的时候，会再打印一次，导致回调重复

**Comment by laofu110** [comment]
前面不加return，直接$alipay->success()->send();

**Comment by twhmr** [comment]
> 前面不加return，直接$ alipay-> success（）-> send（）;

所以文档上应该是写的有点问题的。

而且最后需要die; 结束

**Comment by yansongda** [comment]
需要根据不同框架自行处理最后的返回值
