### ISSUE TITLE
无法复用请求不同API

### ISSUE THREAD

**Issue by Favoryoung** [yansongda/pay#392]
初始化 $pay 后，无法复用请求不同API

例如以下伪代码
```
$pay = Pay::wechat($config);

$reulst = $pay->pos($payParam);
....
$pay->find($order);
```
因为 第一次 pos 请求后 修改了属性  $this->payload
之后的 find 请求时会使用 $this->payload 作为请求参数，导致有很多无效的请求参数

当然 我可以重新 Pay::wechat($config) 生成一个新的 $pay 调用 find 方法，但这显然不是优雅的做法
建议把 config 和 payload 分开，请求的时候 根据 config 和传入参数拼装 payload，保证每次请求时的参数互不影响

不知道您的设计理念是否是 "一次业务请求，应该只对应支付平台的一个API"，所以上述情况不在考虑中

**Comment by yansongda** [comment]
是的，一般情况下，只会有一次请求一次支付

下一个大版本会改善这个问题

感谢支持

**Comment by ihipop** [comment]
同样遇到了这个问题，发起新的支付请求后 关闭其他老的支付流水会多很多没用的甚至有歧义的参数，一些严格的api就会报错，比如 https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=9_3 这个接口 如果有body字段 就会报错
