### ISSUE TITLE
微信支付统一下单 redirect_url参数在哪里设置？

### ISSUE THREAD

**Issue by 422835426** [yansongda/pay#395]
`
        $url = is_null(Support::getInstance()->return_url) ? $mweb_url : $mweb_url.
                        '&redirect_url='.urlencode(Support::getInstance()->return_url);

`
这里有提到，不知道哪里进行设置？还是getTargetUrl获取链接自行跳转呢

**Comment by yansongda** [comment]
设置 return_url 即可

感谢支持

**Comment by freadman** [comment]
> 设置 return_url 即可
> 
> 感谢支持

在配置文件中设置了，无效。
在提交订单中设置，提示api未定义该参数。

求解。。非常感谢！
