### ISSUE TITLE
微信支付 notify 方法报错

### ISSUE THREAD

**Issue by swklswkl** [yansongda/pay#40]
## 问题描述
复制你代码是调用 notify方法 报错
微信支付
## 报错详情
convert to array error !invalid xml

**Comment by yansongda** [comment]
请检查 verify 传参是否正确

**Comment by swklswkl** [comment]
@yansongda verify参数为空是什么原因？

**Comment by yansongda** [comment]
说明你传参为空………………………………

好好检查下吧

**Comment by swklswkl** [comment]
微信支付成功后，我是在回调方法里判断某个参数来确认是否支付成功，还是另外调一个查询订单api接口？
