### ISSUE TITLE
微信支付什么时候准备接V3呢

### ISSUE THREAD

**Issue by mingzaily** [yansongda/pay#401]
因为支付宝也是rsa签名的，所以这样方便设计表，不然微信和支付宝得用两张表来存

希望能接入，谢谢作者

**Comment by yansongda** [comment]
目前 pay 项目的 v3 版本也正在开发中  v3 分支

欢迎 PR

**Comment by mingzaily** [comment]
好的，微信v2用xml可真是吐血了
