### ISSUE TITLE
ERROR_GATEWAY: Get Alipay API Error:Invalid Arguments - isv.app-cert-not-exist

### ISSUE THREAD

**Issue by senmeng** [yansongda/pay#405]
## 包版本号
v2

## 问题描述
用户转账号

## 你的代码
$order = [
            'out_biz_no' => time(),
            'trans_amount' => 1,
            'product_code' => 'TRANS_ACCOUNT_NO_PWD',
            'payee_info' => [
                'identity' => '626512443@qq.com',
                'identity_type' => 'ALIPAY_LOGON_ID',
            ],
        ];

        $alipay = Alipay::getInstance();
        $result = $alipay->transfer($order);

## 报错详情

ERROR_GATEWAY: Get Alipay API Error:Invalid Arguments - isv.app-cert-not-exist
## sdk 日志
Alipay Transfer Has Started ["https://openapi.alipay.com/gateway.do?charset=utf-8",{"app_id":"2021002110695692","format":"JSON","charset":"utf-8","sign_type":"RSA2","version":"1.0","timestamp":"2020-11-27 11:34:06","biz_content":"{\"out_biz_no\":1606448046,\"trans_amount\":1,\"product_code\":\"TRANS_ACCOUNT_NO_PWD\",\"payee_info\":{\"identity\":\"626512443@qq.com\",\"identity_type\":\"ALIPAY_LOGON_ID\"}}","app_cert_sn":"3bf49d3c9b3a4f14f9ec771adbaa130d","alipay_root_cert_sn":"687b59193f3f462dd5336e5abf83c5d8_02941eef3187dddf3d3b83462e1dfcf6","method":"alipay.fund.trans.uni.transfer","sign":"EHK4+/BTqGivK4w0XViMrxLyPX4y/ryp8Dk6GvjRiP2pPox2va9oJF2DdsfkSVbxC602k93pkykeG1bqh7ZEVCnOKTS4si6UQVR+gDuO1m3YbZCC2TbPlP6S4vT68cAKM6qGNRqSKEc7RuWMF8nLJuhVCGqWSQSBb0nWq1gCmSKqAKJpjZWN8nEPDJTbwkokrStqw8jjZ4R3e4B6l6QOuw4wh6nTLwdCw9MV+Ym80FqFFq0UcuRMnuunjc72QIBpl4J0qkkuTjGjMnr9b8eR8YlkDoVzaWq1fygU3i3AM833SuV7m9ddclzIV32ArENMD+gCUjbzWnJ/IY/1dBnAPw=="}] 

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by ken202011** [comment]
配置参数贴出来，估计是证书路径不对！
