### ISSUE TITLE
在yii2框架中使用这个扩展的时候，使用send() 方法，总会报错  headers already sent

### ISSUE THREAD

**Issue by Dorkdomain** [yansongda/pay#406]
## 包版本号
v2.9.5

## 问题描述
在yii2框架中使用这个扩展的时候，使用send() 方法，总会报错  headers already sent，请问是不是跟laravel 框架一样，无需使用send方法即可？

## 你的代码

列如APP支付： $alipay->send();
回调通知： $alipay->success()->send();
            

## 报错详情
file_name ： /vendor/yiisoft/yii2/web/Response.php
message ： Headers already sent.
trace ： 
#0 /home/wwwroot/g2/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders() #1 /home/wwwroot/g2/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Response->send() #2 /home/wwwroot/g2/frontend/web/index.php(17): yii\base\Application->run() #3 {  main }
--

**Comment by crstudio** [comment]
我直接提示没有send这个方法：Call to undefined method Yansongda\Supports\Collection::send()

**Comment by tesun** [comment]
YII很简单
echo $alipay->success()->send();
        exit;

**Comment by yansongda** [comment]
麻烦尝试使用最新 v3 版

感谢支持
