### ISSUE TITLE
提示 Undefined index: sign

### ISSUE THREAD

**Issue by jiutu** [yansongda/pay#410]
## 包版本号
yansongda/pay (v2.10.1)

## 问题描述
Undefined index: sign

## 你的代码
/**
     * 异步地址
     *
     * @return  [type]  [return description]
     */
    public function notify_url(Request $request)
    {
        $alipay = Pay::alipay($this->config);
        try {
            $alipayData = $alipay->verify(); // 是的，验签就这么简单！
        } catch (\Exception $e) {
            Log::channel('pay_notify')->error(['error' => $e->getMessage()]);
            return $alipay->success()->send();
        }
        Log::channel('pay_notify')->error(['data' => $alipayData]);
}

## 报错详情
[2021-01-04 09:16:04] local.ERROR: array (
  'error' => 'Undefined index: sign',
)  

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by happyxiaod** [comment]
我也遇到这个问题了，用证书就会出错

**Comment by jiutu** [comment]
> 我也遇到这个问题了，用证书就会出错

用证书??我好像没用哎,,您解决了吗?

**Comment by happyxiaod** [comment]
不是是指用的crt这种证书文件，我是用的laravels ,调用verify验证签名的时候需要将获取到的参数传进去，因为swoole不支持
` $pay->verify(); // 改为$pay->verify($data)

`

**Comment by happyxiaod** [comment]
> > 我也遇到这个问题了，用证书就会出错
> 
> 用证书?是指https???,您解决了吗?

不是是指用的crt这种证书文件，我是用的laravels ,调用verify验证签名的时候需要将获取到的参数传进去，因为swoole不支持
` $pay->verify(); // 改为$pay->verify($data)

**Comment by yuchenga** [comment]
@happyxiaod 请问$pay->verify($data)  $data 参数如何获取的

**Comment by uniteweiwei** [comment]
> @happyxiaod 请问$pay->verify($data) $data 参数如何获取的

是不是request()->getContent()

**Comment by happyxiaod** [comment]
> > @happyxiaod 请问$pay->verify($data) $data 参数如何获取的
> 
> 是不是request()->getContent()

是的

**Comment by yansongda** [comment]
可以考虑使用最新 v3 版
