### ISSUE TITLE
一些web和wap支付指定可返回html response还是数组

### ISSUE THREAD

**Issue by ihipop** [yansongda/pay#414]
2.10.1

前后分离模式下，前端只需要支付参数，直接返回html不好处理
看了代码也没有参数控制是否返回数组还是response

**Comment by yansongda** [comment]
看文档

感谢

**Comment by ihipop** [comment]
> 看文档
> 
> 感谢

您是想说事件麼，支付宝wap/web支付的时候注册一个事件获取参数。我知道这样可以 但是这样并不是很方便。各种请求都得先注入一个事件才能从回调里面拿到数据。
目前我的做法是自定义一个支付宝的wap/web支付gateway 然后exntend到支付宝里面去。这个支付网关不返回response而是params，然后通过自定义函数在需要的地方把参数生成response或者直接返回参数给前端
