### ISSUE TITLE
PHP8下Function libxml_disable_entity_loader() is deprecated

### ISSUE THREAD

**Issue by Rmiku** [yansongda/pay#415]
## 包版本号
v2.10.1

## 问题描述
升级到php8.0.1后出现如下报错，libxml_disable_entity_loader函数在php8已被弃用

## 报错详情
local.ERROR: ErrorException: Function libxml_disable_entity_loader() is deprecated in /vendor/yansongda/pay/src/Gateways/Wechat/Support.php:309

**Comment by yansongda** [comment]
fixed

thx supporting
