### ISSUE TITLE
支付宝扫码支付，返回值为空；

### ISSUE THREAD

**Issue by 15686208211** [yansongda/pay#418]
![ZJY~ CKJKS7B OAZUM)5)L](https://user-images.githubusercontent.com/48739851/105786371-e759ad80-5fb7-11eb-86aa-70ad6d724cb1.png)

   switch ($method) {
                case 'web':
                    //电脑支付,跳转
                    return $pay->web($params)->send();
                case 'wap':
                    //手机网页支付,跳转
                    return $pay->wap($params)->send();
                case 'app':
                    //APP支付,直接返回字符串
                    return $pay->app($params)->send();
                case 'scan':
                    //扫码支付,直接返回字符串
                    return $pay->scan($params);
                case 'pos':
                    //刷卡支付,直接返回字符串
                    //刷卡支付必须要有auth_code
                    $params['auth_code'] = $auth_code;
                    return $pay->pos($params);
                default:
                    //其它支付类型请参考：https://docs.pay.yansongda.cn/alipay
            }

Thinkphp5框架，加载阎嵩da支付，进行扫码支付，没有返回值；谁遇到过啊？

**Comment by yansongda** [comment]
麻烦使用最新 v3 版

感谢支持
