### ISSUE TITLE
可否为hyperf框架出一个类似于laravel扩展包的扩展包~，我可以参与项目维护~

### ISSUE THREAD

**Issue by myttyy** [yansongda/pay#422]
可否为hyperf框架出一个类似于laravel扩展包的扩展包~，我可以参与项目维护~

**Comment by yansongda** [comment]
目前正在开发 v3 版本，到时候会支持

**Comment by yansongda** [comment]
https://github.com/yansongda/hyperf-pay

欢迎体验

**Comment by myttyy** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        收到，辛苦了
        
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
    
        签名由网易邮箱大师定制
    
 

    在2021年7月10日 ***@***.***> 写道： 




https://github.com/yansongda/hyperf-pay

欢迎体验
