### ISSUE TITLE
支付宝查询错误 Yansongda\Pay\Gateways\Alipay\ScanGateway Done Not Exist Or Done Not Has FIND Method

### ISSUE THREAD

**Issue by fengcheche15** [yansongda/pay#424]
Yansongda\Pay\Gateways\Alipay\ScanGateway Done Not Exist Or Done Not Has FIND Method
已尝试过更新到最新版，重新composer update 也试过，都还是这个错误。目前是在windows本机的错误。经调试上线，linux服务器上也是一样的错误。
这里的具体错误我追踪了一下，最后结果是 Done Not Has FIND Method 这个方法不可用。还请解决一下。
php 7.4  laravel 7.3 Yansongda\Pay 2.10

**Comment by yansongda** [comment]
麻烦尝试使用最新 v3 版

感谢支持
