### ISSUE TITLE
Undefined index: sign  原因；请修改包源码

### ISSUE THREAD

**Issue by diudiuge** [yansongda/pay#426]
## 包版本号
"yansongda/pay": "^2.10"

## 问题描述
/vendor/yansongda/pay/src/Gateways/Alipay/Support.php
报错信息:  Undefined index: sign 

## 出错原因
```
// /vendor/yansongda/pay/src/Gateways/Alipay.php 182 行左右

if (isset($data['fund_bill_list'])) {
	$data['fund_bill_list'] = htmlspecialchars_decode($data['fund_bill_list']);
}
```
- 在这里打印$data['fund_bill_list']发现里面的引号被转义了。
解决方法：使用stripslashes()方法移除转义：

**Comment by Lance-93** [comment]
我微信小程序支付也遇到Undefined index: sign 请问。如何是好呢
