### ISSUE TITLE
支付宝网关建议抛出自定义异常时吧sub_msg也加上,不然排查具体错误很费劲,尤其支付宝参数异常错误

### ISSUE THREAD

**Issue by pianqifei** [yansongda/pay#427]
Yansongda\Pay\Gateways\Alipay\Support下的processingApiResult方法
/**
     * processingApiResult.
     *
     * @author yansongda <me@yansongda.cn>
     *
     * @param $data
     * @param $result
     *
     * @throws GatewayException
     * @throws InvalidConfigException
     * @throws InvalidSignException
     */
    protected static function processingApiResult($data, $result): Collection
    {
        $method = str_replace('.', '_', $data['method']).'_response';

        if (!isset($result['sign']) || '10000' != $result[$method]['code']) {
            //这里 把$result[$method]['sub_msg']也判断并且抛出 方便调试
            throw new GatewayException('Get Alipay API Error:'.$result[$method]['msg'].(isset($result[$method]['sub_code']) ? (' - '.$result[$method]['sub_code']) : ''), $result);
        }

        if (self::verifySign($result[$method], true, $result['sign'])) {
            return new Collection($result[$method]);
        }

        Events::dispatch(new Events\SignFailed('Alipay', '', $result));

        throw new InvalidSignException('Alipay Sign Verify FAILED', $result);
    }

自己排查时单独又记录的支付宝返回结果
array (
  'alipay_fund_trans_uni_transfer_response' => 
  array (
    'code' => '40004',
    'msg' => 'Business Failed',
    'sub_code' => 'INVALID_PARAMETER',
    'sub_msg' => '参数有误biz_scene:不能为空',
  ),

当错误为sub_code为INVALID_PARAMETER时  没有具体的sub_msg 很难排查具体是哪里的参数有问题

望采纳

**Comment by yansongda** [comment]
好的，后续版本加上。同时欢迎 PR
