### ISSUE TITLE
大佬准备什么时候发布v3版本呢?

### ISSUE THREAD

**Issue by zjttfs** [yansongda/pay#438]
看 projects 里面还有挺多 todo 的.
是否可以分版本上线?

**Comment by yansongda** [comment]
已经全力开发中了

目前 Alipay 已经直接支持了 40+ 场景及 API ，间接支持所有场景及 API

wechat 的，目前正准备开发中，但是貌似 v3 版没有沙箱模式，所以不好测试，如果您能够提供下 账号支持，那是极好的

**Comment by zjttfs** [comment]
抱歉,账号都是公司在用的.我没有账号可以帮上..

如果有rc的话,可以本地帮测试下.

**Comment by yansongda** [comment]
8月1日已发布 rc.0 版本，欢迎体验
