### ISSUE TITLE
微信支付 返回curl error 7

### ISSUE THREAD

**Issue by donglf681** [yansongda/pay#444]
## 包版本号
"yansongda/pay": "^2.5"

## 问题描述
环境是k8s集群，api 接口请求微信企业付款接口，部分请求返回 “cURL error 7:  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)”，请问这个是什么原因导致的？

- 使用的是阿里云 容器服务 Kubernetes 版，目前发现深圳节点不会出现这种问题，但杭州节点就会出现

## 你的代码
使用重新封装的composer包，"ibrand/pay": "~0.2",

```php
$params = call_user_func([$this, 'get' . Str::studly($cash->channel) . 'ChargeParams'], $cash);
            $charge = $this->chargeContract->create($params, $cash->channel . '_transfer');
```

## 报错详情

cURL error 7:  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by yansongda** [comment]
麻烦尝试使用最新 v3 版

感谢支持
