### ISSUE TITLE
支付宝订单查询find方法，只能查询支付成功的订单

### ISSUE THREAD

**Issue by EddyLee1010** [yansongda/pay#445]
其他订单都是抛异常？？？

那官方的那么多种状态都该怎么用
********************
交易状态：WAIT_BUYER_PAY（交易创建，等待买家付款）、TRADE_CLOSED（未付款交易超时关闭，或支付完成后全额退款）、TRADE_SUCCESS（交易支付成功）、TRADE_FINISHED（交易结束，不可退款）

**Comment by yansongda** [comment]
返回的数据里有 trade_status  字段吧？

**Comment by yansongda** [comment]
麻烦尝试使用 v3 版吧

v3 版所有的信息都返回了，让开发者自行处理

感谢
