### ISSUE TITLE
V3版本初始化报错

### ISSUE THREAD

**Issue by lkp186** [yansongda/pay#448]
## 问题描述
V3版本初始化报错,config我直接复制文档上的

## 你的代码
![Uploading image.png…]()

## 报错详情
![Uploading image.png…]()

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by lkp186** [comment]
Interface 'Symfony\\Component\\EventDispatcher\\EventDispatcherInterface' not found

**Comment by lkp186** [comment]
tp5框架

**Comment by yansongda** [comment]
已修复，麻烦升级至 最新版

感谢支持

**Comment by micross** [comment]
Hyperf v2.2.14 下同样遇到这个问题
