### ISSUE TITLE
请求成功，但是返回结果为空

### ISSUE THREAD

**Issue by lkp186** [yansongda/pay#451]
## 包版本号
3.0.0-alpha.8

## 问题描述
返回空，代码框架tp5

## 你的代码
![image](https://user-images.githubusercontent.com/24604653/125224042-5ffebd00-e2ff-11eb-8136-853c70631f61.png)
![image](https://user-images.githubusercontent.com/24604653/125224077-73118d00-e2ff-11eb-9d2d-5e46dc3638b6.png)

**Comment by yansongda** [comment]
TP 框架不支持 PSR7 规范，目前只能尝试自行解包 response 后返回了

后续我这边出个 thinkphp 的 psr7 bridge 吧

**Comment by lkp186** [comment]
没事儿，我现在已经自行解析了

**Comment by lkp186** [comment]
> TP 框架不支持 PSR7 规范，目前只能尝试自行解包 response 后返回了
> 
> 后续我这边出个 thinkphp 的 psr7 bridge 吧

恩恩，我现在已经自行解析了

**Comment by uamyangel** [comment]
> > TP 框架不支持 PSR7 规范，目前只能尝试自行解包 response 后返回了
> > 后续我这边出个 thinkphp 的 psr7 bridge 吧
> 
> 恩恩，我现在已经自行解析了

碰到同样问题，可以提供下自行解析的思路吗

**Comment by sunjim** [comment]
你好，我用的是laravel

**Comment by sunjim** [comment]
App支付这样就可以拿到值
```
$data =  Pay::alipay()->app($ali_order);
$res =  $data->getBody()->getContents();
parse_str($res,$result);
return $result;
```

**Comment by yansongda** [comment]
TP 官方已 merge，大家可尝试更新 tp 最新版本

**Comment by heqiang-RD** [comment]
@lkp186 请问ThinkPHP怎么解析包并返回给支付宝正确的响应
