### ISSUE TITLE
希望大佬增加一下支付宝企业付款到银行卡 

### ISSUE THREAD

**Issue by Akuns** [yansongda/pay#453]
希望增加一下支付宝企业付款到银行卡，不少项目要提现到银行卡，希望可以采纳

**Comment by yansongda** [comment]
可以参考代码，提个 PR 过来，v3 版扩展很简单

**Comment by Akuns** [comment]
> 可以参考代码，提个PR过来，v3版扩展很简单

@yansongda 老大，麻烦看下这个问题
