### ISSUE TITLE
请求过去直接报500

### ISSUE THREAD

**Issue by CherishNA** [yansongda/pay#46]
## 问题描述

Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at admin@phpStudy.net to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

get方式测试支付 请求过去直接报500

## 代码
<?php

namespace App\Http\Controllers;

use App\TicketOrder;
use Illuminate\Http\Request;
use  Yansongda\Pay\Pay;

class WxPayController extends Controller
{

    /**
     * @return array
     * 配置微信支付
     */
    public function config()
    {
        return $config = [
            'wechat' => [
                'app_id' => 'wx9c1fa5f5157b8888',
                'mch_id' => '1490434922',
                'notify_url' => 'http://cherishna.natapp1.cc/wxpay/paysuccess',
                'key' => 'huayuanmeiyehuayuanmeiyehuayuanm',
                'cert_client' => public_path() . '/apiclient_cert.pem',
                'cert_key' => public_path() . '/apiclient_key.pem',
            ],
        ];

    }

    /**
     * 支付方法
     */
    public function dopay()
    {

//        $ticketOrder = json_decode($request->input('order'));
        $wxOrder = [
            'out_trade_no' => 'test1',
            'total_amount' => '1',
            'subject' => 'test subject',
            'spbill_create_ip' => '8.8.8.8',
            'openid' => 'obkSg1KweqWKe4aFG_g8VTsdvvtY',
        ];
        $pay = new Pay($this->config());
        $result = $pay->driver('wechat')->gateway('mp')->pay($wxOrder);
        dd($result);
    }

    /**
     * 支付回调
     */
    public function paysuccess(Request $request)
    {
        $pay = new Pay($this->config());
        $verify = $pay->driver('wechat')->gateway('mp')->verify($request->getContent());

        if ($verify) {
            file_put_contents('notify.txt', "收到来自微信的异步通知\r\n", FILE_APPEND);
            file_put_contents('notify.txt', '订单号：' . $verify['out_trade_no'] . "\r\n", FILE_APPEND);
            file_put_contents('notify.txt', '订单金额：' . $verify['total_fee'] . "\r\n\r\n", FILE_APPEND);
        } else {
            file_put_contents(storage_path('notify.txt'), "收到异步通知\r\n", FILE_APPEND);
        }

        echo "success";
    }

}

- 

## 报错详情

500

**Comment by CherishNA** [comment]
`<?php

namespace App\Http\Controllers;

use App\TicketOrder;
use Illuminate\Http\Request;
use  Yansongda\Pay\Pay;

class WxPayController extends Controller
{

    /**
     * @return array
     * 配置微信支付
     */
    public function config()
    {
        return $config = [
            'wechat' => [
                'app_id' => 'wx9c1fa5f5157b8888',
                'mch_id' => '1490434922',
                'notify_url' => 'http://cherishna.natapp1.cc/wxpay/paysuccess',
                'key' => 'huayuanmeiyehuayuanmeiyehuayuanm',
                'cert_client' => public_path() . '/apiclient_cert.pem',
                'cert_key' => public_path() . '/apiclient_key.pem',
            ],
        ];

    }


    /**
     * 支付方法
     */
    public function dopay()
    {

//        $ticketOrder = json_decode($request->input('order'));
        $wxOrder = [
            'out_trade_no' => 'test1',
            'total_amount' => '1',
            'subject' => 'test subject',
            'spbill_create_ip' => '8.8.8.8',
            'openid' => 'obkSg1KweqWKe4aFG_g8VTsdvvtY',
        ];
        $pay = new Pay($this->config());
        $result = $pay->driver('wechat')->gateway('mp')->pay($wxOrder);
        dd($result);
    }

    /**
     * 支付回调
     */
    public function paysuccess(Request $request)
    {
        $pay = new Pay($this->config());
        $verify = $pay->driver('wechat')->gateway('mp')->verify($request->getContent());

        if ($verify) {
            file_put_contents('notify.txt', "收到来自微信的异步通知\r\n", FILE_APPEND);
            file_put_contents('notify.txt', '订单号：' . $verify['out_trade_no'] . "\r\n", FILE_APPEND);
            file_put_contents('notify.txt', '订单金额：' . $verify['total_fee'] . "\r\n\r\n", FILE_APPEND);
        } else {
            file_put_contents(storage_path('notify.txt'), "收到异步通知\r\n", FILE_APPEND);
        }

        echo "success";
    }

}

`

**Comment by yansongda** [comment]
所以，请问 500 的具体错误信息是什么？

**Comment by CherishNA** [comment]
你好 yansongda 大大 ，页面直接报出500 
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at admin@phpStudy.net to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

服务器错误日志里面也没给出具体错误信息，所以我才很迷茫 给您发iss

**Comment by yansongda** [comment]
抱歉，没错误日志没法判断。

目前包已较稳定，有问题的情况比较小。

建议切换 linux 下查看具体错误日志信息，自己尝试拍错。

Windows 下我这边也暂不考虑，情况较诡异。

感谢支持！

**Comment by CherishNA** [comment]
好的吧 我自己看看
