### ISSUE TITLE
无法读取我的公钥证书

### ISSUE THREAD

**Issue by wuzikai18** [yansongda/pay#466]
## 包版本号
3.0.0

## 问题描述
好像无法读取我的公钥证书

## 你的代码
// 应用公钥证书 路径
            'app_public_cert_path' => '/certs/appCertPublicKey_2021002165601246.crt',
            // 支付宝公钥证书 路径
            'alipay_public_cert_path' => '/certs/alipayCertPublicKey_RSA2.crt',
            // 支付宝根证书 路径
            'alipay_root_cert_path' => '/certs/alipayRootCert.crt',
            'return_url' => '',

        if ($request->input('type') == 'aliyun'){
            $order = [
                'out_trade_no' => $order->order_id,
                'total_amount' => $order->amount / 100,
                'subject' => $order->goods()->first()->title . '等' .$order->goods()->count().'件商品',
            ];

            return Pay::alipay()->scan($order);

        }

## 报错详情
![image](https://user-images.githubusercontent.com/74088421/128239224-c23faf7a-2336-40b3-9acd-563d7636675c.png)

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by wuzikai18** [comment]
// 应用公钥证书 路径
            'app_public_cert_path' => storage_path('/certs/appCertPublicKey_2021002165601246.crt'),
            // 支付宝公钥证书 路径
            'alipay_public_cert_path' => storage_path('/certs/alipayCertPublicKey_RSA2.crt'),
            // 支付宝根证书 路径
            'alipay_root_cert_path' => storage_path('/certs/alipayRootCert.crt'),

**Comment by wuzikai18** [comment]
把路径放在storage_path里之后 又会报这个错误
"message": "Class \"Symfony\\Bridge\\PsrHttpMessage\\Factory\\HttpFoundationFactory\" not found",

**Comment by yansongda** [comment]
laravel 框架安装 symfony/psr-http-message-bridge 将会自动处理 psr7 规范

**Comment by wuzikai18** [comment]
![image](https://user-images.githubusercontent.com/74088421/128285683-9fb205cf-a33f-4a9b-80f9-556b2abab7eb.png)
安装了之后又变成这样了

**Comment by wuzikai18** [comment]
return Pay::alipay()->scan($order);  如果改成scan就直接返回500错误了
 "message": "500 Internal Server Error",
    "code": 5003,
    "status_code": 500,
