### ISSUE TITLE
请问服务商模式支持吗

### ISSUE THREAD

**Issue by twosimple** [yansongda/pay#467]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yansongda** [comment]
v3 版支持 支付宝服务商；微信服务商暂不支持，在计划中

v2 版的一直都支持，如果强依赖微信服务商模式，可以使用 v2 版

**Comment by twosimple** [comment]
谢谢大佬
