### ISSUE TITLE
证书内容建议支持直接写字符串

### ISSUE THREAD

**Issue by xtls2** [yansongda/pay#468]
证书内容建议支持直接写字符串（同时支持文件地址指定与直接填写正式内容。。。）

**Comment by yansongda** [comment]
微信还是支付宝？

**Comment by yansongda** [comment]
支付宝方面，从支付宝下载下来的公钥默认就是文件，没必要自己再转成字符串；私钥字符串和地址 SDK都支持 

微信，从微信下载下来的本来都是文件形式
