### ISSUE TITLE
不能安装3.0.0

### ISSUE THREAD

**Issue by newfuture33** [yansongda/pay#469]
![image](https://user-images.githubusercontent.com/34529419/128826869-afa700c0-83a4-43fa-b6f9-2a82076ed09f.png)

**Comment by newfuture33** [comment]
我运行了这个命令
composer require yansongda/pay:~3.0.0 -vvv
不过发生错误。

**Comment by yansongda** [comment]
minimum-stability: "dev"

**Comment by newfuture33** [comment]
give me total command.

**Comment by newfuture33** [comment]
Hi, I want to integrate alipay and wechat payment to my website.
Please help me.
I will pay for this.
Thanks



At 2021-08-10 16:02:11, "yansongda" ***@***.***> wrote:

Closed #469.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
