### ISSUE TITLE
支付宝回调数据验证失败

### ISSUE THREAD

**Issue by anyforever** [yansongda/pay#47]
## 问题描述
用示例做的
$pay->driver('alipay')->gateway()->verify($request->all())
一直返回false
测试数据是支付宝同步return_url中GET的数据

异步通知这步也是验证失败

顺便问下异步通知中gateway类型有关么？比如用wap支付的，这里是否能验证通过？

还有微信的也是如此，支付的时候可能会用h5的wap和mp等，异步通知里能否wap一个网关来做回调数据的验证？我目前只做了wap支付，异步通知数据验证通过了

**Comment by yansongda** [comment]
属于验签错误。

请参考 #5 ，#8 ，#12 。

可以，验签是不区分 gateway 的。这个问题将在 v2.0.0 版本中解决。

感谢您的支持！谢谢

**Comment by anyforever** [comment]
@yansongda 
收到，谢谢。另外一个问题，支付宝这个sign有没有时效性？
如果有的话，我一直拿着之前获得的这个数据测试，估计会不行

**Comment by anyforever** [comment]
@yansongda 
解决了，[支付宝公钥与应用公钥的问题](https://github.com/yansongda/pay/issues/16#issuecomment-333080527)
配置里应该用支付宝公钥

**Comment by yansongda** [comment]
时效问题，请参考支付宝官方文档。

谢谢
