### ISSUE TITLE
微信支付 v2 和 v3 接口是否可以共存？

### ISSUE THREAD

**Issue by rust17** [yansongda/pay#473]
您好，项目中部分业务使用了微信的 v2 接口，现在新的业务想使用一些 v3 接口，如果原先使用的是该项目的 2.0 版本更换为 3.0 之后，原先的业务会不会受到影响？

**Comment by yansongda** [comment]
目前 Pay 的 v3 版直接使用的是 微信支付的 v3 API，但是 v3 API 不支持某些功能，所以 Pay 的 v3 版也不支持某些功能

如果你强依赖 微信支付的v2 API，建议使用 Pay 的 v2 版本即可。

![截屏2021-08-17 下午2 56 12](https://user-images.githubusercontent.com/11869114/129678345-94172fab-fa09-4a99-9e4d-40129636e853.png)

上面是 微信支付v3 不支持的 API

**Comment by rust17** [comment]
好的，谢谢告知，主要是需要用到一些只有在 v3 api 上有的接口，而大部分业务又使用的是 v2，一时半会也改动不了，我参考一下 Pay 的 v3 做个兼容试试，谢谢哈

**Comment by dayu923052830** [comment]
你好 composer install  拉取 失败。

**Comment by dayu923052830** [comment]
<img width="891" alt="lQLPDhryTaPNHDTNAgrNBvawhEYE3AjlB20BujuEDoCRAA_1782_522" src="https://user-images.githubusercontent.com/29965570/145558849-6a4efc53-5de9-4686-b75d-4a4b74585163.png">

**Comment by yansongda** [comment]
这是你网络问题
