### ISSUE TITLE
支付宝verify_alipay_sign失败

### ISSUE THREAD

**Issue by uamyangel** [yansongda/pay#474]
**基本信息**

- 版本：3.0.0
- 框架：tp5

**代码**
![image](https://user-images.githubusercontent.com/15668052/129685318-f81588a3-9c74-4781-ad69-7ec7fa659fb6.png)

**结果：支付回调，openssl_verify返回结果为0**

![image](https://user-images.githubusercontent.com/15668052/129684083-5f08150d-3075-4119-8ecf-b1319568dd57.png)

**Comment by yansongda** [comment]
检查自己的配置文件，支付宝公钥

**Comment by uamyangel** [comment]
> 检查自己的配置文件，支付宝公钥

从支付宝下载的公钥文件，配置如下
![image](https://user-images.githubusercontent.com/15668052/129685821-9afe493e-524b-41d9-a27c-62abd171a70d.png)
![image](https://user-images.githubusercontent.com/15668052/129686051-c00fc071-4895-4d57-9948-f241b743f0b8.png)

**Comment by yansongda** [comment]
查看 文档，自己看看  验签 失败那节 FAQ 吧

**Comment by uamyangel** [comment]
> 查看 文档，自己看看 验签 失败那节 FAQ 吧

是因为回调URL中加了其他参数的原因
已解决，感谢!
