### ISSUE TITLE
微信能收到支付回调并解密，但是无法获取数据

### ISSUE THREAD

**Issue by JieFuHe** [yansongda/pay#477]
## 包版本号
3.0.0-rc.1

## 问题描述
微信能收到支付回调并解密，但是无法获取数据。
我参考了支付宝获取数据的代码，使用`Pay::wechat()->callback($request->all());`之后，再使用`$result->resource`得到的是未解密的数据，请各位大佬指点一下，不胜感激谢谢！

## 你的代码
```
public function wechat(Request $request){
        try {
            $result = Pay::wechat()->callback($request->all());
            file_put_contents(storage_path('logs/wechat_notify.txt'),$result->id);
        }catch (\Exception $e){
            $e->getMessage();
        }
        return Pay::wechat()->success();
}
```

## 报错详情
无

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来
121.51.58.171 - - [25/Aug/2021:02:43:04 +0800] "POST /api/pay/wechat/notify HTTP/1.1" 200 54 "-" "Mozilla/4.0"

**Comment by yansongda** [comment]
什么框架？

PS：麻烦升级至最新版

**Comment by JieFuHe** [comment]
> 什么框架？
> 
> PS：麻烦升级至最新版

框架是laravel，当前版本已是 yansongda/pay (v3.0.2 => v3.0.3)、yansongda/laravel-pay (v3.0.0-rc.1 => v3.0.0):
正常来说`$result = Pay::wechat()->callback($request->all());`之后不是可以直接`$result->out_trade_no`来获取商户订单号嘛，但是返回空。

**Comment by yansongda** [comment]
$result['resource'][‘ciphertext’] 才能拿到 out_trade_no 吧？

你最好仔细看看 微信 的文档

**Comment by JieFuHe** [comment]
> $result['resource'][‘ciphertext’] 才能拿到 out_trade_no 吧？
> 
> 你最好仔细看看 微信 的文档
> 
> PS：fpm 类框架，不需要你在 callback 中额外传参数

已解决，感谢！

**Comment by puzzle9** [comment]
> callback($request->all())

原来这得这么传啊
