### ISSUE TITLE
不兼容 guzzle6 版本

### ISSUE THREAD

**Issue by TotoroLeon** [yansongda/pay#484]
今天更新依赖才发现，不兼容 guzzle6   老项目要怎么升级呢。

**Comment by yansongda** [comment]
有条件的话升级到 guzzle7 吧。。。

guzzle7 基本上是兼容 6 的

**Comment by JimChenWYU** [comment]
某个小版本就去掉6的兼容了...
https://github.com/yansongda/pay/commit/f86067005d18e82c831a0b90b0704509de233bce

**Comment by yansongda** [comment]
> 某个小版本就去掉6的兼容了...
> [f860670](https://github.com/yansongda/pay/commit/f86067005d18e82c831a0b90b0704509de233bce)

主要是 guzzle6 不支持 psr18
