### ISSUE TITLE
公钥证书问题，Argument 1 passed to PreparePlugin::getCertSn() must be of the type array, null given

### ISSUE THREAD

**Issue by morningbao** [yansongda/pay#485]
## 包版本号
V3
环境：
centos7.9
docker
php 7.3.29

## 问题描述
调用支付宝web支付方法，提示getCertSn参数错误

## 你的代码
`
public function pay(Request $request) {
    var_dump(Pay::alipay()->web([
        'out_trade_no' => 'twt'.time(),
        'total_amount' => '0.01',
        'subject' => 'yansongda 测试 - 1',
    ]));
}
`

## 报错详情
Argument 1 passed to Yansongda\\Pay\\Plugin\\Alipay\\PreparePlugin::getCertSn() must be of the type array, null given, called in /srv/http/twt/vendor/yansongda/pay/src/Plugin/Alipay/PreparePlugin.php on line 104

## 解决尝试
找到包代码这个报错的方法，发现是读应用公钥：
1、首先怀疑自己公钥没读到，遂检查文件，权限，获取到的内容，发现没问题。
2、其次怀疑公钥格式有问题，一开始我的公钥是一行内容，我尝试加头尾
-----BEGIN PUBLIC KEY-----
xxxxxx
-----END PUBLIC KEY-----
结果不行,我再尝试换行
-----BEGIN PUBLIC KEY-----
xxxxxx
xxxxxx
-----END PUBLIC KEY-----
还是不行。
这时我的测试重点已经放在openssl_x509_parse方法上，我单独尝试了给这个方法传各种格式的密钥，甚至试了私钥，结果都是返回false

openssl_x509_parse方法搜了谷歌百度都内容甚少

**Comment by yansongda** [comment]
按要求提，注意提问的智慧

**Comment by morningbao** [comment]
已解决，生成证书问题，仔细按照文档重新生成证书即可解决
