### ISSUE TITLE
微信多商户接收回调无法切换配置

### ISSUE THREAD

**Issue by b2894lxlx** [yansongda/pay#490]
## 包版本号

3.0.7
## 问题描述

微信多商户接受回调，无法切换到非默认配置，sdk打印的日志为默认配置
## 你的代码

        $config = array_merge(config('pay'), ['_force' => true, '_config' => $_config]);
        $data = Pay::wechat($config)->callback()->resource;
        $data = $data['ciphertext'];
        //**************
        return Pay::wechat($config)->success();
## 报错详情
local.ERROR: Get Wechat Public Cert Error {"exception":"[object] (Yansongda\\Pay\\Exception\\InvalidConfigException(code: 3006): Get Wechat Public Cert Error at /home/www/yhy-8/vendor/yansongda/pay/src/Functions.php:271)
[stacktrace]
#0 /home/www/yhy-8/vendor/yansongda/pay/src/Functions.php(226): reload_wechat_public_certs()
#1 /home/www/yhy-8/vendor/yansongda/pay/src/Plugin/Wechat/CallbackPlugin.php(35): verify_wechat_sign()
#2 /home/www/yhy-8/vendor/yansongda/supports/src/Pipeline.php(132): Yansongda\\Pay\\Plugin\\Wechat\\CallbackPlugin->assembly()
#3 /home/www/yhy-8/vendor/yansongda/supports/src/Pipeline.php(90): Yansongda\\Supports\\Pipeline->Yansongda\\Supports\\{closure}()
#4 /home/www/yhy-8/vendor/yansongda/pay/src/Provider/AbstractProvider.php(75): Yansongda\\Supports\\Pipeline->then()
#5 /home/www/yhy-8/vendor/yansongda/pay/src/Provider/Wechat.php(134): Yansongda\\Pay\\Provider\\AbstractProvider->pay()
#6 /home/www/yhy-8/app/Api/V1/Controllers/PayController.php(251): Yansongda\\Pay\\Provider\\Wechat->callback()

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by b2894lxlx** [comment]
手动将其他配置复制到默认配置则没问题，
        $resourceConfig = config('pay');
        if ($_config != 'default') {
            $resourceConfig['wechat']['default'] = $resourceConfig['wechat'][$_config];
        }
        $config = array_merge($resourceConfig, ['_force' => true]);

**Comment by yansongda** [comment]
传递 callback 第二个参数切换配置

https://github.com/yansongda/pay/blob/master/src/Provider/Wechat.php#L127
