### ISSUE TITLE
日志配置无效

### ISSUE THREAD

**Issue by mark0325** [yansongda/pay#504]
https://github.com/yansongda/pay/blob/09a431a2a096c9d9243663b8b57c76c113ed3a08/src/Logger.php#L32

!Pay::has(LoggerInterface::class) 始终为true，导致日志配置无效

**Comment by zijinyise** [comment]
我的配置也无效
'logger' => [ // optional
        'enable' => true,
        'file' => ROOT_PATH.'runtime/wechat.log',
        'level' => 'debug', // 建议生产环境等级调整为 info，开发环境为 debug
        'type' => 'single', // optional, 可选 daily.
        'max_file' => 30, // optional, 当 type 为 daily 时有效，默认 30 天
],
