### ISSUE TITLE
微信服务商会有电商收付通这种行业方案，退款接口地址不一样

### ISSUE THREAD

**Issue by ddouvsnniu** [yansongda/pay#512]
那么应该怎么去更改访问接口，直接改代码不方便迁移。
https://pay.weixin.qq.com/wiki/doc/apiv3_partner/apis/chapter7_6_1.shtml

**Comment by yansongda** [comment]
可以自己参考源码写个 plugin

https://pay.yansongda.cn/docs/v3/kernel/plugin.html#%E5%AE%9A%E4%B9%89

搞定的话，可以考虑提个 PR

**Comment by yansongda** [comment]
close via: #513
