### ISSUE TITLE
PHP 8+hyperf2.2  函数 verify_wechat_sign 无法获取到$timestamp $random $body 这三个值

### ISSUE THREAD

**Issue by MidnightDJ** [yansongda/pay#514]
PHP 8+hyperf2.2 
函数 verify_wechat_sign
无法获取到$timestamp $random $body 这三个值 ，var_dump 为空，
请问一下是什么问题？

## 包版本号
"yansongda/hyperf-pay": "~1.0.0"

## 问题描述
<img width="908" alt="1636705436(1)" src="https://user-images.githubusercontent.com/23242278/141434752-a93308aa-778e-4bba-8c0d-f36f00f9e4b2.png">

## 报错详情

![image](https://user-images.githubusercontent.com/23242278/141435415-11b4ea44-ae38-417a-be37-d8b2d5d1d2ec.png)

## sdk 日志
![image](https://user-images.githubusercontent.com/23242278/141435494-dd2fb8d4-8bf1-445f-b90f-2b1eda10a494.png)

**Comment by yansongda** [comment]
https://pay.yansongda.cn/docs/v3/wechat/callback.html#%E5%8F%82%E6%95%B0
