### ISSUE TITLE
Get Wechat Public Cert Error

### ISSUE THREAD

**Issue by MidnightDJ** [yansongda/pay#515]
## 问题描述
<img width="248" alt="1636818463(1)" src="https://user-images.githubusercontent.com/23242278/141650143-2a68e1f8-99bf-4139-b0ea-b0a184e109eb.png">

这段代码返回的false?
<img width="597" alt="1636818558(1)" src="https://user-images.githubusercontent.com/23242278/141650197-65c3d860-fd11-4b99-b77e-ceb4f1bcf914.png">

**Comment by yansongda** [comment]
检查微信商户密钥

**Comment by 0xbyc** [comment]
Get Wechat Public Cert Error
