### ISSUE TITLE
微信wap支付获取app_id取错配置了

### ISSUE THREAD

**Issue by wwwylo** [yansongda/pay#516]
## 包版本号
v3.0.17

## 问题描述
在配置项里有mp_app_id、mini_app_id、app_id三个用于配置appid的，用wap方法来发起支付，取的是mp_app_id的值，因为这是手机网页支付，不是公众号支付，我认为应该取app_id的值而不是mp_app_id的值

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
取 app_id，你真实测试过么？

**Comment by wwwylo** [comment]
测试过，发起网页支付的时候把appid放在app_id里，接口请求报错说appid不存在，放在mp_app_id里就好了

**Comment by yansongda** [comment]
> 测试过，发起网页支付的时候把appid放在app_id里，接口请求报错说appid不存在，放在mp_app_id里就好了

。。。天， app_id 代表 APP 的 id， mp_app_id 代表 微信公众号的 id，微信要求 H5 支付时使用 微信公众号的 id。

仔细看看文档吧
