### ISSUE TITLE
微信支付 v3 签名失败，关于配置文件的几个疑问？

### ISSUE THREAD

**Issue by MidnightDJ** [yansongda/pay#519]
## 疑问？？

**1. 商户公钥证书   指的是商户api证书么？就像这样apiclient_cert.pem**
**2.商户秘钥是apiv3密钥？**
**3. 商户私钥是apiclient_key.pem ？？**

## 包版本号
hyperf-pay：1.0.0
## 你的代码
<img width="403" alt="1637248839(1)" src="https://user-images.githubusercontent.com/23242278/142443640-73a4b4bd-10b5-42ea-9a0d-dba7bee2d60c.png">

## 报错详情
<img width="208" alt="1637248718(1)" src="https://user-images.githubusercontent.com/23242278/142443311-d71fcbfb-f396-4e87-92b2-b4ce96f0923f.png">
<img width="297" alt="1637248875(1)" src="https://user-images.githubusercontent.com/23242278/142443743-fd27afc6-fdff-4972-bdfa-55af3314e889.png">

**Comment by yansongda** [comment]
是的，v3秘钥
