### ISSUE TITLE
感谢作者的开源，希望增加swoft的适配

### ISSUE THREAD

**Issue by Akuns** [yansongda/pay#520]
感谢作者的开源，很喜欢这个支付SDK，一直在用，最近在用swoole开发项目，用到了swoft，求适配swoft，近期有没有计划呀。谢谢

**Comment by JimChenWYU** [comment]
你用3.0就可以了，3.0已经对swoole环境进行了适配

**Comment by yansongda** [comment]
是的，用 v3 即可
