### ISSUE TITLE
关于user_id的获取

### ISSUE THREAD

**Issue by blackcocwhite** [yansongda/pay#526]
小程序支付的时候，需要填写支付宝user_id，不知道大佬会考虑把授权这块的接口加入到版本中吗？

**Comment by yansongda** [comment]
目前可能不会，暂时只专注于支付模块。当然，如果 API 类似的话，可以考虑接进来

**Comment by 393633905** [comment]
> 目前可能不会，暂时只专注于支付模块。当然，如果 API 类似的话，可以考虑接进来

可以自定义插件，实现授权功能接口是吧？

**Comment by yansongda** [comment]
> > 目前可能不会，暂时只专注于支付模块。当然，如果 API 类似的话，可以考虑接进来
> 
> 可以自定义插件，实现授权功能接口是吧？

可以，你自己自定义插件实现就行
