### ISSUE TITLE
LaunchPlugin 不会返回支付宝错误消息

### ISSUE THREAD

**Issue by dut3062796s** [yansongda/pay#529]
## 包版本号
3.0.19

## 问题描述
LaunchPlugin的verifySign方法不会返回支付宝错误消息

## 你的代码
LaunchPlugin 下的这个方法
protected function verifySign(Rocket $rocket): void
    {
        $response = $rocket->getDestination()->get($this->getResponseKey($rocket));
        $sign = $rocket->getDestination()->get('sign', '');

        if ('' === $sign || is_null($response)) {
            throw new InvalidResponseException(Exception::INVALID_RESPONSE_SIGN, '', $response);
        }

        verify_alipay_sign($rocket->getParams(), json_encode($response, JSON_UNESCAPED_UNICODE), base64_decode($sign));
    }

## 报错详情
调试时当支付返回错误消息的时候，$response == null,直接走的下边的InvalidResponseException，导致报错。
$this->getResponseKey($rocket) 返回的是 alipay_system_oauth_token_response。
$rocket->getDestination()->get($this->getResponseKey($rocket)); 这个获取的时候是返回null
$rocket->getDestination() 是可以获取到错误消息的，错误消息如下：
items = {array} [3]
 error_response = {array} [4]
  code = "40002"
  msg = "Invalid Arguments"
  sub_code = "isv.code-invalid"
  sub_msg = "授权码code无效"
 alipay_cert_sn = "18caa3b3a61d81943e1f4395ef4b5e48"
 sign = "asdadasdsdasd"

这个$response 可以调整下么，返回支付宝的错误消息 sub_msg 。

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
自己捕获异常拿 response 处理吧

**Comment by dut3062796s** [comment]
主要是 在catch中 返回Exception 里边都是 Null,拿不到这个错误消息

**Comment by yansongda** [comment]
知道你的意思了。回头优化下

**Comment by dut3062796s** [comment]
好的,谢谢大佬
