### ISSUE TITLE
3.0版本微信小程序支付预下单失败

### ISSUE THREAD

**Issue by sinceyy** [yansongda/pay#531]
## 包版本号
3.0

## 问题描述
微信小程序支付预下单失败

## 你的代码
`
array(6) {
  ["out_trade_no"]=>
  string(12) "202112060928"
  ["description"]=>
  string(18) "测试发起支付"
  ["amount"]=>
  array(2) {
    ["total"]=>
    int(10)
    ["currency"]=>
    string(3) "CNY"
  }
  ["attach"]=>
  string(49) "休闲鞋"
  ["notify_url"]=>
  string(49) "https://xxx/order/notify/wxNotify"
  ["payer"]=>
  array(1) {
    ["openid"]=>
    string(28) "on1f-504a-TzWB1jgeFIc5yHfv1A"
  }
}
`

$this->handler->mini(array_merge($orderData, ['_config' => 'default']));

## 报错详情
 Unpack Response Error[28] in /Users/lianka/Project/payCenter3.0/vendor/yansongda/pay/src/Parser/ArrayParser.php

## sdk 日志
yansongda.pay.INFO > [AbstractProvider] 请求支付服务商 API 成功 {"response":{"GuzzleHttp\\Psr7\\Response":[]},"rocket":{"radar":{"Yansongda\\Pay\\Request":{"url":"https://api.mch.weixin.qq.com/sandboxnew/v3/pay/transactions/jsapi","method":"POST","headers":{"Host":["api.mch.weixin.qq.com"],"Accept":["application/json, text/plain, application/x-gzip"],"User-Agent":["yansongda/pay-v3.0"],"Content-Type":["application/json; charset=utf-8"],"Authorization":["WECHATPAY2-SHA256-RSA2048 mchid=\"1********1\",nonce_str=\"ujSLG4pgLxNalonmktqjpiF3RKyYbQaN\",timestamp=\"1638782907\",serial_no=\"1E924E947ACEFFFFAB004A1D3119D74E4212D091\",signature=\"hyqgRGsm+FL9bNMZjvKIVtSi28SwKe8N1vrnQcYtpffWaN+v/7PGJIyYs2A7jbpaXrcBe4SSg9AqrvqvU0rG7X7VUEsIhkKWwnrpgrWPVXSvKXwgC3fqlQEbQiX6esEjdJ4tWyxPRN+VBdDBHteTKwlcd9rvYP9I3DQl7NBv/3p4/dWWHPepXurD/QL2l6lOx1A4Xekp6uiNVR5IBunDjZlTzYJ2GD8Dp+clUuZ/yv+ab8ssmcgBgLfGdidCE89iZRI6r0BTXEiKpTwwKxv/Eojidv9W1PKu16M+ExlnniVy/IUGXk4scp4+XNNCs+D5bzewXlPDlaRuzV3wIjYFCw==\""]},"body":""}},"params":{"out_trade_no":"202112060928","description":"测试发起支付","amount":{"total":10,"currency":"CNY"},"attach":"https://pay-api.petadmin.cn/order/notify/wxNotify","notify_url":"https://pay-api.petadmin.cn/order/notify/wxNotify","payer":{"openid":"on1f-504a-TzWB1jgeFIc5yHfv1A"},"_config":"default"},"payload":{"Yansongda\\Supports\\Collection":{"out_trade_no":"202112060928","description":"测试发起支付","amount":{"total":10,"currency":"CNY"},"attach":"https://pay-api.petadmin.cn/order/notify/wxNotify","notify_url":"https://pay-api.petadmin.cn/order/notify/wxNotify","payer":{"openid":"on1f-504a-TzWB1jgeFIc5yHfv1A"},"appid":"wx6dce905fbbecfca4","mchid":"1563981051"}},"direction":null,"destination":{"GuzzleHttp\\Psr7\\Response":[]},"destination_origin":{"GuzzleHttp\\Psr7\\Response":[]}}} 

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
自己捕获异常看微信返回吧。你这提供的信息谁知道是啥问题哦

**Comment by sinceyy** [comment]
。。。。。我总不能用大哥你的composer包，我还去你的vendor包中去打印获取异常吧？调试如此麻烦的？按理说我只需在log日志看到微信返回的错误信息原文才对

**Comment by yansongda** [comment]
捕获异常 看具体信息就行了
