### ISSUE TITLE
查询资金插件

### ISSUE THREAD

**Issue by yang316** [yansongda/pay#532]
## 包版本号

3.0.20
## 问题描述
![image](https://user-images.githubusercontent.com/63343312/145140337-b66898cc-02bb-402f-8afd-bf0e626386b4.png)
c查询资金这个接口具体使用

## 你的代码
![image](https://user-images.githubusercontent.com/63343312/145140379-e773be50-ab84-4c5f-9ccb-952e2a5019ca.png)

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
把  `Pay::alipay()->find()`   改为 `Pay::alipay()->pay()`

具体可查看文档

**Comment by yang316** [comment]
> 把 改为`Pay::alipay()->find()``Pay::alipay()->pay()`
> 
> 具体可查看文档

![image](https://user-images.githubusercontent.com/63343312/145167002-62d0d10a-ab75-4320-a985-0f7195c91d02.png)
我是这样写的但是请求后好像不对
![image](https://user-images.githubusercontent.com/63343312/145167055-87a9629a-af81-46a7-a9fe-6027025ea93f.png)

**Comment by yang316** [comment]
![image](https://user-images.githubusercontent.com/63343312/145167428-f36eed60-a16a-43ae-bd0e-d8241f2bb554.png)
代码改成这样但是请求后还是不对
![image](https://user-images.githubusercontent.com/63343312/145167473-d83b7e59-7ac1-4d27-9700-94918f0477be.png)
