### ISSUE TITLE
请问，v2版本支付宝付款中extend和makeExtend方法，可以给一个案例吗，看了好久，只知道是拓展方法，不知道具体如何使用

### ISSUE THREAD

**Issue by peas7777** [yansongda/pay#539]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yansongda** [comment]
有条件的话，升到 v3 吧

**Comment by peas7777** [comment]
耐心看了看V3的源码，发现更不懂了。学识不够了！
