### ISSUE TITLE
composer require symonfy/event-dispatcher 报错了

### ISSUE THREAD

**Issue by peas7777** [yansongda/pay#541]
## 包版本号
V3

## 问题描述
composer require symonfy/event-dispatcher
报错不能安装

**Comment by yansongda** [comment]
具体信息

**Comment by peas7777** [comment]
Could not find a matching version of package symonfy/event-dispatcher. Check the package spelling, your version con
  straint and that the package is available in a stability which matches your minimum-stability (stable).

**Comment by yansongda** [comment]
symfony   打错了
