### ISSUE TITLE
支付宝是不是没有当面付

### ISSUE THREAD

**Issue by couldnice** [yansongda/pay#543]
是不是没得支付宝当面付

**Comment by yansongda** [comment]
？？刷卡、扫码不都是么？

**Comment by couldnice** [comment]
沙河测试中支付成功了
然后切到了我的密钥，对的没营业执照也能申请的那个当面付。(应该可能和商业的分开了吧)
写入key，
一开始我看文档我也以为当面付就是是扫码，后来失败了(=￣ ρ￣=) ..zzZZ
我明天试试看因为确实我的key在原来的程序还是能跑的
原来使用的库https://www.dedemao.com/alipay/demo.html
所以来问一下是不是做了这个，
这么晚了，十分抱歉。
