### ISSUE TITLE
日志配置文件打开无效

### ISSUE THREAD

**Issue by zijinyise** [yansongda/pay#544]
## 包版本号
3.0

## 问题描述
日志配置文件打开无效 enable为true，

## 你的代码
'logger' => [ // optional
                'enable' => true,
                'file' => './logs/wechat.log',
                'level' => 'debug', // 建议生产环境等级调整为 info，开发环境为 debug
                'type' => 'single', // optional, 可选 daily.
                'max_file' => 30, // optional, 当 type 为 daily 时有效，默认 30 天
            ],

## 报错详情
没有生成文件，手动生成wechat.log也无效

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
Monolog\Logger   安装了么

**Comment by zijinyise** [comment]
> Monolog\Logger 安装了么

感谢大佬哈  
还真没装，我看大佬你写的教程那里说内置了日志系统，还就以为我配置错了
