### ISSUE TITLE
大佬，V2版本支持swoole环境运行吗？

### ISSUE THREAD

**Issue by shuipf** [yansongda/pay#545]
想用V3，但是一些配置不方便处理。
所以选择V2，V2不知道对于swoole 4.8 版本支持怎么样？

**Comment by yansongda** [comment]
支持，可以参考 [yansongda/hyperf-pay](https://github.com/yansongda/hyperf-pay)

**Comment by shuipf** [comment]
v3单例模式不是很好用。
微信还有支付宝，要的配置内容比较多。我配置都是几年前的，更新一次太麻烦了。
