### ISSUE TITLE
HTTP header缺少微信支付平台证书序列号(Wechatpay-Serial)

### ISSUE THREAD

**Issue by zijinyise** [yansongda/pay#546]
## 包版本号
v3.0.21

## 问题描述
微信请求分账时返回这个错误

## 报错详情
{
    "code":"PARAM_ERROR",
    "message":"HTTP header缺少微信支付平台证书序列号(Wechatpay-Serial)"
}

## sdk 日志
[wechat][LaunchPlugin] 插件装载完毕 {"rocket":{"Yansongda\\Pay\\Rocket":{"radar":{"url":"https://api.mch.weixin.qq.com/v3/profitsharing/orders","method":"POST","headers":{"Host":["api.mch.weixin.qq.com"],"Accept":["application/json, text/plain, application/x-gzip"],"User-Agent":["yansongda/pay-v3.0"],"Content-Type":["application/json; charset=utf-8"],"Authorization":["WECHATPAY2-SHA256-RSA2048 mchid=\"1561144081\",nonce_str=\"N9bUqHPSpinCEgSxb5jZhBkivjk68gNE\",timestamp=\"1641613622\",serial_no=\"250C806874AC4721B21A27121D0HJ75F52567909\",signature=\"Xh5YTQgMoyhlzClWOd4jXYQZnCuyC+hha2EyDyGRD8mJAnxf8h9Cwq5sjDdrgYHshiqX5WAaDZBZ/BRTeqGFqshoG5KYLCAVXR5kkFGHjGt4yV899wImU3jyANTjw3+YiLVkoqgOtebjGwj6/kN09ba5qDIwo6vIWwfdNEnMtphEZqZeREKrux18P+yCfa+4SNbDJ/4vQShZepnMZpPLqSg4xH5pKAMFlwgKGzUHeiH2aN6ObyVUwBBhSyGTyejKfNaEs6BmLiL0u/oEv/uHTj9ZLZRb87ADSnbCuiAwzoSXYXStwIawW7nIGuChnNFuiA4oPUrMbhTA8w6XKIqijA==\""]},"body":""},"params":{"transaction_id":"4200001372202112286687******","out_order_no":"2021122916050738512","receivers":[{"type":"PERSONAL_OPENID","account":"oFUShng7bUpyZX_sAmj8It******","name":"张三","amount":2.0,"description":"购买商品分账"}],"unfreeze_unsplit":false},"payload":{"transaction_id":"4200001372202112286687******","out_order_no":"2021122916050738512","receivers":[{"type":"PERSONAL_OPENID","account":"oFUShng7bUpyZX_sAmj8ItaWHfL8","name":"张三","amount":2.0,"description":"购买商品分账"}],"unfreeze_unsplit":false,"appid":"wxfe7f5423cc******"},"direction":null,"destination":{"code":"PARAM_ERROR","message":"HTTP header缺少微信支付平台证书序列号(Wechatpay-Serial)"},"destination_origin":{}}}} 

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
是有这个问题。晚些时候修复下

**Comment by zijinyise** [comment]
> 是有这个问题。

好的好的，谢谢大佬
