### ISSUE TITLE
支付宝的接口加签方式

### ISSUE THREAD

**Issue by zouum** [yansongda/pay#553]
现在包里是只支持公钥证书模式是吗，没有普通公钥模式

**Comment by yansongda** [comment]
v3 只支持 公钥证书 模式

v2 支持 普通公钥 模式

PS： 普通公钥模式 很多场景没办法使用，建议尽快升级至 证书 模式

**Comment by zingimmick** [comment]
> v3 只支持 公钥证书 模式

@yansongda 您好，这里我想要确认下，**v3 只支持 公钥证书 模式**是临时性调整还是长期的？

因为支付宝文档里提到对个人开发者不涉及到资金类接口，是建议使用 公钥 方式进行加签的。

文档链接：https://opendocs.alipay.com/common/02kf5p#%E7%AD%BE%E5%90%8D%E6%96%B9%E5%BC%8F%E9%80%89%E6%8B%A9%E8%AF%B4%E6%98%8E
