### ISSUE TITLE
支付宝 APP支付 没有返回json，返回了字符串参数

### ISSUE THREAD

**Issue by buildwide** [yansongda/pay#555]
## 包版本号
yansongda/laravel-pay": "~3.0.0

## 问题描述
进行支付宝 APP支付时 没有返回json，返回了字符串参数
![image](https://user-images.githubusercontent.com/50657743/149259233-51a634a8-12dd-4869-bf38-aa3ffbadb1ee.png)

## 你的代码
```
//配置
    public function config()
    {
        $config = config('pay');
        Pay::config($config);
    }
    //支付宝支付
    public function alipayPay($no, $amount, $subject = '订单支付')
    {
        $this->config();
        return Pay::alipay()->app([
            'out_trade_no' => $no,
            'total_amount' => $amount,
            'subject' => $subject,
        ]);
    }
```
### composer
![image](https://user-images.githubusercontent.com/50657743/149263329-2d558535-40f9-42ba-9d41-197f1915c9d9.png)

### 配置文件
![image](https://user-images.githubusercontent.com/50657743/149261103-c9004a9e-bc59-45fa-a158-e3254313a4f6.png)

## sdk 日志
![image](https://user-images.githubusercontent.com/50657743/149259539-5e6b5946-7f9b-441d-b9d7-014f60440ff7.png)
![image](https://user-images.githubusercontent.com/50657743/149259603-7650d62d-d185-4090-97f6-af3c9cb270f0.png)

**Comment by yansongda** [comment]
app 要的就是这一串 string，如果你要其它的，自己在系统中转吧

**Comment by buildwide** [comment]
> 

不好意思，之前没有对接过支付宝支付。
能不能问一嘴，为什么微信返回的是json，支付宝返回的是这种格式，是他们的实现方式有差异么
