### ISSUE TITLE
话说2.x版本改成这样，完全没有代码提示和跟踪了。。。

### ISSUE THREAD

**Issue by niefufeng** [yansongda/pay#56]
## 问题描述
`Null`

## 代码
`Null`

## 报错详情
`Null`

**Comment by yansongda** [comment]
作为一个用 Sublime Text 写项目的人，表示体会不到您的烦恼，当然了，我也是 PHPStorm 的用户，这并不代表哪个好哪个坏。editor 给我最大的感觉就是：自信与莫名的成就感。推荐试试看 editor，返璞归真。

SDK 已经做到了简单，语义化，我想开发起来丝毫不会增加任何开发效率上的损失，相反可能会有提高。

如果您想关心细节，我想告诉您**别太在意内部实现**。如果您想更加提高自己，那么，**机会来了！**

**Comment by niefufeng** [comment]
嗯，不过用`IDE`的人大多都是为了代码提示，不然肯定会使用`editor`，这大概也是`laravel-ide-helper`、`swoole-ide-helper`之类的东西存在的意义。
当然，我也只是吐槽一下，并没有其他意思:joy:

**Comment by m3yang** [comment]
建议加入注释解决代码提示

**Comment by m3yang** [comment]
有提示跟踪还是方便一些的。比如在ide中直接跳转到对应的代码。

**Comment by yansongda** [comment]
v2.0.19 版已经增加针对 phpstorm 的代码提示注释！

感谢 @krissss 的 PR！
