### ISSUE TITLE
支付宝：SystemOauthTokenPlugin插件相关bug

### ISSUE THREAD

**Issue by 393633905** [yansongda/pay#564]
## 包版本号
v3.0.25

## 问题描述
- 1.使用SystemOauthTokenPlugin换取用户令牌的时候，不抛出具体错误，只抛出了sign验签错误，其实并不是sign验签错误；
- 2.当是服务商模式代商户调用此接口时，若在调试接口的时候传入app_auth_token时，底层会将参数存入到biz_content中，从而导致支付宝那边提示app_auth_token错误。但根据支付宝文档发现此接口的app_auth_token是单独的参数，并不存放再biz_content；

## 你的代码
 $plugin = Pay::alipay()->mergeCommonPlugins([SystemOauthTokenPlugin::class]);
  $result = Pay::alipay()->pay($plugin,$params);

## 报错详情

> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by pierre1992** [comment]
支付宝支付的时候，添加的自定义notify_url不生效，还是只能在config里面配置吗？

**Comment by yansongda** [comment]
fixed by: #894
