### ISSUE TITLE
添加分账接收方报错

### ISSUE THREAD

**Issue by bupthui** [yansongda/pay#565]
## 包版本号
v3.0.26

## 问题描述
添加分账接收方报错

## 你的代码
// 选填-微信公钥证书路径, optional，强烈建议 php-fpm 模式下配置此参数
                    'wechat_public_cert_path' => [
                        '563CDFAD7C899FD3411268FD1C4641859315FC5B' => '***.pem',//通过CertificateDownloader-1.1.jar第一次生成的pem文件

Pay::config($this->config);
        $params = [
            'appid' => '***',
            'sub_mchid' => '***',
            'type' => 'MERCHANT_ID',
            'account' => '****',
            'relation_type' => 'SERVICE_PROVIDER',
            'sub_appid' => '*****',
            'name' => '北京*****',
        ];
        $allPlugins = Pay::wechat()->mergeCommonPlugins([AddReceiverPlugin::class]);
        $plugin_result = Pay::wechat()->pay($allPlugins, $params);

                    ],

## 报错详情

接口返回 {\"code\":\"PARAM_ERROR\",\"message\":\"HTTP header缺少微信支付平台证书序列号(Wechatpay-Serial)\"},\"destination_origin\":{}})
## sdk 日志
插件装载完毕 {"rocket":"[object] (Yansongda\\Pay\\Rocket: {\"radar\":{\"url\":\"https://api.mch.weixin.qq.com/v3/profitsharing/receivers/add\",\"method\":\"POST\",\"headers\":{\"Host\":[\"api.mch.weixin.qq.com\"],\"Accept\":[\"application/json, text/plain, application/x-gzip\"],\"User-Agent\":[\"yansongda/pay-v3.0\"],\"Content-Type\":[\"application/json; charset=utf-8\"],\"Authorization\":[\"WECHATPAY2-SHA256-RSA2048 mchid=\\\"1614392812\\\",nonce_str=\\\"QWln1OIRhqkwvreguSQ1C8dBtgmCOCwE\\\",timestamp=\\\"1645002038\\\",serial_no=\\\"1155B5A316BC81EFBF67AA5962C046177FD7EFDD\\\",signature=\\\"p+hLi5hpg3AOVDUIgCQg1nxTBrIgf0yNiY4CKNwFFoS00LVMZan4YFPonPabcp4gSn3dOOC7GB9NcRH0TI7b5AqaGcyKWSCIpwGtbp7i2OryxKkrrztOY+f3n5fSRp1nPASw5cTVjtu6NPyecVHXOb0kLy9QA6OaB3bfFDp6QPu4R9/+e3E59ZUVTdu3QI9K63Za3WP4HryQ6E2LXLlpMUIMzIJLXsUJxr1pM1gfeE1F8Kai9IfzmlJa4AtWAUT/wKFKEJoupeTQ8bp4RekZHNm5w1yZfhDcy0GCSWzLoj0K0Nni85lMzoazvZpLkYbCiz/adiGMHjZ2LP/VwTJ9mg==\\\"\"]},

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by bupthui** [comment]
如果对$params添加一个key value对， '_serial_no' => '563CDFAD7C899FD3411268FD1C4641859315FC5B',
就会爆新的错误
{\"code\":\"PARAM_ERROR\",\"message\":\"请确认待处理的消息是否为加密后的密文\"},\"destination_origin\":{}})"}



 [wechat][SignPlugin] 插件装载完毕 {"rocket":"[object] (Yansongda\\Pay\\Rocket: {\"radar\":{\"url\":\"https://api.mch.weixin.qq.com/v3/profitsharing/receivers/add\",\"method\":\"POST\",\"headers\":{\"Host\":[\"api.mch.weixin.qq.com\"],\"Accept\":[\"application/json, text/plain, application/x-gzip\"],\"User-Agent\":[\"yansongda/pay-v3.0\"],\"Content-Type\":[\"application/json; charset=utf-8\"],\"Authorization\":[\"WECHATPAY2-SHA256-RSA2048 mchid=\\\"1614392812\\\",nonce_str=\\\"xRO9bggLSvtXHgCUQf53VZ5AVXJaQ5Cq\\\",timestamp=\\\"1645004027\\\",serial_no=\\\"1155B5A316BC81EFBF67AA5962C046177FD7EFDD\\\",signature=\\\"KCvZaiDVPs7SZVYzBNLjan30AdcwUxtoYRaCUT5Oy3z1BVXLWPvNkDBcvx4twCUVjdnWnGcvyVIjQoj7zcM9SmepzGiOi7syfNVSBP+zwCNcUmljzMqs8tvPTCNN+W3NTKzYd2m3uQhxhHjAsj4GWbLyKQUIvZie/rWpA5vXdDeHbm7zf7U4rKz1/v4yF50JPMqTQ1L0ZEIlw/gBmqls7T1of1+0Q7bmNwrykToR18KxegAeCU2gjlyh/YdSefzh6sHRLXvedklHqFnP48hvxiIY/+ggidipmgaNcXvUFBeIaLfgfmar5CEmd/mh7B4ssVYceSR134oUMgzGISBdrg==\\\"\"],\"Wechatpay-Serial\":[\"563CDFAD7C899FD3411268FD1C4641859315FC5B\"]},

**Comment by yansongda** [comment]
你参数有问题吧？都没有 receivers

**Comment by bupthui** [comment]
参数没有问题，我是故意把敏感信息隐藏了部分。

我在重新发一下 
```
{"rocket":"[object] (Yansongda\\Pay\\Rocket: {\"radar\":{\"url\":\"https://api.mch.weixin.qq.com/v3/profitsharing/receivers/add\",\"method\":\"POST\",\"headers\":{\"Host\":[\"api.mch.weixin.qq.com\"],\"Accept\":[\"application/json, text/plain, application/x-gzip\"],\"User-Agent\":[\"yansongda/pay-v3.0\"],\"Content-Type\":[\"application/json; charset=utf-8\"],\"Authorization\":[\"WECHATPAY2-SHA256-RSA2048 mchid=\\\"1614392812\\\",nonce_str=\\\"NsqDahwXSi8ENp0eWinDyTZqwOTFyT4z\\\",timestamp=\\\"1645005731\\\",serial_no=\\\"1155B5A316BC81EFBF67AA5962C046177FD7EFDD\\\",signature=\\\"t8fOKE9g2swVWV/eHMhUEMRRc5cQs5aCDNsseC1f9SVVd2EI261AmceNE9YTnS6uty5ifVuS+MHGeX4FBppasia5jiVEUL3FAmwJesGGYlJeqGmSy1trLSzgeDVEnQPqERaR2iIJ7ubuIvBVScYghFUQuz3W9X00r/s2sjehm6XH+ED4ocPxw+YtkFK1r5G2fzQnoaBDy6TnZDtS1qMZsZ1GguQ6mAhks/AJwKQu3/Op1UA6Qygj4s1ExADc00INVttSmj2NFocPFJR0QENYr8vAaIdOzT22Gp30ohyzxlebhqwhVwBtXhMyp/H8REUL+uWkOpF5MQYrcfzlRfu2xg==\\\"\"],\"Wechatpay-Serial\":[\"1155B5A316BC81EFBF67AA5962C046177FD7EFDD\"]},\"body\":\"\"},\"params\":{\"appid\":\"wx11b66d5162\",\"sub_mchid\":\"1620276562\",\"type\":\"MERCHANT_ID\",\"account\":\"16143812\",\"relation_type\":\"SERVICE_PROVIDER\",\"sub_appid\":\"wx72ab46e6d51f\",\"name\":\"北京有限公司\",\"_serial_no\":\"1155B5A316BC81EFBF67AA5962C046177FD7EFDD\"},\"payload\":{\"appid\":\"wx11b6901162\",\"sub_mchid\":\"1620276562\",\"type\":\"MERCHANT_ID\",\"account\":\"16143912\",\"relation_type\":\"SERVICE_PROVIDER\",\"sub_appid\":\"wx72abe31d51f\",\"name\":\"北京有限公司\"},\"direction\":null,\"destination\":{\"code\":\"PARAM_ERROR\",\"message\":\"请确认待处理的消息是否为加密后的密文\"},\"destination_origin\":{}})"}
```

**Comment by yansongda** [comment]
你看看微信的文档，文档里有 `receivers` 这个参数，从你的代码里没看到

**Comment by bupthui** [comment]
接口文档 [添加分账方](https://pay.weixin.qq.com/wiki/doc/apiv3_partner/apis/chapter8_1_8.shtml)， 并没有`receivers `这个参数

**Comment by bupthui** [comment]
是添加分账方接收方接口，不是请求分账接口。
添加个人分账是可以成功的，但是添加服务商为分账方，就报错了。 @yansongda

**Comment by yansongda** [comment]
我看错了。。。

https://github.com/yansongda/pay/blob/master/src/Plugin/Wechat/Fund/Profitsharing/AddReceiverPlugin.php#L31

这一行改为 `if (!empty($params['name'] ?? '')) {` 试试

**Comment by bupthui** [comment]
对字段参数不正确问题、加密问题进行了fix。 #566
