### ISSUE TITLE
v2版本的配置文件与报错不符

### ISSUE THREAD

**Issue by sinceyy** [yansongda/pay#567]
## 包版本号
v2

## 问题描述
依照https://pay.yansongda.cn/docs/v2/quickUsage.html#%E5%BE%AE%E4%BF%A1 的微信配置，已填写配置，但运行初始化时，报错“请确认请求参数是否正确param mch_id invalid”，已确认配置文件中mch_id已配置

## 你的代码
$this->handler = Pay::wechat($config['config']);

## 报错详情
`
[
  "return_code" => "FAIL"
  "retmsg" => "请确认请求参数是否正确param mch_id invalid"
  "retcode" => "1"
]
`

## sdk 日志
 "请确认请求参数是否正确param mch_id invalid"

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by sinceyy** [comment]
已检查出问题在，你请求 "pay/getsignkey"  做校验时候，post的options参数中请求的主体是xml，但header中未增加
`
'headers' => [
                    "Content-Type"=>"application/xml"
                ]
`
增加上去即可，但pay的配置文件的key，经测试，无法使用v3的key，实际使用v2key才可验证成功返回：

`
<xml>\n
  <return_code><![CDATA[SUCCESS]]></return_code>\n
  <return_msg><![CDATA[ok]]></return_msg>\n
  <sandbox_signkey><![CDATA[752599788582106c9422b789e7eca154]]></sandbox_signkey>\n
</xml>

`

麻烦看到后修改下

**Comment by yansongda** [comment]
确定要加这个么？v2 版本很久没更新过了，应该是稳定的

实际测试过么？

**Comment by sinceyy** [comment]
系呀，测试是ok的

**Comment by sinceyy** [comment]
看你官方文档v2版本拉下来是用的v2哦

**Comment by yansongda** [comment]
> 看你官方文档v2版本拉下来是用的v2哦

Pay 的 v2 版本，用的本来就是 微信v2 的 api

如果有条件，升级到 v3 吧
