### ISSUE TITLE
查询订单接口文档有误,且查询参数未重写appid

### ISSUE THREAD

**Issue by sinceyy** [yansongda/pay#569]
## 包版本号
v2

## 问题描述
查询文档有误，跟踪代码实际发现内部代码“src/Gateways/Wechat.php”文件中，find方法的第二个参数是需要传参的，

1.默认使用pay::wechat($config)->find(); 查询，实例化时进入 “src/Gateways/Wechat.php”文件的 “__construct”方法
 此时如我要查询miniapp即小程序订单时，按配置文件中配置的是miniapp_id参数，但此方法中默认读取的“app_id”即app的配置，如下代码

`
$this->payload = [
            'appid' => $config->get('app_id', ''),
            'mch_id' => $config->get('mch_id', ''),
            'nonce_str' => Str::random(),
            'notify_url' => $config->get('notify_url', ''),
            'sign' => '',
            'trade_type' => '',
            'spbill_create_ip' => Request::createFromGlobals()->getClientIp(),
        ];
`

待上面初始化过后，此时appid为空，因我只使用了miniapp进行下单所以配置文件中仅有miniapp_id

继续运行代码最终提示 “ERROR_GATEWAY: Get Wechat API Error:AppID不存在，请检查后再试[398]”，即问题出在我要获取miniapp的订单时，文档书写的是 pay::wechat($config)->find($order); 但实际调用查找代码是由如下代码查询并重写appid

`
$this->payload = Support::filterPayload($this->payload, $config['order']);
`
但这里的$config['order'] 仅仅是订单号的字符串而已，则无法在 “filterPayload”方法中获取type值并根据type获取实际的appid
`
$type = self::getTypeName($params['type'] ?? ''); //这里无type字段，因这里的type是需包含在传入的order中
`

查找如下代码：
$config = call_user_func([new $gateway(), 'find'], $order);

//修改为这行
$config = call_user_func([new $gateway(), 'find'], ['out_trade_no' => $order,'type' => $type]);

//这样Support的filterPayload方法中即可获取到type值，并根据type进行获取对应appid

//备注：`pay::wechat($config)->find($order);`find方法第二个参数必传，否则无法重写并获取到当前appid

## 你的代码
`pay::wechat($config)->find($order);`
//需替换为如下
`pay::wechat($config)->find($order,'我的支付类型（wap,miniapp,mp）等');`
## 报错详情
提示错误：
ERROR_GATEWAY: Get Wechat API Error:AppID不存在，请检查后再试[398]

实际打印传入的$this->payload参数值为：

`
array(5) {
  ["appid"]=>
  string(0) ""
  ["mch_id"]=>
  string(10) "156301xxxx"
  ["nonce_str"]=>
  string(16) "ACdCh8Ay7xxxxxxx"
  ["sign"]=>
  string(32) "4EE651xx5A674Exxxxxxxx95829"
  ["out_trade_no"]=>
  string(14) "20220218141254"
}
`

## sdk 日志
无

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by Rogueingh** [comment]
此fix不严谨。

src/Gateways/Wechat.php中的find方法，注释中第一个参数$order是支持数组类型的，文档中的示例也是数组类型。若实际传参为数组，例如 Pay::wechat($conf)->find(["out_trade_no" => "123456"])，则 
$config = call_user_func([new $gateway(), 'find'], ['out_trade_no' => $order, 'type' => $type]); 
这行代码会构成如下嵌套的参数"out_trade_no" => [  "out_trade_no" => "123456" ]，
并进而在toXml方法中引发如下错误
Array to string conversion at ./vendor/yansongda/pay/src/Gateways/Wechat/Support.php:296)

**Comment by yansongda** [comment]
> 此fix不严谨。
> 
> src/Gateways/Wechat.php中的find方法，注释中第一个参数$order是支持数组类型的，文档中的示例也是数组类型。若实际传参为数组，例如 Pay::wechat($conf)->find(["out_trade_no" => "123456"])，则 $config = call_user_func([new $gateway(), 'find'], ['out_trade_no' => $order, 'type' => $type]); 这行代码会构成如下嵌套的参数"out_trade_no" => [ "out_trade_no" => "123456" ]， 并进而在toXml方法中引发如下错误 Array to string conversion at ./vendor/yansongda/pay/src/Gateways/Wechat/Support.php:296)

提个 PR 吧？
