### ISSUE TITLE
微信H5支付成功后如何获取返回的数据？

### ISSUE THREAD

**Issue by yujiak** [yansongda/pay#57]
## 问题描述
使用微信H5支付成功后，在 notify 函数里面写成功后的业务逻辑不起作用，也没报错，感觉就是整个流程没走 notify_url 这一步。设置了 return_url 后到是有返回这里，但看文档里说这个地方仅仅只是做跳转用，请问支付成功后在哪做数据处理呢？

**Comment by yansongda** [comment]
请查看 Apache/nginx 的访问日志确保微信服务器有异步通知数据请求过来。

请告知您使用的包的版本号。

请贴代码。

**Comment by yujiak** [comment]
nginx日志有看到这条：[27/Dec/2017:17:24:35 +0800] "POST /m/wechat_notify HTTP/1.1" 419 1530 "-" "Mozilla/4.0"，用的是2.x版本的。notify里面处理的是写入数据到数据库，写入数据的代码测试是没问题的。

**Comment by yansongda** [comment]
既然您看到了 nginx 日志，那您应该知道问题所在了吧~

HTTP 419

感谢您的支持

**Comment by yujiak** [comment]
用的是您提供的实例代码，支付没问题，就是没搞明白这个 认证超时 问题出在哪

**Comment by yansongda** [comment]
检查下是否用了框架？laravel 框架有验证 csrf。

麻烦请自行检查下吧，整个包没有任何关于认证的代码。看看是否与框架集成的问题。

感谢支持！

**Comment by yujiak** [comment]
好的 谢谢您
