### ISSUE TITLE
充值金额4.1报错，其它金额正常，捕获异常为空

### ISSUE THREAD

**Issue by scpzc** [yansongda/pay#570]
## 包版本号
yansongda/pay": "3.0.27

## 问题描述
{"recharge_money":"4.1","method":"scan"}  充值金额4.1报错，其它金额正常，捕获异常为空

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

![image](https://user-images.githubusercontent.com/22276159/154698370-c8bfdb69-2586-470e-a21a-4b0558ecbe4e.png)

**Comment by yansongda** [comment]
按规范提 issue
