### ISSUE TITLE
该包使用的yansongda/supports包与laravel的全局帮助函数冲突

### ISSUE THREAD

**Issue by javalaw** [yansongda/pay#572]
## 包版本号
v3.0.26

## 问题描述
执行composer install/update/require有概率在`post-autoload-dump: @php artisan package:discover --ansi`阶段错误。粗看代码应该是yansongda/supports包内的全局帮助函数`collect`与laravel的全局帮助函数`collect`冲突。如果作者确认是此问题的话，麻烦看看能不能移除这个依赖或者给这个依赖的帮助函数加上命名空间，或者以其他的方式解决这个问题，感谢。

## 你的代码
无

## 报错详情
PHP Fatal error:  Uncaught Error: Call to undefined method Yansongda\Supports\Collection::mapWithKeys() in /data/wwwroot/xxxxx/releases/7/vendor/laravel/framework/src/Illuminate/Support/Traits/ReflectsClosures.php:49

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
正常不应该：`if (!function_exists('collect'))`

可以把 composer.json 发下

**Comment by javalaw** [comment]
> 



> 正常不应该：`if (!function_exists('collect'))`
> 
> 可以把 composer.json 发下

是有`function_exists`的判断，但是执行composer命令后的`post-autoload-dump: @php artisan package:discover --ansi`的相关逻辑里面，调用`collect`函数似乎是优先走了Yansongda/Supports包里面的方法。

**Comment by yansongda** [comment]
使用了这么久，一直没出现过你这个问题

**Comment by zishang520** [comment]
+1，pls

**Comment by yansongda** [comment]
composer update 即可

**Comment by gfwfail** [comment]
composer update了，仍然遇到了这个问题

**Comment by yansongda** [comment]
升级到 Pay 的 v3.1 版本吧，其它版本改这个会造成 BC

**Comment by gfwfail** [comment]
所以php7.3不能用laravel-pay了

**Comment by Jackfinal** [comment]
把src/Functions.php 中 use Yansongda\Supports\Collection;改为 use Illuminate\Support\Collection;
