### ISSUE TITLE
refactor: 去掉 phpdi 依赖

### ISSUE THREAD

**Issue by yansongda** [yansongda/pay#573]

**Comment by augushong** [comment]
为什么要去掉这个依赖?
现在需要主动集成这个依赖吗?

**Comment by yansongda** [comment]
方便自己的框架集成，或者使用自己的 container

可参考文档：https://pay.yansongda.cn/docs/v3/quick-start/install.html#%E8%BF%90%E8%A1%8C%E7%8E%AF%E5%A2%83
