### ISSUE TITLE
hyperf2.2框架安装扩展失败

### ISSUE THREAD

**Issue by myttyy** [yansongda/pay#575]
## 包版本号
v1.0.1

## 问题描述
hyperf2.2框架安装扩展失败

## 报错详情
![image](https://user-images.githubusercontent.com/19262805/155123167-def7faa1-a617-4811-b554-dc93a28e4886.png)

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
-W 安装

**Comment by myttyy** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
