### ISSUE TITLE
微信支付始终无法使用

### ISSUE THREAD

**Issue by chen900804** [yansongda/pay#585]
## 包版本号
v3

## 问题描述
Yansongda\Pay\Exception\InvalidResponseException

始终报错。

## 你的代码
     $order = [
            'out_trade_no' => time(),
            'body' => 'subject-测试',
            'total_fee'      => '1',
        ];

        $result = Pay::wechat()->scan($order);

## sdk 日志
[2022-03-08 01:28:53] local.ERROR:  {"exception":"[object] (Yansongda\\Pay\\Exception\\InvalidResponseException(code: 5003):  at /www/wwwroot/zvn.cc/laravel/vendor/yansongda/pay/src/Functions.php:204)
[stacktrace]
#0 /www/wwwroot/zvn.cc/laravel/vendor/yansongda/pay/src/Plugin/Wechat/LaunchPlugin.php(32): verify_wechat_sign()
#1 /www/wwwroot/zvn.cc/laravel/vendor/yansongda/supports/src/Pipeline.php(126): Yansongda\\Pay\\Plugin\\Wechat\\LaunchPlugin->assembly()
#2 /www/wwwroot/zvn.cc/laravel/vendor/yansongda/pay/src/Plugin/Wechat/SignPlugin.php(49): Yansongda\\Supports\\Pipeline->Yansongda\\Supports\\{closure}()
#3 /www/wwwroot/zvn.cc/laravel/vendor/yansongda/supports/src/Pipeline.php(126): Yansongda\\Pay\\Plugin\\Wechat\\SignPlugin->assembly()
#4 /www/wwwroot/zvn.cc/laravel/vendor/yansongda/pay/src/Plugin/Wechat/GeneralPlugin.php(30): Yansongda\\Supports\\Pipeline->Yansongda\\Supports\\{closure}()
#5 /www/wwwroot/zvn.cc/laravel/vendor/yansongda/supports/src/Pipeline.php(126): Yansongda\\Pay\\Plugin\\Wechat\\GeneralPlugin->assembly()
#6 /www/wwwroot/zvn.cc/laravel/vendor/yansongda/pay/src/Plugin/Wechat/PreparePlugin.php(23): Yansongda\\Supports\\Pipeline->Yansongda\\Supports\\{closure}()
#7 /www/wwwroot/zvn.cc/laravel/vendor/yansongda/supports/src/Pipeline.php(126): Yansongda\\Pay\\Plugin\\Wechat\\PreparePlugin->assembly()
#8 /www/wwwroot/zvn.cc/laravel/vendor/yansongda/supports/src/Pipeline.php(84): Yansongda\\Supports\\Pipeline->Yansongda\\Supports\\{closure}()
#9 /www/wwwroot/zvn.cc/laravel/vendor/yansongda/pay/src/Provider/AbstractProvider.php(70): Yansongda\\Supports\\Pipeline->then()
#10 /www/wwwroot/zvn.cc/laravel/vendor/yansongda/pay/src/Provider/AbstractProvider.php(44): Yansongda\\Pay\\Provider\\AbstractProvider->pay()
#11 /www/wwwroot/zvn.cc/laravel/vendor/yansongda/pay/src/Provider/Wechat.php(54): Yansongda\\Pay\\Provider\\AbstractProvider->call()
#12 /www/wwwroot/zvn.cc/laravel/app/Http/Controllers/Home/User/PayController.php(95): Yansongda\\Pay\\Provider\\Wechat->__call()
#13 /www/wwwroot/zvn.cc/laravel/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Home\\User\\PayController->ewm()
#14 /www/wwwroot/zvn.cc/laravel/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#15 /www/wwwroot/zvn.cc/laravel/vendor/laravel/framework/src/Illuminate/Routing/Route.php(261): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#16 /www/wwwroot/zvn.cc/laravel/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\\Routing\\Route->runController()
#17 /www/wwwroot/zvn.cc/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\\Routing\\Route->run()
#18 /www/wwwroot/zvn.cc/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#19 /www/wwwroot/zvn.cc/laravel/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /www/wwwroot/zvn.cc/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#21 /www/wwwroot/zvn.cc/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /www/wwwroot/zvn.cc/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#23 /www/wwwroot/zvn.cc/laravel/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /www/wwwroot/zvn.cc/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#25 /www/wwwroot/zvn.cc/laravel/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /www/wwwroot/zvn.cc/laravel/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#27 /www/wwwroot/zvn.cc/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#28 /www/wwwroot/zvn.cc/laravel/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /www/wwwroot/zvn.cc/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#30 /www/wwwroot/zvn.cc/laravel/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /www/wwwroot/zvn.cc/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#32 /www/wwwroot/zvn.cc/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /www/wwwroot/zvn.cc/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(727): Illuminate\\Pipeline\\Pipeline->then()
#34 /www/wwwroot/zvn.cc/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(702): Illuminate\\Routing\\Router->runRouteWithinStack()
#35 /www/wwwroot/zvn.cc/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(666): Illuminate\\Routing\\Router->runRoute()
#36 /www/wwwroot/zvn.cc/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(655): Illuminate\\Routing\\Router->dispatchToRoute()
#37 /www/wwwroot/zvn.cc/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#38 /www/wwwroot/zvn.cc/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#39 /www/wwwroot/zvn.cc/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /www/wwwroot/zvn.cc/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#41 /www/wwwroot/zvn.cc/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#42 /www/wwwroot/zvn.cc/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /www/wwwroot/zvn.cc/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#44 /www/wwwroot/zvn.cc/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#45 /www/wwwroot/zvn.cc/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /www/wwwroot/zvn.cc/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#47 /www/wwwroot/zvn.cc/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /www/wwwroot/zvn.cc/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#49 /www/wwwroot/zvn.cc/laravel/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /www/wwwroot/zvn.cc/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle()
#51 /www/wwwroot/zvn.cc/laravel/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /www/wwwroot/zvn.cc/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#53 /www/wwwroot/zvn.cc/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /www/wwwroot/zvn.cc/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#55 /www/wwwroot/zvn.cc/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#56 /www/wwwroot/zvn.cc/laravel/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#57 {main}
"} 

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
绝大部分是你配置问题，检查你的配置吧。

可以自己捕获异常，把异常 debug 出来，看具体错误信息

**Comment by whs891015** [comment]
兄弟解决了没有
