### ISSUE TITLE
希望在文档中从V2过渡到V3更新每个初始化参数的用法

### ISSUE THREAD

**Issue by Yuii-guoguo** [yansongda/pay#587]
因为在V2版本不需要很多参数就能调起支付，到V3后发现多了一些参数不知道如何填写.

**Comment by yansongda** [comment]
注释不都很清楚了么

**Comment by Yuii-guoguo** [comment]
比如在V2版本里面初始化参数仅需appid、商户id、商户公钥、商户秘钥即可，过渡到V3后发现缺了个wechat_public_cert_path,这个明明是选填参数但实际是必填的。

**Comment by yansongda** [comment]
确实是选填，文档里也说清楚了吧

**Comment by Yuii-guoguo** [comment]
我现在迷惑wechat_public_cert_path该怎么填，因为一直报Get Wechat Public Cert Error

**Comment by yansongda** [comment]
FAQ

**Comment by Yuii-guoguo** [comment]
谢谢，已经解决，V3版不能使用微信V2的秘钥了，但建议当行注释里写上。
