### ISSUE TITLE
vendor\guzzlehttp\guzzle\src\Handler\CurlFactory 这个class,因为我们是php7.4版本，但是这个类中有一些写法是php8.0才支持的，请问如何调整或者您有没有php7.4版本的v3的代码仓库

### ISSUE THREAD

**Issue by asshead493** [yansongda/pay#590]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yansongda** [comment]
？？

哪些写法是 8.0 才支持的？

我感觉是你环境问题，不是 guzzle 的问题
