### ISSUE TITLE
微信服务商模式V2版本支持么

### ISSUE THREAD

**Issue by CoderSwitch** [yansongda/pay#592]
一直在使用这个轮子，很好用，现在有更改使用微信服务商模式，我查看了详细文档https://pay.yansongda.cn/，没有找到关于服务商的相关配置，所以想请问下V2版本是否支持服务商模式，支持的话有没有相关的代码实例或者文档注解，再次感谢作者！！

**Comment by yansongda** [comment]
支持： https://pay.yansongda.cn/docs/v2/alipay/

但建议切换到 v3

**Comment by CoderSwitch** [comment]
好的，感谢回复
