### ISSUE TITLE
php-di  psr/container 版本冲突

### ISSUE THREAD

**Issue by pgfeng** [yansongda/pay#593]
## 包版本号
V3.1.1 || master

## 问题描述及建议
php-di/php-di 依赖psr/container ^1.0 然而目前大多数框架都会依赖psr/container，如果版本冲突会导致无法安装，不建议依赖一个这么底层的包。

## 报错详情
php-di/php-di[6.3.0, ..., 6.3.5] require psr/container ^1.0 -> found psr/container[1.0.0, 1.1.0, 1.1.1, 1.1.2] but the package is fixed to 2.0.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

**Comment by yansongda** [comment]
如果是 laravel / hyperf 框架，无需安装

如果非上述框架，且想使用 php-di ，安装时 `composer require php-di/php-di -W` 安装

如果不想使用 php-di，可以参考 https://pay.yansongda.cn/docs/v3/quick-start/install.html 自行处理 container 部分
