### ISSUE TITLE
道理我不懂 为啥 src/Provider/Alipay.php 这文件中的 dispatch 都是 wechat

### ISSUE THREAD

**Issue by puzzle9** [yansongda/pay#594]
https://github.com/yansongda/pay/blob/master/src/Provider/Alipay.php#L67

**Comment by yansongda** [comment]
很显然，复制的时候忘了改过来了😓

**Comment by puzzle9** [comment]
哦 天哪
我想尝试加入银联支付的时候 曾经怀疑过自己

**Comment by yansongda** [comment]
> 哦 天哪 我想尝试加入银联支付的时候 曾经怀疑过自己

考虑提个 PR 把银联集成来么？

一直想接入下银联

**Comment by puzzle9** [comment]
> > 哦 天哪 我想尝试加入银联支付的时候 曾经怀疑过自己
> 
> 考虑提个 PR 把银联集成来么？
> 
> 一直想接入下银联

我想 我会的

**Comment by yansongda** [comment]
期待ing...

**Comment by puzzle9** [comment]
> 期待ing...

天哪 
我又发现一个问题 我对接的是 https://up.95516.com/open/openapi?code=unionpay  银联综合前置平台 
而不是我们熟知的银联 https://open.unionpay.com/tjweb/doc/index
所以 可能帮不到了

**Comment by yansongda** [comment]
没事，可以都接进来

不过，这两个有啥不同？

**Comment by puzzle9** [comment]
这两个按我目前理解 
一个是个体工商户或者小微商户用的
另一个给企业用的 需要付费接入 大多用的都是企业这个
