### ISSUE TITLE
插件的使用

### ISSUE THREAD

**Issue by juvenrui** [yansongda/pay#598]
你好：

        试了多次，一直不太明白插件的使用。比如微信的“发起批量转账” \Yansongda\Pay\Plugin\Wechat\Fund\Transfer\CreatePlugin ，如何正常的使用？有示例吗？

        另外，请教下v3Api如何调用生成签名的方法？

**Comment by yansongda** [comment]
https://pay.yansongda.cn/docs/v3/kernel/plugin.html#%E5%AE%9A%E4%B9%89
