### ISSUE TITLE
请教各位达佬，手机网站支付唤起支付宝一直系统繁忙

### ISSUE THREAD

**Issue by LeeBabaTest** [yansongda/pay#606]
## 包版本号

^3.0
## 问题描述
用的3.0以上版本，接入支付宝手机网站支付时，手机浏览器打开后唤起支付宝时候一直报错“系统繁忙，请稍后再试”，
望大佬们不吝赐教

## 你的代码
    public function getCrt(Request $request)
    {
        Pay::config(config('pay'));
        return  Pay::alipay()->wap([
           'out_trade_no' =>'asdadasdasadadas',
            'total_amount' => 2.02,
            'subject' => 'ssss',
            'quit_url' => 'www.3w4ee.com',
            'product_code' => 'QUICK_WAP_WAY' 
        ]);
    }

## 报错详情
手机浏览器里点击打开支付宝APP付款，报错“系统繁忙，请稍后再试”

## sdk 日志
无

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
正式环境试试吧，还有 total_amount 不应该是 string 类型的么？

**Comment by LeeBabaTest** [comment]
total_amount&nbsp; string类型也试了,也是唤起支付宝APP时候系统繁忙,现在的参数和配置都是用的正式环境的支付宝应用



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月20日(星期三) 上午10:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yansongda/pay] 请教各位达佬，手机网站支付唤起支付宝一直系统繁忙 (Issue #606)





 
正式环境试试吧，还有 total_amount 不应该是 string 类型的么？
