### ISSUE TITLE
Parse error: syntax error, unexpected ')' src/Functions.php on line 150

### ISSUE THREAD

**Issue by phalapi** [yansongda/pay#610]
## 问题描述
Parse error: syntax error, unexpected ')' in vendor/yansongda/pay/src/Functions.php on line 150

## 报错详情
```        $auth = sprintf(
            'mchid="%s",nonce_str="%s",timestamp="%d",serial_no="%s",signature="%s"',
            $config->get('mch_id', ''),
            $random,
            $timestamp,
            $ssl['serialNumberHex'],
            get_wechat_sign($params, $contents), // 这里多了一个逗号，去掉后正常
        );
```

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
php 版本多少？通过什么安装的？

**Comment by phalapi** [comment]
> php 版本多少？通过什么安装的？

$ php -v
PHP 7.1.27 (cli) (built: Mar 21 2019 12:06:37) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies

之前已安装，忽略PHP版本进行update。
composer update --ignore-platform-reqs  

建议可以兼容一下。
