### ISSUE TITLE
微信支付关闭订单异常

### ISSUE THREAD

**Issue by HaoNanDreams** [yansongda/pay#611]
## 包版本号
v2.7.8

## 问题描述
微信支付（web) 关闭订单 异常

## 你的代码
`return app('wechat_pay')->close(['out_trade_no' => $this->trade_no]);`

## 报错详情
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/44458806/168529176-25a466f5-580a-4ac7-8ec2-3d795a079c80.png">

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by HaoNanDreams** [comment]
<img width="739" alt="image" src="https://user-images.githubusercontent.com/44458806/168530715-a69724de-53db-448e-800b-6610914f176a.png">

当前位置第三个参数是否传递true可以解决问题

**Comment by yansongda** [comment]
有条件的话，升级到 v3 吧
