### ISSUE TITLE
是否可以支持微信发票相关

### ISSUE THREAD

**Issue by wilbur-yu** [yansongda/pay#613]
个人感觉, 发票也是支付中一个部分. 所以做为支付工具类库, 是否考虑接入发票服务.

**Comment by Memory-9527** [comment]
> api 发一下看看

https://pay.weixin.qq.com/wiki/doc/apiv3/Offline/open/chapter4_8_1.shtml

**Comment by wilbur-yu** [comment]
不好意思, 忽略了自己提交的issues, 实在对不起.

> > api 发一下看看
> 
> [pay.weixin.qq.com/wiki/doc/apiv3/Offline/open/chapter4_8_1.shtml](https://pay.weixin.qq.com/wiki/doc/apiv3/Offline/open/chapter4_8_1.shtml)
