### ISSUE TITLE
支付宝支持配置接口内容加密方式

### ISSUE THREAD

**Issue by freadman** [yansongda/pay#616]
支付宝的网站支付中有个接口内容加密方式，而且一旦配置无法取消，但是这个包没有这个配置（或者我不知道怎么配置），建议增加。
关于支付宝AES加密说明文档：https://opendocs.alipay.com/common/02mse3

**Comment by yansongda** [comment]
暂不支持

**Comment by freadman** [comment]
> 暂不支持

希望能够支持，支付宝现在要异步通知必要要这个加密

**Comment by RayFongChan** [comment]
请问一下,你是怎么解决的呢,我也遇到这个问题了,设置了接口内容加密

**Comment by yansongda** [comment]
我看过支付宝的文档，就算设置加密了，实际传参的时候可以按非加密传参吧

![截屏2022-10-24 15 07 03](https://user-images.githubusercontent.com/11869114/197467428-a204aadb-dba0-4c14-b224-6eb91d09a516.png)

**Comment by RayFongChan** [comment]
> 我看过支付宝的文档，就算设置加密了，实际传参的时候可以按非加密传参吧
> 
> ![截屏2022-10-24 15 07 03](https://user-images.githubusercontent.com/11869114/197467428-a204aadb-dba0-4c14-b224-6eb91d09a516.png)

感谢
