### ISSUE TITLE
refund 方法退费的时候出错

### ISSUE THREAD

**Issue by mrliu1021** [yansongda/pay#618]
## 包版本号
v2.3

## 问题描述

退费的时候
 //订单数据
        $order_data = [
            'out_trade_no' => request('out_trade_no'),
            'refund_amount' => number_format(request('refund_amount'),2,".","")
//                number_format(request('refund_amount'),2,".","")
        ];

        $alipay = Pay::alipay($this->config);
        return $alipay->refund($order_data);

## 报错详情
    
\vendor\yansongda\pay\src\Gateways\Alipay\Support.php  第417行   Alipay Sign Verify FAILED  这个错误激发了

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
升级到 v2 最新版本吧。v2 很久没更新过了，很稳定，一般不会有问题，可以检查下自己的配置

如果有条件，可以升级到 v3

**Comment by mrliu1021** [comment]
发错地方了是这个 https://github.com/yansongda/laravel-pay/issues/86    laravel的版本v2最新的就更新到v2.3了
