### ISSUE TITLE
微信支付沙箱模式问题

### ISSUE THREAD

**Issue by anyforever** [yansongda/pay#62]
## 包版本号
2.0.6

## 问题描述
微信沙箱模式接口调用失败

## 代码
涉及到 异步通知、同步通知 的问题，请将 nginx/Apache 的相关日志贴出来

## 报错详情
Yansongda\Pay\Exceptions\GatewayException: Get Wechat API Error:验证签名失败, 请调用getsignkey生成沙箱密钥 in file E:\Server\www\project\vendor\yansongda\pay\src\Gateways\Wechat\Support.php on line 72
Stack trace:

**Comment by yansongda** [comment]
微信沙箱模式不像支付宝沙箱模式使用那样简单。

微信沙箱模式对于测试用例有严格要求。详情请查看微信支付官方文档。

谢谢

**Comment by anyforever** [comment]
@yansongda 嗯。好的。谢谢。我去详细查一下。

**Comment by anyforever** [comment]
@yansongda 
验签秘钥API说明：
▽ 接口地址：
https://api.mch.weixin.qq.com/sandboxnew/pay/getsignkey
这个接口返回沙箱密钥，pay包里没有方法能调出这个吧？没找到。
是需要自己从这里取出密钥，替换到config里的key上么？谢谢

**Comment by yansongda** [comment]
是的，需要自己设置 key

**Comment by anyforever** [comment]
@yansongda 好的。不过觉得这个还是可以集成一下相关调用方法，或者配置里设置了'mode' => 'dev' 自动能完成这个过程比较完美。
能顺便问下这个沙箱给的key是获取一次不会变那种，还是需要间隔一段时间就重新获取新的？

**Comment by yansongda** [comment]
当时看了微信官方文档，沙箱较坑，又太复杂，人懒了，就没做了。。。

沙箱 key 具体信息还要麻烦看官方文档。

感谢支持

**Comment by hebiao6446** [comment]
微信的文档太坑爹了  。简直日了狗   ，还有就是建议  return Pay::wechat($this->config)->app($order)->send();  建议以字符串的形式返回 ，这种返回无法封装 ， 谢谢你的成果 。

**Comment by yansongda** [comment]
@hebiao6446 凡是说「这种返回无法封装」的只能说没自己看文档！

**Comment by hebiao6446** [comment]
@yansongda   大神，我错了 。。。      微信文档那个鸟样，比你写的差几个数量级 哈哈 。。。  谢谢大神

**Comment by qiuquanwu** [comment]
怎么直接使用正式环境，我的一直是沙箱环境，是在哪里配置吗

**Comment by shorlyn** [comment]
微信扫码支付沙箱报“沙箱验证签名失败，请确认沙箱签名key是否正确（通过getsignkey调用生成）”，不用沙箱即正常。

**Comment by yansongda** [comment]
沙箱模式在 v2.7.0 及以后版本已完全支持

感谢大家支持
