### ISSUE TITLE
记录一个小问题

### ISSUE THREAD

**Issue by giftpapa** [yansongda/pay#621]
## 包版本号
3.0

## 问题描述
支付宝同步回调，之前因为业务问题，直接在代码里echo Pay::alipay()->success();一直是正常的，今天突然报错了，改成了Pay::alipay()->success()->getBody()才可以使用

## 你的代码
echo Pay::alipay()->success();
===》
Pay::alipay()->success()->getBody();

## 报错详情
Symfony\Component\Debug\Exception\FatalThrowableError
Object of class GuzzleHttp\Psr7\Response could not be converted to string

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
看你自己是否升级过什么东西，然后框架是否修改过

**Comment by giftpapa** [comment]
> 看你自己是否升级过什么东西，然后框架是否修改过

没有动过，就是突然这样了，我后续再找找原因
