### ISSUE TITLE
v3版的支付宝app支付返回空看代码直接走的  return $rocket->getDestination();

### ISSUE THREAD

**Issue by wksnow** [yansongda/pay#622]
<img width="377" alt="image" src="https://user-images.githubusercontent.com/49552045/174473579-e7840460-68b7-4435-8ca3-e38c0a0541b4.png">
<img width="550" alt="image" src="https://user-images.githubusercontent.com/49552045/174473600-7b5f1608-efc8-4006-8a7f-90d73de40766.png">
<img width="834" alt="image" src="https://user-images.githubusercontent.com/49552045/174473726-0eae3002-139a-465b-9b68-19e181030d16.png">
用的是 "yansongda/pay": "~3.0.0"，

**Comment by yansongda** [comment]
按格式提 issue

**Comment by wksnow** [comment]
@yansongda 大佬救命~

**Comment by yansongda** [comment]
看文档， `app()` 返回类型

**Comment by wksnow** [comment]
直接从圈的这个地方返回了,打印的内容就是这样的,证书什么的配置错了会出现这个问题嘛。大佬~
<img width="811" alt="image" src="https://user-images.githubusercontent.com/49552045/174473965-c3d04f15-edc8-49d2-b016-1f66d26e5b9d.png">
![image](https://user-images.githubusercontent.com/49552045/174474030-3d7f3d63-5411-4ff5-a4af-35efcf1850b5.png)
