### ISSUE TITLE
V3版本支付宝支付返回为空

### ISSUE THREAD

**Issue by yangjie1998** [yansongda/pay#623]
![image](https://user-images.githubusercontent.com/50521274/176348193-7d1cda26-f524-4886-9b32-8f57691120b9.png)
![image](https://user-images.githubusercontent.com/50521274/176348256-8076c572-bcd1-4b5a-8653-eba3a2e50d20.png)

**Comment by yansongda** [comment]
仔细看文档， `app()` 方法的返回值
