### ISSUE TITLE
微信和支付宝周期扣款签约接口支持

### ISSUE THREAD

**Issue by sololibra** [yansongda/pay#624]
微信和支付宝周期扣款签约服务 可以支持吗?
![image](https://user-images.githubusercontent.com/25891207/176814559-a9c321d0-deb0-4c28-a813-7d2789b10fee.png)

**Comment by yansongda** [comment]
url 地址麻烦发下

**Comment by sololibra** [comment]
微信 https://pay.weixin.qq.com/wiki/doc/api/wxpay_v2/papay/chapter3_5.shtml
支付宝 https://opendocs.alipay.com/open/02fkan?ref=api&scene=35

**Comment by yansongda** [comment]
微信的没有 v3 的 API 支持么？

**Comment by sololibra** [comment]
目前没有

> 微信的没有 v3 的 API 支持么？

**Comment by yansongda** [comment]
closed by #644
