### ISSUE TITLE
怎么不支持php8.0版本呀，安装都无法安装呢

### ISSUE THREAD

**Issue by yeshili** [yansongda/pay#626]
麻烦什么时候升级了可以是否支持php8.0版本！！

**Comment by yansongda** [comment]
支持 >=7.4 版本，包括 8.0   8.1

可以检查下你自己的环境

**Comment by yeshili** [comment]
检查了，还是不行，我直接composer require yansongda/pay这样子安装就成功了，就自动是这个版本 "yansongda/pay": "^3.0"，没有默认最新版本！

**Comment by yansongda** [comment]
`php -v` 检查环境看版本多少
