### ISSUE TITLE
如何关闭多租户模式

### ISSUE THREAD

**Issue by wwwylo** [yansongda/pay#632]

**Comment by yansongda** [comment]
？？原因是啥？

**Comment by wwwylo** [comment]
我们现在的支付配置都是从数据库读取的，增删改会比较频繁，每次取支付配置的时候都是根据一系列规则来最终确定使用哪个支付配置，目前我所用的是每次发起支付或者回调的时候都使用_force和_config，但由于支付配置是常驻内存的缘故，又担心在极端并发情况下造成数据混乱，发起支付或者支付回调验证的时候使用了错误的商户

**Comment by yansongda** [comment]
程序启动时，把所有配置从数据库拿出来，config() 一下

后面用的时候，直接 _config 不就行了？

**Comment by wwwylo** [comment]
【表结构】
`
CREATE TABLE `setting_pay_v3` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `flag` varchar(30) COLLATE utf8_bin DEFAULT NULL COMMENT '唯一标识',
  `gateway` varchar(20) COLLATE utf8_bin DEFAULT NULL COMMENT '支付网关',
  `scenes` varchar(20) COLLATE utf8_bin DEFAULT NULL COMMENT '支付渠道 app,h5...',
  `package_name` varchar(50) COLLATE utf8_bin DEFAULT NULL COMMENT '包名',
  `api_configure` json DEFAULT NULL COMMENT '支付api配置',
  `rule` json DEFAULT NULL COMMENT '其他规则',
  `status` enum('Y','N') COLLATE utf8_bin DEFAULT 'Y' COMMENT 'Y启用，N禁用',
  `desc` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '描述',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_flag` (`flag`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
`
【Model】
`
<?php

declare (strict_types=1);

namespace App\Libs\Pay\Model;

use App\Model\Model;
use Hyperf\Database\Model\Builder;

/**
 * @property int $id
 * @property string $flag
 * @property string $gateway
 * @property string $scenes
 * @property string $package_name
 * @property array $api_configure
 * @property array $rule
 * @property string $status
 * @property string $desc
 */
class SettingPay extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'setting_pay_v3';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [];
    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'id'            => 'integer',
        'api_configure' => 'array',
        'rule'          => 'array',
    ];

    /**
     * booted event.
     * @return void
     */
    public function booted(): void
    {
        static::addGlobalScope(function (Builder $query) {
            return $query->where('status', 'Y');
        });
    }
}
`
【重载配置代码】
`
    public function reload(bool $force = false): void
    {
        $collection = SettingPay::get();
        $config     = [
            'http'   => [
                'timeout'         => 5.0,
                'connect_timeout' => 5.0,
            ],
            'logger' => [
                'enable' => true,
                'config' => 'default',
            ],
        ];
        if ($force) {
            Arr::set($config, '_force', true);
        }

        foreach ($collection as $item) {
            $config[$item->gateway][$item->flag] = $item->api_configure;
        }
        Pay::config($config);
    }
`

【实际调用代码】
将数据库数据库中的flag作为alipay、wechat的商户标识
`
    public function index(\Yansongda\HyperfPay\Pay $pay)
    {


        $default = [
            'time_expire'         => date('Y-m-d H:i:s', time() + 60),
            'enable_pay_channels' => 'balance,moneyFund,bankPay,debitCardExpress',
            'out_trade_no'        => (string)time(),
            'total_amount'        => 1,
            'subject'             => 'test',
            '_config'             => 'alipay-app',
        ];

        try {
            $response = (string)$pay->alipay()->app($default)->getBody();
        } catch (Throwable $throwable) {
            $response = 'error';
        }

        return [
            'body' => $response,
        ];
    }
`
【复现步骤】
1：执行发起支付的代码租户标识为alipay-app
2：删除数据库中的flag为alipay-app的数据
3：执行重载配置方法
4：回去重新执行发起支付代码，这是会发现可以成功发起支付，但是在多刷新几下之后就异常了报找不到证书的错误
5：重新将数据库中的flag为alipay-app的数据加回去
6：执行重载配置的方法
7：回去重新执行发起支付代码，前几次会报证书找不到的错误，但是在多刷新几次就会恢复正常，继续刷的话偶尔也会报找不到证书的错误

**Comment by wwwylo** [comment]
- 表结构

```
CREATE TABLE `setting_pay_v3` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `flag` varchar(30) COLLATE utf8_bin DEFAULT NULL COMMENT '唯一标识',
  `gateway` varchar(20) COLLATE utf8_bin DEFAULT NULL COMMENT '支付网关',
  `scenes` varchar(20) COLLATE utf8_bin DEFAULT NULL COMMENT '支付渠道 app,h5...',
  `package_name` varchar(50) COLLATE utf8_bin DEFAULT NULL COMMENT '包名',
  `api_configure` json DEFAULT NULL COMMENT '支付api配置',
  `rule` json DEFAULT NULL COMMENT '其他规则',
  `status` enum('Y','N') COLLATE utf8_bin DEFAULT 'Y' COMMENT 'Y启用，N禁用',
  `desc` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '描述',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_flag` (`flag`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
```

- Model
``` 
<?php

declare (strict_types=1);

namespace App\Libs\Pay\Model;

use App\Model\Model;
use Hyperf\Database\Model\Builder;

/**
 * @property int $id
 * @property string $flag
 * @property string $gateway
 * @property string $scenes
 * @property string $package_name
 * @property array $api_configure
 * @property array $rule
 * @property string $status
 * @property string $desc
 */
class SettingPay extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'setting_pay_v3';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [];
    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'id'            => 'integer',
        'api_configure' => 'array',
        'rule'          => 'array',
    ];

    /**
     * booted event.
     * @return void
     */
    public function booted(): void
    {
        static::addGlobalScope(function (Builder $query) {
            return $query->where('status', 'Y');
        });
    }
}
```


- 重载配置代码
``` 
public function reload(bool $force = false): void
{
    $collection = SettingPay::get();
    $config     = [
        'http'   => [
            'timeout'         => 5.0,
            'connect_timeout' => 5.0,
        ],
        'logger' => [
            'enable' => true,
            'config' => 'default',
        ],
    ];
    if ($force) {
        Arr::set($config, '_force', true);
    }

    foreach ($collection as $item) {
        $config[$item->gateway][$item->flag] = $item->api_configure;
    }
    try {
        Pay::config($config);
    } catch (ContainerException $e) {
        LoggerUtils::throwable($e);
    }


}
```

- 实际调用代码
``` 
public function index(\Yansongda\HyperfPay\Pay $pay)
{


    $default = [
        'time_expire'         => date('Y-m-d H:i:s', time() + 60),
        'enable_pay_channels' => 'balance,moneyFund,bankPay,debitCardExpress',
        'out_trade_no'        => (string)time(),
        'total_amount'        => 1,
        'subject'             => 'test',
        '_config'             => 'alipay-app',
    ];

    try {
        $response = (string)$pay->alipay()->app($default)->getBody();
    } catch (Throwable $throwable) {
        $response = 'error';
    }

    return [
        'body' => $response,
    ];
}
 ```

- 复现步骤
- 1：执行发起支付的代码租户标识为alipay-app 
- 2：删除数据库中的flag为alipay-app的数据 
- 3：执行重载配置方法 
- 4：回去重新执行发起支付代码，这是会发现可以成功发起支付，但是在多刷新几下之后就异常了报找不到证书的错误
- 5：重新将数据库中的flag为alipay-app的数据加回去 
- 6：执行重载配置的方法 
- 7：回去重新执行发起支付代码，前几次会报证书找不到的错误，但是在多刷新几次就会恢复正常，继续刷的话偶尔也会报找不到证书的错误

**Comment by yansongda** [comment]
swoole 是多进程的模型

这个配置，正常情况下，不会天天修改吧

**Comment by wwwylo** [comment]
我们这个情况比较特殊，修改配置会比较频繁，所以想问一下怎么能把多租户功能关闭

**Comment by yansongda** [comment]
你们具体产品我不懂啊。

但是我感觉是不是得考虑下产品或者技术实现方案了，理论上来说，配置信息都是固定的

**Comment by wwwylo** [comment]
找到个解决办法，将swoole的运行模式修改为SWOOLE_BASE，希望后续能出个可以自定义读取配置的接口

**Comment by Akuns** [comment]
我也遇到再搞个问题了，达到一定的并发，会导致读取配置混乱的问题。即使开启了强制覆盖！比如A请求过来，正常使用A配置，这个时候B在同一秒请求过来，并发状态下会到时B读取了A的配置导致验签失败！

> 我用的hyperf框架，按照你的方案试了一下，每次修改支付配置的时候从就重新生成一份配置，但是会有读取不到配置的情况，不知道是什么原因

**Comment by yansongda** [comment]
建议调整应用层面的技术方案，常驻进程 + 单例 就是这样，你这用法就不是单例的用法，在并发的情况下，的确可能出现配置被覆盖的情况。

临时方案可以直接在 config 强制覆盖的时候加个锁啥的，然后再 merge 进去

完美方案当然就是将所有配置都在初始化（即调用 config() 方法的时候全部加载）

**Comment by Akuns** [comment]
> 建议调整应用层面的技术方案，常驻进程 + 单例 就是这样，你这用法就不是单例的用法，在并发的情况下，的确可能出现配置被覆盖的情况。
> 
> 临时方案可以直接在 config 强制覆盖的时候加个锁啥的，然后再 merge 进去
> 
> 完美方案当然就是将所有配置都在初始化（即调用 config() 方法的时候全部加载）

每个微信租户我用了单独的配置文件，默认都读取default，不用_config这种方式，临时解决了。
