### ISSUE TITLE
接口加签方式能否支持公钥模式

### ISSUE THREAD

**Issue by zeasly** [yansongda/pay#639]
当前加签方式只支持证书模式.能否支持一下公钥模式.

![image](https://user-images.githubusercontent.com/2832573/180692977-173094a7-4ecf-4ca0-a2b0-ca8773a859ad.png)
同时发请求之前通过应用公钥验证加签能否使用配置, 这样我就只需要配置appid, 应用私钥和支付宝公钥了.
![image](https://user-images.githubusercontent.com/2832573/180693007-8fbb8e53-00b6-4b6d-a389-e32625fdc2c0.png)

**Comment by yansongda** [comment]
不支持，且当前没有计划

升级有困难么？

**Comment by yansongda** [comment]
v2 版支持老的 公钥 模式，如果升级困难，你可以用 v2 版本
