### ISSUE TITLE
Log 类定位错误

### ISSUE THREAD

**Issue by duxphp** [yansongda/pay#64]
## 包版本号
2.X

## 问题描述
Class 'Yansongda\Pay\Gateways\Wechat\Log' not found

## 代码
涉及到 异步通知、同步通知 的问题，请将 nginx/Apache 的相关日志贴出来
src/Gateways/Wechat/AppGateway.php  36line

**Comment by yansongda** [comment]
您好，麻烦请升级到最新版。感谢支持
