### ISSUE TITLE
支付宝订单参数异常，请重新发起支付

### ISSUE THREAD

**Issue by xiaodongy** [yansongda/pay#640]
### 包版本号
v3.1  thinkphp5.1
### 问题描述
发起支付宝APP支付时提示：支付宝订单参数异常，请重新发起支付
### 你的代码
`
        $pay = Pay::alipay()->app([
            'out_trade_no' => time(),
            'total_amount' => '0.01',
            'subject' => 'yansongda 测试 - 01',
        ]);
        return $pay->getBody()->getContents();
`

### 报错详情

以下是decode 之后内容

`app_id=2021003141640118&method=alipay.trade.app.pay&format=JSON&return_url=https://api.youzhiketang.com/notify/alipay&charset=utf-8&sign_type=RSA2&timestamp=2022-07-26+18:57:28&version=1.0&notify_url=https://api.youzhiketang.com/notify/alipay&app_cert_sn=bc57072b6ef91198dfd28d94bcae38d5&alipay_root_cert_sn=687b59193f3f462dd5336e5abf83c5d8_02941eef3187dddf3d3b83462e1dfcf6&biz_content={"product_code":"QUICK_MSECURITY_PAY","out_trade_no":1658833048,"total_amount":"0.01","subject":"yansongda+\u6d4b\u8bd5+-+01"}&sign=SgjCbfMRURuDGFUNxoS785s81GLuUseld5I9QvaBanPr3tg+VLFmccyuULJQIUjrvbXPUyWVUaUWj3/spExuQjGpNC5l6RbtclQVHBzdvbYfvRvm30xjc+0y9H+W93Aov8bfWwDW79RZDmwcq0tfm8WpILs7nJSHp0cXfogYWiAM0kli0v2uI12SVyOOVbxCwz/Cc/vMkINJjAqWNIg5OJJG7GvU4g9kWsibz0rnLE5xtowMWdSEqlPv6np8Y1s0vDfiSAiFk3T5U/0H1nvKkOz4QPxE1rvjEueFnV409HL97JpjE1iJ44re+Xm29iLKuymGfX3Tj6K74uWQ+ul+kw==`

**Comment by yansongda** [comment]
按格式提 issue
