### ISSUE TITLE
laravel中 支付宝发起支付后返回网页源码

### ISSUE THREAD

**Issue by mgx888** [yansongda/pay#641]
laravel中 支付宝发起支付后返回网页源码
$pay = Pay::alipay($this->aliconfig())->app($order);

$pay = response()->json($pay)->setEncodingOptions(JSON_UNESCAPED_UNICODE);
返回$pay如下：

:HTTP/1.0 200 OK
Cache-Control: no-cache, private
Content-Type:  application/json
Date:          Fri, 29 Jul 2022 17:39:54 GMT

{}

**Comment by yansongda** [comment]
？？难道不应该么？

看看文档吧

**Comment by mgx888** [comment]
我也刚刚解决，头晕了，
$pay = $pay->getBody()->getContents();
这样就正常字符串得到了

**Comment by mgx888** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
