### ISSUE TITLE
Parse [mch_public_cert_path] Serial Number Error

### ISSUE THREAD

**Issue by Pray-Ming** [yansongda/pay#642]
## 包版本号
"yansongda/pay": "3.0.*"

## 问题描述
H5支付调起  Parse [mch_public_cert_path] Serial Number Error

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
检查 mch_public_cert_path 配置

**Comment by Pray-Ming** [comment]
> 检查 mch_public_cert_path 配置

mch_public_cert_path是通过微信支付商户平台证书工具生成的cert

**Comment by yansongda** [comment]
反了吧

**Comment by Pray-Ming** [comment]
> 反了吧

确实反了 我错了
