### ISSUE TITLE
支付宝APP支付无任何数据返回

### ISSUE THREAD

**Issue by ziyanwl** [yansongda/pay#651]
## 包版本号

 V3.1.7
## 问题描述

支付宝H5支付 扫码支付 都是正常的 就app支付无任何数据返回

## 你的代码
$order=[
            'out_trade_no' => time().'123123',
            'total_amount' => 10,
            'subject' => 'test'.time().'1221',
        ];
        $data=Pay::alipay()->app($order);

## 报错详情
无任何报错

## sdk 日志

<img width="825" alt="image" src="https://user-images.githubusercontent.com/30615242/185866027-30c6ee69-9ecc-4522-861c-4fd191217adf.png">

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
你的 `$data` 是 null ？

**Comment by ziyanwl** [comment]
> 你的 `$data` 是 null ？

是的  直接返回的就是一个object  {}
我getBody  getHeaders都是空

**Comment by yansongda** [comment]
不清楚，你自己 dump 排查下吧

**Comment by yansongda** [comment]
解决了么？

**Comment by god-ran** [comment]
我也遇到了 
![1661335005546](https://user-images.githubusercontent.com/57313098/186389590-b4cf3cbb-9b20-4016-9f17-e7714216dcd9.jpg)

**Comment by yansongda** [comment]
> 我也遇到了 ![1661335005546](https://user-images.githubusercontent.com/57313098/186389590-b4cf3cbb-9b20-4016-9f17-e7714216dcd9.jpg)

?? 你这不都返回数据了么

**Comment by god-ran** [comment]
这是什么意思呢，app支付就返回这些吗，以下是代码
![1661335547111](https://user-images.githubusercontent.com/57313098/186391552-f91dfc93-011f-4bae-a3da-68c0f02559ca.jpg)

**Comment by god-ran** [comment]
> > 我也遇到了 ![1661335005546](https://user-images.githubusercontent.com/57313098/186389590-b4cf3cbb-9b20-4016-9f17-e7714216dcd9.jpg)
> 
> ?? 你这不都返回数据了么

返回的这些是什么意思呢，app支付就返回这些吗，以下是代码
![1661335547111](https://user-images.githubusercontent.com/57313098/186391808-5d3ca667-5cce-44dd-b5ac-469334f44ae0.jpg)

**Comment by god-ran** [comment]
> 看文档返回 返回值 / FAQ。

好的，谢谢

**Comment by jefferyjob** [comment]
> 看文档返回 返回值 / FAQ。

不行啊，和他们一样，也是 null
