### ISSUE TITLE
Yansongda  \  Pay  \  Exception  \  InvalidParamsException 3.1.0

### ISSUE THREAD

**Issue by wangguangwei406** [yansongda/pay#654]
[\Yansongda\Pay\Plugin\Alipay\Shortcut\VerifyShortcut] is not incompatible

**Comment by wangguangwei406** [comment]
这个问题是什么原因，请问，使用的是沙箱环境

**Comment by wangguangwei406** [comment]
配置如下：
 'alipay' => [
        'default' => [
            'app_id' => env('ALIPAY_APP_ID'),    //你自己的appid
            // 'notify_url' => 'http://localhost/alipay/notify.php',  //服务器回调地址
            'notify_url' => 'http://localhost/payment/alipay/notify',  //服务器回调地址
            // 'return_url' => 'http://localhost/alipay/return.php',  //前端回调地址
            'return_url' => 'http://localhost/payment/alipay/return',  //前端回调地址
            'alipay_public_cert_path' => config_path(env('ALIPAY_PUBLIC_CERT_PATH')),
            'app_public_cert_path' => config_path(env('APP_PUBLIC_CERT_PATH')),  //可能要加上appid
            'alipay_root_cert_path' => config_path(env('ALIPAY_ROOT_CERT_PATH')),
            'app_secret_cert' => env('APP_SECRET_CERT'),  //支付宝开放平台生成的私钥
            'log' => [
            'file' => storage_path('logs/alipay.log'),  //记录日志的目录
            'level' => 'debug',
            'type' => 'single',
            'max_file' => 30,
            ],
            'http' => [
            'timeout' => 5.0,
            'connect_timeout' => 5.0,
            ],
            'mode' => Pay::MODE_SANDBOX,  // optional,设置此参数，将进入沙箱模式
        ]
  ],

**Comment by wangguangwei406** [comment]
AppServiceProvider调用如下：
$this->app->singleton('alipay',function(){
            $config = config('pay');
            // dd(route('payment.alipay.notify'));
            // $config['notify_url'] = route('payment.alipay.notify');
            // $config['return_url'] = route('payment.alipay.return');
            //判断当前项目运行环境是否为线上环境
            if(app()->environment() !== 'production'){
                $config['mode'] = 'dev';
                $config['log']['level'] = Logger::DEBUG;
            }else{
                $config['log']['level'] = Logger::WARNING;
            }
            //调用Yansongda\Pay来创建一个支付宝支付对象
            return Pay::alipay($config);
        });
Controller调用如下
 public function payByAlipay(Order $order, Request $request)
    {
        // 判断订单是否属于当前用户
        $this->authorize('own', $order);
        // 订单已支付或者已关闭
        if ($order->paid_at || $order->closed) {
            throw new InvalidRequestException('订单状态不正确');
        }

        // 调用支付宝的网页支付
        return app('alipay')->web([
            'out_trade_no' => $order->no, // 订单编号，需保证在商户端不重复
            'total_amount' => $order->total_amount, // 订单金额，单位元，支持小数点后两位
            'subject'      => '支付 Laravel Shop 的订单：'.$order->no, // 订单标题
        ]);
    }

    // 前端回调页面
    public function alipayReturn()
    {
        // 校验提交的参数是否合法
        $data = app('alipay')->verify();
        dd($data);
    }

    // 服务器端回调
    public function alipayNotify()
    {
        $data = app('alipay')->verify();
        \Log::debug('Alipay notify', $data->all());
    }

**Comment by yansongda** [comment]
`verify ` -->  `callback`
