### ISSUE TITLE
接口文档很多页面都进不去 

### ISSUE THREAD

**Issue by light-speak** [yansongda/pay#657]
## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
国内的 cdn 挂了，可以用源站  https://pay.yansongda.vercel.app

**Comment by yansongda** [comment]
经过确认，是 vercel 国内又被墙了导致 cdn 回源失败。。。

切换至 netlify，现已恢复
