### ISSUE TITLE
商户转账到零钱

### ISSUE THREAD

**Issue by light-speak** [yansongda/pay#658]
## 问题描述
新注册的没有企业付款到零钱，只能用商户转账到零钱，是批量接口，无法调用

## 报错详情
NO_AUTH - 产品权限验证失败,请查看您当前是否具有该产品的权限

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
https://pay.yansongda.cn/docs/v3/wechat/pay.html#%E8%B4%A6%E6%88%B7%E8%BD%AC%E8%B4%A6

不能用么？

**Comment by light-speak** [comment]
嗷我用的是v2的，hhh，看来要切换v3
