### ISSUE TITLE
微信支付V3 base64_decode变乱码

### ISSUE THREAD

**Issue by 517389670github** [yansongda/pay#659]
## 包版本号

V3，框架laravel

## 问题描述

微信支付base64_decode变乱码

## 你的代码
![image](https://user-images.githubusercontent.com/112452754/187334055-09b39a1d-72c0-4ab5-953d-a2eef33319c3.png)
![image](https://user-images.githubusercontent.com/112452754/187334079-40be70f2-0a6c-4628-a0be-ac19df7ab112.png)

请问如何解决？

**Comment by 517389670github** [comment]
![image](https://user-images.githubusercontent.com/112452754/187338031-d4f03d62-b490-401b-9d22-e518006e2d9c.png)
我打印了报错问题，是不是因为微信返回这个错误，导致解密变乱码

**Comment by yansongda** [comment]
？？ 你打印 ciphertext 目的是什么呢？这东西本来就是加密的，打印出来了有啥用呢？

**Comment by 517389670github** [comment]
报错了，提示这个Get Wechat Public Cert Error，然后我就排查原因，打断点测试

**Comment by yansongda** [comment]
文档 FAQ

**Comment by 517389670github** [comment]
是的，密钥弄错了，现在又报其他错误，提示500 Internal Server Error

报错位置：
class: "Yansongda\Pay\Exception\InvalidResponseException"
file: "E:\phpstudy_pro\WWW\shop\vendor\yansongda\pay\src\Functions.php"
line: 223

**Comment by 517389670github** [comment]
这次提示Missing PrepayId
但是我检查了参数，都没有问题，大神，可以帮看看是什么原因吗
![image](https://user-images.githubusercontent.com/112452754/187346506-af2a3935-270f-435b-a842-422bef5d9c3a.png)
![image](https://user-images.githubusercontent.com/112452754/187346564-84062623-3856-4b2f-9a55-a05c33ddfbcb.png)
