### ISSUE TITLE
在think-swoole扩展中  服务无法注入。一直报这个错误。下文

### ISSUE THREAD

**Issue by weilewantieba** [yansongda/pay#673]
## 包版本号
3.1.0

## 问题描述
thinkphp6+thinkswoole使用的时候。一直无法使用。我看了源码是因为服务无法注入还是什么原因导致。在this->register的时候会爆出错误

## 你的代码
        $result = Pay::alipay($this->config)->web([
            'out_trade_no' => ''.time(),
            'total_amount' => '0.01',
            'subject' => 'yansongda 测试 - 1',
        ]);

## 报错详情
syntax error, unexpected token \")\";\/www\/wwwroot\/erp-agent-platforme\/api\/vendor\/symfony\/event-dispatcher\/EventDispatcher.php:270

## composer版本
        "yansongda/pay": "^3.1",
        "php-di/php-di": "^6.4",
        "guzzlehttp/guzzle": "^7.0"
## sdk 日志
无

## nginx/apache 日志
无
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by weilewantieba** [comment]
config文件配置是没有问题。对了很多次了

**Comment by yansongda** [comment]
php 版本多少？

然后看看弄个最小的复现 demo 出来吧

**Comment by weilewantieba** [comment]
PHP 8.0.20 demo代码已经贴出来了。thinkphp6+ think-swoole  
<?php
namespace app\controller\pub;
use app\common\services\ErpService;
use app\common\services\WechatService;
use app\common\services\OrdersService;
use \Yansongda\Pay\Pay;
use \Yansongda\Pay\Contract\HttpClientInterface;
use think\App;
//基础控制器(无需权限)
use app\common\controller\BaseController;

//api文档
use hg\apidoc\annotation as Apidoc;
use think\Exception;


/**
 * @Apidoc\Title("测试控制器")
 * @Apidoc\Group("pub")
 */
class Test extends BaseController
{
    protected $erpService;
    protected $config = [
        'alipay' => [
            'default' => [
                // 必填-支付宝分配的 app_id
                'app_id' => '2016082000295641',
                // 必填-应用私钥 字符串或路径
                'app_secret_cert' => '89iZ2iC16H6/6a3YcP+hDZUjiNGQx9cuwi9eJyykvcwhD...',
                // 必填-应用公钥证书 路径
                'app_public_cert_path' => '/Users/yansongda/pay/cert/appCertPublicKey_2016082000295641.crt',
                // 必填-支付宝公钥证书 路径
                'alipay_public_cert_path' => '/Users/yansongda/pay/cert/alipayCertPublicKey_RSA2.crt',
                // 必填-支付宝根证书 路径
                'alipay_root_cert_path' => '/Users/yansongda/pay/cert/alipayRootCert.crt',
                'return_url' => 'https://yansongda.cn/alipay/return',
                'notify_url' => 'https://yansongda.cn/alipay/notify',
                // 选填-服务商模式下的服务商 id，当 mode 为 Pay::MODE_SERVICE 时使用该参数
                'service_provider_id' => '',
                // 选填-默认为正常模式。可选为： MODE_NORMAL, MODE_SANDBOX, MODE_SERVICE
                'mode' => Pay::MODE_NORMAL,
            ],
        ],
        'logger' => [ // optional
            'enable' => false,
            'file' => './logs/alipay.log',
            'level' => 'info', // 建议生产环境等级调整为 info，开发环境为 debug
            'type' => 'single', // optional, 可选 daily.
            'max_file' => 30, // optional, 当 type 为 daily 时有效，默认 30 天
        ],
        'http' => [ // optional
            'timeout' => 5.0,
            'connect_timeout' => 5.0,
            // 更多配置项请参考 [Guzzle](https://guzzle-cn.readthedocs.io/zh_CN/latest/request-options.html)
        ],
    ];

    public function __construct(App $app,ErpService $erpService)
    {
        parent::__construct($app);
        $this->erpService = $erpService;


    }

    /**
     * @Apidoc\Title("测试接口")
     * @Apidoc\Desc("测试接口无用")
     * @Apidoc\Method("POST")
     * @Apidoc\Url("/example")
     */
    public function index(){
        $result = Pay::alipay($this->config)->web([
            'out_trade_no' => ''.time(),
            'total_amount' => '0.01',
            'subject' => 'yansongda 测试 - 1',
        ]);

        return $result;
    }

}

**Comment by weilewantieba** [comment]
PHP 8.0.20 demo代码已经贴出来了。thinkphp6+ think-swoole
        $result = Pay::alipay($this->config)->web([
            'out_trade_no' => ''.time(),
            'total_amount' => '0.01',
            'subject' => 'yansongda 测试 - 1',
        ]);

**Comment by yansongda** [comment]
composer.json 里的呢

**Comment by weilewantieba** [comment]
{
    "name": "topthink/think",
    "description": "the new thinkphp framework",
    "type": "project",
    "keywords": [
        "framework",
        "thinkphp",
        "ORM"
    ],
    "homepage": "http://thinkphp.cn/",
    "license": "Apache-2.0",
    "authors": [
        {
            "name": "liu21st",
            "email": "liu21st@gmail.com"
        },
        {
            "name": "yunwuxin",
            "email": "448901948@qq.com"
        }
    ],
    "require": {
        "php": ">=7.2.5",
        "topthink/framework": "^6.0.0",
        "topthink/think-orm": "^2.0",
        "topthink/think-swoole": "^4.0",
        "hg/apidoc": "^3.1",
        "d-os/jwt": "^1.6",
        "alibabacloud/darabonba-openapi": "^0.2.5",
        "yuchl/aliyun-dy-sdk-lite": "^1.0",
        "overtrue/wechat": "~5.0",
        "overtrue/pinyin": "~4.0",
        "phpoffice/phpspreadsheet": "^1.14",
        "weilewantieba/1688openapi": "dev-master",
        "pda/pheanstalk": "^4.0",
        "yansongda/pay": "~3.1.0",
        "php-di/php-di": "^6.4"
    },
    "require-dev": {
        "symfony/var-dumper": "^4.2",
        "topthink/think-trace":"^1.0"
    },
    "autoload": {
        "psr-4": {
            "app\\": "app"
        },
        "psr-0": {
            "": "extend/"
        }
    },
    "config": {
        "preferred-install": "dist",
        "allow-plugins": {
            "easywechat-composer/easywechat-composer": true
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "@php think service:discover",
            "@php think vendor:publish"
        ]
    }
}

**Comment by weilewantieba** [comment]
我是thinkphp6 + think-swoole得composer 来运行的。

**Comment by weilewantieba** [comment]
"code":0,"message":"No entry or class found for 'alipay' 偶尔也会报这个错误

**Comment by yansongda** [comment]
> PHP 8.0.20 demo代码已经贴出来了。

你这不对吧，都安装不上，你弄个最小的 demo repo  出来吧。

我感觉你这是哪个包里的 `symfony/event-dispatcher` 冲突了

![截屏2022-09-07 09 53 50](https://user-images.githubusercontent.com/11869114/188771315-e3aef197-d9d5-4d50-97da-479c357c0cac.png)

**Comment by weilewantieba** [comment]
这个包你要忽略掉来装。这个jwt包是我自己的
composer install  --ignore-platform-reqs  我没有更新最新包。你把jwt忽略掉

**Comment by weilewantieba** [comment]
你把jwt包弄掉 应该是没问题。
  "d-os/jwt": "^1.6", 这个包你可以去除掉

**Comment by yansongda** [comment]
你弄个最小的能复现的项目 repo 吧

**Comment by weilewantieba** [comment]
已经排查 和ewasywechat这个包有冲突  "overtrue/wechat": "~5.0",

**Comment by yansongda** [comment]
这个包不冲突的，无论是最新版还是历史版本，你检查你自己的环境吧

**Comment by weilewantieba** [comment]
已经排查 和ewasywechat这个包有冲突 "overtrue/wechat": "~5.0", 我就单独去了这个包 就不会报错了。。
