### ISSUE TITLE
调用支付宝APP支付返回空

### ISSUE THREAD

**Issue by anyuhanfei** [yansongda/pay#676]
## 包版本号
Lavavel 版本：9.*
php 版本：8.0.*
yansongda/pay：3.1.0

## 问题描述

调用支付宝的APP支付，得到了空数据，并且日志中也没有错误

## 你的代码
![alt https://cdn.learnku.com/uploads/images/202209/09/38676/9o7aXr93Kh.png!large](https://cdn.learnku.com/uploads/images/202209/09/38676/9o7aXr93Kh.png!large)
[https://cdn.learnku.com/uploads/images/202209/09/38676/lH0wS0h8fS.png!large](https://cdn.learnku.com/uploads/images/202209/09/38676/lH0wS0h8fS.png!large)

## 报错详情
[https://cdn.learnku.com/uploads/images/202209/09/38676/ydhEKmc6pj.png!large](https://cdn.learnku.com/uploads/images/202209/09/38676/ydhEKmc6pj.png!large)
## sdk 日志
[https://cdn.learnku.com/uploads/images/202209/09/38676/9OZdDcVRMZ.png!large](https://cdn.learnku.com/uploads/images/202209/09/38676/9OZdDcVRMZ.png!large)

**Comment by yansongda** [comment]
文档 FAQ

**Comment by anyuhanfei** [comment]
刚把图片展示出来了。大佬看下图片，谢谢

**Comment by anyuhanfei** [comment]
```
var_dump($res->getBody());exit;
```
这个方法返回的也是空的

**Comment by jefferyjob** [comment]
> ```
> var_dump($res->getBody());exit;
> ```
> 
> 这个方法返回的也是空的

解决了吗，我返回有东西，但是不是支付宝接口返回的内容，而是我的请求参数
