### ISSUE TITLE
支付宝和微信支付成功后会多次接收回调

### ISSUE THREAD

**Issue by yuanyuZQ** [yansongda/pay#685]
## 包版本号
pay 3.2
php框架tp5.1
## 问题描述
支付宝和微信支付成功后会多次接收回调

## 你的代码
public function wxpay_notify(){
        try{    
            $pay= Pay::wechat($this->wxpay_config);
            $result =$pay->callback();
            //支付成功后
            $result=json_decode($result,true)['resource']['ciphertext'];
            if($result['trade_state']=='SUCCESS'){
                $record['appid']=$result['attach'];
                $record['out_trade_no']=$result['out_trade_no'];
                $record['trade_no']=$result['transaction_id'];
                $record['total_amount']=number_format($result['amount']['total']/100,2);
                $record['payment_method']=1;
                $res=db('app_pay_record')->insert($record);
            }
            // return 'success';
            return $pay->success();
        }catch(\Exception $e){
            $handle=fopen('./cert/wxlog.txt', 'w');
            fwrite($handle, $e);
            fclose($handle);
        }
    }

## 报错详情

使用return $pay->success();会接收多次回调，重复写入数据库；改为return 'success';后只会接收一次回调
支付宝回调也是一样。
## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
https://pay.yansongda.cn/docs/v3/quick-start/return-format.html#messageinterface
