### ISSUE TITLE
请问 微信分账功能 有没有对应的文档呢

### ISSUE THREAD

**Issue by manager668899** [yansongda/pay#691]
请问 微信分账功能 有没有对应的文档呢

**Comment by yansongda** [comment]
通过「插件」支持：https://pay.yansongda.cn/docs/v3/wechat/more.html#%E8%B5%84%E9%87%91%E5%BA%94%E7%94%A8-%E5%88%86%E8%B4%A6

**Comment by gm-fire** [comment]
> 通过「插件」支持：https://pay.yansongda.cn/docs/v3/wechat/more.html#%E8%B5%84%E9%87%91%E5%BA%94%E7%94%A8-%E5%88%86%E8%B4%A6

页面404了

**Comment by yansongda** [comment]
最新的文档是：https://pay.yansongda.cn/docs/v3/wechat/all.html

但还没更新文档，可以先看源码：https://github.com/yansongda/pay/tree/master/src/Plugin/Wechat/V3/Extend/ProfitSharing

感兴趣的话，可以把文档帮忙补充一下
