### ISSUE TITLE
支付宝App支付，使用demo调用后，返回的是个obj，建议完善下使用文档，返回array

### ISSUE THREAD

**Issue by yexuchu** [yansongda/pay#692]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yansongda** [comment]
文档里有具体返回格式，你先自己看看文档

**Comment by yexuchu** [comment]
OK，找到了，返回的是\GuzzleHttp\Psr7\Response，问下为什么不处理成array呢，感觉这样会友好一点。
