### ISSUE TITLE
配置文件里这3个到底是什么啊

### ISSUE THREAD

**Issue by wongvio** [yansongda/pay#695]
## 包版本号
3.10

## 问题描述 

 'mch_secret_key' => 'ZvM4dzvYJDB********fEojgVzeEmi6h',   这个是V3生成的秘钥？？？
 // 必填-商户私钥 字符串或路径
 'mch_secret_cert' => ,
// 必填-商户公钥证书路径
 'mch_public_cert_path' => ,

生成的证书里就3个文件，apiclient_cert.pem， apiclient_cert.p12， apiclient_key.pem

mch_secret_cert = apiclient_key.pem？？？

mch_public_cert_path = apiclient_cert.pem？？？

**Comment by super-Yuan** [comment]
支付宝公钥证书方式时候才需要这三个证书路径

**Comment by KEN-studio** [comment]
'mch_secret_key' => 这个是API v3秘钥，没错
// 必填-商户私钥 字符串或路径
'mch_secret_cert' => 微信支付API证书 PRIVATE KEY，也就是 apiclient_key.pem 文件
// 必填-商户公钥证书路径
'mch_public_cert_path' => 微信支付API证书 CERTIFICATE，也就是 apiclient_cert.pem 文件

从 apiclient_cert.p12 中可以抽离出 apiclient_key.pem 和  apiclient_cert.pem ，文件包已经自带了，不用自己抽一次。

然后还有个微信平台证书 wechat_public_cert_path 可以配置，这是另外的，不配置也可以，有性能损失。

**Comment by yansongda** [comment]
@KEN-studio 感兴趣的话，文档帮忙提个 PR 吧

**Comment by KEN-studio** [comment]
@yansongda  哎哟，真的想帮你提个PR，文档过于简洁，对于刚开始熟悉的的，会有好多地方感觉语焉不详，只能反反复复看，踩坑踩了一周了。等我有空帮你提一下文档。
