### ISSUE TITLE
消息回调一个小兼容性问题，可以做个判断

### ISSUE THREAD

**Issue by wen-gg** [yansongda/pay#697]
## 包版本号
^3.2

## 问题描述
微信消息回调，不匹配的配置会报代码异常，当我_config使用了另一个有效配置时，
![image](https://user-images.githubusercontent.com/17865026/198825191-39a9f47b-c7fb-43b4-ba3f-0f01cca781f3.png)

## 你的代码
\Yansongda\Pay\Pay::wechat($config)->callback($request->all(), ['_config' => $driver])->toArray();

## 报错详情
json_decode(): Argument #1 ($json) must be of type string, bool given

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
感谢反馈
