### ISSUE TITLE
thinkPHP该如何引入呢

### ISSUE THREAD

**Issue by super-Yuan** [yansongda/pay#699]
## 包版本号

3.2.0
## 问题描述
thinkPHP该如何引入呢

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
按文档安装

**Comment by super-Yuan** [comment]
> 按文档安装

thinkphp能直接运行么，我安装后运行报错了Config Error
![image](https://user-images.githubusercontent.com/35750234/198992335-3ad5c8a8-5f37-47c8-8765-b94de9dc4434.png)
