### ISSUE TITLE
支付宝APP支付没有返回orderStr,支付配置文件没有问题

### ISSUE THREAD

**Issue by Your-little-smile** [yansongda/pay#702]
## 包版本号
yansongda/pay    "version": "v3.1.12"

## 问题描述
支付宝app支付无法获取到orderStr，请求响应是200，配置没有问题（wap支付可以返回支付链接（orderStr））

## 你的代码
// 创建支付（YII框架）
        $order = [
            'out_trade_no' => time().mt_rand(10000000,99999999999),
            'total_amount' => '1',
            'subject' => '订单支付',
            //'_method' => 'get',
        ];
        dump($order);
        // 配置
        $config = [
            'notify_url' => 'https://www.rlshijie.com/notify', // 支付通知回调地址
        ];
        $tradeType = 'app';
        $res = Yii::$app->pay->alipay($config)->$tradeType($order);
        $body = $res->getBody();
        dump($body);
        dd($res);
        
<img width="874" alt="image" src="https://user-images.githubusercontent.com/25879884/199404953-9825ff30-6f20-4e0f-9f93-c2be0b64eb5d.png">

## 报错详情
打印返回结果
![image](https://user-images.githubusercontent.com/25879884/199405154-b1df67d4-488a-442d-a196-6cffd924642f.png)

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by xiaohe4966** [comment]
试试 ->getBody()->__toString();

**Comment by Your-little-smile** [comment]
> 试试 ->getBody()->__toString();

试过了，可以了；多谢哈；刚才直接 echo $response->getBody() ，也是有数据的，我就想着应该是文件流没有被转换

**Comment by Your-little-smile** [comment]
> 试试 ->getBody()->__toString();

使用  $response->getBody()->getContents(); 也是可以的
