### ISSUE TITLE
laravel命令行调用报错Exception::ALIPAY_CONFIG_ERROR, 'Parse `app_public_cert_path` Error'

### ISSUE THREAD

**Issue by zhaoduo110** [yansongda/pay#704]
## 包版本号
`yansongda/pay  3.2.8`

## 问题描述
laravel在命令行中调用一直返回 
`throw new InvalidConfigException(Exception::ALIPAY_CONFIG_ERROR, 'Missing Alipay Config -- [app_public_cert_path]');`

## 你的代码
$params = [
      'out_trade_no' => $orderCode,
  ];

  $result = Pay::alipay($this->config)->cancel($params);
  if ($result->toArray()['code'] == 10000 && $result->toArray()['msg'] == 'Success') {
      return true;
  }

## 报错详情
   ValueError

  Path cannot be empty

  at vendor/yansongda/pay/src/Plugin/Alipay/PreparePlugin.php:111
    107▕         if (is_null($path)) {
    108▕             throw new InvalidConfigException(Exception::ALIPAY_CONFIG_ERROR, 'Missing Alipay Config -- [app_public_cert_path]');
    109▕         }
    110▕
    111▕         $cert = file_get_contents($path);
    112▕         $ssl = openssl_x509_parse($cert);
    113▕
    114▕         if (false === $ssl) {
    115▕             throw new InvalidConfigException(Exception::ALIPAY_CONFIG_ERROR, 'Parse `app_public_cert_path` Error');

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by zhaoduo110** [comment]
自己的问题  已解决，谢谢

**Comment by liuwenzi** [comment]
@zhaoduo110 什么问题? 还记得吗?
