### ISSUE TITLE
微信支付返回“201 商户订单号重复”

### ISSUE THREAD

**Issue by ChartWay** [yansongda/pay#705]
## 包版本号
3.2.0

## 问题描述
PC端使用扫码微信支付，中途放弃了；然后，在手机端，使用同样的商户订单号，再次发起支付，提示“201 商户订单号重复”。
这个时候用商户订单号去查，是存在一条未支付的订单的。
也就是说，只要用一种方式创建了支付订单，那就不能再用其他方式创建订单，反之亦然。
 那么，如果需要切换成其他支付，比如从扫码切换到h5支付，如何对这个订单再次发起支付？

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by KEN-studio** [comment]
一、如果你想继续用原商户订单号发起继续支付，需要 订单号，描述，金额等与原信息完全相同，如果稍有不同就会不行，可能是被视为另外的订单。
二、如果你无法用原描述信息提交，那就只能生成新的商户订单号发起新的一条支付。

注意有个坑就是，微信的商户订单号必须是string类型，如果是int类型，会发生未知错误。

**Comment by ChartWay** [comment]
> 一、如果你想继续用原商户订单号发起继续支付，需要 订单号，描述，金额等与原信息完全相同，如果稍有不同就会不行，可能是被视为另外的订单。 二、如果你无法用原描述信息提交，那就只能生成新的商户订单号发起新的一条支付。
> 
> 注意有个坑就是，微信的商户订单号必须是string类型，如果是int类型，会发生未知错误。

我主要是换了终端，从PC换到H5，H5的参数和PC的有差异，所以就出现不能支付的情况。同一个终端没问题。

**Comment by KEN-studio** [comment]
> > 一、如果你想继续用原商户订单号发起继续支付，需要 订单号，描述，金额等与原信息完全相同，如果稍有不同就会不行，可能是被视为另外的订单。 二、如果你无法用原描述信息提交，那就只能生成新的商户订单号发起新的一条支付。
> > 注意有个坑就是，微信的商户订单号必须是string类型，如果是int类型，会发生未知错误。
> 
> 我主要是换了终端，从PC换到H5，H5的参数和PC的有差异，所以就出现不能支付的情况。同一个终端没问题。

这种情况必须刷新订单号 out_trade_no，因为订单信息中的支付接口值变了（如：Native 变成了 H5），这在微信那里是两个不同产品。
你本地的订单可以做2个id，一个本地的固定id号（用于内部处理），一个发给微信的 out_trade_no，这里可能要自己做一下对应逻辑，防止刷新后的 out_trade_no 在本地找不到的情况。

**Comment by ChartWay** [comment]
> > > 一、如果你想继续用原商户订单号发起继续支付，需要 订单号，描述，金额等与原信息完全相同，如果稍有不同就会不行，可能是被视为另外的订单。 二、如果你无法用原描述信息提交，那就只能生成新的商户订单号发起新的一条支付。
> > > 注意有个坑就是，微信的商户订单号必须是string类型，如果是int类型，会发生未知错误。
> > 
> > 
> > 我主要是换了终端，从PC换到H5，H5的参数和PC的有差异，所以就出现不能支付的情况。同一个终端没问题。
> 
> 这种情况必须刷新订单号 out_trade_no，因为订单信息中的支付接口值变了（如：Native 变成了 H5），这在微信那里是两个不同产品。 你本地的订单可以做2个id，一个本地的固定id号（用于内部处理），一个发给微信的 out_trade_no，这里可能要自己做一下对应逻辑，防止刷新后的 out_trade_no 在本地找不到的情况。

好主意。
