### ISSUE TITLE
[ERROR] Missing Alipay Config -- [app_public_cert_path]

### ISSUE THREAD

**Issue by garenlyu1993** [yansongda/pay#710]
## 包版本号
^3.2

## 问题描述
error: [ERROR] Missing Alipay Config -- [app_public_cert_path]

## 你的代码
配置代码（hyperf2.2/config/config.php）：
![image](https://user-images.githubusercontent.com/73512013/201804535-104c9bb5-a19c-496b-a7ce-39b8099104a5.png)
支付代码：
![image](https://user-images.githubusercontent.com/73512013/201804749-58458d6c-ac9c-4a89-bce8-ffed31326ce2.png)

## 报错详情
![image](https://user-images.githubusercontent.com/73512013/201804942-4396e3cc-443d-42d2-9574-4b409a28e939.png)

[ERROR] Missing Alipay Config -- [app_public_cert_path][107] in /var/www/root/topuphub-api/vendor/yansongda/pay/src/Plugin/Alipay/PreparePlugin.php

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
1、config 有问题，要把全部 config 传递，可以认真看看文档

2、hyperf 有  yansongda/hyperf-pay 可以直接使用

**Comment by garenlyu1993** [comment]
1.阁下的方法里要求的是array $config，却实际要求整个配置文件。这让我理解不了
2.hyperf只是一个php框架，为何不能使用你的通用版，只能使用专门版

**Comment by yansongda** [comment]
1、整个配置就是 config，不是 alipay 的 config ，你认真看看文档，按文档来就行了。

2、可以用通用版，你想用哪个版本就行。
