### ISSUE TITLE
请问 v3 版本如何使用微信沙箱模式

### ISSUE THREAD

**Issue by sym134** [yansongda/pay#711]
请问 v3 版本如何使用沙箱模式

**Comment by yansongda** [comment]
配置 mode

麻烦看看文档

**Comment by sym134** [comment]
我看到文档写的，但没有标沙箱模式
![image](https://user-images.githubusercontent.com/32946251/202599595-ce866ec6-a5cb-4b22-a605-7150cc65abae.png)
我在Pay里面看到有沙箱尝试配置
![image](https://user-images.githubusercontent.com/32946251/202599637-6cc25015-cb63-4d79-be34-7e14dc88fab6.png)
但是返回的是404
![image](https://user-images.githubusercontent.com/32946251/202601318-f1271af9-2d92-45b9-9771-59a2942e155b.png)
 折腾一天，今天早上找到微信支付人工客服的回复是
![image](https://user-images.githubusercontent.com/32946251/202601421-1bcf4cb2-6d5a-485e-96a6-38bc34c70bf7.png)
