### ISSUE TITLE
参数错误：输入的商户订单号有误

### ISSUE THREAD

**Issue by jerryyyq** [yansongda/pay#72]
## 包版本号
2.0.10

## 问题描述
微信小程序提现时报 参数错误：输入的商户订单号有误。
app_id 为小程序 id，openid 为小程序相关用户 id

## 报错详情
2018-01-17 00:17:19 > DEBUG > Request To Wechat Api ["https://api.mch.weixin.qq.com/mmpaymkttransfers/promotion/transfers",{"nonce_str":"rtzJhjXA1pYjcGLK","sign":"C27003166A4ECCA8C74A2312666DE589","spbill_create_ip":"139.196.237.56","out_trade_no":"14495213028","total_fee":990,"body":"用户提现","openid"......
2018/01/17 00:17:19 [error] 25380#0: *226153 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Yansongda\Pay\Exceptions\GatewayException: Get Wechat API Error:参数错误：输入的商户订单号有误参数错误：输入的商户订单号有误 in /data/wwwroot/www.xxguan.cn/fire/vendor/yansongda/pay/src/Gateways/Wechat/Support.php:71
Stack trace:
#0 /data/wwwroot/www.xxguan.cn/fire/vendor/yansongda/pay/src/Gateways/Wechat/TransferGateway.php(38): Yansongda\Pay\Gateways\Wechat\Support::requestApi('mmpaymkttransfe...', Array, '6d3265829b8be70...', './cert/apiclien...', './cert/apiclien...')
#1 /data/wwwroot/www.xxguan.cn/fire/vendor/yansongda/pay/src/Gateways/Wechat.php(207): Yansongda\Pay\Gateways\Wechat\TransferGateway->pay('https://api.mch...', Array)
#2 /data/wwwroot/www.xxguan.cn/fire/vendor/yansongda/pay/src/Gateways/Wechat.php(79): Yansongda\Pay\Gateways\Wechat->makePay('Yansongda\\Pay\\G...')
#3 /data/wwwroot/www.xxguan.cn/fire/vendor/yansongda/pay/src/Gateways/Wechat.php(225): Yansongda\Pay\Gateways\Wechat->pay('Yansongda\\Pay\\G...', Array)
#4 /" while reading response header from upstream, client: 113.47.35.226, server: www.xxguan.cn, request: "POST /fire/fire.php?m=extracted_money HTTP/2.0", upstream: "fastcgi://unix:/dev/shm/php-cgi.sock:", host: "w.xxguan.cn", referrer: "https://servicewechat.com/wx1c93e079b02bf390/devtools/page-frame.html"

**Comment by yansongda** [comment]
您好，首先麻烦请升级到最新版。

提现请看微信付款文档，根据您日志可以看出您的参数是错的。

感谢支持
