### ISSUE TITLE
v2.x 微信支付查询订单接口提示“ERROR_GATEWAY: Get Wechat API Error:请求中含有未在API文档中定义的参数”

### ISSUE THREAD

**Issue by Mac527** [yansongda/pay#723]
## 包版本号
v2.x

## 问题描述
微信支付查询订单接口提示“ERROR_GATEWAY: Get Wechat API Error:请求中含有未在API文档中定义的参数”

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
升级到 v2 最新版

PS：如果有条件，尽快升级到 v3

**Comment by Mac527** [comment]
V3和V2兼容吗




快拖筑导
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yansongda/pay"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月12日(星期一) 晚上6:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yansongda/pay] v2.x 微信支付查询订单接口提示“ERROR_GATEWAY: Get Wechat API Error:请求中含有未在API文档中定义的参数” (Issue #723)





 
升级到 v2 最新版
 
PS：如果有条件，尽快升级到 v3
