### ISSUE TITLE
Alipay create order link

### ISSUE THREAD

**Issue by walidaalhomsi** [yansongda/pay#729]
Hello,

First of all, thank you for this priceless work, it's very useful and easy to use!

This is not a bug but a question.

I have a questions about create payment link with Alipay, I have seen the following example in the docs

```php
 public function web()
    {
        $result = Pay::alipay($this->config)->web([
            'out_trade_no' => ''.time(),
            'total_amount' => '0.01',
            'subject' => 'yansongda 测试 - 1',
        ]);
        
        return $result;
    }
```

My question is about the `$result` variable, is it `string` with the redirect link which we should send to the browser in the `Location` header? If no, can you please share with me the type of the `$result` variable, so I can see its properties in the source code.

Thank you again!

**Comment by walidaalhomsi** [comment]
Another question, 

Can I include characters in the `out_trade_no` parameter, or it should only be numbers.

Example:
```php
[ 'out_trade_no' => 'product_3234' ]
``` 
Thank you

**Comment by yansongda** [comment]
`$result` is an instance of `\GuzzleHttp\Psr7\Response`

see: https://pay.yansongda.cn/docs/v3/quick-start/return-format.html

**Comment by yansongda** [comment]
> Can I include characters in the out_trade_no parameter, or it should only be numbers.

Please refer to Alipay documentation

**Comment by walidaalhomsi** [comment]
Thank you for your response, it was very helpful.

I checked the docs and looks like `out_trade_no` can include characters, so this answers my second questions, many thanks 👍 

As per the Alipay docs, calling their API would result in [html form that should rendered in the client browser](https://opendocs.alipay.com/open/028r8t?scene=22#%E5%93%8D%E5%BA%94%E7%A4%BA%E4%BE%8B),

So can I use the string representation of the `$result` variable that is returned by ` Pay::alipay()->web()` to render the result form?

```php
$result->__toString() == '// 响应为表单格式，可嵌入页面，具体以返回的结果为准
<form name="submit_form" method="post" action="https://openapi.alipay.com/gateway.do?charset=UTF-8&method=alipay.trade.page.pay&sign=k0w1DePFqNMQWyGBwOaEsZEJuaIEQufjoPLtwYBYgiX%2FRSkBFY38VuhrNumXpoPY9KgLKtm4nwWz4DEQpGXOOLaqRZg4nDOGOyCmwHmVSV5qWKDgWMiW%2BLC2f9Buil%2BEUdE8CFnWhM8uWBZLGUiCrAJA14hTjVt4BiEyiPrtrMZu0o6%2FXsBu%2Fi6y4xPR%2BvJ3KWU8gQe82dIQbowLYVBuebUMc79Iavr7XlhQEFf%2F7WQcWgdmo2pnF4tu0CieUS7Jb0FfCwV%2F8UyrqFXzmCzCdI2P5FlMIMJ4zQp%2BTBYsoTVK6tg12stpJQGa2u3%2BzZy1r0KNzxcGLHL%2BwWRTx%2FCU%2Fg%3D%3D&notify_url=http%3A%2F%2F114.55.81.185%2Fopendevtools%2Fnotify%2Fdo%2Fbf70dcb4-13c9-4458-a547-3a5a1e8ead04&version=1.0&app_id=2014100900013222&sign_type=RSA&timestamp=2021-02-02+14%3A11%3A40&alipay_sdk=alipay-sdk-java-dynamicVersionNo&format=json">
<input type="submit" value="提交" style="display:none" >
</form>
<script>document.forms[0].submit();</script>';
``` 

Is my understanding correct?

Thank you again, and wish you a great day!

**Comment by yansongda** [comment]
yes
