### ISSUE TITLE
支付宝 app支付 异步通知 notify_url

### ISSUE THREAD

**Issue by sanyuanya** [yansongda/pay#730]
## 包版本号
"yansongda/pay": "~3.2.0"

## 问题描述
[2022-12-28 09:58:23] local.ERROR: `getContainer()` failed! Maybe you should `setContainer()` first {"exception":"[object] (Yansongda\\Pay\\Exception\\ContainerNotFoundException(code: 1001): `getContainer()` failed! Maybe you should `setContainer()` first at /app/yjj/vendor/yansongda/pay/src/Pay.php:222)

## 你的代码
![image] (https://user-images.githubusercontent.com/46390493/209748388-67ecff89-acc7-4b75-9b2a-9b07535fab75.png)

## 报错详情
[stacktrace]
#0 /app/yjj/vendor/yansongda/pay/src/Pay.php(183): Yansongda\\Pay\\Pay::getContainer()
#1 /app/yjj/vendor/yansongda/pay/src/Pay.php(97): Yansongda\\Pay\\Pay::get('alipay')
#2 /app/yjj/app/Http/Controllers/Web/PayController.php(87): Yansongda\\Pay\\Pay::__callStatic('alipay', Array)
#3 /app/yjj/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Web\\PayController->notifyAliyun(Object(Illuminate\\Http\\Request))
#4 /app/yjj/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction('notifyAliyun', Array)
#5 /app/yjj/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\Web\\PayController), 'notifyAliyun')

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by Hardy-chen** [comment]
应该是引入的Yansongda\LaravelPay\Facades\Pay 这个类有问题, 改了就好了
