### ISSUE TITLE
微信小程序预支付失败

### ISSUE THREAD

**Issue by daiyuanfei741** [yansongda/pay#737]
版本 V3.1
$config_alipay 是我本地支付中心获取的微信支付 ,然后调用微信支付。 ->mp  
![image](https://user-images.githubusercontent.com/34326481/212458272-d589c589-2e5c-434b-a77a-9e564332afa4.png)
出现一下报错：
[WARNING] Yansongda\Pay\Exception\InvalidResponseException: Prepay Response Error: Missing PrepayId(5005) in /m2odata/www/vendor/yansongda/pay/src/Plugin/Wechat/Pay/Common/InvokePrepayPlugin.php:38
疑问：
这是预支付，PrepayId 不应该是返回的值吗 为什么在预支付的时候也会需要这个参数？
xia'tu下图是完成的报错信息
![image](https://user-images.githubusercontent.com/34326481/212458352-790a9b6d-88b1-4bf1-93fc-3031f353de02.png)

**Comment by yansongda** [comment]
文档 FAQ
