### ISSUE TITLE
$alipay->send(); 怎样不直接输出

### ISSUE THREAD

**Issue by zjttfs** [yansongda/pay#74]
## 包版本号
18年1月25日 最新

## 问题描述
现在 $alipay->send();  会直接输出,但现在系统接口会对所有数据处理后,按特定格式返回.这就造成了数据格式错误,请问怎么修改能让其返回值而不是输出值

## 代码
涉及到 异步通知、同步通知 的问题，请将 nginx/Apache 的相关日志贴出来

**Comment by yansongda** [comment]
返回的 Response 中，getContent() 可获取内容，RedirectResponse 中，getTargetUrl() 可获取跳转链接，JsonResponse 中，getContent() 可获取Json。

具体可参考 `Symfony\Component\HttpFoundation\Response`

感谢支持

**Comment by yansongda** [comment]
返回的 Response 中，getContent() 可获取内容，RedirectResponse 中，getTargetUrl() 可获取跳转链接，JsonResponse 中，getContent() 可获取Json。

具体可参考 `Symfony\Component\HttpFoundation\Response`

感谢支持

**Comment by zjttfs** [comment]
感谢
