### ISSUE TITLE
V2 支付宝异步回调验签问题

### ISSUE THREAD

**Issue by DevHaoZi** [yansongda/pay#749]
## 包版本号
v2.10.5

## 问题描述
扫码支付异步回调验签一直过不去，反复debug后发现使用`stripslashes`函数去掉`$toVerify`中的反斜杠，就能成功验签。

## 你的代码
文件`vendor/yansongda/pay/src/Gateways/Alipay/Support.php`第220行由：

```
$toVerify = $sync ? json_encode($data, JSON_UNESCAPED_UNICODE) : self::getSignContent($data, true);
```

修改为：

```
$toVerify = $sync ? json_encode($data, JSON_UNESCAPED_UNICODE) : stripslashes(self::getSignContent($data, true));
```

## 报错详情
修改前报错`INVALID_SIGN: Alipay Sign Verify FAILED`

## sdk 日志
无，不涉及

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

无，不涉及

**Comment by yansongda** [comment]
用 v3 吧。

我记得 stripslashes 这个好像来回修改过好多次，所以 v2 不在修改了

**Comment by longxianlin** [comment]
v2可以不适用证书cert

**Comment by devhaozi** [comment]
> v2可以不适用证书cert

是的，当时客户要求不用证书所以才用v2，这个issue留着给后面人踩到坑的看吧。

**Comment by longxianlin** [comment]
> > v2可以不适用证书cert
> 
> 是的，当时客户要求不用证书所以才用v2，这个issue留着给后面人踩到坑的看吧。

他这个改验签的方法，修改还后还是：Alipay Sign Verify FAILED
