### ISSUE TITLE
使用 H5 支付时，如果配置参数中有 return_url 参数，则 SDK 将自动将return_url 设置为 redirect_url。

### ISSUE THREAD

**Issue by freadman** [yansongda/pay#759]
使用 H5 支付时，如果配置参数中有 return_url 参数，则 SDK 将自动将return_url 设置为 redirect_url。

https://github.com/yansongda/pay/blob/master/src/Gateways/Wechat/WapGateway.php#L26

_Originally posted by @yansongda in https://github.com/yansongda/pay/issues/128#issuecomment-406178940_
            

没效果啊。我在配置文件中设置了return_url，但是实际调用接口并没有传这个参数给微信，导致，支付成功后重定向到了网站首页。

**Comment by yansongda** [comment]
redirect_url 是 微信 v2 版支持的，v3 已经没有这个参数了，具体见微信官方文档
