### ISSUE TITLE
微信平台公钥证书获取不正确

### ISSUE THREAD

**Issue by cjango** [yansongda/pay#760]
## 包版本号
v3.2.14

## 问题描述
```
<?php
\Yansongda\Pay\Pay::config($config);
$params = [
    '_config' => 'default' // 多租户配置时使用
];
\Yansongda\Pay\get_wechat_public_certs($params, storage_path('pay/wechat_default'));
```
获取证书的时候，如果`$config`中配置了 `wechat_public_cert_path` ，会直接返回配置内的证书路径。如果未配置，
 
yansongda /pay/src/ Functions.php: 168

会抛出异常，Illegal string offset "28179ABA2126B8F53B37DDC79BDC0F2069E7F75D"

**Comment by yansongda** [comment]
这个感觉不会出现，能尝试帮忙分析下么？

**Comment by cjango** [comment]
vendor/yansongda/pay/src/Functions.php

**Comment by cjango** [comment]
reload_wechat_public_certs  好像是在执行这个方法的时候，报了个错误，导致下面的代码无法运行了

**Comment by cjango** [comment]
$data = Pay::wechat()->pay(
            [PreparePlugin::class, WechatPublicCertsPlugin::class, RadarSignPlugin::class, ParserPlugin::class],
            $params
        )->get('data', []);

这个方法没有获取到值

**Comment by cjango** [comment]
是我的问题，错把mch_secret_key填成 v2的密钥了

**Comment by cjango** [comment]
如果把 wechat_public_cert_path 这个参数设置成了 '' 就会报这个错误。

**Comment by yansongda** [comment]
还是没搞明白。就算 秘钥设置错了，现有代码理论上不会出现报错的

能具体分析下哪行报「Illegal string offset 」这个错么？

**Comment by xfle** [comment]
和楼主一样的报错，微信扫码，如果默认设置  'wechat_public_cert_path' => ‘’ 就会抛出Illegal string offset "44......."，而如果写入'wechat_public_cert_path' => [ '33.....'=>config_path('Pay/wechat/wechatPublicKey.crt')  ]，确实在这个地方会生成文件，打开...crt文件。里面就是pay/wechat/wechatPublicKey.crt'路径。
