### ISSUE TITLE
关于支付宝支付可以使用【手机网站支付2.0】alipay.trade.wap.pay 由手机端jsapi调起来支付吗？

### ISSUE THREAD

**Issue by huanzipap** [yansongda/pay#761]
接口地址 https://opendocs.alipay.com/open/02ivbs?scene=21

**Comment by yansongda** [comment]
https://pay.yansongda.cn/docs/v3/alipay/pay.html#%E6%89%8B%E6%9C%BA%E7%BD%91%E7%AB%99%E6%94%AF%E4%BB%98
