### ISSUE TITLE
如何获取 微信、支付宝 支付流水对账单？

### ISSUE THREAD

**Issue by gyp719** [yansongda/pay#762]
版本 "yansongda/pay": "^3.2"

如何获取 微信、支付宝 支付流水对账单？

查看了[文档](https://pay.yansongda.cn/docs/v2/alipay/find.html#%E6%9F%A5%E8%AF%A2%E6%99%AE%E9%80%9A%E6%94%AF%E4%BB%98%E8%AE%A2%E5%8D%95) 没有描述， 是否没有对应的方法？

**Comment by yansongda** [comment]
https://pay.yansongda.cn/docs/v3/alipay/more.html#%E4%B8%8B%E8%BD%BD%E5%AF%B9%E8%B4%A6%E5%8D%95
