### ISSUE TITLE
支付宝支付下单返回错误时的问题

### ISSUE THREAD

**Issue by krissss** [yansongda/pay#77]
## 包版本号
v1和v2

## 问题描述
支付宝支付返回错误时的 `sub_code` 不是必定有的，所以代码上对于抛出 `GatewayException` 时直接通过数组取 `sub_code` 时会报 `Undefined index: sub_code`

## 代码
https://github.com/yansongda/pay/blob/f64bc7e5a9ae69707239f58bba0f51f1c9d1123e/src/Gateways/Alipay/Support.php#L78

## 报错详情
`Undefined index: sub_code`

**Comment by yansongda** [comment]
已修复。

感谢支持！
