### ISSUE TITLE
对于刷卡支付的处理

### ISSUE THREAD

**Issue by krissss** [yansongda/pay#78]
## 包版本号
v1 v2

## 问题描述
先申明这个不算 bug，只是一个建议和 Enh。

刷卡支付的支付结果是同步的，而且存在需要用户输入密码等的特殊情况，因此微信和支付宝都存在非正常的返回（微信 return_code Success，支付宝 code 10000）。

因为你的包下面对于非正常返回都是抛出 `GatewayException` 异常的，当然我可以通过 catch 这个异常的 `raw` 来处理对应的结果，但感觉相当的不优雅，也不够理想，尤其是支付宝返回的 `raw` 数组下有 key。

所以建议是不是可以返回一个指明需要客户端轮询 `query` 来检查结果的异常，然后客户端通过捕获这个异常来进行相关操作。

支付宝是 '10003' 时需要客户端轮询，微信是 'SYSTEMERROR','BANKERROR','USERPAYING' 时需要客户端轮询。

[微信业务流程](https://pay.weixin.qq.com/wiki/doc/api/micropay_sl.php?chapter=9_10&index=1)
[支付宝业务流程](https://docs.open.alipay.com/194/105205/)

**Comment by riseno** [comment]
我的處理方式是直接無視了任何正常或不正常返回，再指派 queue job 來處理支付結果。

但個人覺得，如果把不正常返回都放在包裡，感覺是太腫了。
