### ISSUE TITLE
微信H5支付下单成功后，微信内付款提示“该商户支付权限已被取消”

### ISSUE THREAD

**Issue by Tomorrowxxy** [yansongda/pay#792]
## 包版本号
3.2.14

## 问题描述
微信H5支付下单成功后，微信内付款提示“该商户支付权限已被取消”
疑似用错了预支付ID

## 你的代码
        Pay::config($config);
        $pay_result = Pay::wechat()->wap([
            'out_trade_no' => 'aaaaaaa'.time(),
            'description'  => '高级会员-测试',
            'amount'       => ['total' => 1],
            'scene_info'   => ['payer_client_ip' => 'x.x.x.x', 'h5_info' => ['type' => 'Wap']],
        ]);

## 报错详情
无报错

## sdk 日志
暂无

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
这个我感觉是你商户有问题，被腾讯給 ban 了。

**Comment by Tomorrowxxy** [comment]
> 这个我感觉是你商户有问题，被腾讯給 ban 了。

如果被ban了，理论上不能下单了吧

**Comment by yansongda** [comment]
所以提示 「该商户支付权限已被取消」 啊。你在商户后台看有没有这权限吧
