### ISSUE TITLE
get_wechat_public_certs([], path)  如果在配置 wechat_public_cert_path 之后执行， 证书文件的内容会被替换为 证书的路径。

### ISSUE THREAD

**Issue by zhuxbo** [yansongda/pay#796]
## 包版本号
3.3

## 问题描述
get_wechat_public_certs([], path)  如果在配置 wechat_public_cert_path 之后执行， 证书文件的内容会被替换为 证书的路径。
也就是 证书文件的内容会是 $config['wechat']['default']['wechat_public_cert_path'][$serialNo] 的值。

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
这不会吧。

**Comment by zhuxbo** [comment]
如果使用 get_wechat_public_certs  获取证书之后，添加 $config['wechat']['default']['wechat_public_cert_path'][$serialNo] 配置，然后证书会自动更新吗？
如果会自动更新，那get_wechat_public_certs 只能运行一次也是对的。
如果不会自动更新，那需要怎样才能设置自动更新呢？

我在mac和linux都反复测试好多次，只要在配置了  $config['wechat']['default']['wechat_public_cert_path'][$serialNo]  之后 再用 get_wechat_public_certs 获取证书，证书内容就会变成 $config['wechat']['default']['wechat_public_cert_path'][$serialNo] 的值。

    function get_wechat_public_certs(array $params = [], ?string $path = null): void
    {
        reload_wechat_public_certs($params);

        $config = get_wechat_config($params);

        if (empty($path)) {
            var_dump($config['wechat_public_cert_path']);

            return;
        }

        foreach ($config['wechat_public_cert_path'] as $serialNo => $cert) {
            file_put_contents($path.'/'.$serialNo.'.crt', $cert);
        }
    }

这个函数，最后也是把 配置文件路径的值 当做内容写入 证书， 并没有做 判断是 $cert 是路径还是证书内容。


多谢开源如此好用的工具，感谢。。。

**Comment by zhuxbo** [comment]
> 这不会吧。

如果使用 get_wechat_public_certs 获取证书之后，添加 $config['wechat']['default']['wechat_public_cert_path'][$serialNo] 配置，然后证书会自动更新吗？
如果会自动更新，那get_wechat_public_certs 只能运行一次也是对的。
如果不会自动更新，那需要怎样才能设置自动更新呢？

我在mac和linux都反复测试好多次，只要在配置了 $config['wechat']['default']['wechat_public_cert_path'][$serialNo] 之后 再用 get_wechat_public_certs 获取证书，证书内容就会变成 $config['wechat']['default']['wechat_public_cert_path'][$serialNo] 的值。

function get_wechat_public_certs(array $params = [], ?string $path = null): void
{
    reload_wechat_public_certs($params);

    $config = get_wechat_config($params);

    if (empty($path)) {
        var_dump($config['wechat_public_cert_path']);

        return;
    }

    foreach ($config['wechat_public_cert_path'] as $serialNo => $cert) {
        file_put_contents($path.'/'.$serialNo.'.crt', $cert);
    }
}
这个函数，最后也是把 配置文件路径的值 当做内容写入 证书， 并没有做 判断是 $cert 是路径还是证书内容。

多谢开源如此好用的工具，感谢。。。

**Comment by yansongda** [comment]
`get_wechat_public_certs` 这个方法不应该在上线之后使用

如果在配置了 `$config['wechat']['default']['wechat_public_cert_path'][$serialNo]` 之后使用，会在 生命周期内 改变其值，但是不会改变物理配置文件的值

生命周期过后自动恢复为以前的值
