### ISSUE TITLE
微信支付方式：刷卡支付（付款码，被扫码）出错

### ISSUE THREAD

**Issue by jiningrich** [yansongda/pay#798]
V3包(v3.3.0)：
排除配置错误，因为相同配置下，调用扫码支付是没问题，能成功返回扫码信息
```
$result = Pay::wechat()->scan($order);
```

刷卡支付（付款码，被扫码）,传参也没问题，直接复制文档示例的参数，其中把`spbill_create_ip`修改为了自己的IP4地址，`auth_code`字段也有尝试过真实的，还是同样错误。错误如下：
```
ERROR：{"userId":"1","exception":"[object] (Yansongda\\Pay\\Exception\\InvalidResponseException(code: 5003):  at /var/www/project/vendor/yansongda/pay/src/Functions.php:203)
#0 /var/www/project/vendor/yansongda/pay/src/Plugin/Wechat/LaunchPlugin.php(41): Yansongda\\Pay\\verify_wechat_sign(Object(GuzzleHttp\\Psr7\\Response), Array)
```

**Comment by whs891015** [comment]
解决了没有

**Comment by whs891015** [comment]
@jiningrich 我搞了一天自己造轮子把

**Comment by yansongda** [comment]
能排查出哪里有问题么？

**Comment by jiningrich** [comment]
@whs891015 没解决，换了一个包，解决的的，w7corp/easywechat 可以进行 刷卡支付（付款码，被扫码）方式接口调用，我两个包混合使用的，支付宝使用yansongda的，微信使用 w7corp/easywechat

@yansongda 没排查，因为没有仔细阅读微信支付文档，盲猜因为刷卡支付（付款码，被扫码）官方还是是V2接口的原因，导致签名出错，然后我使用的V3接口的包
