### ISSUE TITLE
支付宝验证方式

### ISSUE THREAD

**Issue by ruziyi** [yansongda/pay#8]
我的支付宝验证方式为RSA，该如何配置

**Comment by yansongda** [comment]
我们全部使用的是最新的、官方推荐的方式进行开发的，所以，目前支持且只支持 RSA2 验证方式。

建议直接更换为 RSA2，只需要在 支付宝 端生成秘钥即可。

感谢您的支持！

**Comment by vt-nwei** [comment]
可以拖过修改源码来实现.

- 在 /vendor/yansongda/pay/src/Gateways/Alipay/Support.php 文件中将 openssl_verify() 方法的 signature_alg 参数改为 OPENSSL_ALGO_SHA1. 同样将 openssl_sign() 方法中的该参数也改为 OPENSSL_ALGO_SHA1

- 修改 /vendor/yansongda/pay/src/Gateways/Alipay.php 文件中 payload 数组的 sign_type 键值改为 RSA.

修改完就是 RSA 加密的验证方式了.
