### ISSUE TITLE
支付宝当面付支付问题

### ISSUE THREAD

**Issue by qianqian123** [yansongda/pay#80]
## 包版本号
v2.0.17

## 问题描述
1.当面付支付时候scene参数值bar_code后面有空格
2.如果appid失效情况，不是返回sign签名

## 代码
涉及到 异步通知、同步通知 的问题，请将 nginx/Apache 的相关日志贴出来

**Comment by yansongda** [comment]
麻烦请详细说明下 第2点 ？

不是特别理解您的意思，因为签名只与密钥有关，和 appid 无关

感谢支持

**Comment by qianqian123** [comment]
出现这类错误时候["alipay_trade_pay_response"]=> array(4) { ["code"]=> string(5) "40003" ["msg"]=> string(23) "Insufficient Conditions" ["sub_code"]=> string(28) "isv.missing-signature-config" ["sub_msg"]=> string(62) "验签出错, 未配置对应签名算法的公钥或者证书" }，下面的验签方法会有问题，报数据越界

**Comment by yansongda** [comment]
第二点这个是您未配置支付宝密钥造成的，和 SDK 无关，详情请参考支付宝官方文档

感谢支持
