### ISSUE TITLE
我需要在 laravel 监听你的日志输出。在laravel 事件监听怎么做，但是官方Log 日志输出不影响

### ISSUE THREAD

**Issue by jasonccs** [yansongda/pay#806]
## 包版本号
V1.x

## 问题描述
我需要在 laravel 监听你的日志输出。在laravel 事件监听怎么做，但是官方Log 日志输出不影响

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
v1.x 不支持

**Comment by jasonccs** [comment]
2.X 支持你的日志输出监控吗&nbsp;


风起时，想你
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月11日(星期天) 晚上6:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yansongda/pay] 我需要在 laravel 监听你的日志输出。在laravel 事件监听怎么做，但是官方Log 日志输出不影响 (Issue #806)





 
v1.x 不支持
