### ISSUE TITLE
Hyperf 3.0 报错verify_wechat_sign

### ISSUE THREAD

**Issue by whs891015** [yansongda/pay#808]
php框架：Hyperf 3.0
插件版本：yansongda/pay3.4.0
php版本：8.0+
问题：vendor/yansongda/pay/src/Plugin/Wechat/LaunchPlugin.php(41): Yansongda\Pay\verify_wechat_sign()
解决过程:把同样配置文件(pay.php)以及证书文件，放在laravel框架中没有没有任何问题，但是放在Hyperf就报错 ，两个框架下都没有配置wechat_public_cert_path

**Comment by yansongda** [comment]
根据这个文档修改下试试：https://pay.yansongda.cn/docs/v3/wechat/callback.html#%E7%AC%AC%E4%B8%80%E4%B8%AA%E5%8F%82%E6%95%B0
