### ISSUE TITLE
建议verify_wechat_sign抛异常的时候把$body放到错误信息

### ISSUE THREAD

**Issue by aoding9** [yansongda/pay#811]
这个报错没有任何提示，后面到抛异常的地方，dd($body)才发现具体原因，是微信支付的金额以分为单位，我传了小数。
![image](https://github.com/yansongda/pay/assets/65276046/aa91d3be-35bc-4ed2-82f8-fc441b32daf9)

![image](https://github.com/yansongda/pay/assets/65276046/2e602781-55fb-45e6-ba4e-eedf293fabf1)

之前是没有任何提示的，排查问题不方便，现在把$body内容抛出了就好找多了

![image](https://github.com/yansongda/pay/assets/65276046/daaf6e36-4d1f-4af7-92a8-5b5417dd61d4)

**Comment by yansongda** [comment]
晚些时候优化下
