### ISSUE TITLE
代码有BUG，获取微信证书的时候，在返回结果为数组中调用方法

### ISSUE THREAD

**Issue by wlq673736503** [yansongda/pay#816]
## 包版本号
v3.4.2

## 问题描述

在使用 Pay::set(DirectionInterface::class, ArrayDirection::class); 后，会出错

Functions.php  239行， 在返回为数组的方法中， 调用另一个方法，报错

![image](https://github.com/yansongda/pay/assets/37679561/02fcd6d5-7796-4998-a8c9-80831710e93c)

前面返回的是数组，但是后面 在数组中调用 get('data', []) ，导致报错

![image](https://github.com/yansongda/pay/assets/37679561/8ce621a2-e93b-4d7c-92ce-9c409cb802ce)
 这里返回的数组，不是对象，导致报错

## 你的代码

![image](https://github.com/yansongda/pay/assets/37679561/6654b10b-1e1a-4370-adeb-4b174a903f69)

$result = Pay::wechat()->scan($order);

我是要生成微信二维码， 这个问题导致 支付宝和微信都不能生成二维码，但是API已经正确返回

## 报错详情

     "message": "Call to a member function get() on array",
    "exception": "Error",
    "file": "/www/wwwroot/code/cnbtb/self/lpshop/lpshop_pc/vendor/yansongda/pay/src/Functions.php",
    "line": 239,
    "trace": [
        {
            "file": "/www/wwwroot/code/cnbtb/self/lpshop/lpshop_pc/vendor/yansongda/pay/src/Functions.php",
            "line": 203,
            "function": "Yansongda\\Pay\\reload_wechat_public_certs"
        },

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
这里是有问题，后面会删掉这个 `ArrayDirection`

**Comment by yansongda** [comment]
是的，晚些时候我想想看怎么处理比较好

**Comment by yansongda** [comment]
> > 是的，晚些时候我想想看怎么处理比较好
> 
> 还有个问题 3.4.0 3.4.1 3.4.2 都一样
> 
> $result = Pay::alipay()->scan($order);
> 
> 支付宝生成二维码，好像不能用，我没去排查源码，
> 
> ```
> "msg" => "Business Failed"
> "code" => "40004"
> "sub_msg" => "ACCESS_FORBIDDEN"
> "sub_code" => "ACQ.ACCESS_FORBIDDEN"
> ```
> 
> 返回这个， 我现在用的 支付宝表单 没有问题，只有QR二维码有问题

这个你参考 支付宝，支付宝那边报错，看看是不是没权限
