### ISSUE TITLE
v2版本的商户转账到用户零钱接口微信官方以及修改了

### ISSUE THREAD

**Issue by JianJiaPHP** [yansongda/pay#817]
![image](https://github.com/yansongda/pay/assets/43328671/7a35ee45-867b-46c4-b383-f0057cae5bdf)

文档地址
https://pay.weixin.qq.com/docs/merchant/apis/batch-transfer-to-balance/transfer-batch/initiate-batch-transfer.html

**Comment by yansongda** [comment]
这个 yansongda/pay:v3 版本已经支持了，升级到 v3 即可，文档：https://pay.yansongda.cn/docs/v3/wechat/pay.html#%E8%B4%A6%E6%88%B7%E8%BD%AC%E8%B4%A6。

yansongda/pay:v2 版本不再进行更新

感谢支持
