### ISSUE TITLE
return_url参数无效

### ISSUE THREAD

**Issue by pasawu** [yansongda/pay#822]
## 包版本号

"yansongda/pay": "~3.2.0",

## 问题描述

return_url参数无效，微信手机网站支付，传了return_url，支付成功没有跳转return_url地址

## 你的代码

            $this->config['wechat']['default']['return_url'] = $return_url
            Pay::config($this->config);

            $order = [
                'out_trade_no' => $payInfo['pay_order_sn'],
                'description'  => $payInfo['description'],
                'amount'       => [
                    'total' => round($payInfo['pay_price'] * 100, 2),
                ],
                'scene_info'   => [
                    'payer_client_ip' => request()->ip(),
                    'h5_info'         => [
                        'type' => 'Wap',
                    ]
                ],
            ];

## 报错详情

无报错，可正常支付回调，只是支付成功没有跳转回来

## sdk 日志

无

## nginx/apache 日志
无

**Comment by yansongda** [comment]
微信的 v3 接口貌似取消这个功能了，支付成功后返回的是默认支付发起页，可以看看微信的文档
