### ISSUE TITLE
V3.3微信扫码支付异步回调的值是空的（null），thinkphp6.x/php7.4

### ISSUE THREAD

**Issue by bmkj** [yansongda/pay#823]
## 包版本号
V3.3
thinkphp6.x/php7.4

## 问题描述
V3.3微信扫码支付异步回调的值是空的（null）

## 你的代码
$wechat = Pay::wechat(config('wechat'));
$data = $wechat->callback();
此$data的值是空的（null）

## 报错详情
没有报错，就是$wechat->callback();获取不到值

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
单凭提供的信息，不知道啥原因，你自己调试看看吧

**Comment by bmkj** [comment]
> 单凭提供的信息，不知道啥原因，你自己调试看看吧

谢谢你，我开启支付日志后，看相关参数就解决了，我自己的问题
建议：微信支付回调的相关参数在文档写具体点，对新手有帮助，回调参数跟支付宝的回调参数是不一样的。

**Comment by yansongda** [comment]
> 谢谢你，我开启支付日志后，看相关参数就解决了，我自己的问题 建议：微信支付回调的相关参数在文档写具体点，对新手有帮助，回调参数跟支付宝的回调参数是不一样的。

你可以尝试帮忙提个PR，把你认为具体的部分写一下
