### ISSUE TITLE
3.3.0使用支付宝的二维码支付会抛异常: Verify Alipay Response Sign Failed

### ISSUE THREAD

**Issue by Hardy-chen** [yansongda/pay#829]
## 包版本号
~3.30

## 问题描述
使用支付宝扫码支付时, 会抛出异常: Verify Alipay Response Sign Failed
![image](https://github.com/yansongda/pay/assets/32698168/00c55d05-0dc5-4c9c-8667-81244f1d98c1)
同样的参数使用
![image](https://github.com/yansongda/pay/assets/32698168/72ef7705-a4ff-4144-9bd9-25e1b169565d)
可以正常弹出支付

## 你的代码
$channel_order = [
                    'out_trade_no' => $order->uuid,
                    'total_amount' => $order->amount,
                    'subject' => $order->subject,
                ];
                $response = Pay::alipay()->scan($channel_order);

## 报错详情
Verify Alipay Response Sign Failed

## 配置信息
![微信图片_20230710181951](https://github.com/yansongda/pay/assets/32698168/031631bc-5108-4216-8434-89c48c27a6bf)

**Comment by yansongda** [comment]
完整信息贴出来，你这没啥有用的信息啊

**Comment by Hardy-chen** [comment]
> 完整信息贴出来，你这没啥有用的信息啊

使用的laravel8.2版本, 引入您写好的包之后, 也就只有这一块用到了, 那些配置的证书跟属性使用app支付都能正常弹出支付且回调也都能正常使用, 换了scan就出现这个问题, 所以我怀疑是不是配置哪里有问题, 所以只贴了配置那一块的信息

**Comment by yansongda** [comment]
二维码支付的时候不涉及验证支付宝的秘钥，你是不是回调验签的时候出错了哦

自己检查下相关证书和秘钥把

**Comment by xiangming** [comment]
@Hardy-chen 最后解决了吗？我也遇到同样的问题。方便的话，把解决方法贴出来，让其他人参考。谢谢
