### ISSUE TITLE
对v2接口返回结果的疑问

### ISSUE THREAD

**Issue by krissss** [yansongda/pay#83]
## 包版本号
v2

## 问题描述
v1 对于 pay 的返回都是数组或者string，请问下为什么到 v2 调整成了部分为 `Response`？感觉对于v1版本的形式更加便于对返回结果进行处理后再返回。比如我的app接口是使用我特定的json格式的，或者我要使用xml的返回格式，你做成Response 的话就没法处理了。

**Comment by yansongda** [comment]
请参考 https://yansongda.gitbooks.io/pay/docs/others/faq.html

至于为什么调整到 `Response`或`Collection` 请自行体会，这里不做解释。

感谢支持
