### ISSUE TITLE
可以扫码成功，但是laravel定义的回调接口收不到支付宝回调消息

### ISSUE THREAD

**Issue by LPtrichor** [yansongda/pay#832]
## 包版本号
3.5.1

## 问题描述
可以扫码成功，但是laravel定义的回调接口收不到支付宝回调消息

## 你的代码
    'alipay' => [
        'default' => [
            // 必填-支付宝分配的 app_id
            'app_id' => env('ALIPAY_APP_ID'),
            // 必填-应用私钥 字符串或路径
            // 在 https://open.alipay.com/develop/manage 《应用详情->开发设置->接口加签方式》中设置
            'app_secret_cert' => env('ALIPAY_APP_SECRET_CERT'),
            // 必填-应用公钥证书 路径
            // 设置应用私钥后，即可下载得到以下3个证书
            'app_public_cert_path' => resource_path('alipay/appPublicCert.crt'),
            // 必填-支付宝公钥证书 路径
            'alipay_public_cert_path' => resource_path('alipay/alipayPublicCert.crt'),
            // 必填-支付宝根证书 路径
            'alipay_root_cert_path' => resource_path('alipay/alipayRootCert.crt'),
            'return_url' => 'http://127.0.0.1/api/alipay_return',
            'notify_url' => 'http://127.0.0.1/api/alipay_notify',
            // 选填-第三方应用授权token
            'app_auth_token' => '',
            // 选填-服务商模式下的服务商 id，当 mode 为 Pay::MODE_SERVICE 时使用该参数
            'service_provider_id' => '',
            // 选填-默认为正常模式。可选为： MODE_NORMAL, MODE_SANDBOX, MODE_SERVICE
            'mode' => Pay::MODE_NORMAL,
        ]
    ],

回调接口路由
![image](https://github.com/yansongda/pay/assets/78304742/8afc528b-3238-4e84-a6e7-a5213a043ea0)

## 报错详情
定义的接口收不到回调信息
判断理由是下面两个回调接口没有打印日志信息
![image](https://github.com/yansongda/pay/assets/78304742/63872888-2ecc-4f94-92cf-7e41231e70c5)

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
尝试检查 laravel 的 csrf 配置
