### ISSUE TITLE
Provider response Error[290] in /opt/www/vendor/yansongda/pay/src/Functions.php

### ISSUE THREAD

**Issue by echo-LuGuang** [yansongda/pay#841]
用了yansongda/pay这个包  微信支付异步通知偶尔会报错：
Provider response Error[290] in /opt/www/vendor/yansongda/pay/src/Functions.php

"hyperf/framework": "~2.2.0",
"yansongda/pay": "~3.2.0"

完整日志：
![FireShot Capture 003 - 检索分析 - 日志服务 - 控制台 - console cloud tencent com](https://github.com/yansongda/pay/assets/50095011/3352147a-0a05-4b87-a102-8630f4e0189b)

代码截图：
![d99eb22ad943d79b1b591b3978122e03](https://github.com/yansongda/pay/assets/50095011/58c0f642-804f-4f0b-8764-1f381c902182)

**Comment by echo-LuGuang** [comment]
![FireShot Capture 003 - 检索分析 - 日志服务 - 控制台 - console cloud tencent com](https://github.com/yansongda/pay/assets/50095011/82ff6106-8cf5-4d77-8cb0-71ed287a829f)

**Comment by echo-LuGuang** [comment]
通过trace看不出来具体是哪个方法抛的异常。  可以确定的配置没问题。 参数也没问题。 用postman请求接口，3次就会有1次这个报错。

**Comment by yansongda** [comment]
用的 hyperf？那别 `_force => true`。可以用多租户功能去实现

内部使用单例，你 force 之后会导致内存中的数据乱，可能会导致解密或验签出错

**Comment by echo-LuGuang** [comment]
okay
