### ISSUE TITLE
微信 WAP 支付跳转后出现商家参数格式有误

### ISSUE THREAD

**Issue by airycanon** [yansongda/pay#85]
微信的官方文档说是没有 referer 导致了的，是否可以在这里把 referer 传到 headers 中？
 https://github.com/yansongda/pay/blob/2809f3af38af0e7da757d6d93bc514b632d98295/src/Gateways/Wechat/WapGateway.php#L29

**Comment by yansongda** [comment]
抱歉，不清楚您的意思

**Comment by airycanon** [comment]
不好意思，是我理解有问题，已经解决了，我这里把遇到的问题详细描述一下。

#### 问题

在 Laravel 定义了一个路由
```php
class OrderController extends Controller {
    public function pay(){
        //其他业务逻辑
        return $wechat->wap($order)
    }
}
```
在浏览器新中访问该路由的 url，跳转到了微信支付的页面，提示`商家参数格式有误`，根据微信支付官方文档，是 `referer` 为空导致。
#### 原因
由于我是手动在浏览器中打开该 url ，所以 HTTP header 中的 referer 是空的，经过 302 跳转到微信后仍然是空的，放到 Web 应用中就不会出现这个问题了。

**Comment by mr-chen-king** [comment]
是在页面中放进去一个按钮然后在这个域名下点击这个按钮吗，那和在浏览器打开这个url不是一样的效果吗，你说的在web应用中打开是什么意思？

**Comment by mr-chen-king** [comment]
确实是这个原因必须是在域名下通过a 标签或者其他方式打开这个链接，不能直接在浏览器访问，否则referer获取不到
