### ISSUE TITLE
异步回调 提示 Undefined index: sign

### ISSUE THREAD

**Issue by song-wu** [yansongda/pay#852]
## 包版本号
v2.0

## 问题描述
订单回调 的时候 提示 这个错误 ：Undefined index: sign
Wechat_Notify {"status":false,"msg":"Undefined index: sign"}

## 你的代码
![image](https://github.com/yansongda/pay/assets/35286913/c5c5786e-2ae8-4064-8393-0bac654b4391)
 /**
     * @return array
     * @回调验证
     */
    public function verify(): array
    {
        $result = [
            'status' => true,
            'msg' => 'ok',
        ];
        try{
            $this->obj->verify();
            //支付成功
        }catch (\Exception $e){
            $result = [
                'status' => false,
                'msg' => $e->getMessage(),
            ];
        }
        return $result;
    }
Wechat_Notify {"status":false,"msg":"Undefined index: sign"}
## 报错详情
![image](https://github.com/yansongda/pay/assets/35286913/2842cea0-0dd8-4d2e-b269-7a94052db2b9)

## sdk 日志

dd
## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来
无

**Comment by yansongda** [comment]
升级到v3 吧

**Comment by song-wu** [comment]
> 升级到v3 吧

直接升级版本，有啥影响没，需不需要有些改动

**Comment by yansongda** [comment]
可以从 https://pay.yansongda.cn/docs/v3/upgrade/v3.0.html 这个地方开始看。升级到 v3 的最新版本

**Comment by song-wu** [comment]
> https://pay.yansongda.cn/docs/v3/upgrade/v3.0.html

好的，谢谢，我看看
