### ISSUE TITLE
Missing Wechat Config -- [mch_public_cert_path]

### ISSUE THREAD

**Issue by murodovCorp** [yansongda/pay#853]
yansongda/pay:~3.5.0 -vvv
guzzlehttp/guzzle:^7.0.1
hyperf/pimple:~2.2.0

Hi all. Please tell me am I doing something wrong or is this a bug? If I change Pay::get(ConfigInterface::class)->get('wechat') to config('pay.wechat') in the file yansongda/pay/src/Functions.php then everything works. Even if everything works after changing the file, when you try to go to wechat it gives the error: Invalid signature. Check
that it matches the signature on
open platform. To open the wechat application
I use flutter fluwx. 

![image](https://github.com/yansongda/pay/assets/99648284/1a7c08a0-1f7c-4084-a0fb-62ff1c357c10)
![image](https://github.com/yansongda/pay/assets/99648284/6c99380f-af62-42a2-ad22-ddbf7158378e)
![image](https://github.com/yansongda/pay/assets/99648284/af4635ce-59e0-4f8f-849d-c1421435f141)
![image](https://github.com/yansongda/pay/assets/99648284/768c9011-6297-44af-96b6-3f60ed3bedaa)
![image](https://github.com/yansongda/pay/assets/99648284/99d93b91-be02-4421-87f7-57adc750f82e)
![image](https://github.com/yansongda/pay/assets/99648284/63098f6b-e4c1-4489-9523-f18891640753)

**Comment by yansongda** [comment]
检查你代码中配置文件
