### ISSUE TITLE
v2版本查询订单，提示：请求中含有未在API文档中定义的参数

### ISSUE THREAD

**Issue by zoudaren** [yansongda/pay#862]
## 包版本号
v2

## 问题描述
查询订单 提示：请求中含有未在API文档中定义的参数

## 你的代码
 public function Weixinfind()
    {
        $order = [
            'out_trade_no' => '1697597637',
        ];

        $result = Pay::wechat($this->config)->find($order);

        var_dump($result);
        
    }

## 报错详情
Yansongda\Pay\Exceptions\GatewayException #4

ERROR_GATEWAY: Get Wechat API Error:请求中含有未在API文档中定义的参数
/mnt/www/sswk/dayrui/Vendor/yansongda/pay/src/Gateways/Wechat/Support.php（389）

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
升级到 v2 最新版。

PS：如果有条件，请尽快升级到 v3 版本
