### ISSUE TITLE
微信转账提示参数错误

### ISSUE THREAD

**Issue by dogeow** [yansongda/pay#863]
之前已经接过微信支付（APP支付），运行一段时间了，现在需要弄微信提现。

提示：

{"code":"PARAM_ERROR","detail":{"location":"body","value":0},"message":"输入源“/body/appid”映射到值字段“商户appid”字符串规则校验失败，字符数 0，小于最小值 1"}

代码：

 Pay::wechat()->transfer([
                'out_batch_no' => $orderNo,
                'batch_name' => $name,
                'batch_remark' => '-',
                'total_amount' => $money,
                'total_num' => 1,
                'transfer_detail_list' => [
                    [
                        'openid' => $user->uuid,
                        'out_detail_no' => $orderNo,
                        'transfer_amount' => $money,
                        'transfer_remark' => $name,
                    ],
                ],
            ])

appid 之前在 pay.php 有加了的。

            'appid' => 'wx9638a835ccd4ea**',
            'app_id' => 'wx9638a835ccd4ea**',

**Comment by yansongda** [comment]
参数里加 `'_type' => 'app'` 或者 把配置文件里的 `mp_app_id` 填上
