### ISSUE TITLE
同步通知 return_url 如何不要附带参数？

### ISSUE THREAD

**Issue by shunhua** [yansongda/pay#864]
现在 return_url 默认附带支付参数  类似于：
`https://yansongda.cn/return.php?charset=utf-8&out_trade_no=20231020164628915774&method=alipay.trade.page.pay.return&total_amount=0.01&sign=hHW1CaEhVKauMTkUNY%2B7FET2x%2BuNE5S8FMyrQ26prGWVSQxRcjjSW3ibvKDrR7XmxwfHl24ki%2BShjAk3rZUPnFCHv%2Fz1ZEn0HYHAttULzHCRYWaqztjb81K9HI%2BiRrlDaadcJXhiKSUmqDilAD%2BhNxd0saGzPb1RUZCUOcctOjNlk%2FC7CiYKShlvwdBL8PZjwbvMYuuso8t9F8x2uili8Rw%2Bc%2FVxkwOCJiHfhYghuvPhYlIxHRVeGyAhbuy0LfC4%2B1%2BSkAfFSyiGHfqXRTQuVFcFUGnGlBNpPEZ%2Bh3pZHNd9SV5TOZEKNpd03mwgQhRp9JkrGiN0tWj4OVAIRogB5w%3D%3D&trade_no=2023102022001456211452442381&auth_app_id=2021003174651366&version=1.0&app_id=2021003174651366&sign_type=RSA2&seller_id=2088541548358182&timestamp=2023-10-20+16%3A46%3A58`

新配置`$order['return_url'] = 'https://www.baidu.com/';` 后还是默认附带
想要直接跳转 https://www.baidu.com/
怎么才能不附带参数？

**Comment by yansongda** [comment]
这个是 支付宝 那边的规范，用于同步支付通知。

详情请可以移步支付宝官方文档。

**Comment by shunhua** [comment]
> 这个是 支付宝 那边的规范，用于同步支付通知。
> 
> 详情请可以移步支付宝官方文档。

这个参数能去掉吗？有没有可能去掉？之前弄过吗？

**Comment by shunhua** [comment]
官方说 去不掉
