### ISSUE TITLE
大佬，麻烦指点一下如何获取微信支付的wechat_public_cert_path呗

### ISSUE THREAD

**Issue by wocall** [yansongda/pay#865]
// 选填-微信平台公钥证书路径, optional，强烈建议 php-fpm 模式下配置此参数
                'wechat_public_cert_path' => [
                    '45F59D4DABF31918AFCEC556D5D2C6E376675D57' => __DIR__.'/Cert/wechatpay_45F***D57.pem',
                ],

感谢感谢！

**Comment by yansongda** [comment]
看文档
