### ISSUE TITLE
错误提示：微信支付 AppID不存在,请检查后再试

### ISSUE THREAD

**Issue by wocall** [yansongda/pay#867]
## 问题描述
一切配置停当，支付宝支付正常，微信支付提示如题错误，不知该如何修改

## 你的代码
```php
          'mch_id' => '1524XXXX',
            // 必填-商户秘钥
            'mch_secret_key' => 'DuoXXXXX',
            // 必填-商户私钥 字符串或路径
            'mch_secret_cert' => base_path().'/config/wechat/apiclient_key.pem',
            // 必填-商户公钥证书路径
            'mch_public_cert_path' => base_path().'/config/wechat/apiclient_cert.pem',
            // 必填
            'notify_url' => '',
            // 公众号 的 app_id
           'mp_app_id' => '',
            // 选填-小程序 的 app_id
            'mini_app_id' => 'wx1a29XXXXX',
            // 选填-app 的 app_id
            'app_id' => '',

``` 

## 报错详情

微信支付 AppID不存在,请检查后再试

**Comment by yansongda** [comment]
小程序支付，在支付参数里加 `['_type' => 'mini']`，否则默认使用 公众号的 app_id

**Comment by wocall** [comment]
> 小程序支付，在支付参数里加 `['_type' => 'mini']`，否则默认使用 公众号的 app_id
`// 必填
            'notify_url' => '',
            // 公众号 的 app_id
            'mp_app_id' => '',
            // 选填-小程序 的 app_id
            '_type' => 'mini',
            'mini_app_id' => 'wx1a29XXXXX',
            // 选填-app 的 app_id
            'app_id' => '',
            // 选填-合单 app_id
            'combine_app_id' => '',
            // 选填-合单商户号
            'combine_mch_id' => '',
            // 选填-服务商模式下，子公众号 的 app_id`


是这样写么？加上后，依然还是这个错误提示

**Comment by yansongda** [comment]
```php
$order = [
    '_type' => 'mini',
    ...
];

Pay::wechat()->mini($order);
```

**Comment by wocall** [comment]
> ```
> $order = [
>     '_type' => 'mini',
>     ...
> ];
> 
> Pay::wechat()->mini($order);
> ```

```
        $order = [
	        '_type' => 'mini',
            'out_trade_no' => $orderId,
            'description' => $subject,
            'amount' => [
                'total' => (float)$totalAmount * 100,
            ],
        ];
        //$result = Pay::wechat()->scan($order);
        $result = Pay::wechat()->mini($order);

```
大佬，我这修改后，然后一堆报错：（

**Comment by wocall** [comment]
> ```
> $order = [
>     '_type' => 'mini',
>     ...
> ];
> 
> Pay::wechat()->mini($order);
> ```

忘了贴报错内容了：

Yansongda\Pay\Exception\InvalidResponseException in /yansongda/pay/src/Functions.php:204
Stack trace:
