### ISSUE TITLE
微信刷卡支付后响应校验header错误

### ISSUE THREAD

**Issue by dyanwang** [yansongda/pay#869]
## 包版本号
3.5.0

## 问题描述
微信刷卡支付后，由于刷卡支付非v3版本接口，因此header头中无Wechatpay-Signature 等平台证书校验相关信息，因此在调用verify_wechat_sign时报错

## 你的代码
`$order = [
            "auth_code" => "134214981492345911",
            "body" => "AAA",
            "out_trade_no" => "93852311038293",
            "spbill_create_ip" => "127.0.0.1",
            "total_fee" => 1
        ];
$pay = Pay::wechat()->pos($order);
`

## 报错详情
![图片](https://github.com/yansongda/pay/assets/9457852/044f21ee-f513-4c5f-8ed8-eec59bdb7636)

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
v3 版本目前确实对 微信支付v2 的 API 支持的不是很好，也没有经过全面的测试过

如果重度依赖 微信支付v2 的功能，建议还是用 Payv2 版本。目前也不大想再花时间去兼容。

不过，如果您有时间有需求，欢迎 PR
