### ISSUE TITLE
类缺失

### ISSUE THREAD

**Issue by scarecrowpqs** [yansongda/pay#87]
## 包版本号
2.x

## 问题描述
Yansongda\Supports\Collection; 
Yansongda\Supports\Config; 
Yansongda\Supports\Str;
这三个类在你的Alipay文件中使用了，但是却找不到它的源文件。
## 代码
涉及到 异步通知、同步通知 的问题，请将 nginx/Apache 的相关日志贴出来

**Comment by yansongda** [comment]
请通过 composer 安装，谢谢
