### ISSUE TITLE
商家扣款

### ISSUE THREAD

**Issue by yang-chun** [yansongda/pay#872]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yansongda** [comment]
帮忙把描述写清楚，还有支付宝对应的 API 页面

**Comment by yang-chun** [comment]
场景是用户签约协议,然后支付,次月自己续费 ,支付宝接口

**Comment by yang-chun** [comment]
https://opendocs.alipay.com/open/08bpuc?pathHash=74036bac

**Comment by gsvampire** [comment]
fous
