### ISSUE TITLE
v3版本报错Config Error

### ISSUE THREAD

**Issue by mcc7178** [yansongda/pay#879]
## 问题描述
thinkphp框架

## 你的代码
$order = [
            'out_batch_no' => time() . '',
            'batch_name' => 'subject-测试',
            'batch_remark' => 'test',
            'total_amount' => 1,
            'total_num' => 1,
            'transfer_detail_list' => [
                [
                    'out_detail_no' => time() . '-1',
                    'transfer_amount' => 1,
                    'transfer_remark' => 'test',
                    'openid' => 'xxxxx',
                ],
            ],
        ];

        Pay::config($this->config2);
        $result = Pay::wechat()->transfer($order);

## 报错详情

[3004] InvalidConfigException in AbstractProvider.php line 110
Config Error

$http = Pay::get(HttpClientInterface::class);

        if (!$http instanceof ClientInterface) {
            throw new InvalidConfigException(Exception::HTTP_CLIENT_CONFIG_ERROR);
        }
## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
`composer require guzzlehttp/guzzle:^7.0`

**Comment by mcc7178** [comment]
php 7.4.3
Using version ^2.1 for hyperf/pimple
Using version ^6.5 for guzzlehttp/guzzle
Using version ^3.3 for yansongda/pay

**Comment by mcc7178** [comment]
现有版本是这样的，php 7.4.3
Using version ^2.1 for hyperf/pimple
Using version ^6.5 for guzzlehttp/guzzle
Using version ^3.3 for yansongda/pay
