### ISSUE TITLE
YII2框架中是否可以用return $alipay->success()这样的用法

### ISSUE THREAD

**Issue by haohetao** [yansongda/pay#88]
## 包版本号
2.x版本
## 问题描述
YII2框架中是否可以用return $alipay->success()这样的用法

**Comment by yansongda** [comment]
YII2 框架我暂时没用过，不过您可以试一试看看

感谢支持

**Comment by haohetao** [comment]
结果是yii会把包括http头部的内容全部打印到页面上，我猜是调用了response对象的toString()方法

**Comment by yansongda** [comment]
感谢支持，感谢总结
