### ISSUE TITLE
新增需求：银联条码支付

### ISSUE THREAD

**Issue by involvements** [yansongda/pay#888]
希望能够增加银联的条码支付，这是目前比较容易申请的接口，且同时支持银联支付宝微信

文档是：https://up.95516.com/open/openapi/wiki?index=2&chapter=1

**Comment by yansongda** [comment]
@involvements 你有测试账号么？

**Comment by involvements** [comment]
@yansongda 

https://up.95516.com/open/openapi/doc?index_1=2&index_2=1&chapter_1=271&chapter_2=283

测试账户

测试商户号 QRA29045311KKR1 
测试密钥 979da4cfccbae7923641daa5dd7047c2 

测试商户号注意事项：
1、测试金额应为小额，建议单笔测试交易10元以内；
2、正向测试交易完成后，应当日完成对应反向交易（撤销或退款）；
3、条码支付前置平台不提供事后人工退款服务；


用测试帐户支付后需要自行当天内调用退款接口退款，不然这个钱就退不回来了😄，因为它是T+1自动提现了
