### ISSUE TITLE
openssl_verify(): supplied key param cannot be coerced into a public key

### ISSUE THREAD

**Issue by haohetao** [yansongda/pay#89]
## 包版本号
Yansongda\Pay 2.0.22
php7.1,nginx1.10.3,ubuntu16.04,yii2.0.14.1

## 问题描述
同步返回，openssl_verify()函数报错

## 代码
    public static function verifySign(array $data, $publicKey = null, $sync = false, $sign = null): bool
    {
        if (is_null($publicKey)) {
            throw new InvalidConfigException('Missing Alipay Config -- [ali_public_key]', 2);
        }

        if (Str::endsWith($publicKey, '.pem')) {
            $publicKey = openssl_pkey_get_public($publicKey);
        } else {
            $publicKey = "-----BEGIN PUBLIC KEY-----\n".
                wordwrap($publicKey, 64, "\n", true).
                "\n-----END PUBLIC KEY-----";
        }

        $sign = $sign ?? $data['sign'];

        $toVerify = $sync ? mb_convert_encoding(json_encode($data, JSON_UNESCAPED_UNICODE), 'gb2312', 'utf-8') :
                            self::getSignContent($data, true);

        return openssl_verify($toVerify, base64_decode($sign), $publicKey, OPENSSL_ALGO_SHA256) === 1;
    }

## 报错详情
$_GET = [
    'total_amount' => '0.01',
    'timestamp' => '2018-03-13 18:41:20',
    'sign' => 'JCbx0qaUfiiWP+x0Xj0tDjVWrGcLfoum2BIuUZZY94UEarzHad9v4NKc34+ALm2rGK0cklkWBukg9l7f2zW0tZG0vEwkU1BSnYWPyQLYNiDH3Wb/w/KeXM7xZsKacWRo4b9NsJrOd5qCHwWCdeUk6tmdvrAn+M/44W/NfpDlv3ixaKM5VryBH0XFVRafb9eqNBK3hauoIeyyERo/OsJBgtnMDuM0l9SVj/A4fo/B8zdI37QwwmJgwkkbGXgFg0KwOGlhUaXVyeCb/4ZihY3zmzqHWeRE1V1zgHT/+KNQjd+oQ/vjVwQ5qcpaB1L1lC/GXRum2MPQsd4iucynYq9nyQ==',
    'trade_no' => '2018031321001004720534086550',
    'sign_type' => 'RSA2',
    'auth_app_id' => '2018030702330543',
    'charset' => 'GBK',
    'seller_id' => '2088302769686131',
    'method' => 'alipay.trade.wap.pay.return',
    'app_id' => '2018030702330543',
    'out_trade_no' => '00000035',
    'version' => '1.0',
];

**Comment by haohetao** [comment]
问题已经解决，是配置问题，稍后总结一下配置要点

**Comment by haohetao** [comment]
打开蚂蚁金服开放平台
开发者中心-》网页&移动应用-》应用信息

使用阿里提供的RSA生成工具，是个java程序
生成密钥选项卡
选择PKCS1，密钥长度2048
点击生成密钥
生成的密钥自动放入RSA密钥文件夹中
在接口加签方式一栏设置“应用公钥”，然后在弹出的窗口中直接点击下载支付宝公钥或者稍后查看支付宝公钥并下载

传递密钥的时候最好通过文件的方式，不要直接通过聊天窗口发送，设置公钥以后要逐字比对确认设置成功，源代码中设置时也同样。
源代码中设置的是商户应用私钥和支付宝公钥，是appid不是pid

**Comment by yansongda** [comment]
感谢支持，感谢总结
