### ISSUE TITLE
alipay支付，当subject为中文时候，下单失败。

### ISSUE THREAD

**Issue by shizhice** [yansongda/pay#9]
Yansongda\Pay\Gateways\Alipay\Alipay文件219行，当subject为中文时，会导致下单失败。去掉JSON_UNESCAPED_UNICODE参数后，问题解决。

![image](https://user-images.githubusercontent.com/13327958/30103424-35c71d94-9325-11e7-9f5d-185a4a0ff285.png)

**Comment by yansongda** [comment]
只有使用 刷卡和扫码 两种支付方法时才会调用这个函数，请问您是在这两种支付方式中下单失败吗？还有请问下报错信息是什么呢？

**Comment by shizhice** [comment]
我刚完成扫码功能，发现这个问题。刷卡，目前没有需求。这个是报错信息

```
Yansongda\Pay\Exceptions\GatewayException: get result error: - 
```

我测试了您的代码，阿里返回的错误代码如下

```
{"code":"40002","msg":"Invalid Arguments","sub_code":"isv.invalid-signature",...}
```
具体内容，不方便截图，请见谅

**Comment by yansongda** [comment]
好的，感谢您的支持，我晚些时候重现下，确定将进行修复。

目测应该是因为支付宝不支持中文，不过我看文档，上面是支持中文的，奇怪。

**Comment by shizhice** [comment]
恩恩，好的。

**Comment by yansongda** [comment]
已经修复。我想是因为支付宝需要支持 gb2312 和 utf8 两种格式，所以不支持解码时使用 utf8 的中文造成的这个问题。

同时，还发现支付宝服务器返回编码居然是 gb2312 格式。也修复了这个问题。

感谢您的支持！

**Comment by shizhice** [comment]
👍
