### ISSUE TITLE
yii2日志中报Headers already sent的错误，不影响正常支付

### ISSUE THREAD

**Issue by haohetao** [yansongda/pay#90]
## 包版本号
2.x

## 问题描述
日志中报错，输出正常

## 代码

return $alipay->send();// laravel 框架中请直接 `return $alipay`
以及
return $alipay->success()->send();// laravel 框架中请直接 `return $alipay->success()`

## 报错详情
2018-03-14 02:58:38 [110.75.248.100][-][-][error][yii\web\HeadersAlreadySentException] yii\web\HeadersAlreadySentException: Headers already sent in /var/www/easy2eat/vendor/symfony/http-foundation/Response.php on line 354. in /var/www/easy2eat/vendor/yiisoft/yii2/web/Response.php:366
Stack trace:
#0 /var/www/easy2eat/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#1 /var/www/easy2eat/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Response->send()
#2 /var/www/easy2eat/frontend/web/index.php(23): yii\base\Application->run()
#3 {main}

**Comment by haohetao** [comment]
报错的原因是send()方法关闭了http输出流，导致yii2处理响应输出的时候报错。我的解决方法是用如下代码
            $alipay = Payment::aliPay()->wap($order);
            return $alipay->getContent();
以及
        return $alipay->success()->getContent();

**Comment by yansongda** [comment]
感谢支持，感谢总结
