### ISSUE TITLE
唤起支付和下载验签都会报同样的问题decrypt_wechat_resource_aes_256_gcm

### ISSUE THREAD

**Issue by kkkreset** [yansongda/pay#908]
## 包版本号
PHP 8.2.3
Laravel 10.38.1

## 问题描述
请求返回验签错误

## 你的代码
 \Yansongda\Pay\Pay::config(config('pay'));
        $params = [

            '_config' => 'default' // 多租户配置时使用

        ];
 \Yansongda\Pay\get_wechat_public_certs($params);

## 报错详情
Yansongda\Pay\decrypt_wechat_resource_aes_256_gcm(): Return value must be of type array|string, bool returned

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
检查微信 v3 秘钥是否正确

**Comment by kkkreset** [comment]
mch_secret_cert: apiclient_key.pem
mch_public_cert_path: apiclient_cert.pem

**Comment by yansongda** [comment]
mch_secret_key

**Comment by kkkreset** [comment]
好像不是这个问题，公众号的mp报这个问题，使用微信小程序测试也是一样的。跟PHP版本有关系吗. 我通过申请的密钥，wechat_public_cert_path这个也申请不了都是报签名解析问题
