### ISSUE TITLE
微信查单文档错误

### ISSUE THREAD

**Issue by bref0** [yansongda/pay#931]
## 包版本号

"yansongda/pay": "~3.5.0",
## 问题描述

文档上是

$order = [
    'transaction_id' => '1217752501201407033233368018',
];
// $order = '1217752501201407033233368018';

$result = Pay::wechat()->find($order);
## 你的代码
$order = '1217752501201407033233368018';
$result = Pay::wechat()->find($order);
改成
$order = [
    'out_trade_no' => '1217752501201407033233368018',
];
就没问题了
## 报错详情
微信订单号非法

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
https://github.com/yansongda/pay/blob/v3.5.3/src/Provider/Wechat.php#L69

传递 string 的情况下，默认使用微信的 `transaction_id `，并非 `out_trade_no `。
