### ISSUE TITLE
"yansongda/pay": "^3.6"  签名异常: 微信签名为空

### ISSUE THREAD

**Issue by YouZiXiL** [yansongda/pay#939]
## 包版本号
"yansongda/pay": "^3.6"

## 问题描述
小程序出现  3.5->3.6  出现   签名异常: 微信签名为空

## 报错详情
 签名异常: 微信签名为空

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
先尝试升级到最新版试试

**Comment by YouZiXiL** [comment]
已经尝试了  3.6版本确实不行

**Comment by YouZiXiL** [comment]
换回3.5版本可以了

**Comment by yansongda** [comment]
composer info 麻烦发一下，如果能提供 sdk 的日志话最好了
