### ISSUE TITLE
小程序根据prepayId发起支付

### ISSUE THREAD

**Issue by ajiader** [yansongda/pay#942]
根据文档调用小程序接口返回prepayId存入数据库，微信官方文档说 prepayId 两小时内有效
也就是说可以直接用prepayId发起支付，文档貌似没有讲这个，看源码有这个getInvokeConfig方法 但是不知道怎么调用
![image](https://github.com/yansongda/pay/assets/4979798/75b6b0b0-15c3-4285-aed7-6ad965dc41ea)

**Comment by yansongda** [comment]
直接 `Pay::wechat()->app($order);` 即可，SDK 内部已经自动处理了，无需关系 prepay_id 。

详情：https://pay.yansongda.cn/docs/v3/wechat/pay.html#app-%E6%94%AF%E4%BB%98

如果感兴趣可参考源码：https://github.com/yansongda/pay/blob/master/src/Shortcut/Wechat/AppShortcut.php
