### ISSUE TITLE
微信支付异步通知希望增加对签名探测流量的处理

### ISSUE THREAD

**Issue by shp1102** [yansongda/pay#945]
具体查看官方文档：https://pay.weixin.qq.com/docs/merchant/development/interface-rules/signature-verification.html

**Comment by yansongda** [comment]
不需要特殊处理吧？

错误签名 `Pay::wechat()->callback()` 会报错的，业务系统自行捕获异常即可

**Comment by shp1102** [comment]
> 不需要特殊处理吧？
> 
> 错误签名 `Pay::wechat()->callback()` 会报错的，业务系统自行捕获异常即可

V2版的需要处理下

**Comment by yansongda** [comment]
您发的这文档是 V3 的

![截屏2024-03-05 12 18 01](https://github.com/yansongda/pay/assets/11869114/1ff14229-7a3e-43c1-a576-897258d86393)

**Comment by yansongda** [comment]
同时，V2 版不做新功能开发，条件允许的情况下，麻烦尽快升级到 最新版
