### ISSUE TITLE
支付宝怎么设置密钥模式（非证书模式）

### ISSUE THREAD

**Issue by bennkwok** [yansongda/pay#949]
如果我不配证书，会报“配置异常: 缺少支付宝配置 -- [app_public_cert_path]”
但是我的支付宝是密钥模式，不需要用到根证书

**Comment by yansongda** [comment]
v3 版只支持 证书模式，如非证书，请使用 v2 版

同时，请尽快升级至 v3 版

**Comment by bennkwok** [comment]
> v3 版只支持 证书模式，如非证书，请使用 v2 版
> 
> 同时，请尽快升级至 v3 版

好的谢谢
