### ISSUE TITLE
Pay::wechat(config('pay.wechat'))->mp($order)

### ISSUE THREAD

**Issue by ZhuRongJian** [yansongda/pay#95]
## 问题描述
Pay::wechat(config('pay.wechat'))->mp($order)的结果中是否包含paySign 参数？

在文档中没有标出来 只有5个参数
 // $pay->appId
        // $pay->timeStamp
        // $pay->nonceStr
        // $pay->package
        // $pay->signType

**Comment by yansongda** [comment]
看文档，谢谢
