### ISSUE TITLE
关于微信支付配置wechat_public_cert_path的问题

### ISSUE THREAD

**Issue by MaxCode-fan** [yansongda/pay#958]
示例地址: https://pay.yansongda.cn/docs/v3/quick-start/init.html
官方给的配置示例中: 
// 选填-微信平台公钥证书路径, optional，强烈建议 php-fpm 模式下配置此参数
    'wechat_public_cert_path' => [
        '45F59D4DABF31918AFCEC556D5D2C6E376675D57' => __DIR__.'/Cert/wechatPublicKey.crt',
    ],
    
   后缀是.crt文件,而我从微信官方下载下来的微信平台公钥是.pem后缀.影响使用嘛?
   微信官方平台公钥下载文档地址: https://github.com/wechatpay-apiv3/wechatpay-php/tree/main/bin
   
  还有一个是 没看到微信初始化配置示例中没有配置公众号开发者秘钥的地方?请问是在哪里配置的?

**Comment by yansongda** [comment]
> 后缀是.crt文件,而我从微信官方下载下来的微信平台公钥是.pem后缀.影响使用嘛?

不影响。同时，建议直接使用 Pay 去生成 公钥，减少心智

> 还有一个是 没看到微信初始化配置示例中没有配置公众号开发者秘钥的地方?请问是在哪里配置的?

mch_secret_key。如果方便可以仔细多看几遍文档

**Comment by MaxCode-fan** [comment]
'wechat' => [
        'default' => [
            // 必填-商户号，服务商模式下为服务商商户号
            // 可在 https://pay.weixin.qq.com/ 账户中心->商户信息 查看
            'mch_id' => '',
            // 选填-v2商户私钥
            'mch_secret_key_v2' => '',
            // 必填-v3 商户秘钥
            // 即 API v3 密钥(32字节，形如md5值)，可在 账户中心->API安全 中设置
            'mch_secret_key' => '',
            // 必填-商户私钥 字符串或路径
            // 即 API证书 PRIVATE KEY，可在 账户中心->API安全->申请API证书 里获得
            // 文件名形如：apiclient_key.pem
            'mch_secret_cert' => '',
            // 必填-商户公钥证书路径
            // 即 API证书 CERTIFICATE，可在 账户中心->API安全->申请API证书 里获得
            // 文件名形如：apiclient_cert.pem
            'mch_public_cert_path' => '',
            // 必填-微信回调url
            // 不能有参数，如?号，空格等，否则会无法正确回调
            'notify_url' => 'https://yansongda.cn/wechat/notify',
            // 选填-公众号 的 app_id
            // 可在 mp.weixin.qq.com 设置与开发->基本配置->开发者ID(AppID) 查看
            'mp_app_id' => '2016082000291234',
            // 选填-小程序 的 app_id
            'mini_app_id' => '',
            // 选填-app 的 app_id
            'app_id' => '',
            // 选填-服务商模式下，子公众号 的 app_id
            'sub_mp_app_id' => '',
            // 选填-服务商模式下，子 app 的 app_id
            'sub_app_id' => '',
            // 选填-服务商模式下，子小程序 的 app_id
            'sub_mini_app_id' => '',
            // 选填-服务商模式下，子商户id
            'sub_mch_id' => '',
            // 选填-微信平台公钥证书路径, optional，强烈建议 php-fpm 模式下配置此参数
            'wechat_public_cert_path' => [
                '45F59D4DABF31918AFCEC556D5D2C6E376675D57' => __DIR__.'/Cert/wechatPublicKey.crt',
            ],
            // 选填-默认为正常模式。可选为： MODE_NORMAL, MODE_SERVICE
            'mode' => Pay::MODE_NORMAL,
        ]
    ]
    
    大哥,mch_secret_key不是v3 商户秘钥嘛  我说的是公众号秘钥的配置字段

**Comment by MaxCode-fan** [comment]
> > 后缀是.crt文件,而我从微信官方下载下来的微信平台公钥是.pem后缀.影响使用嘛?
> 
> 不影响。同时，建议直接使用 Pay 去生成 公钥，减少心智
> 
> > 还有一个是 没看到微信初始化配置示例中没有配置公众号开发者秘钥的地方?请问是在哪里配置的?
> 
> mch_secret_key。如果方便可以仔细多看几遍文档

大哥,mch_secret_key不是v3 商户秘钥嘛  我说的是公众号秘钥的配置字段

**Comment by yansongda** [comment]
公众号秘钥 和支付有啥关系？

**Comment by MaxCode-fan** [comment]
> 公众号秘钥 和支付有啥关系？

哪个jsapi支付好像需要获取授权来着,好像要用到公众号秘钥来换取openID来着
https://developers.weixin.qq.com/doc/offiaccount/OA_Web_Apps/Wechat_webpage_authorization.html

**Comment by MaxCode-fan** [comment]
早些时候写微信支付的时候是需要换的 我记着 现在改版了 获取code的时候也返回openId了?

**Comment by MaxCode-fan** [comment]
> 公众号秘钥 和支付有啥关系？

我理解了大佬,哪个openID需要我们这边自己换取入参,这个扩展库是没有处理这个的
openid, 因为里面授权换code回跳地址我们要自己处理,是这样的吧. 我给整迷糊了 以为扩展库处理呢
