### ISSUE TITLE
微信异步获取不到通知

### ISSUE THREAD

**Issue by bref0** [yansongda/pay#96]
## 包版本号
1.0

## 问题描述
微信异步获取不到通知

## 代码
涉及到 异步通知、同步通知 的问题，请将 nginx/Apache 的相关日志贴出来
异步回调方法内容：
        file_put_contents(Env::get('root_path') . 'public/notify.txt', '收到微信回调', FILE_APPEND);
        file_put_contents(Env::get('root_path') . 'public/notify.txt', json_encode(input()), FILE_APPEND);
        file_put_contents(Env::get('root_path') . 'public/notify.txt', '收到微信回调结束', FILE_APPEND);
notify.txt文件内容
        收到微信回调[]收到微信回调结束[]
## 报错详情
微信异步获取不到通知

**Comment by yansongda** [comment]
涉及到 异步通知、同步通知 的问题，请将 nginx/Apache 的相关日志贴出来

请按格式 ISSUE

谢谢

**Comment by bref0** [comment]
解决了 post和get都是获取不到的 file_put_contents php://input 是可以获取到 。结帖~~
