### ISSUE TITLE
支付宝APP支付无法使用

### ISSUE THREAD

**Issue by fengxiaolei** [yansongda/pay#960]
## 包版本号
3.6.4

## 问题描述
按照文档提供的代码这边使用APP支付的时候一直报错，无法唤起支付
![image](https://github.com/yansongda/pay/assets/8679403/f0fe5ea7-b3de-4d77-90f3-f388b7a635fc)

## 报错详情
![image](https://github.com/yansongda/pay/assets/8679403/6c22c51f-8cfa-4fb0-b569-f8777af83b1c)

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by fengxiaolei** [comment]
使用的代码 就是文档里面的例子
![image](https://github.com/yansongda/pay/assets/8679403/525354a2-6764-44ef-8175-ddb576f77d9e)

**Comment by zuoWinger** [comment]
<img width="492" alt="image" src="https://github.com/yansongda/pay/assets/32150068/32aef43d-a7d6-4be1-853e-dd508f520a12">
你试试这样呢，能用吗

**Comment by fengxiaolei** [comment]
![image](https://github.com/yansongda/pay/assets/8679403/17c6cd13-ce65-4a5b-91e5-726fc97373f8)
 试过了不行，而且最新版本退款也有问题了，目前无法退款

**Comment by fengxiaolei** [comment]
![image](https://github.com/yansongda/pay/assets/8679403/11b971ad-8237-445b-bed6-195bb595e27f)
退款的s时候报这个错误
