### ISSUE TITLE
3.3版本怎么没有微信红包功能接口？

### ISSUE THREAD

**Issue by hzysoft** [yansongda/pay#962]
3.3版本怎么没有微信红包功能接口？
因为已经做了laravel集成，不想随意更改版本
如果自己扩展，如何扩展红包功能？

感谢赐教！

**Comment by yansongda** [comment]
可以参考 https://github.com/yansongda/pay/tree/master/src/Plugin/Wechat/V2 里的插件机制自行实现一些 红包的插件

同时，欢迎 PR 进来

**Comment by yansongda** [comment]
close by: #973
