### ISSUE TITLE
Missing Wechat Config -- [mch_public_cert_path]

### ISSUE THREAD

**Issue by xxj-moxiaom** [yansongda/pay#963]
## 包版本号
"yansongda/pay": "^3.2.0"

## 问题描述
微信h5支付 调用报Missing Wechat Config -- [mch_public_cert_path]
私钥和公钥都能获取到
## 你的代码
<img width="874" alt="image" src="https://github.com/yansongda/pay/assets/30680453/cfac33a7-bd38-4b83-9481-564fe13d1520">

## 报错详情

![Uploading image.png…]()

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
`$config = config('pay')`

多租户按照多租户的形式来配置

**Comment by xxj-moxiaom** [comment]
我不是多租户啊

**Comment by xxj-moxiaom** [comment]
我不是多租户啊

**Comment by xxj-moxiaom** [comment]
> `$config = config('pay')`
> 
> 多租户按照多租户的形式来配置

我不是多租户呀

**Comment by yansongda** [comment]
不是多租户你改 app_id 那些干啥

**Comment by xxj-moxiaom** [comment]
这个网络是真差 我加qq群里 能通过一下么

**Comment by yansongda** [comment]
$config = config('pay')

你看看文档吧，这样传 配置参数 就行了

**Comment by xxj-moxiaom** [comment]
这个网络是真差 我加qq群里 能通过一下么

**Comment by xxj-moxiaom** [comment]
> $config = config('pay')
> 
> 你看看文档吧，这样传 配置参数 就行了

好了 我知道了，原来只需要config('pay')，而不是自足聪明的config('pay.wechat.default')

**Comment by xxj-moxiaom** [comment]
正确姿势config('pay')✅
错误姿势config('pay.wechat.default')❌
