### ISSUE TITLE
Missing Wechat Config -- [mch_public_cert_path]

### ISSUE THREAD

**Issue by xxj-moxiaom** [yansongda/pay#964]
## 包版本号
"yansongda/pay": "^3.2.0"

## 问题描述
微信h5支付报Missing Wechat Config -- [mch_public_cert_path]

## 你的代码
<img width="843" alt="image" src="https://github.com/yansongda/pay/assets/30680453/6686b581-f2f8-4f11-84f5-d941bfd4a5d4">

## 报错详情

![image](https://github.com/yansongda/pay/assets/30680453/8b98c5fd-3305-46a3-acf3-5c7b8f37bd46)

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by xxj-moxiaom** [comment]
配置文件

**Comment by yansongda** [comment]
#963
