### ISSUE TITLE
AppID不存在，请检查后再试

### ISSUE THREAD

**Issue by xxj-moxiaom** [yansongda/pay#965]
## 包版本号
"yansongda/pay": "^3.2.0"

## 问题描述
微信h5支付 报“AppID不存在，请检查后再试” 
配置文件中已经填写了app_id

## 你的代码
<img width="731" alt="image" src="https://github.com/yansongda/pay/assets/30680453/34b1de4d-1683-4b47-aa79-1f62e3b595b2">

## 报错详情

![image](https://github.com/yansongda/pay/assets/30680453/efc47a48-9348-4a4f-891f-e2277c81dfb5)

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
https://pay.yansongda.cn/docs/v3/wechat/pay.html#%E5%85%B6%E5%AE%83

**Comment by yansongda** [comment]
多看看文档吧，文档比较全了

**Comment by xxj-moxiaom** [comment]
> 多看看文档吧，文档比较全了

这个是小程序的呀 我们没有小程序，我们是应用呀

**Comment by xxj-moxiaom** [comment]
使用的是开放平台的移动应用app_id，现在又报“appid和mch_id不匹配，请检查后再试”是必须使用公众平台的么

**Comment by xxj-moxiaom** [comment]
我们之前都是用开放平台的 没用过公众平台的
