### ISSUE TITLE
疑似验签失败 throw new InvalidResponseException(Exception::INVALID_RESPONSE_SIGN, '', ['headers' => $message->getHeaders(), 'body' => $body]);

### ISSUE THREAD

**Issue by xxj-moxiaom** [yansongda/pay#966]
## 包版本号

3.2.12
## 问题描述
疑似验签失败 
php-fpm模式 wechat_public_cert_path 这个我没处理过

## 你的代码
Pay::config($config);
$result = Pay::wechat()->callback();
<img width="800" alt="image" src="https://github.com/yansongda/pay/assets/30680453/cc0df20a-7ebd-4136-8969-b59d77e228e9">

## 报错详情
![image](https://github.com/yansongda/pay/assets/30680453/148ccb6c-c2ad-43c5-a84d-62c66a8954b5)

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by wolfwithsheep** [comment]
这个问题咋解决的
