### ISSUE TITLE
返回headers{}

### ISSUE THREAD

**Issue by admingalery** [yansongda/pay#97]
## 包版本号
2.0

## 问题描述
适用的laravel包，composer.json里面是"yansongda/laravel-pay": "^2.0",
返回信息一直是{"headers":{}}

## 代码
$order = [
            'out_trade_no' => $userOrder->out_trade_no,
            'total_amount' => strval($userOrder->total_amount),//订单金额
            'subject' => $userOrder->subject,//订单标题
//            'goods_type' => '0',
        ];
        $result = [
            "code" => 1,
            "msg" => "success",
            "data" => [
                "orderInfo" => Pay::alipay($this->config['alipay'])->app($order)
            ]
        ];
返回的结果一直是
{
"code":1,
"msg":"success",
"data":{"orderInfo":{"headers":{}}}
}
是我哪里配置错了吗？有没有其他人遇到这样的问题？

**Comment by yansongda** [comment]
请仔细看文档

谢谢

**Comment by zhitaochan** [comment]
你好，我也遇到了这个问题了，请问最后是怎么解决的

**Comment by jehazXu** [comment]
同样的问题，请问怎么解决的，文档没看到

**Comment by jehazXu** [comment]
> 请仔细看文档
> 
> 谢谢

请问怎么去掉响应头呢
