### ISSUE TITLE
容器未找到: `getContainer()` 方法调用失败! 或许你应该先 `setContainer()`

### ISSUE THREAD

**Issue by chen900804** [yansongda/pay#976]
## 包版本号
3.7

## 问题描述
![QQ截图20240505234117](https://github.com/yansongda/pay/assets/54523339/fd284cfa-9927-4b0f-a35c-91fc0f920f04)

容器未找到: `getContainer()` 方法调用失败! 或许你应该先 `setContainer()`
## 你的代码
  ```
$order = [

            'out_trade_no' => time().'',

            'description' => 'subject-测试',

            'amount' => [

                'total' => 1,

            ],

        ];

        $p = Pay::wechat()->scan($order);
```

**Comment by yansongda** [comment]
https://pay.yansongda.cn/docs/v3/quick-start/install.html

看看有没有按照文档进行安装相关包
