### ISSUE TITLE
新版支付宝不支持

### ISSUE THREAD

**Issue by xydream** [yansongda/pay#978]
## 包版本号
3.7.3

## 问题描述
新版支付宝无法支持。报错为：配置异常: 解析 `app_public_cert_path` 失败
具体为\yansongda\pay\src\Plugin\Alipay\V2\StartPlugin.php 115行 openssl_x509_parse函数返回false导致报错。
单独测试php原生函数openssl_x509_parse，确实无法解析新版支付宝密钥工具生成的《应用公钥》

## 报错详情
配置异常: 解析 `app_public_cert_path` 失败

**Comment by liuwenzi** [comment]
@xydream 我也遇到这个问题了 检查了很多遍,  证书没问题, 生成后没有修改过,  也是跑到 openssl_x509_parse 的时候失败.  
麻烦问一下, 你当时是怎么解决的吗?

**Comment by nightcsl** [comment]
需要改写方法，我这个错误是升级到3.7.10导致的，用的是在线的证书路径，需要把报错地方的get_public_cert()这个方法直接改为file_get_contents()获取
