### ISSUE TITLE
支付宝H5支付提示未实现 `ShortcutInterface`

### ISSUE THREAD

**Issue by freadman** [yansongda/pay#985]
## 包版本号
3.7.4

## 问题描述
支付宝支付提示：[\\Yansongda\\Pay\\Shortcut\\Alipay\\WapShortcut] 未实现 `ShortcutInterface`

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
https://pay.yansongda.cn/docs/v3/quick-start/alipay.html#h5-%E6%94%AF%E4%BB%98

```php
Pay::config($this->config);

// 注意返回类型为 Response，具体见详细文档
return Pay::alipay()->h5([
    'out_trade_no' => time(),
    'total_amount' => '0.01',
    'subject' => 'yansongda 测试 - 01',
    'quit_url' => 'https://yansongda.cn',
 ]);
```
