### ISSUE TITLE
微信支付偶尔报错yansongda/pay/src/Plugin/Wechat/SignPlugin.php(34): get_wechat_authorization()

### ISSUE THREAD

**Issue by lscho** [yansongda/pay#989]
## 包版本号
  "yansongda/pay": "~3.1.0",

## 问题描述

偶尔会出现这个情况，大多数请求正常

## 报错详情
Missing Wechat Config -- [mch_public_cert_path]
/vendor/yansongda/pay/src/Plugin/Wechat/SignPlugin.php(34): get_wechat_authorization()

## sdk 日志

2024-05-30T15:00:34.544632+08:00 > yansongda.pay.INFO > [wechat][SignPlugin] 插件开始装载

走到这一步停止

## 疑问
看官网3.2版本删除了get_wechat_authorization这个方法，请问升级是否能解决？

**Comment by yansongda** [comment]
可以升级到最新版试试看
