### ISSUE TITLE
支付宝H5支付   配置里填写return_url， 但是支付完成后， 只停留在支付页面， 并没有跳转到填写的url地址

### ISSUE THREAD

**Issue by longmao8633** [yansongda/pay#990]
## 包版本号

V3
## 问题描述
支付宝H5支付   配置里填写return_url， 但是支付完成后， 只停留在支付页面， 并没有跳转到填写的url地址

## 你的代码

 $config['alipay']['default']['return_url'] = 'url';

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
这个恐怕得看看支付宝那边了，只要参数传递正确的
