### ISSUE TITLE
[doc]微信扫码支付参数确认

### ISSUE THREAD

**Issue by sorshion** [yansongda/pay#991]
## 包版本号
3.7

## 问题描述
在webman使用微信扫码支付

## 你的代码

Pay::config($config);

$order = [
    'out_trade_no' => time().'',
    'description' => 'subject-测试',
    'amount' => [
        'total' => 1,
    ],
];

$result = Pay::wechat()->scan($order);

## 报错详情
AppID不存在，请检查后再试

当上面的$order 添加 $order['_type'] 参数，则能跑通，所以，我想确认下，是文档没有补充完整，还是其他问题

**Comment by yansongda** [comment]
默认都是是有微信公众号的 appid，如果你需要指定其他 appid 就得使用 `_type` 参数
