### ISSUE TITLE
微信支付关闭单必定出现 InvalidResponseException  响应异常: 解包错误, 但再查询订单就会关闭

### ISSUE THREAD

**Issue by WillieOng-HK** [yansongda/pay#999]
## 包版本号
yansongda/artful: v1.1.1
yansongda/pay: v3.7.5
yansongda/supports: v4.0.10

## 问题描述
微信支付关闭单必定出现 
`InvalidResponseException  响应异常: 解包错误`
, 但即时再查询订单就会显示订单关闭

微信支付官网是指关闭订单后只会用http code代码请求成功／失败， 不会返回body 的， 会不会是这个原因？
<img width="1096" alt="image" src="https://github.com/yansongda/pay/assets/5966527/1b1f9b62-ac14-495d-978a-5e6830278872">

https://pay.weixin.qq.com/docs/merchant/apis/jsapi-payment/close-order.html#%E5%BA%94%E7%AD%94%E5%8F%82%E6%95%B0

## 你的代码
```
$data = [
    'internal_order_no' => '20240614172507C',
];

$this->apiService->config($paymentChannel)->closeOrder($closeOrderData);

```

## 报错详情
Yansongda\Artful\Exception\InvalidResponseException  响应异常: 解包错误.

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
晚些时候我看看

**Comment by yansongda** [comment]
麻烦升级至最新版即可，感谢反馈
